### ISSUE TITLE
ERROR: CUDA initialization failure with error 222

### ISSUE THREAD

**Issue by wangxiaoyunNV** [NVIDIA/TensorRT#1052]
## Description
I am trying to run the pytorch example. https://github.com/NVIDIA/TensorRT/tree/master/samples/python/network_api_pytorch_mnist

I first run python3 -m pip install -r requirements.txt
it works well.
Then I run  python sample.py
After 2 epochs, it gives error
Test set: Average loss: 0.0775, Accuracy: 9734/10000 (97%)

[TensorRT] ERROR: CUDA initialization failure with error 222. Please check your CUDA installation:  http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html
Traceback (most recent call last):
  File "sample.py", line 112, in <module>
    main()
  File "sample.py", line 98, in main
    with build_engine(weights) as engine:
  File "sample.py", line 76, in build_engine
    with trt.Builder(TRT_LOGGER) as builder, builder.create_network() as network, builder.create_builder_config() as config:
TypeError: pybind11::init(): factory function returned nullptr
## Environment

**TensorRT Version**:  7.2.2.3
**NVIDIA GPU**: Quadro RTX 8000  
**NVIDIA Driver Version**:  450.102.04 
**CUDA Version**:  11.0 
**CUDNN Version**: 
**Operating System**: linux
**Python Version (if applicable)**: 3.7
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 1.7.1
**Baremetal or Container (if so, version)**:

**Comment by wangxiaoyunNV** [comment]
problem solved by using nvidia pytorch docker
