### ISSUE TITLE
sampleUffFasterRCNN convert-to-uff fails with an error: node is not Const

### ISSUE THREAD

**Issue by JanuszTaterka** [NVIDIA/TensorRT#1100]
## Description
I"ve installed TensorRT-7.2.3.4.Windows10.x86_64.cuda-11.1.cudnn8.1 (ZIP file) and try to run the sampleUffFasterRCNN sample  (Windows 10, x86-64). The convert-to-uff command fails.

## Environment

**TensorRT Version**:  7.2.3.4
**NVIDIA GPU**: Quadro T1000
**NVIDIA Driver Version**: installed with CUDA 11.2 package
**CUDA Version**: 11.2
**CUDNN Version**: 8.1.3
**Operating System**: Windows 10
**Python Version (if applicable)**: 3.6.4 (x86-64)
**Tensorflow Version (if applicable)**: 1.15.3
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**: Baremetal

## Steps To Reproduce
I've followed the readme file.
I've installed CUDA 11.2 and 11.1, cudnn 8.1.3., python 3.6.4 (x86-64) and installed tensorflow 1.15.3 (not tensorflow-gpu).
I've installed uff, graphsurgeon and onnx_graphsurgeon python packages (using python -m pip install FILENAME).
I've patched the convert_functions.py.
Finally I've copied: faster_rcnn.rb and config.py to the same directory and run convert-to-uff -p config.py -O dense_class/Softmax -O dense_regress/BiasAdd -O proposal faster_rcnn.pb command.

I get the following output:
`
WARNING:tensorflow:From c:\python36\lib\site-packages\uff\converters\tensorflow\conversion_helpers.py:274: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.

NOTE: UFF has been tested with TensorFlow 1.15.0.
WARNING: The version of TensorFlow installed on this system is not guaranteed to work with UFF.
UFF Version 0.6.9
=== Automatically deduced input nodes ===
[name: "input_1"
op: "Placeholder"
attr {
  key: "dtype"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "shape"
  value {
    shape {
      dim {
        size: -1
      }
      dim {
        size: 3
      }
      dim {
        size: 272
      }
      dim {
        size: 480
      }
    }
  }
}
]
'========================================='
`
Using output node dense_class/Softmax
Using output node dense_regress/BiasAdd
Using output node proposal
Converting to UFF graph
Warning: No conversion function registered for layer: Proposal yet.
Converting proposal as custom op: Proposal
WARNING:tensorflow:From c:\python36\lib\site-packages\uff\converters\tensorflow\converter.py:226: The name tf.AttrValue is deprecated. Please use tf.compat.v1.AttrValue instead.

DEBUG: convert reshape to flatten node
Warning: No conversion function registered for layer: CropAndResize yet.
Converting roi_pooling_conv_1/CropAndResize_new as custom op: CropAndResize
Traceback (most recent call last):
  File "c:\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python36\Scripts\convert-to-uff.exe\__main__.py", line 7, in <module>
  File "c:\python36\lib\site-packages\uff\bin\convert_to_uff.py", line 139, in main
    debug_mode=args.debug
  File "c:\python36\lib\site-packages\uff\converters\tensorflow\conversion_helpers.py", line 276, in from_tensorflow_frozen_model
    return from_tensorflow(graphdef, output_nodes, preprocessor, **kwargs)
  File "c:\python36\lib\site-packages\uff\converters\tensorflow\conversion_helpers.py", line 225, in from_tensorflow
    debug_mode=debug_mode)
  File "c:\python36\lib\site-packages\uff\converters\tensorflow\converter.py", line 141, in convert_tf2uff_graph
    uff_graph, input_replacements, debug_mode=debug_mode)
  File "c:\python36\lib\site-packages\uff\converters\tensorflow\converter.py", line 126, in convert_tf2uff_node
    op, name, tf_node, inputs, uff_graph, tf_nodes=tf_nodes, debug_mode=debug_mode)
  File "c:\python36\lib\site-packages\uff\converters\tensorflow\converter.py", line 94, in convert_layer
    return cls.registry_[op](name, tf_node, inputs, uff_graph, **kwargs)
  File "c:\python36\lib\site-packages\uff\converters\tensorflow\converter_functions.py", line 449, in convert_conv2d
    return _conv2d_helper(name, tf_node, inputs, uff_graph, func="conv2d", **kwargs)
  File "c:\python36\lib\site-packages\uff\converters\tensorflow\converter_functions.py", line 465, in _conv2d_helper
    tf_node, inputs, kwargs["tf_nodes"])
  File "c:\python36\lib\site-packages\uff\converters\tensorflow\converter.py", line 208, in apply_fused_padding
    p = cls.convert_tf2numpy_const_node(tf_padding_node)
  File "c:\python36\lib\site-packages\uff\converters\tensorflow\converter.py", line 169, in convert_tf2numpy_const_node
    raise UffException("Const node conversion requested, but node is not Const\n" + str(tf_node))
uff.model.exceptions.UffException: Const node conversion requested, but node is not Const
name: "roi_pooling_conv_1/CropAndResize_new"
op: "CropAndResize"
input: "activation_7/Relu"
input: "proposal"
attr {
  key: "crop_height_u_int"
  value {
    i: 7
  }
}
attr {
  key: "crop_width_u_int"
  value {
    i: 7
  }
}

**Comment by ttyio** [comment]
Hello @JanuszTaterka , could you take a try with TF 1.15.0? thanks

**Comment by ttyio** [comment]
Close since no activity for more than 3 weeks, please reopen if you still have question, thanks!
