### ISSUE TITLE
RuntimeError: Driver error:

### ISSUE THREAD

**Issue by whcjb** [NVIDIA/TensorRT#1118]
## Description
when convert onnx to tensorrt, comes the error

## Environment

**TensorRT Version**:  7.2.3.4
**NVIDIA GPU**: tesla p40
**NVIDIA Driver Version**: 460.32.03
**CUDA Version**: 11.0, 11.2
**CUDNN Version**: 8.0
**Operating System**: centos7
**Python Version (if applicable)**: 3.6
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 1.6
**Baremetal or Container (if so, version)**: docker image

## Relevant Files

```import os
import numpy as np
import tensorrt as trt
import onnxruntime as ort

trt_logger = trt.Logger(trt.Logger.VERBOSE)
explicit_batch = 1 << (int)(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)
onnx_file_path = "./examples/ceshi/ceshi.onnx"
engine_file_path = "./examples/ceshi/ceshi.trt"
if os.path.exists(engine_file_path):
    # If a serialized engine exists, use it instead of building an engine.
    print("Reading engine from file {}".format(engine_file_path))
    with open(engine_file_path, "rb") as f, trt.Runtime(TRT_LOGGER) as runtime:
        engine = runtime.deserialize_cuda_engine(f.read())
else:
    with trt.Builder(trt_logger) as builder, \
            builder.create_network(explicit_batch) as network, \
            trt.OnnxParser(network, trt_logger) as parser:
        with open(onnx_file_path, 'rb') as model:
            if not parser.parse(model.read()):
                print ('ERROR: Failed to parse the ONNX file.')
                for error in range(parser.num_errors):
                    print (parser.get_error(error))
                exit()
        print('Building an engine from file temp.pb; this may take a while...')
        engine = builder.build_cuda_engine(network)
        print("Completed creating Engine")
        with open(engine_file_path, "wb") as f:
            f.write(engine.serialize())
```

## Steps To Reproduce

```
[TensorRT] VERBOSE: Fastest Tactic: 1002 Time: 0.053248
[TensorRT] VERBOSE: --------------- Timing Runner: <reformat> (Reformat)
[TensorRT] VERBOSE: Tactic: 1002 time 0.089088
[TensorRT] VERBOSE: Tactic: 0 time 0.791552
[TensorRT] VERBOSE: Fastest Tactic: 1002 Time: 0.089088
[TensorRT] VERBOSE: --------------- Timing Runner: <reformat> (Reformat)
[TensorRT] VERBOSE: Tactic: 1002 time 0.053248
[TensorRT] VERBOSE: Tactic: 0 time 0.194336
[TensorRT] VERBOSE: Fastest Tactic: 1002 Time: 0.053248
[TensorRT] VERBOSE: --------------- Timing Runner: <reformat> (Reformat)
[TensorRT] VERBOSE: Tactic: 1002 time 0.075776
[TensorRT] VERBOSE: Tactic: 0 time 0.878592
[TensorRT] VERBOSE: Fastest Tactic: 1002 Time: 0.075776
[TensorRT] VERBOSE: --------------- Timing Runner: <reformat> (Reformat)
[TensorRT] VERBOSE: Tactic: 1002 time 0.16896
[TensorRT] VERBOSE: Tactic: 0 time 0.22016
[TensorRT] VERBOSE: Fastest Tactic: 1002 Time: 0.16896
[TensorRT] VERBOSE: --------------- Timing Runner: <reformat> (Reformat)
[TensorRT] VERBOSE: Tactic: 1002 time 0.075776
[TensorRT] VERBOSE: Tactic: 0 time 0.054272
[TensorRT] VERBOSE: Fastest Tactic: 0 Time: 0.054272
[TensorRT] VERBOSE: *************** Autotuning format combination: Float(1,224,50176,1204224), Float(1,224,50176,1204224) -> Float(1,224,50176,1204224) ***************
[TensorRT] VERBOSE: Builder timing cache: created 42 entries, 29 hit(s)
Traceback (most recent call last):
  File "examples/ceshi/ceshi_rt.py", line 26, in <module>
    engine = builder.build_cuda_engine(network)
RuntimeError: Driver error:
```
samples ```./deviceQuery ``` passed

**Comment by whcjb** [comment]
someone can help？changed the driver to 450.102.04, still have the problem

**Comment by whcjb** [comment]
it's good in tensorrt7.0, so this is a bug in tensorrt7.2.3.4

**Comment by ttyio** [comment]
Hello @whcjb ,
I see the last line in your log is

         [TensorRT] VERBOSE: Builder timing cache: created 42 entries, 29 hit(s)

Not sure if this crash come from the builder cache. Could you try creating `builder_config` and disable the builder cache via

        builder_config.set_flag(trt.BuilderFlag.DISABLE_TIMING_CACHE)

sample code on create `builder_config`  and call `build_engine` with `builder_config` can be found in https://github.com/NVIDIA/TensorRT/blob/master/demo/BERT/builder.py#L618

Thanks!

**Comment by whcjb** [comment]
hello, @ttyio 
```
[TensorRT] VERBOSE: Tactic: 0 time 0.054048
[TensorRT] VERBOSE: Fastest Tactic: 0 Time: 0.054048
[TensorRT] VERBOSE: --------------- Timing Runner: <reformat> (Reformat)
[TensorRT] VERBOSE: Tactic: 1002 time 0.053248
[TensorRT] VERBOSE: Tactic: 0 time 0.063488
[TensorRT] VERBOSE: Fastest Tactic: 1002 Time: 0.053248
[TensorRT] VERBOSE: --------------- Timing Runner: <reformat> (Reformat)
[TensorRT] VERBOSE: Tactic: 1002 time 0.089088
[TensorRT] VERBOSE: Tactic: 0 time 0.610304
[TensorRT] VERBOSE: Fastest Tactic: 1002 Time: 0.089088
[TensorRT] VERBOSE: --------------- Timing Runner: <reformat> (Reformat)
[TensorRT] VERBOSE: Tactic: 1002 time 0.052224
[TensorRT] VERBOSE: Tactic: 0 time 0.193536
[TensorRT] VERBOSE: Fastest Tactic: 1002 Time: 0.052224
[TensorRT] VERBOSE: --------------- Timing Runner: <reformat> (Reformat)
[TensorRT] VERBOSE: Tactic: 1002 time 0.0768
[TensorRT] VERBOSE: Tactic: 0 time 0.702464
[TensorRT] VERBOSE: Fastest Tactic: 1002 Time: 0.0768
[TensorRT] VERBOSE: --------------- Timing Runner: <reformat> (Reformat)
[TensorRT] VERBOSE: Tactic: 1002 time 0.16896
[TensorRT] VERBOSE: Tactic: 0 time 0.221184
[TensorRT] VERBOSE: Fastest Tactic: 1002 Time: 0.16896
[TensorRT] VERBOSE: --------------- Timing Runner: <reformat> (Reformat)
[TensorRT] VERBOSE: Tactic: 1002 time 0.075776
[TensorRT] VERBOSE: Tactic: 0 time 0.054272
[TensorRT] VERBOSE: Fastest Tactic: 0 Time: 0.054272
[TensorRT] VERBOSE: *************** Autotuning format combination: Float(1,224,50176,1204224), Float(1,224,50176,1204224) -> Float(1,224,50176,1204224) ***************
[TensorRT] VERBOSE: Builder timing cache: created 0 entries, 0 hit(s)
Traceback (most recent call last):
  File "examples/ceshi/ceshi_rt.py", line 27, in <module>
    engine = builder.build_engine(network, builder_config)
RuntimeError: Driver error:
```

**Comment by ttyio** [comment]
Hello @whcjb , could you share the onnx file? thanks

**Comment by whcjb** [comment]
hello @ttyio 
https://drive.google.com/file/d/1XDQ5X-Rh_HwRgWf1V-ScLoMWn7Tnm6De/view?usp=sharing

**Comment by ttyio** [comment]
Hello @whcjb ,
I tried on P40 

the docker image is run by 

     git clone https://github.com/NVIDIA/TensorRT.git
     git checkout release/7.2
     cd TensorRT
     ./docker/build.sh --file docker/ubuntu.Dockerfile --tag tensorrt-ubuntu --os 18.04 --cuda 11.1
     ./docker/launch.sh --tag tensorrt-ubuntu --gpus all --release $TRT_RELEASE --source $TRT_SOURCE

After enter the container, I run using command line 

     /tensorrt/bin/trtexec --onnx=./TensorRT/ceshi.onnx  --verbose

but cannot reproduce the issue, could you also try if you can repro the failure in the container? thanks!

**Comment by whcjb** [comment]
hello, @ttyio 
i change a machine, works.
