### ISSUE TITLE
async for dynamic shape input with multiple streams and contexts

### ISSUE THREAD

**Issue by pxu4114** [NVIDIA/TensorRT#1157]
***Environment***
docker nvcr.io/nvidia/tensorrt/21.02-py3
by the way I also tried
nvcr.io/nvidia/tensorrt/20.10-py3
same problem
The following informantion is based on 21.02-py3
TensorRT Version: 7.2.2.3
NVIDIA GPU: Nvidia 2080 super
NVIDIA Driver Version: 460.39
CUDA Version: 11.2.0
CUDNN Version: 8.1.0
Operating System: ubuntu 20.04 (at least in side docker)
Python Version (if applicable): 3.8
Tensorflow Version (if applicable):no
PyTorch Version (if applicable): 1.6.0
Baremetal or Container (if so, version): at top

***Description***
I am trying to use multiple contexts and multiple streams to parallelize the inference. The input is dynamic. Since the input is dynamic I have to use multiple contexts and I get error after some iterations of running inference. I need multiple contexts because I have to set the input shape for multiple inputs simultaneously so that I can run inference on them simultaneously 

```
[TensorRT] ERROR: ../rtExt/cuda/cudaFusedConvActRunner.cpp (319) - Cuda Error in executeFused: 700 (an illegal memory access was encountered)
[TensorRT] ERROR: FAILED_EXECUTION: std::exception
Traceback (most recent call last):
  File "onnx2trt.py", line 812, in <module>
    trt_output = do_inference_v2(buffer_list[i][0], buffer_list[i][1], buffer_list[i][2], context, streams)
  File "onnx2trt.py", line 736, in do_inference_v2
    [cuda.memcpy_dtoh(out.host, out.device) for out in outputs]
  File "onnx2trt.py", line 736, in <listcomp>
    [cuda.memcpy_dtoh(out.host, out.device) for out in outputs]
pycuda._driver.LogicError: cuMemcpyDtoH failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFreeHost failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFree failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFreeHost failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFree failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFreeHost failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFree failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFreeHost failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFree failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFreeHost failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFree failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFreeHost failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFree failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFree failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFreeHost failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFree failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFreeHost failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFree failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFreeHost failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFree failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFreeHost failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFree failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFreeHost failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFree failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFreeHost failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFree failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFree failed: an illegal memory access was encountered
```
We did some debugging and we are quite sure that the problem is using multiple contexts.

**Comment by pranavm-nvidia** [comment]
@pxu4114 Are you using multiple _CUDA_ contexts or multiple _TensorRT_ execution contexts? You need only the latter, not the former. 

It might be a good idea to start with Polygraphy so you can pipeclean the rest of your code. You can refer to my comment here for details: https://github.com/NVIDIA/TensorRT/issues/1121#issuecomment-802003043

**Comment by pxu4114** [comment]
@pranavm-nvidia I am using multiple TensorRT execution contexts and not multiple CUDA contexts. We are not doing multi threading, We are just trying to use the async functions and parallelize the inference using context.execute_async_v2.

```
def do_inference_v2(inputs, outputs, bindings, context, stream):
    """do_inference_v2 (for TensorRT 7.0+)

    This function is generalized for multiple inputs/outputs for full
    dimension networks.
    Inputs and outputs are expected to be lists of HostDeviceMem objects.
    """
    # Transfer input data to the GPU.
    [cuda.memcpy_htod_async(inp.device, inp.host, stream) for inp in inputs]
    # Run inference
    context.execute_async_v2(bindings=bindings, stream_handle=stream.handle)
    # Transfer predictions back from the GPU.
    [cuda.memcpy_dtoh_async(out.host, out.device, stream) for out in outputs]
    # Synchronize the stream
    # stream.synchronize()
    # Return only the host outputs.
    return [out.host for out in outputs]
```

**Comment by pranavm-nvidia** [comment]
@pxu4114 It's hard to say what's going wrong without seeing more of your inference code. Can you share how you're calling `do_inference_v2`?

**Comment by pxu4114** [comment]
```
num_streams = 2
streams = [cuda.Stream() for i in range(num_streams)]
contexts = [engine.create_execution_context() for i in range(num_streams)]
# preprocess input
for i in range(num_streams):
    '''
   some preprocessing on input
    '''
# allocate buffers
for i in range(num_streams):
    buffer = allocate_buffers(engine, contexts[i], np_im_tensor_list[i].shape[-1])
    buffer[0][0].host = np.ascontiguousarray(np_im_tensor_list[i])
    buffer_list.append(buffer)
# inference
for i in range(num_streams):
    # ctx.push()
    context = buffer_list[i][3]
    stream = buffer_list[i][4]
    trt_output = do_inference_v2(buffer_list[i][0], buffer_list[i][1], buffer_list[i][2], context, stream)
stream.synchronize()
```

I tried with no streams at all and doing it in synchronous way still the code breaks after some iterations with the above mentioned error. It works only if I use one context.

**Comment by pranavm-nvidia** [comment]
@pxu4114 I think there are a couple issues:

1. The allocation should be moved out of the inference loop (and you need to free the memory when you're done), otherwise you will quickly run out of memory
2. You need to synchronize all the streams you've created, not just the last one:
```python
for i in range(num_streams):
    buffer_list[i][4].synchronize()
```

**Comment by pxu4114** [comment]
Thank you for your reply. Do you know the right way to free up the memory after use?

**Comment by pranavm-nvidia** [comment]
@pxu4114

> Do you know the right way to free up the memory after use?

You can use the `free()` method described [here](https://documen.tician.de/pycuda/driver.html#pycuda.driver.DeviceAllocation.free). 

> and I should synchronize all the streams after the for loop, right? like below

Yes

**Comment by ttyio** [comment]
close since no activity for 3 weeks, please reopen if you still have question, thanks!
