### ISSUE TITLE
Getting error while converting model from h5 to uff during segmentation using tensor rt

### ISSUE THREAD

**Issue by akshayacharya97** [NVIDIA/TensorRT#1312]
## Description

I have a Jetson Xavier NX. I am trying to run instan ce segmentation using tensor rt . However, I am getting the rror as shown below. I am following he exact instructions as shown in the github readme of the same. I want to run instance segmentation on the coco dataset. I have installed all the necesasry modules . I am unsure why it is not able to convert the model

## Environment

GPU Type: Jetson Xavier NX GPU
Nvidia Driver Version: -
CUDA Version: 10.2.89
CUDNN Version: 8.0.0
Operating System + Version: Ubuntu 18.04 LTS
Python Version (if applicable): 3.6.9
TensorFlow Version (if applicable): 1.15.4
PyTorch Version (if applicable): -
Baremetal or Container (if container which image + tag): -

## Relevant Files
[https://github.com/NVIDIA/TensorRT/tree/master/samples/opensource/sampleUffMaskRCNN](url)

Error 
```
Traceback (most recent call last):
  File "mrcnn_to_trt_single.py", line 164, in <module>
    main()
  File "mrcnn_to_trt_single.py", line 113, in main
    model = modellib.MaskRCNN(mode="inference", model_dir=LOG_DIR, config=config).keras_model
  File "/usr/local/lib/python3.6/dist-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1837, in __init__
  File "/usr/local/lib/python3.6/dist-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1901, in build
  File "/usr/local/lib/python3.6/dist-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 180, in resnet_graph
  File "/home/nvidia/.local/lib/python3.6/site-packages/keras/engine/topology.py", line 590, in __call__
    self.build(input_shapes[0])
  File "/home/nvidia/.local/lib/python3.6/site-packages/keras/layers/convolutional.py", line 129, in build
    raise ValueError('The channel dimension of the inputs '
ValueError: The channel dimension of the inputs should be defined. Found `None`.
```

**Comment by ttyio** [comment]
Adding @Tyler-D , thanks!

**Comment by Tyler-D** [comment]
Are you running with commit 3deaec5 of Matterport's MaskRCNN ?

**Comment by Tyler-D** [comment]
Highly suggest you to generate uff on a x86 host instead of on NX. You could follow these steps to generate this uff in a Nvidia image: https://github.com/NVIDIA/TensorRT/issues/626#issuecomment-652222259

**Comment by ttyio** [comment]
Closing since no activities for more than 3 weeks, please reopen if you still have question. Thanks!
