### ISSUE TITLE
pytorch-quantization install error with `pip install`

### ISSUE THREAD

**Issue by un-knight** [NVIDIA/TensorRT#1388]
## Description

running command with `pip install pytorch-quantization --extra-index-url https://pypi.ngc.nvidia.com`, but got an error:

```
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com, https://pypi.ngc.nvidia.com
Collecting pytorch-quantization
  Downloading pytorch-quantization-0.0.1.dev5.tar.gz (7.9 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/yejunxian/anaconda3/envs/torch/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-qw2hkpfc/pytorch-quantization/setup.py'"'"'; __file__='"'"'/tmp/pip-install-qw2hkpfc/pytorch-quantization/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-cdt6c626
         cwd: /tmp/pip-install-qw2hkpfc/pytorch-quantization/
    Complete output (16 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-qw2hkpfc/pytorch-quantization/setup.py", line 150, in <module>
        raise RuntimeError(open("ERROR.txt", "r").read())
    RuntimeError:
    ###########################################################################################
    The package you are trying to install is only a placeholder project on PyPI.org repository.
    This package is hosted on NVIDIA Python Package Index.
    
    This package can be installed as:
    ```
    $ pip install nvidia-pyindex
    $ pip install pytorch-quantization
    ```
    ###########################################################################################
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by ttyio** [comment]
Hello @un-knight , we also have the docker image `nvcr.io/nvidia/pytorch:21.09-py3`, could you take a try? thanks

**Comment by ttyio** [comment]
close since no activity for more than 3 weeks, please reopen if you still have question, thanks!

**Comment by Gwencong** [comment]
I encountered the similar problem, and successfully installed it  through source code compilation according to the instruction [here](https://github.com/NVIDIA/TensorRT/tree/main/tools/pytorch-quantization#from-source) finally.
