### ISSUE TITLE
samples/python/efficientdet out of memory on jetson nano

### ISSUE THREAD

**Issue by partus** [NVIDIA/TensorRT#1404]
## Description
Unable to create engine on jetson nano as it results to out of memory issue. Seems to be strange as efficientdet-d0 is a very lightweight model. Meanwhile , monitoring the memory doesn't show any signs of approaching the limit ( no signs of considerable occupation of the memery , conversion just interupts) .
```
python3  build_engine.py \
    --onnx ./efficientdet-d0-legacy.onnx \
    --engine ./efficientdet-d0-legacy.trt \
    --precision fp16

[TensorRT] WARNING: onnx2trt_utils.cpp:220: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] INFO: ModelImporter.cpp:135: No importer registered for op: ResizeNearest_TRT. Attempting to import as plugin.
[TensorRT] INFO: builtin_op_importers.cpp:3659: Searching for plugin: ResizeNearest_TRT, plugin_version: 1, plugin_namespace: 
[TensorRT] INFO: builtin_op_importers.cpp:3676: Successfully created plugin: ResizeNearest_TRT
...
[TensorRT] INFO: builtin_op_importers.cpp:3676: Successfully created plugin: BatchedNMS_TRT
INFO:EngineBuilder:Network Description
INFO:EngineBuilder:Input 'image_arrays:0' with shape (1, 512, 512, 3) and dtype DataType.FLOAT
INFO:EngineBuilder:Output 'num_detections' with shape (1,) and dtype DataType.INT32
INFO:EngineBuilder:Output 'detection_boxes' with shape (1, 100, 4) and dtype DataType.FLOAT
INFO:EngineBuilder:Output 'detection_scores' with shape (1, 100) and dtype DataType.FLOAT
INFO:EngineBuilder:Output 'detection_classes' with shape (1, 100) and dtype DataType.FLOAT
INFO:EngineBuilder:Building fp16 Engine in /home/jets/bikes/tort/efficientdet-d0-legacy.trt
[TensorRT] ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
[TensorRT] ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
Traceback (most recent call last):
  File "build_engine.py", line 240, in <module>
    main(args)
  File "build_engine.py", line 212, in main
    args.calib_batch_size)
  File "build_engine.py", line 203, in create_engine
    with self.builder.build_engine(self.network, self.config) as engine, open(engine_path, "wb") as f:
AttributeError: __enter__
```

## Environment
Unless spcified, defaults to standard jetpack
![image](https://user-images.githubusercontent.com/1966996/126897259-6e7cf5ae-c3cf-4c92-bb1f-56df241c7e31.png)

**TensorRT Version: 7.1.3:
**NVIDIA GPU: jetson Nano: 
**NVIDIA Driver Version**: 
**CUDA Version**: 
**CUDNN Version**: 
**Operating System**: 
**Python Version (if applicable)**:  3.6.9
**Tensorflow Version (if applicable)**: 
**Baremetal or Container (if so, version)**:

**Comment by jishadav** [comment]
Any update on this? Cannot do the conversion in Jetson Nano. Please help
