### ISSUE TITLE
Error in onnx model converting to trt engine

### ISSUE THREAD

**Issue by xiaohu2015** [NVIDIA/TensorRT#1414]
## Description

Error in onnx model converting to trt engine:

```python
[TensorRT] ERROR: 2: [ltWrapper.cpp::setupHeuristic::327] Error Code 2: Internal Error (Assertion cublasStatus == CUBLAS_STATUS_SUCCESS failed.)
[TensorRT] ERROR: 2: [builder.cpp::buildSerializedNetwork::417] Error Code 2: Internal Error (Assertion enginePtr != nullptr failed.)
Traceback (most recent call last):
  File "onnx_to_tensorrt.py", line 86, in <module>
    main()
  File "onnx_to_tensorrt.py", line 72, in main
    with get_engine(onnx_file_path, engine_file_path) as engine, engine.create_execution_context() as context:
  File "onnx_to_tensorrt.py", line 52, in get_engine
    return build_engine()
  File "onnx_to_tensorrt.py", line 40, in build_engine
    engine = runtime.deserialize_cuda_engine(plan)
TypeError: deserialize_cuda_engine(): incompatible function arguments. The following argument types are supported:
    1. (self: tensorrt.tensorrt.Runtime, serialized_engine: buffer) -> tensorrt.tensorrt.ICudaEngine

Invoked with: <tensorrt.tensorrt.Runtime object at 0x7f7c21b51c70>, None
```

## Environment

**TensorRT Version**:  8.0.0.1
**NVIDIA GPU**:  T4
**NVIDIA Driver Version**: 
**CUDA Version**:  cuda10.2
**CUDNN Version**:  cuDNN 8.2.0
**Operating System**: ubuntu 18.04 (docker)
**Python Version (if applicable)**: 3.8.5
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**:  1.9
**Baremetal or Container (if so, version)**: 

## Steps To Reproduce

torchvison resnet50 to onnx

```python
dummy_input = torch.randn(1, 3, 224, 224, device='cuda')
model = torchvision.models.resnet50(pretrained=True).cuda()
model.eval()

output_onnx_file = "resnet50.onnx"

torch.onnx.export(model,
    dummy_input,
    output_onnx_file,
    #export_params=True,
    verbose=True,
    input_names=["input_image"],
    output_names=["logits"],
    #keep_initializers_as_inputs=True,
    opset_version=11
)
```

**Comment by ttyio** [comment]
Hello @xiaohu2015 , this error means cublaslt setup failure, are you using 8.0EA? could you upgrade to 8.0GA or 8.0GA update1?

Or you can disable cublaslt using `setTacticSources` https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/classnvinfer1_1_1_i_builder_config.html#a37a53d51544307e31a274986ab6dad53
Thanks

**Comment by xiaohu2015** [comment]
@ttyio the version I used is 8.0.1.6-GA

**Comment by ttyio** [comment]
thanks @xiaohu2015 , It is probably CUDA environment issue, 

could you try container 21.08?
https://docs.nvidia.com/deeplearning/tensorrt/container-release-notes/rel_21-08.html#rel_21-08

**Comment by xywang93** [comment]
@ttyio I meet same issue, the difference is my os is ubuntu 16.04. What should i do？

TensorRT Version: 8.0.1.6
NVIDIA GPU: T4
NVIDIA Driver Version: 450.51.05 
CUDA Version: cuda10.2
CUDNN Version: cuDNN 8.3.0
Operating System: ubuntu 16.04 (docker)
Python Version (if applicable): 3.9.7

**Comment by ttyio** [comment]
@xywang93 , could you try official container ?
https://docs.nvidia.com/deeplearning/tensorrt/container-release-notes/rel_21-11.html#rel_21-11
thanks!

**Comment by ttyio** [comment]
close since no activity for more than 3 weeks, please reopen if you still have question, thanks!

**Comment by TaylorHere** [comment]
face same issue with nvcr.io/nvidia/tensorrt:22.01-py3
```shell
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [21], in <module>
----> 1 with get_engine('gpt2-retrained.onnx', 'gpt2-retrained.trt') as eng:
      2         inputs, outputs, bindings, stream = common.allocate_buffers(engine)
      3         # Do inference

Input In [17], in get_engine(onnx_file_path, engine_file_path)
     37         return runtime.deserialize_cuda_engine(f.read())
     38 else:
---> 39     return build_engine()

Input In [17], in get_engine.<locals>.build_engine()
     25 print('Building an engine from file {}; this may take a while...'.format(onnx_file_path))
     26 plan = builder.build_serialized_network(network, config)
---> 27 engine = runtime.deserialize_cuda_engine(plan)
     28 print("Completed creating Engine")
     29 with open(engine_file_path, "wb") as f:

TypeError: deserialize_cuda_engine(): incompatible function arguments. The following argument types are supported:
    1. (self: tensorrt.tensorrt.Runtime, serialized_engine: buffer) -> tensorrt.tensorrt.ICudaEngine

Invoked with: <tensorrt.tensorrt.Runtime object at 0x7fdba1f3cab0>, None
```

**Comment by TaylorHere** [comment]
> face same issue with nvcr.io/nvidia/tensorrt:22.01-py3 NVIDIA-SMI 470.57.02 Driver Version: 470.57.02 CUDA Version: 11.6
> 
> ```shell
> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> Input In [21], in <module>
> ----> 1 with get_engine('gpt2-retrained.onnx', 'gpt2-retrained.trt') as eng:
>       2         inputs, outputs, bindings, stream = common.allocate_buffers(engine)
>       3         # Do inference
> 
> Input In [17], in get_engine(onnx_file_path, engine_file_path)
>      37         return runtime.deserialize_cuda_engine(f.read())
>      38 else:
> ---> 39     return build_engine()
> 
> Input In [17], in get_engine.<locals>.build_engine()
>      25 print('Building an engine from file {}; this may take a while...'.format(onnx_file_path))
>      26 plan = builder.build_serialized_network(network, config)
> ---> 27 engine = runtime.deserialize_cuda_engine(plan)
>      28 print("Completed creating Engine")
>      29 with open(engine_file_path, "wb") as f:
> 
> TypeError: deserialize_cuda_engine(): incompatible function arguments. The following argument types are supported:
>     1. (self: tensorrt.tensorrt.Runtime, serialized_engine: buffer) -> tensorrt.tensorrt.ICudaEngine
> 
> Invoked with: <tensorrt.tensorrt.Runtime object at 0x7fdba1f3cab0>, None
> ```

I fix this by increasing workspace memory

**Comment by GeneralJing** [comment]
[05/25/2022-07:52:34] [TRT] [E] 1: Unexpected exception basic_string::_S_construct null not valid
[05/25/2022-07:52:34] [TRT] [I] build_serialized_network.
[05/25/2022-07:52:34] [TRT] [I] [MemUsageChange] Init CUDA: CPU +0, GPU +0, now: CPU 728, GPU 313 (MiB)
Traceback (most recent call last):
  File "builder.py", line 155, in <module>
    engine = runtime.deserialize_cuda_engine(plan)
TypeError: deserialize_cuda_engine(): incompatible function arguments. The following argument types are supported:
    1. (self: tensorrt.tensorrt.Runtime, serialized_engine: buffer) -> tensorrt.tensorrt.ICudaEngine

Invoked with: <tensorrt.tensorrt.Runtime object at 0x7f3e51734570>, None
free(): invalid pointer
Aborted (core dumped)

almost the same problem

**Comment by harishprabhala** [comment]
> > face same issue with nvcr.io/nvidia/tensorrt:22.01-py3 NVIDIA-SMI 470.57.02 Driver Version: 470.57.02 CUDA Version: 11.6
> > ```shell
> > ---------------------------------------------------------------------------
> > TypeError                                 Traceback (most recent call last)
> > Input In [21], in <module>
> > ----> 1 with get_engine('gpt2-retrained.onnx', 'gpt2-retrained.trt') as eng:
> >       2         inputs, outputs, bindings, stream = common.allocate_buffers(engine)
> >       3         # Do inference
> > 
> > Input In [17], in get_engine(onnx_file_path, engine_file_path)
> >      37         return runtime.deserialize_cuda_engine(f.read())
> >      38 else:
> > ---> 39     return build_engine()
> > 
> > Input In [17], in get_engine.<locals>.build_engine()
> >      25 print('Building an engine from file {}; this may take a while...'.format(onnx_file_path))
> >      26 plan = builder.build_serialized_network(network, config)
> > ---> 27 engine = runtime.deserialize_cuda_engine(plan)
> >      28 print("Completed creating Engine")
> >      29 with open(engine_file_path, "wb") as f:
> > 
> > TypeError: deserialize_cuda_engine(): incompatible function arguments. The following argument types are supported:
> >     1. (self: tensorrt.tensorrt.Runtime, serialized_engine: buffer) -> tensorrt.tensorrt.ICudaEngine
> > 
> > Invoked with: <tensorrt.tensorrt.Runtime object at 0x7fdba1f3cab0>, None
> > ```
> 
> I fix this by increasing workspace memory

Hi. I have the same issue. How much did you increase your workspace size to?

**Comment by Emekaborisama** [comment]
i am having the same issue convert onnx to tensor RT on google colab pro gpu
