### ISSUE TITLE
I can not run sample on T4

### ISSUE THREAD

**Issue by yyf1986** [NVIDIA/TensorRT#1453]
## Description

when I run sampe with “end_to_end_tensorflow_mnist” on T4
execution step:
```
cd ~/TensorRT-6.0.1.5/samples/python/end_to_end_tensorflow_mnist
python3.6 model.py
python3.6 /opt/conda/lib/python3.6/site-packages/uff/bin/convert_to_uff.py --input_file ~/TensorRT-6.0.1.5/samples/python/end_to_end_tensorflow_mnist/models/lenet5.pb
cd ~/TensorRT-6.0.1.5/samples/python/end_to_end_tensorflow_mnist
python3.6 sample.py
````
An error is as follows
`[TensorRT] ERROR: ../rtSafe/runnerUtils.cpp (425) - Cudnn Error in safeCudnnAddTensor: 8 (CUDNN_STATUS_EXECUTION_FAILED)
[TensorRT] ERROR: ../rtSafe/runnerUtils.cpp (425) - Cudnn Error in safeCudnnAddTensor: 8 (CUDNN_STATUS_EXECUTION_FAILED)
Traceback (most recent call last):
  File "sample.py", line 113, in <module>
    main()
  File "sample.py", line 99, in main
    with build_engine(model_file) as engine:
AttributeError: __enter__
`
the same operator on V100,run the sample is ok.
## Environment

**TensorRT Version**:  6.0.1.5
**NVIDIA GPU**: Tesla T4
**NVIDIA Driver Version**: 
**CUDA Version**: CUDA Version 9.0.176
**CUDNN Version**: 7.6.4
**Operating System**: Ubuntu 16.04.7 LTS
**Python Version (if applicable)**: 3.6
**Tensorflow Version (if applicable)**: 1.8
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**: Container

**Comment by ttyio** [comment]
Hello @yyf1986 , could you upgrade your TRT version to latest? thanks

**Comment by ttyio** [comment]
Closing since no activity for more than 3 weeks, please reopen if you still have question, thanks!
