### ISSUE TITLE
[TensorRT8] Can't build_engine 

### ISSUE THREAD

**Issue by SmileTM** [NVIDIA/TensorRT#1472]
## Description

Could you tell me how to modify  the `build.py` ?

```shell
2021-09-06 00:27:47.268161: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 22691 MB memory) -> physical GPU (device: 0, name: TITAN RTX, pci bus id: 0000:3e:00.0, compute capability: 7.5)
/data/private/user1/workspace/lx/learnTensorRT/demo1/build.py:58: DeprecationWarning: Use build_serialized_network instead.
  engine = builder.build_engine(network, config)
[TensorRT] ERROR: 2: [graphShapeAnalyzer.cpp::throwIfError::1306] Error Code 2: Internal Error (no further information)
[TensorRT] ERROR: 4: [network.cpp::validate::2604] Error Code 4: Internal Error (Could not compute dimensions for (Unnamed Layer* 0) [Fully Connected]_output, because the network is not valid.)
Traceback (most recent call last):
  File "/data/private/user1/workspace/lx/learnTensorRT/demo1/build.py", line 76, in <module>
    engine = build_engine(weights)
  File "/data/private/user1/workspace/lx/learnTensorRT/demo1/build.py", line 60, in build_engine
    return runtime.deserialize_cuda_engine(engine)
TypeError: deserialize_cuda_engine(): incompatible function arguments. The following argument types are supported:
    1. (self: tensorrt.tensorrt.Runtime, serialized_engine: buffer) -> tensorrt.tensorrt.ICudaEngine

Invoked with: <tensorrt.tensorrt.Runtime object at 0x7fe9510136f0>, None

```
## Environment

**TensorRT Version**: 
**NVIDIA GPU**: TITAN RTX  
**NVIDIA Driver Version**: 450.51.06
**CUDA Version**: 11.0
**CUDNN Version**: 8.2.1
**Operating System**: linux
**Python Version (if applicable)**: 3.9
**Tensorflow Version (if applicable)**: 2.5
**PyTorch Version (if applicable)**: -
**Baremetal or Container (if so, version)**: -

## Relevant Files

`models.py`
```python


import tensorflow as tf
import numpy as np




class MyLayer(tf.keras.layers.Layer):
    def __init__(self, **kwargs):
        super(MyLayer, self).__init__(**kwargs)

    def build(self, input_shape):
        self.dense1 = tf.keras.layers.Dense(5, name='dense1')
        self.dense2 = tf.keras.layers.Dense(5, name='dense2')

    def call(self, inputs, training=None, mask=None):
        out = self.dense1(inputs)
        out = self.dense2(out)
        return out


def build_model(input_shape=(100,)):
    input = tf.keras.layers.Input(shape=input_shape)
    mylayer = MyLayer(name='mylayer')
    output = mylayer(input)
    model = tf.keras.models.Model(inputs=input, outputs=output)
    return model


```

`build.py`
```python

import numpy.random
import tensorrt as trt
import numpy as np
from models import build_model

TRT_LOGGER = trt.Logger(trt.Logger.WARNING)


def get_weights(model):
    weights = {}
    for i in model.weights:
        weights[i.name.split(':')[0]] = i.numpy()

    return weights


def populate_network(network, weights):
    input_tensor = network.add_input(name="data", dtype=trt.float32, shape=(100,))

    fc1 = network.add_fully_connected(input=input_tensor,
                                      num_outputs=5,
                                      kernel=weights['mylayer/dense1/kernel'].T,
                                      bias=weights['mylayer/dense1/bias'])

    relu1 = network.add_activation(fc1.get_output(0),
                                   type=trt.ActivationType.RELU)

    fc2 = network.add_fully_connected(input=relu1.get_output(0), num_outputs=5,
                                      kernel=weights['mylayer/dense2/kernel'].T,
                                      bias=weights['mylayer/dense2/bias'])
    fc2.get_output(0).name = "prob"

    network.mark_output(tensor=fc2.get_output(0))


def build_engine(weights):
    builder = trt.Builder(TRT_LOGGER)
    network = builder.create_network()
    config = builder.create_builder_config()
    runtime = trt.Runtime(TRT_LOGGER)
    config.max_workspace_size = （1<<20）
    populate_network(network, weights)
    builder.max_batch_size = 1
    engine = builder.build_engine(network, config)
    return runtime.deserialize_cuda_engine(engine)


if __name__ == '__main__':
    model = build_model()
    weights = get_weights(model)
    engine = build_engine(weights)

```

## Steps To Reproduce

```python
python build.py
```

**Comment by SmileTM** [comment]
@rajeevsrao

**Comment by Huang9495** [comment]
same error for me

**Comment by zhafree** [comment]
same error, 2080Ti with window10

**Comment by nvpohanh** [comment]
@SmileTM Two things:

1. Please create the network with EXPLICIT_BATCH flag.
2. The input to the FullyConnected layers are expected to have at least 4 dimensions, while yours have only 1 dimension. 

Let me know if you still run into issues after these fixes. Thanks

**Comment by nvpohanh** [comment]
I am going to close this due to >2wk of no action. Please feel free to reopen if this issue still exists. Thanks!
