### ISSUE TITLE
Batch inference worked well in 21.06, but failed in latest 21.09. (with code snippet to reproduce)

### ISSUE THREAD

**Issue by siahuat0727** [NVIDIA/TensorRT#1548]
## Description

The batch inference for a BERT model (Hugging Face implementation) is incorrect in Release 21.09 except for the first sample (without any error message). The wrong results are random-like values (with same order of magnitude).

I found some related issues [1](https://forums.developer.nvidia.com/t/batch-inference-wrong-in-python-api/112183/12) [2](https://forums.developer.nvidia.com/t/output-of-batch-inference/72129) [3](https://github.com/dusty-nv/jetson-inference/issues/320) #842 and some are then reported as fixed without a clear conclusion.
[This issue](https://github.com/jkjung-avt/tensorrt_demos/issues/313) state that TensorRT 7.2 fix it.

So I try with Release 21.06 and it solve my problem!

I'm not sure if this is due to some bug in my code, so I pasted a reproducible code snippet below.
Additionally, I found that it works well when I replace BERT to a single fully-connected network. (see the TODO comment block)

## Environment

**Release 21.06 and Release 21.09**

**TensorRT Version**: 
**NVIDIA GPU**: P100
**NVIDIA Driver Version**: 470.57.02
**CUDA Version**: 11.4 
**CUDNN Version**: 
**Operating System**: Ubuntu 20.04
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**: 

## Steps To Reproduce

**Codes**

```python
# trt_utils.py
import os

import tensorrt as trt
import pycuda.driver as cuda
import numpy as np
import pycuda.autoinit


TRT_LOGGER = trt.Logger(trt.Logger.WARNING)

def build_engine(onnx_file_path, input_shape, max_batch_size):
    with trt.Builder(TRT_LOGGER) as builder, builder.create_network(1 << int(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)) as network, trt.OnnxParser(network, TRT_LOGGER) as parser:
        builder.max_batch_size = max_batch_size

        config = builder.create_builder_config()
        config.max_workspace_size = (1 << 32)
        profile = builder.create_optimization_profile()

        with open(onnx_file_path, 'rb') as model:
            parsing_succeed = parser.parse(model.read())
            assert parsing_succeed, 'Failed to parse the ONNX model'

        profile.set_shape('input', (2,) + input_shape, (2,) +
                          input_shape, (max_batch_size,) + input_shape)
        config.add_optimization_profile(profile)

        engine = builder.build_engine(network, config=config)
        assert engine, 'Failed to build the engine'
    return engine


class HostDeviceMem(object):
    def __init__(self, host_mem, device_mem):
        self.host = host_mem
        self.device = device_mem

    def __str__(self):
        return "Host:\n" + str(self.host) + "\nDevice:\n" + str(self.device)

    def __repr__(self):
        return self.__str__()


def allocate_buffers(engine):
    inputs = []
    outputs = []
    bindings = []
    stream = cuda.Stream()
    for binding in engine:
        size = trt.volume(engine.get_binding_shape(
            binding)[1:]) * engine.max_batch_size
        dtype = trt.nptype(engine.get_binding_dtype(binding))
        binding_index = engine.get_binding_index(binding)

        # Allocate host and device buffers
        host_mem = cuda.pagelocked_empty(size, dtype)
        # Only bytes, no need for size
        device_mem = cuda.mem_alloc(host_mem.nbytes)

        # Append the device buffer to device bindings.
        bindings.append(int(device_mem))

        # Append to the appropriate list.
        if engine.binding_is_input(binding):
            inputs.append(HostDeviceMem(host_mem, device_mem))
        else:
            outputs.append(HostDeviceMem(host_mem, device_mem))
    return inputs, outputs, bindings, stream
```

```python
# test.py
import numpy as np
import pycuda.driver as cuda
import torch
import torch.nn as nn
import onnxruntime
from transformers import BertConfig, BertModel

from trt_utils import allocate_buffers, build_engine


VEC_LEN = 512
BATCH_SIZE = 2
MAX_BATCH_SIZE = 32


class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        self.fc = nn.Linear(VEC_LEN, VEC_LEN)

    def forward(self, x):
        y = self.fc(x)
        return y, x


def assert_equality(pytorch_output, np_output, method=''):

    def extract_pytorch_output(tensor):
        return [
            tensor.last_hidden_state.numpy(),
            tensor.pooler_output.numpy(),
        ]

    def correct_rate(pytorch_output, np_output):
        def do_correct_rate(arr1, arr2):
            correct = np.isclose(
                arr1.flatten(), arr2.flatten(), atol=1e-05).sum()
            total = arr1.flatten().size
            return f'{correct}/{total}'
        return [
            do_correct_rate(arr1, arr2)
            for arr1, arr2 in zip(extract_pytorch_output(pytorch_output), np_output)
        ]

    assert all(
        np.allclose(arr1.flatten(), arr2.flatten(), atol=1e-05)
        for arr1, arr2 in zip(extract_pytorch_output(pytorch_output), np_output)
    ), (f"Output of {method} and PyTorch doesn't match.\n"
        f"Correct rate: {correct_rate(pytorch_output, np_output)}\n"
        f"{pytorch_output=}\n"
        f"{np_output=}\n")


def test():

    model = BertModel(BertConfig())
    input_ids = torch.randint(30522, (BATCH_SIZE, VEC_LEN), dtype=torch.long)

    # TODO: Uncomment this block to try simple fc net
    # model = Net()
    # input_ids = torch.rand((BATCH_SIZE, VEC_LEN))

    model.eval()

    with torch.no_grad():
        pytorch_output = model(input_ids)

    # ONNX
    onnx_model_path = 'net.onnx'
    torch.onnx.export(model, input_ids, onnx_model_path, export_params=True,
                      opset_version=13, verbose=False, input_names=['input'],
                      output_names=['output1', 'output2'],
                      dynamic_axes={'input': {0: 'batch_size'},
                                    'output1': {0: 'batch_size'},
                                    'output2': {0: 'batch_size'}},
                      )

    ort_session = onnxruntime.InferenceSession(onnx_model_path)
    onnx_output = ort_session.run(
        None, {ort_session.get_inputs()[0].name: input_ids.numpy()})

    assert_equality(pytorch_output, onnx_output, 'ONNXRuntime')
    print('ONNX Good!')

    # TensorRT
    engine = build_engine(onnx_model_path,
                          input_ids.size()[1:],
                          max_batch_size=MAX_BATCH_SIZE)

    context = engine.create_execution_context()
    context.set_binding_shape(0, input_ids.size())

    inputs, outputs, bindings, stream = allocate_buffers(engine)
    inputs[0].host[:input_ids.nelement()] = np.asarray(input_ids).ravel()

    [cuda.memcpy_htod(inp.device, inp.host) for inp in inputs]
    success = context.execute_v2(bindings=bindings)
    print(f'TensorRT exec {success=}')
    [cuda.memcpy_dtoh(out.host, out.device) for out in outputs]

    trt_output = [
        out.host.reshape(MAX_BATCH_SIZE, -1)[:BATCH_SIZE]
        for out in outputs
    ]

    assert_equality(pytorch_output, trt_output, 'TensorRT')
    print('TensorRT Good!')


test()
```

**Run**

```
python3 test.py
```

**Output of Release 21.06**

```
/usr/local/lib/python3.8/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py:350: UserWarning: Deprecation warning. This ORT build has ['CUDAExecutionProvider', 'CPUExecutionProvider'] enabled. The next release (ORT 1.10) will require explicitly setting the providers parameter (as opposed to the current behavior of providers getting set/registered by default based on the build flags) when instantiating InferenceSession.For example, onnxruntime.InferenceSession(..., providers=["CUDAExecutionProvider"], ...)
  warnings.warn("Deprecation warning. This ORT build has {} enabled. ".format(available_providers) +
ONNX Good!
[TensorRT] WARNING: /home/jenkins/agent/workspace/OSS/OSS_L0_MergeRequest/oss/parsers/onnx/onnx2trt_utils.cpp:271: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: Output type must be INT32 for shape outputs
TensorRT exec success=True
TensorRT Good!
```

**Output of Release 21.09**

```
/usr/local/lib/python3.8/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py:350: UserWarning: Deprecation warning. This ORT build has ['CUDAExecutionProvider', 'CPUExecutionProvider'] enabled. The next release (ORT 1.10) will require explicitly setting the providers parameter (as opposed to the current behavior of providers getting set/registered by default based on the build flags) when instantiating InferenceSession.For example, onnxruntime.InferenceSession(..., providers=["CUDAExecutionProvider"], ...)
  warnings.warn("Deprecation warning. This ORT build has {} enabled. ".format(available_providers) +
ONNX Good!
[TensorRT] WARNING: onnx2trt_utils.cpp:362: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: Output type must be INT32 for shape outputs
[TensorRT] WARNING: Detected invalid timing cache, setup a local cache instead
TensorRT exec success=True
Traceback (most recent call last):
  File "bert_snippet.py", line 111, in <module>
    test()
  File "bert_snippet.py", line 107, in test
    assert_equality(pytorch_output, trt_output, 'TensorRT')
  File "bert_snippet.py", line 46, in assert_equality
    assert all(
AssertionError: Output of TensorRT and PyTorch doesn't match.
Correct rate: ['393222/786432', '768/1536']
pytorch_output=BaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=tensor([[[ 0.0546,  0.2669,  0.8374,  ..., -0.7832, -0.5110, -0.9227],
         [-0.1837, -0.3121, -0.2003,  ..., -0.7889,  0.2879, -0.0161],
         [ 0.2569, -0.9711,  1.9910,  ...,  0.0300, -1.0024, -0.6459],
         ...,
         [ 1.1023,  0.0119,  1.8955,  ...,  0.0562, -0.2778,  0.7635],
         [-0.1440, -0.5040,  0.9521,  ...,  1.1965,  0.1977, -0.7471],
         [-0.5223, -1.4304, -0.0173,  ...,  0.2297, -0.4449, -0.2978]],

        [[ 0.6351, -0.1982, -0.2601,  ...,  0.4886,  0.0689,  0.7333],
         [-1.1930, -0.3422,  1.1272,  ...,  0.4254, -0.2549, -0.1675],
         [ 1.2090, -0.4521,  1.7832,  ..., -0.4979, -0.5859, -0.1861],
         ...,
         [ 1.1340, -0.3403,  2.0484,  ...,  0.1718, -0.0468, -0.4998],
         [ 0.5129, -0.6067,  1.0069,  ...,  0.4663, -0.7445,  0.6771],
         [ 0.0607, -1.0137,  1.8691,  ...,  0.2961,  0.1203,  0.4264]]]), pooler_output=tensor([[-0.1826,  0.0255, -0.2046,  ...,  0.2922,  0.8912,  0.3630],
        [-0.1114,  0.0243, -0.6291,  ...,  0.2883,  0.8470,  0.5640]]), hidden_states=None, past_key_values=None, attentions=None, cross_attentions=None)
np_output=[array([[ 0.05455616,  0.26694223,  0.8373928 , ...,  0.22968616,
        -0.4449291 , -0.29782966],
       [ 0.52241874, -0.3795954 ,  0.44035733, ..., -0.81233   ,
        -0.27850032,  0.01815133]], dtype=float32), array([[-0.18258236,  0.02551227, -0.20462437, ...,  0.2921529 ,
         0.891194  ,  0.36304623],
       [-0.37625638,  0.14089146, -0.61692894, ...,  0.28234258,
         0.63531446,  0.2062083 ]], dtype=float32)
```

**Comment by oxana-nvidia** [comment]
Hi @siahuat0727,

Could you please try more recent version of TensorRT?
you test is passing for me when I'm using TensorRT 8.4:

```
~/trt$ python3 test.py
ONNX Good!
[05/26/2022-11:11:12] [TRT] [W] onnx2trt_utils.cpp:367: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[05/26/2022-11:12:16] [TRT] [W] The getMaxBatchSize() function should not be used with an engine built from a network created with NetworkDefinitionCreationFlag::kEXPLICIT_BATCH flag. This function will always return 1.
[05/26/2022-11:12:16] [TRT] [W] The getMaxBatchSize() function should not be used with an engine built from a network created with NetworkDefinitionCreationFlag::kEXPLICIT_BATCH flag. This function will always return 1.
[05/26/2022-11:12:16] [TRT] [W] The getMaxBatchSize() function should not be used with an engine built from a network created with NetworkDefinitionCreationFlag::kEXPLICIT_BATCH flag. This function will always return 1.
TensorRT exec success=True
TensorRT Good!

```

**Comment by siahuat0727** [comment]
Ok. Thanks!
