### ISSUE TITLE
HuggingFace GPT-2 large example failed

### ISSUE THREAD

**Issue by vinhngx** [NVIDIA/TensorRT#1559]
## Description

I have been trying the HuggingFace GPT-2 large example without success on both V100 32GB and A100 80GB.

Follow instruction in https://github.com/NVIDIA/TensorRT/tree/master/demo/HuggingFace

Then execute GPT-2 large. On A100 80GB it produces:
```
trtuser@2f6656b9f82c:/workspace/TensorRT/demo/HuggingFace$ python3 run.py run GPT2 trt --variant gpt2-large --working-dir ./temp
2021-10-17 03:15:23.899425: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
Frameworks file already exists, skipping generation and loading from file instead.
[10/17/2021-03:15:38] [TRT] [E] 1: [stdArchiveReader.cpp::StdArchiveReader::54] Error Code 1: Serialization (Serialization assertion sizeRead == static_cast<uint64_t>(mEnd - mCurrent) failed.Size specified in header does not match archive size)
[10/17/2021-03:15:38] [TRT] [E] 4: [runtime.cpp::deserializeCudaEngine::50] Error Code 4: Internal Error (Engine deserialization failed.)
Traceback (most recent call last):
  File "run.py", line 233, in <module>
    main()
  File "run.py", line 229, in main
    return action.execute(known_args)
  File "run.py", line 81, in execute
    print(module.RUN_CMD())
  File "/workspace/TensorRT/demo/HuggingFace/NNDF/interface.py", line 229, in __call__
    warmup=int(self._args.warmup),
  File "/workspace/TensorRT/demo/HuggingFace/GPT2/trt.py", line 225, in run_trt
    self.gpt2_trt = GPT2TRTDecoder(self.gpt2_engine, metadata, tfm_config)
  File "/workspace/TensorRT/demo/HuggingFace/GPT2/trt.py", line 83, in __init__
    super().__init__(trt_engine_file, network_metadata, hf_config)
  File "/workspace/TensorRT/demo/HuggingFace/GPT2/trt.py", line 73, in __init__
    super().__init__(trt_engine_file, network_metadata)
  File "/workspace/TensorRT/demo/HuggingFace/NNDF/tensorrt_utils.py", line 73, in __init__
    self.trt_context = self.trt_engine.create_execution_context()
AttributeError: 'NoneType' object has no attribute 'create_execution_context'
```
## Environment

**TensorRT Version**: 
**NVIDIA GPU**: 
**NVIDIA Driver Version**: 
**CUDA Version**: 
**CUDNN Version**: 
**Operating System**: 
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**:

**Comment by vinhngx** [comment]
Resolved. TRT OSS build was not the latest.
