### ISSUE TITLE
from .tensorrt import * ImportError: DLL load failed: The specified procedure could not be found.

### ISSUE THREAD

**Issue by moezet01** [NVIDIA/TensorRT#1620]
I am new to TensorRT and I try to run Python sample, "end_to_end_tensorflow_mnist" on Windows OS. I used TensorRT version 8.2 (zip installation file for Windows) and I faced with following error when I run sample.py:

Traceback (most recent call last):
  File "sample.py", line 26, in <module>
    import tensorrt as trt
  File "C:\anaconda3\envs\tensorRT\lib\site-packages\tensorrt\__init__.py", line 195, in <module>
    from .tensorrt import *
ImportError: DLL load failed: The specified procedure could not be found.

And I also found that the tensorrt cannot import as well.

>>>import tensorrt as trt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\anaconda3\envs\tensorRT\lib\site-packages\tensorrt\__init__.py", line 195, in <module>
    from .tensorrt import *
ImportError: DLL load failed: The specified procedure could not be found.

I would like to request guidelines and instructions to implement TensorRT on Windows OS.
Thank you!

Environment
TensorRT Version: 8.2.0.6 
NVIDIA GPU: Quadro RTX 8000 
CUDA Version: 10.1 
CUDNN Version: 7.6 
Operating System: Windows 10 
Python Version: 3.6 
Tensorflow Version: 1.15.0

**Comment by ttyio** [comment]
hello @moezet01 , could you check the installation guide in https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html#installing-zip? 
Notice python support for Windows included in the zip package is considered a preview release and not ready for production use. thanks!

**Comment by ttyio** [comment]
close since no activity for more than 3 weeks, please reopen if you still have question, thanks!
