### ISSUE TITLE
pytorch-quantization 2.1.1 Problem.

### ISSUE THREAD

**Issue by Water2style** [NVIDIA/TensorRT#1685]
When we follow the tutorial in https://docs.nvidia.com/deeplearning/tensorrt/pytorch-quantization-toolkit/docs/tutorials/quant_resnet50.html.

We follow https://docs.nvidia.com/deeplearning/tensorrt/pytorch-quantization-toolkit/docs/userguide.html#export-to-onnx and try to export it to ONNX. The error occurs:

Traceback (most recent call last):
File "/home/lnc/.local/lib/python3.9/site-packages/torch/onnx/utils.py", line 785, in _export
_check_onnx_proto(proto)
RuntimeError: Unrecognized attribute: axis for operator QuantizeLinear

==> Context: Bad node spec for node. Name: QuantizeLinear_7 OpType: QuantizeLinear

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/media/lnc/Samsung_T5/Chalmers/MaterThesis/auto vehicle/test.py", line 22, in <module>
torch.onnx.export(
File "/home/lnc/.local/lib/python3.9/site-packages/torch/onnx/__init__.py", line 316, in export
return utils.export(model, args, f, export_params, verbose, training,
File "/home/lnc/.local/lib/python3.9/site-packages/torch/onnx/utils.py", line 107, in export
_export(model, args, f, export_params, verbose, training, input_names, output_names,
File "/home/lnc/.local/lib/python3.9/site-packages/torch/onnx/utils.py", line 787, in _export
raise ONNXCheckerError(e)
torc

**Comment by Water2style** [comment]
Ok, I sloved it by editing:
opset_version=10  to opset_version=13

torch.onnx.export(model, dummy_input, "quant_resnet50.onnx", verbose=True, opset_version=13, enable_onnx_checker=False)

**Comment by ttyio** [comment]
Cool, closing since this is solved.
