### ISSUE TITLE
Bert plugin occurred core dump during concurrency

### ISSUE THREAD

**Issue by mdztravelling** [NVIDIA/TensorRT#1748]
## Description

bert plugin occurred core dump when multiple concurrent ,  the code location where segfault cocurred  is 
plugin/embLayerNormPlugin/embLayerNormVarSeqlenPlugin.cpp gLogVerbose, because gLogVerbose `operator << ` is not thread  safe that use `std::ostrem` and `std::stringbuf`.
```
void EmbLayerNormVarSeqlenPluginHFace::configurePlugin(const DynamicPluginTensorDesc* inputs, int32_t nbInputs,
    const DynamicPluginTensorDesc* outputs, int32_t nbOutputs) noexcept
{
    gLogVerbose << "EmbLayerNormVarSeqlenPluginHFace configurePlugin\n";
    ...
}
```
```
template <ILogger::Severity kSeverity>
class LogStream : public std::ostream
{
    class Buf : public std::stringbuf
    {   
    public:
        int sync() override;
    };  

    Buf buffer;

public:
    LogStream() : std::ostream(&buffer) {}; 
};

extern LogStream<ILogger::Severity::kERROR> gLogError;
extern LogStream<ILogger::Severity::kWARNING> gLogWarning;
extern LogStream<ILogger::Severity::kINFO> gLogInfo;
extern LogStream<ILogger::Severity::kVERBOSE> gLogVerbose;

```

And the stack information of core dump as bellow.
```
(gdb) bt
#0  0x00007fd5f4679e85 in __memmove_avx_unaligned_erms () from /lib64/libc.so.6
#1  0x000000000043e2a8 in std::char_traits<char>::copy (__n=<optimized out>, __s2=<optimized out>, __s1=<optimized out>)
    at /usr/include/c++/8/bits/char_traits.h:352
#2  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_S_copy (__n=<optimized out>, __s=<optimized out>, 
    __d=<optimized out>) at /usr/include/c++/8/bits/basic_string.h:340
#3  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace (this=0x7fd5abfc8e80, __pos=<optimized out>, 
    __len1=<optimized out>, __s=0x7fd3ddfeb010 <error: Cannot access memory at address 0x7fd3ddfeb010>, __len2=33554432)
    at /usr/include/c++/8/bits/basic_string.tcc:440
#4  0x00007fd5f4f9920a in std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::overflow(int) ()
   from /lib64/libstdc++.so.6
#5  0x00007fd5f4fa3d2b in std::basic_streambuf<char, std::char_traits<char> >::xsputn(char const*, long) () from /lib64/libstdc++.so.6
#6  0x00007fd5f4f93d74 in std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, long) () from /lib64/libstdc++.so.6
#7  0x00007fd60985616f in std::operator<< <std::char_traits<char> > (__out=..., 
    __s=0x7fd6098d4998 "EmbLayerNormVarSeqlenPluginHFace configurePlugin\n") at /usr/include/c++/8/bits/char_traits.h:322
#8  bert::EmbLayerNormVarSeqlenPluginHFace::configurePlugin (this=0x1c852980, inputs=0x7fd124084440, nbInputs=4, outputs=0x7fd124013be0, nbOutputs=2)
    at /search/odin/modanzeng/work/model_serving/tensorrt-oss/plugin/embLayerNormPlugin/embLayerNormVarSeqlenPlugin.cpp:303
#9  0x00007fd60d570f62 in ?? () from /search/odin/modanzeng/work/model_serving/debug/model_server/third_party/tensorrt/lib/libnvinfer.so.8
#10 0x00007fd60d61e48a in ?? () from /search/odin/modanzeng/work/model_serving/debug/model_server/third_party/tensorrt/lib/libnvinfer.so.8
#11 0x00007fd60d62393d in ?? () from /search/odin/modanzeng/work/model_serving/debug/model_server/third_party/tensorrt/lib/libnvinfer.so.8
#12 0x00007fd60d6242d8 in ?? () from /search/odin/modanzeng/work/model_serving/debug/model_server/third_party/tensorrt/lib/libnvinfer.so.8
#13 0x0000000000499848 in nvinfer1::IExecutionContext::enqueueV2 (this=<optimized out>, inputConsumed=0x0, stream=<optimized out>, 
    bindings=<optimized out>) at /search/odin/test/work/model_serving/debug/model_server/third_party/tensorrt/include/NvInferRuntime.h:2233
#14 model_server::TRTContext::Run (this=0x340b6a00, input=..., output=..., model_config=...)
...
```

Please confirm this bug.

## Environment

**TensorRT Version**:   8.0.3
**NVIDIA GPU**:  T4
**NVIDIA Driver Version**:  465.19.01
**CUDA Version**:  11.3
**CUDNN Version**:  8.2
**Operating System**:  CentOS 8.2
**Python Version (if applicable)**:  
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**:

**Comment by ttyio** [comment]
@mdztravelling yes, the logger stream in trt core is thread safe, but not in plugin. I have created internal issue to track this, you can either add mutex or remove the log in plugin to unblock yourself, thanks!

**Comment by ttyio** [comment]
This will be fixed in 8.4GA, thanks!

**Comment by nvpohanh** [comment]
@mdztravelling Could you try TRT 8.4 and see if it's fixed? Thanks

**Comment by ttyio** [comment]
closing due to no activity for more than 3 weeks, please reopen if you still have question, thanks!
