### ISSUE TITLE
Pytorch_Quantization QAT export to onnx failed: RuntimeError: Zero-point must be Long, found Int

### ISSUE THREAD

**Issue by bigsheep2012** [NVIDIA/TensorRT#1763]
@ttyio hello, 

## Description
I followed the examples here: 
1) calibrate and finetune: https://docs.nvidia.com/deeplearning/tensorrt/pytorch-quantization-toolkit/docs/tutorials/quant_resnet50.html
2) export to onnx: https://docs.nvidia.com/deeplearning/tensorrt/pytorch-quantization-toolkit/docs/userguide.html#export-to-onnx 

I got the following logs: 
WARNING: Logging before flag parsing goes to stderr.
W0127 16:49:16.806731 140187533513664 tensor_quantizer.py:280] Use Pytorch's native experimental fake quantization.
/home/lin/anaconda3/envs/torch19/lib/python3.8/site-packages/pytorch_quantization-2.1.2-py3.8-linux-x86_64.egg/pytorch_quantization/nn/modules/tensor_quantizer.py:285: TracerWarning: Converting a tensor to a Python number might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  inputs, amax.item() / bound, 0,
/home/lin/anaconda3/envs/torch19/lib/python3.8/site-packages/pytorch_quantization-2.1.2-py3.8-linux-x86_64.egg/pytorch_quantization/nn/modules/tensor_quantizer.py:291: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  quant_dim = list(amax.shape).index(list(amax_sequeeze.shape)[0])
Traceback (most recent call last):
  File "quantization/tensorrt/to_onnx_quant_model.py", line 29, in <module>
    torch.onnx.export(model, dummy_input, "model_quant_percentile.onnx", verbose=True, opset_version=10, enable_onnx_checker=False)
  File "/home/lin/anaconda3/envs/torch19/lib/python3.8/site-packages/torch/onnx/__init__.py", line 275, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/home/lin/anaconda3/envs/torch19/lib/python3.8/site-packages/torch/onnx/utils.py", line 88, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/home/lin/anaconda3/envs/torch19/lib/python3.8/site-packages/torch/onnx/utils.py", line 689, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/home/lin/anaconda3/envs/torch19/lib/python3.8/site-packages/torch/onnx/utils.py", line 458, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args,
  File "/home/lin/anaconda3/envs/torch19/lib/python3.8/site-packages/torch/onnx/utils.py", line 422, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/home/lin/anaconda3/envs/torch19/lib/python3.8/site-packages/torch/onnx/utils.py", line 373, in _trace_and_get_graph_from_model
    torch.jit._get_trace_graph(model, args, strict=False, _force_outplace=False, _return_inputs_states=True)
  File "/home/lin/anaconda3/envs/torch19/lib/python3.8/site-packages/torch/jit/_trace.py", line 1160, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/home/lin/anaconda3/envs/torch19/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lin/anaconda3/envs/torch19/lib/python3.8/site-packages/torch/jit/_trace.py", line 127, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "/home/lin/anaconda3/envs/torch19/lib/python3.8/site-packages/torch/jit/_trace.py", line 118, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/home/lin/anaconda3/envs/torch19/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lin/anaconda3/envs/torch19/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1039, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/lindisk/train_framework/quantization/tensorrt/models/cnnseg_quant.py", line 112, in forward
    shallow_feature_1 = self.conv_seg_1(x)
  File "/home/lin/anaconda3/envs/torch19/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lin/anaconda3/envs/torch19/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1039, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/lin/anaconda3/envs/torch19/lib/python3.8/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/home/lin/anaconda3/envs/torch19/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lin/anaconda3/envs/torch19/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1039, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/lin/anaconda3/envs/torch19/lib/python3.8/site-packages/pytorch_quantization-2.1.2-py3.8-linux-x86_64.egg/pytorch_quantization/nn/modules/quant_conv.py", line 119, in forward
    quant_input, quant_weight = self._quant(input)
  File "/home/lin/anaconda3/envs/torch19/lib/python3.8/site-packages/pytorch_quantization-2.1.2-py3.8-linux-x86_64.egg/pytorch_quantization/nn/modules/quant_conv.py", line 85, in _quant
    quant_weight = self._weight_quantizer(self.weight)
  File "/home/lin/anaconda3/envs/torch19/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lin/anaconda3/envs/torch19/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1039, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/lin/anaconda3/envs/torch19/lib/python3.8/site-packages/pytorch_quantization-2.1.2-py3.8-linux-x86_64.egg/pytorch_quantization/nn/modules/tensor_quantizer.py", line 345, in forward
    outputs = self._quant_forward(inputs)
  File "/home/lin/anaconda3/envs/torch19/lib/python3.8/site-packages/pytorch_quantization-2.1.2-py3.8-linux-x86_64.egg/pytorch_quantization/nn/modules/tensor_quantizer.py", line 313, in _quant_forward
    outputs = self._fb_fake_quant(inputs, amax)
  File "/home/lin/anaconda3/envs/torch19/lib/python3.8/site-packages/pytorch_quantization-2.1.2-py3.8-linux-x86_64.egg/pytorch_quantization/nn/modules/tensor_quantizer.py", line 293, in _fb_fake_quant
    outputs = torch.fake_quantize_per_channel_affine(
RuntimeError: Zero-point must be Long, found Int

## Environment

**TensorRT Version**: 8.2.2
**NVIDIA GPU**: 3090
**NVIDIA Driver Version**:  
**CUDA Version**: 10.2
**CUDNN Version**: 8.2.2
**Operating System**: ubuntu 18.04
**Python Version (if applicable)**: 3.8
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 1.9.0
**Baremetal or Container (if so, version)**: 

## Relevant Files

The zip file contains 
1) the model.pth, calibrated && finetuned
2) the model.py, the model file re-implemented with quant_nn 
3) the to_onnx.py, the code export to .onnx

## Steps To Reproduce
python to_onnx.py

**Comment by bigsheep2012** [comment]
it seems the .zip is too large to upload 
check the link: https://pan.baidu.com/s/1jpZE66RSWjOoKCBtDz0j1Q?pwd=gkmk 
code: gkmk

**Comment by ttyio** [comment]
@bigsheep2012 , have you tried the container `nvcr.io/nvidia/pytorch:21.09-py3`? We have not test baremetal, thanks!

**Comment by bigsheep2012** [comment]
@ttyio , tried the mentioned container and got the same error.
root@5bebd387df0d:/lindisk/quantization# python to_onnx.py
"...
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1056, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1044, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_quantization/nn/modules/tensor_quantizer.py", line 345, in forward
    outputs = self._quant_forward(inputs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_quantization/nn/modules/tensor_quantizer.py", line 313, in _quant_forward
    outputs = self._fb_fake_quant(inputs, amax)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_quantization/nn/modules/tensor_quantizer.py", line 293, in _fb_fake_quant
    outputs = torch.fake_quantize_per_channel_affine(
RuntimeError: Zero-point must be Int32, found Long
"
Plz let me know if there is any update.

**Comment by boba-milk-tea** [comment]
I have to modify this file: pytorch_quantization/nn/modules/tensor_quantizer.py line 293 to get by           

            #outputs = torch.fake_quantize_per_channel_affine(
            #    inputs, scale.data, torch.zeros_like(scale, dtype=torch.int32).data, quant_dim,
            #    -bound - 1 if not self._unsigned else 0, bound)
            outputs = torch.fake_quantize_per_channel_affine(
                inputs, scale.data, torch.zeros_like(scale, dtype=torch.long).data, quant_dim,
                -bound - 1 if not self._unsigned else 0, bound)

Not sure if this is the right way to do it.

**Comment by ttyio** [comment]
hmmm,  I checked latest toolkit we use `torch.int32`

https://github.com/NVIDIA/TensorRT/blob/main/tools/pytorch-quantization/pytorch_quantization/nn/modules/tensor_quantizer.py#L294

After more grep, I found the reason why we use `torch.long` at first is that the first commit in `pytorch` use this, see https://github.com/pytorch/pytorch/commit/7363da7c57729d70532b647935dd6a9e68be612a, and the data type updated to `torch.int32` later in https://github.com/pytorch/pytorch/commit/7a15576a65715e7bcba017e5c2fa755610a0db22.

Also I checked the newer container `nvcr.io/nvidia/pytorch:21.12-py3` uses `torch.int32`, could you take a try? thanks!

**Comment by wywywy01** [comment]
refer : https://github.com/NVIDIA/TensorRT/pull/1606

**Comment by ttyio** [comment]
Closing since the latest commit already fixed the issue. Thanks!

**Comment by DAVID-Hown** [comment]
`WARNING: Logging before flag parsing goes to stderr.
W1215 06:33:56.869878 140371805468480 tensor_quantizer.py:281] Use Pytorch's native experimental fake quantization.
/root/anaconda3/envs/tres/lib/python3.6/site-packages/pytorch_quantization/nn/modules/tensor_quantizer.py:286: TracerWarning: Converting a tensor to a Python number might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  inputs, amax.item() / bound, 0,
/root/anaconda3/envs/tres/lib/python3.6/site-packages/pytorch_quantization/nn/modules/tensor_quantizer.py:292: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  quant_dim = list(amax.shape).index(list(amax_sequeeze.shape)[0])
Traceback (most recent call last):
  File "/workspace/docker/TReS/IQA_INT8/convert_to_onnx.py", line 38, in <module>
    do_constant_folding=True)
  File "/root/anaconda3/envs/tres/lib/python3.6/site-packages/torch/onnx/__init__.py", line 276, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/root/anaconda3/envs/tres/lib/python3.6/site-packages/torch/onnx/utils.py", line 94, in export
    use_external_data_format=use_external_data_format)
  File "/root/anaconda3/envs/tres/lib/python3.6/site-packages/torch/onnx/utils.py", line 698, in _export
    dynamic_axes=dynamic_axes)
  File "/root/anaconda3/envs/tres/lib/python3.6/site-packages/torch/onnx/utils.py", line 456, in _model_to_graph
    use_new_jit_passes)
  File "/root/anaconda3/envs/tres/lib/python3.6/site-packages/torch/onnx/utils.py", line 417, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/root/anaconda3/envs/tres/lib/python3.6/site-packages/torch/onnx/utils.py", line 377, in _trace_and_get_graph_from_model
    torch.jit._get_trace_graph(model, args, strict=False, _force_outplace=False, _return_inputs_states=True)
  File "/root/anaconda3/envs/tres/lib/python3.6/site-packages/torch/jit/_trace.py", line 1139, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/root/anaconda3/envs/tres/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/envs/tres/lib/python3.6/site-packages/torch/jit/_trace.py", line 130, in forward
    self._force_outplace,
  File "/root/anaconda3/envs/tres/lib/python3.6/site-packages/torch/jit/_trace.py", line 116, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/root/anaconda3/envs/tres/lib/python3.6/site-packages/torch/nn/modules/module.py", line 887, in _call_impl
    result = self._slow_forward(*input, **kwargs)
  File "/root/anaconda3/envs/tres/lib/python3.6/site-packages/torch/nn/modules/module.py", line 860, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/workspace/docker/TReS/IQA_INT8/models.py", line 98, in forward
    layer1, layer2, layer3, layer4 = self.model(x)
  File "/root/anaconda3/envs/tres/lib/python3.6/site-packages/torch/nn/modules/module.py", line 887, in _call_impl
    result = self._slow_forward(*input, **kwargs)
  File "/root/anaconda3/envs/tres/lib/python3.6/site-packages/torch/nn/modules/module.py", line 860, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/workspace/docker/TReS/IQA_INT8/resnet_modify.py", line 245, in forward
    return self._forward_impl(x)
  File "/workspace/docker/TReS/IQA_INT8/resnet_modify.py", line 225, in _forward_impl
    x = self.conv1(x)
  File "/root/anaconda3/envs/tres/lib/python3.6/site-packages/torch/nn/modules/module.py", line 887, in _call_impl
    result = self._slow_forward(*input, **kwargs)
  File "/root/anaconda3/envs/tres/lib/python3.6/site-packages/torch/nn/modules/module.py", line 860, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/envs/tres/lib/python3.6/site-packages/pytorch_quantization/nn/modules/quant_conv.py", line 120, in forward
    quant_input, quant_weight = self._quant(input)
  File "/root/anaconda3/envs/tres/lib/python3.6/site-packages/pytorch_quantization/nn/modules/quant_conv.py", line 86, in _quant
    quant_weight = self._weight_quantizer(self.weight)
  File "/root/anaconda3/envs/tres/lib/python3.6/site-packages/torch/nn/modules/module.py", line 887, in _call_impl
    result = self._slow_forward(*input, **kwargs)
  File "/root/anaconda3/envs/tres/lib/python3.6/site-packages/torch/nn/modules/module.py", line 860, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/envs/tres/lib/python3.6/site-packages/pytorch_quantization/nn/modules/tensor_quantizer.py", line 346, in forward
    outputs = self._quant_forward(inputs)
  File "/root/anaconda3/envs/tres/lib/python3.6/site-packages/pytorch_quantization/nn/modules/tensor_quantizer.py", line 314, in _quant_forward
    outputs = self._fb_fake_quant(inputs, amax)
  File "/root/anaconda3/envs/tres/lib/python3.6/site-packages/pytorch_quantization/nn/modules/tensor_quantizer.py", line 296, in _fb_fake_quant
    -bound - 1 if not self._unsigned else 0, bound)
RuntimeError: Zero-point must be Long, found Int

Process finished with exit code 1`
