### ISSUE TITLE
Fail to convert simple threshold model 

### ISSUE THREAD

**Issue by elinep** [NVIDIA/TensorRT#1773]
## Description

A simple onnx model which apply a threshold on the input data fails to convert to trt v8 while it used to work with trt v7.

## Environment

**TensorRT Version**: 8.2.3.0
**NVIDIA GPU**: GeForce GTX 1080 ti
**NVIDIA Driver Version**: 460.91.03
**CUDA Version**: 
**CUDNN Version**: 
**Operating System**: Ubuntu 20.04.3 LTS
**Python Version (if applicable)**: 3.6
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 1.8
**Baremetal or Container (if so, version)**: 

## Relevant Files

The onnx model that cause troubles.
[threshold.zip](https://github.com/NVIDIA/TensorRT/files/7977549/threshold.zip)

## Steps To Reproduce

The script I use to reproduce the error :

```
import torch
import tensorrt as trt

TRT_LOGGER = trt.Logger(trt.Logger.WARNING)
trt_runtime = trt.Runtime(TRT_LOGGER)


def tensorrt_export(onnx_path, input_values):
    with trt.Builder(TRT_LOGGER) as builder, builder.create_network(
        1
    ) as network, builder.create_builder_config() as config, trt.OnnxParser(
        network, TRT_LOGGER
    ) as parser:
        config.max_workspace_size = 256 << 20
        with open(onnx_path, "rb") as model:
            parser.parse(model.read())
            network.get_input(0).shape = input_values.shape
        engine = builder.build_engine(network, config)

        assert engine is not None


class Model(torch.nn.Module):
    def forward(self, x):
        mask = (x > 0.).float()  # ko
        return mask


if __name__ == "__main__":
    ONNX_PATH = "/tmp/threshold.onnx"
    model = Model()
    input_x = torch.rand(1, 32)

    # torch inference
    model(input_x)

    # generate the ONNX model (the result has been posted in the "Relevant Files" section of this issue
    torch.onnx.export(
        model,
        input_x,
        ONNX_PATH,
        verbose=True,
        input_names=["x"],
        output_names=["output"],
        opset_version=11,
    )

    # convert to TRT
    tensorrt_export(ONNX_PATH, input_x)
```

This script runs correctly with trt v7 but fails with trt v8.

Below are the command I use to switch between trt v7 and v8 :
```
# install trt 7
pip install nvidia-tensorrt==7.1.3.4 --extra-index-url https://pypi.ngc.nvidia.com
# install trt 8
pip install nvidia-tensorrt==8.2.3.0 --extra-index-url https://pypi.ngc.nvidia.com```
```

Below is the log I get when trying to run the script with trt 8:
```
graph(%x : Float(1, 32, strides=[32, 1], requires_grad=0, device=cpu)):
  %1 : Float(requires_grad=0, device=cpu) = onnx::Constant[value={0}]()
  %2 : Bool(1, 32, strides=[32, 1], requires_grad=0, device=cpu) = onnx::Greater(%x, %1) # /home/peline/Code/anomaly-detection-torch/VAEtrain_package/test/nvidia_issue.py:25:0
  %output : Float(1, 32, strides=[32, 1], requires_grad=0, device=cpu) = onnx::Cast[to=1](%2) # /home/peline/Code/anomaly-detection-torch/VAEtrain_package/test/nvidia_issue.py:25:0
  return (%output)

[02/01/2022-11:15:13] [TRT] [W] TensorRT was linked against cuBLAS/cuBLAS LT 11.6.5 but loaded cuBLAS/cuBLAS LT 11.5.1
[02/01/2022-11:15:13] [TRT] [W] TensorRT was linked against cuDNN 8.2.1 but loaded cuDNN 8.2.0
Traceback (most recent call last):
  File "/home/peline/Code/anomaly-detection-torch/VAEtrain_package/test/nvidia_issue.py", line 49, in <module>
    tensorrt_export(ONNX_PATH, input_x)
  File "/home/peline/Code/anomaly-detection-torch/VAEtrain_package/test/nvidia_issue.py", line 20, in tensorrt_export
    assert engine is not None
AssertionError
[02/01/2022-11:15:14] [TRT] [W] Skipping tactic 0 due to Myelin error: cuBLAS error 1 querying major version.
[02/01/2022-11:15:14] [TRT] [E] 10: [optimizer.cpp::computeCosts::2011] Error Code 10: Internal Error (Could not find any implementation for node {ForeignNode[1 + (Unnamed Layer* 1) [Shuffle]...Cast_2]}.)

Process finished with exit code 1
```

Note that I manage to convert some other model, so my setup doesn't seem totaly wrong.
I tried to fix the cudnn/cublas warning but from my understanding these libraries are shipped by nvidia-tensorrt when we install it via pip.

**Comment by VikasOjha666** [comment]
From this part 'Internal Error (Could not find any implementation for node {ForeignNode[1 + (Unnamed Layer* 1) [Shuffle]...Cast_2]}.)' it appears like the particular layer or operation is not supported by TensorRT 8 although I am not sure. One of the possibilities could be something is wrong with your installation of TensorRT. May be you should try once with docker version of TensorRT 8.2

**Comment by elinep** [comment]
Thanks for the advice.

Indeed it works within the docker (https://docs.nvidia.com/deeplearning/tensorrt/container-release-notes/running.html)

I reinstalled my venv on the host and got rid of the library mismatch warnings.

But I still have a cublas error when running the script.
```
graph(%x : Float(1, 32, strides=[32, 1], requires_grad=0, device=cpu)):
  %1 : Float(requires_grad=0, device=cpu) = onnx::Constant[value={0}]()
  %2 : Bool(1, 32, strides=[32, 1], requires_grad=0, device=cpu) = onnx::Greater(%x, %1) # /home/peline/Code/anomaly-detection-torch/VAEtrain_package/test/nvidia_issue.py:25:0
  %output : Float(1, 32, strides=[32, 1], requires_grad=0, device=cpu) = onnx::Cast[to=1](%2) # /home/peline/Code/anomaly-detection-torch/VAEtrain_package/test/nvidia_issue.py:25:0
  return (%output)

Traceback (most recent call last):
  File "/home/peline/Code/anomaly-detection-torch/VAEtrain_package/test/nvidia_issue.py", line 49, in <module>
    tensorrt_export(ONNX_PATH, input_x)
  File "/home/peline/Code/anomaly-detection-torch/VAEtrain_package/test/nvidia_issue.py", line 20, in tensorrt_export
    assert engine is not None
AssertionError
[02/02/2022-10:27:34] [TRT] [W] Skipping tactic 0 due to Myelin error: cuBLAS error 1 querying major version.
[02/02/2022-10:27:34] [TRT] [E] 10: [optimizer.cpp::computeCosts::2011] Error Code 10: Internal Error (Could not find any implementation for node {ForeignNode[1 + (Unnamed Layer* 1) [Shuffle]...Cast_2]}.)
```

**Comment by galagam** [comment]
Was not able to reproduce. Since this works within the docker container, it is most likely a faulty installation. 
Please consider a fresh installation of driver, CUDA and TensorRT.
