### ISSUE TITLE
Erronious driver mismatch report

### ISSUE THREAD

**Issue by SteveDraper** [NVIDIA/TensorRT#1786]
## Description

Attempting to load an ONNX model with the TensorRT execution provider on the NVidia `TensorRT` docker image (from AWS marketplace, hosted on the NVidia Deep Learning AMI also from AWS marketplace) fails with:
```
RuntimeError: /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:122 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true] /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:116 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true] CUDA failure 35: CUDA driver version is insufficient for CUDA runtime version ; GPU=0 ; hostname=8f2a5528ea84 ; expr=cudaSetDevice(device_id_);
```

## Environment

**TensorRT Version**: 8.2.2
**NVIDIA GPU**: V100
**NVIDIA Driver Version**: 460.73.01
**CUDA Version**: 11.6
**CUDNN Version**: 8.3.2
**Operating System**: Ubuntu 20.04.3 LTS
**Python Version (if applicable)**: 3.8.10
**Tensorflow Version (if applicable)**: N/A
**PyTorch Version (if applicable)**: N/A
**Baremetal or Container (if so, version)**: NVidia TensorRT 22.01 (https://aws.amazon.com/marketplace/pp/prodview-jbbleexnwpstk)

## Relevant Files

Minimal ONNX model created on a CPU installation of pytorch using the script:

```
import torch
import argparse


class MinimalModel(torch.nn.Module):
    def __init__(self):
        super(MinimalModel, self).__init__()
        self.linear = torch.nn.Linear(5, 2)

    def forward(self, x):
        return self.linear(x)


if __name__ == "__main__":
    # Parse arguments
    parser = argparse.ArgumentParser()
    parser.add_argument('--file', type=str, help='Path to save ONNX model to')
    parser.add_argument('--dummy')
    args = parser.parse_args()

    model = MinimalModel()

    # Export to ONNX
    x = torch.randn(5)
    # traced_script_module = torch.jit.trace(self.model, waveform, strict=False, check_trace=True)
    torch.onnx.export(model,                     # model being run
                      x,                         # model input (or a tuple for multiple inputs)
                      args.file,                 # where to save the model (can be a file or file-like object)
                      export_params=True,        # store the trained parameter weights inside the model file
                      opset_version=11,          # the ONNX version to export the model to
                      do_constant_folding=True,  # whether to execute constant folding for optimization
                      input_names = ['input'],   # the model's input names
                      output_names = ['output']  # the model's output names
                      )
```

Minimal test loader (that is run on the tensorRT environment as detailed below):

```
import os
import argparse
import onnxruntime


def run(onnx):
    if not os.path.exists(onnx):
        raise ValueError("Specified model file not found")

    #  'TensorrtExecutionProvider',
    ort_session = onnxruntime.InferenceSession(onnx,
                                               providers=['TensorrtExecutionProvider'])
    print(f"ONNX device: {onnxruntime.get_device()}")
    print(f"Session providers: {ort_session.get_providers()}")


if __name__ == "__main__":
    # Parse arguments
    parser = argparse.ArgumentParser()
    parser.add_argument('--onnx', type=str, help='Optional path to save/restore ONNX to and run with ONNX runtime')
    parser.add_argument('--dummy')
    args = parser.parse_args()

    run(args.onnx)
```

## Steps To Reproduce

1. Build minimal ONNX model (see script above) to serve as test model (any ONNX model should do really).  I did this on my Mac locally and then copied it to a mounted volume on the test VM.  The env that built this should not be terribly relevant, but I kept it separate from the tensorRT VM so as not to have to install pytorch there.  For ref it was python 3.7.10 with torch 1.1

2. Shell into TensorRT docker container.  The setup for this was an EC2 VM running he NVidia Deep Learning AMI (https://aws.amazon.com/marketplace/pp/prodview-e7zxdqduz4cbs?qid=1606075638508&sr=0-1&ref_=srh_res_product_title#pdp-overview), hosting docker with the container being the NVidia `TensorRT` container image from the AWS marketplace (https://aws.amazon.com/marketplace/pp/prodview-jbbleexnwpstk):
```
docker run -it -v /ebs:/ebs 709825985650.dkr.ecr.us-east-1.amazonaws.com/nvidia/containers/nvidia/tensorrt:22.01-py3 bash
```
Here `709825985650.dkr.ecr.us-east-1.amazonaws.com/nvidia/containers/nvidia/tensorrt:22.01-py3` is just my local copy of the TensorRT base image (no modifications) and `/ebs` is just an external mount containing the test runtime script (above) and the test model image (as generated by the script above)

3. Install the ONNX runtime (ephemerally for the sake of a minimally intrusive test that doesn't require me to build a bespoke container on top of the base TensorRT image):
```
pip install onnxruntime-gpu
```

4.  Attempt to run the minimal loader script :
```
python onnx_load_test.py /ebs/models/minimal_model.onnx
```
Result is a runtime-driver mismatch error being reported:
```
Traceback (most recent call last):
  File "onnx_load_test.py", line 37, in <module>
    run(args.onnx)
  File "onnx_load_test.py", line 14, in run
    ort_session = onnxruntime.InferenceSession(onnx,
  File "/usr/local/lib/python3.8/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 335, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/usr/local/lib/python3.8/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 379, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:122 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true] /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:116 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true] CUDA failure 35: CUDA driver version is insufficient for CUDA runtime version ; GPU=0 ; hostname=21b052b97708 ; expr=cudaSetDevice(device_id_);
```

Since its driver version `460.73.01` and CUDA `11.6`, which requires driver `>=450.80.02` this seems like it should not occur...

**Comment by nvpohanh** [comment]
According to this page: https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html

CUDA-11.6 requires r510 driver or above. Could you try newer driver versions? Thanks

**Comment by nvpohanh** [comment]
closing for now due to >14 days with no response. Please feel free to reopen if the issue still exists. Thanks

**Comment by vahvero** [comment]
I am currently experiencing this issue. 

```[E:onnxruntime:Default, cuda_call.cc:118 CudaCall] CUDA failure 35: CUDA driver version is insufficient for CUDA runtime version ; GPU=0 ; hostname=d158deaa4612 ; expr=cudaGetDeviceCount(&num_devices);```

On computer I have local output of the `nvidia-smi`

```
Mon Jun 27 16:46:44 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.48.07    Driver Version: 515.48.07    CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:17:00.0 Off |                  N/A |
|  0%   55C    P8    19W / 300W |      1MiB / 11264MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce ...  On   | 00000000:65:00.0 Off |                  N/A |
|  0%   55C    P8    44W / 300W |      1MiB / 11264MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

The CUDAExecutionProvider works when not attempting the deploy in a docker image. Should I revert my cuda version to match that in the docker image? I expect the docker to follow this [file](https://github.com/NVIDIA/TensorRT/blob/main/docker/ubuntu-20.04.Dockerfile). I am new to docker so I may have some other docker related errors too.

My docker file starts with
```
ARG TRT_CONTAINER_VERSION=22.05

FROM nvcr.io/nvidia/tensorrt:${TRT_CONTAINER_VERSION}-py3 as python-base
ENV PYTHON_VERSION=3.9.13
# Install python3.9 with pyenv and install some libraries as image contains 3.8

RUN --mount=type=ssh poetry install --no-dev # install onnxruntime-gpu for my project
```
