### ISSUE TITLE
AttributeError: 'tensorrt.tensorrt.Builder' object has no attribute 'fp16_mode'

### ISSUE THREAD

**Issue by snailkn** [NVIDIA/TensorRT#1820]
## Description

I want to use tensorrt-8.2.2.1 convert my onnx model to tensorrt, but I get an `AttributeError` when I try to build a engine.

```python3
AttributeError: 'tensorrt.tensorrt.Builder' object has no attribute 'fp16_mode'
```

it is my code to build engine:

```python3
TRT_LOGGER = trt.Logger(trt.Logger.WARNING)
trt_runtime = trt.Runtime(TRT_LOGGER)
def build_engine(onnx_path, seq_len):
    with trt.Builder(TRT_LOGGER) as builder:
        network = builder.create_network(1)
        config = builder.create_builder_config()
        parser = trt.OnnxParser(network, TRT_LOGGER)
        profile = builder.create_optimization_profile()
        
        profile.set_shape('input', (1, seq_len), (32, seq_len), (64, seq_len))
        profile.set_shape('input_mask', (1, seq_len), (32, seq_len), (64, seq_len))
        
        config.add_optimization_profile(profile)
        config.max_workspace_size = (1 << 32)
        
        builder.max_batch_size = 64
        builder.fp16_mode = True
        builder.int8_mode = True
        with open(onnx_path, 'rb') as model:
            parser.parse(model.read())
        engine = builder.build_serialized_network(network, config)
        return engine

engine = build_engine(onnx_path, 128)
```

## Environment

**TensorRT Version**: 8.2.2.1
**NVIDIA GPU**: V100
**NVIDIA Driver Version**: 
**CUDA Version**: 
**CUDNN Version**: 
**Operating System**: 
**Python Version (if applicable)**: 3.8.12
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**: 

the same error exist in `int16_mode`, is there some update from tensorrt 7.x to 8.x ? how can I build a int8 or fp16 engine?

**Comment by ttyio** [comment]
@snailkn , now we use new api `builder_config` to setup the precision. see our sample code:

https://github.com/NVIDIA/TensorRT/blob/main/demo/BERT/builder.py#L405

thanks!

**Comment by ttyio** [comment]
Closing since no activity for more than 3 weeks, please reopen if you still have issue, thanks!

**Comment by harshraj22** [comment]
@ttyio 
Getting the following issue:
```bash
2022-07-15 10:47:28,184 convert_onnx_to_trt [INFO]: Starting....
2022-07-15 10:47:28,189 convert_onnx_to_trt [INFO]: Loading onnx model

2022-07-15 11:07:12,814 convert_onnx_to_trt [INFO]: Reading model shape from model
Traceback (most recent call last):
  File "convert_onnx_to_trt.py", line 33, in <module>
    convert_onnx_to_trt(args.engine_name, args.onnx_model, args.batch_size, args.build_mode)
  File "convert_onnx_to_trt.py", line 26, in convert_onnx_to_trt
    engine = eng.build_engine(onnx_model, build_mode, shape=shape)
  File "/home/harshraj22/TRT_Model_Conversion-develop/engine.py", line 29, in build_engine
    builder_config.max_workspace_size = workspace_size * (1024 * 1024)
NameError: name 'workspace_size' is not defined
```

for the given code
```python

def build_engine(onnx_path, b_mode, shape=None):
    """
   This is the function to create the TensorRT engine
   Args:
      onnx_path : Path to onnx_file. 
      shape : Shape of the input of the ONNX file. 
  """
    if shape is None:
        shape = [1, 128, 224, 3]
    with trt.Builder(TRT_LOGGER) as builder, builder.create_network(1) as network, trt.OnnxParser(network,
                                                                                                  TRT_LOGGER) as parser, builder.create_builder_config() as builder_config:
        # https://github.com/NVIDIA/TensorRT/issues/1820
        builder_config.max_workspace_size = workspace_size * (1024 * 1024)
        if config.use_fp16:
            builder_config.set_flag(trt.BuilderFlag.FP16)
```

```python
>>> tensorrt.__version__
'8.0.1.6'
```
