### ISSUE TITLE
tensorrt8 getOutput(0)->getDimensions() segmentation fault

### ISSUE THREAD

**Issue by Tartisan** [NVIDIA/TensorRT#1891]
## Description

When I used cuda 10.2 and tensorrt 7.2, the code works fine. When update to cuda11.2, tensorrt8.0, and use gpu rtx 3090, I compile sucess, but gets  **Segmentation fault**  at **convLayer->getOutput(0)->getDimensions()** while running

The input dimensions: 6x1152x1152, num_output: 16, pad: 0, kernel_size: 1, stride: 1, dilation: 1

```c++
void addConvLayer(const LayerParameter &layer_param,
                  nvinfer1::ITensor *const *inputs,
                  WeightMap *weight_map,
                  nvinfer1::INetworkDefinition *net) {
  ConvolutionParameter conv = layer_param.convolution_param();
  ConvParam param;
  CHECK(ParserConvParam(conv, &param));
  nvinfer1::IConvolutionLayer *convLayer = NULL;
  int size =
      conv.num_output() * param.kernel_w * param.kernel_h
          * inputs[0]->getDimensions().d[0];

  auto wt = loadLayerWeights(conv.weight_filler().value(), size);
  nvinfer1::Weights bias_weight{nvinfer1::DataType::kFLOAT, nullptr, 0};
  convLayer = net->addConvolution(*inputs[0],
                                  static_cast<int>((conv.num_output())),
                                  nvinfer1::DimsHW{param.kernel_h,
                                                   param.kernel_w},
                                  wt,
                                  bias_weight);
  if ((*weight_map)[layer_param.name().c_str()].size() > 0) {
    convLayer->setKernelWeights((*weight_map)[layer_param.name().c_str()][0]);
    if ((*weight_map)[layer_param.name().c_str()].size() > 1) {
      convLayer->setBiasWeights((*weight_map)[layer_param.name().c_str()][1]);
    }
  }
  std::vector<nvinfer1::Weights> lw;
  lw.resize(2);
  lw[0] = convLayer->getKernelWeights();
  lw[1] = convLayer->getBiasWeights();
  (*weight_map)[layer_param.name().c_str()] = lw;

  convLayer->setStride(nvinfer1::DimsHW{param.stride_h, param.stride_w});
  convLayer->setPadding(nvinfer1::DimsHW{param.padding_h, param.padding_w});
  convLayer->setNbGroups(1);
  convLayer->setName(layer_param.name().c_str());
  convLayer->setDilation(nvinfer1::DimsHW{param.dilation, param.dilation});

  std::string dim_string = " input: ";
  auto tmp_out_dims = convLayer->getInput(0)->getDimensions();
  for (int i = 0; i < 3; i++) {
    dim_string += " " + std::to_string(tmp_out_dims.d[i]);
  }
  dim_string += " | output: ";
  tmp_out_dims = convLayer->getOutput(0)->getDimensions();
  for (int i = 0; i < 3; i++) {
    dim_string += " " + std::to_string(tmp_out_dims.d[i]);
  }
  std::cout << layer_param.name() << dim_string;
}
```

```
(gdb) bt
#0  0x00007fff760979fd in ?? () from ***/lib/libnvinfer.so.8
#1  0x00007fff75efd6c2 in ?? () from ***/lib/libnvinfer.so.8
#2  0x00007fff75f018e1 in ?? () from ***/lib/libnvinfer.so.8
#3  0x00007fff76175e1c in ?? () from ***/lib/libnvinfer.so.8
#4  0x00007fff7617611f in ?? () from ***/lib/libnvinfer.so.8
#5  0x00007fff7617661a in ?? () from ***/lib/libnvinfer.so.8
#6  0x00007fffc8444a51 in nvinfer1::ITensor::getDimensions (this=<optimized out>) at ***/include/NvInfer.h:248
```

## Environment

**TensorRT Version**: 8.0
**NVIDIA GPU**: RTX 3090
**NVIDIA Driver Version**: 470.86
**CUDA Version**: 11.2
**CUDNN Version**: 8.2.0
**Operating System**: Ubuntu18.04
**Python Version (if applicable)**:
**Tensorflow Version (if applicable)**:
**PyTorch Version (if applicable)**:
**Baremetal or Container (if so, version)**:

**Comment by Tartisan** [comment]
Fixed it due to the tensorrt plugin adding mode
