### ISSUE TITLE
[codeGenerator.cpp::compileGraph::476] Error Code 1: Myelin (No results returned from cublas heuristic search)

### ISSUE THREAD

**Issue by nguyenvanhoang7398** [NVIDIA/TensorRT#2115]
I am trying to convert a sequence to sequence model in ONNX format to TensorRT engine. The inputs are of dynamic shapes.
Then the error about cuBLAS heuristic search was thrown when I run the `build_engine()` function. 

```
[07/01/2022-02:46:21] [TRT] [V] *************** Autotuning format combination: Float(E1,1024,1), Float(1024,1), Float(E0,E0,(# 1 (SHAPE attention_mask)),1), Int32(), Int32() -> Float(E1,1024,1), Float((* 64 (# 1 (SHAPE input_ids))),64,1), Float((* 16 E3),E3,E2,1) where E0=(* (# 1 (SHAPE attention_mask)) (# 1 (SHAPE attention_mask))) E1=(* 1024 (# 1 (SHAPE input_ids))) E2=(BROADCAST_SIZE (# 1 (SHAPE input_ids)) (# 1 (SHAPE attention_mask))) E3=(* E2 E2) ***************
[07/01/2022-02:46:21] [TRT] [V] --------------- Timing Runner: {ForeignNode[306 + (Unnamed Layer* 175) [Shuffle]...Add_165]} (Myelin)
[07/01/2022-02:46:21] [TRT] [W] Myelin graph with multiple dynamic values may have poor performance if they differ. Dynamic values are: 
[07/01/2022-02:46:21] [TRT] [W]  (# 1 (SHAPE attention_mask))
[07/01/2022-02:46:21] [TRT] [W]  (# 1 (SHAPE input_ids))
[07/01/2022-02:46:25] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +0, now: CPU 2676, GPU 7130 (MiB)
[07/01/2022-02:46:25] [TRT] [E] 1: [codeGenerator.cpp::compileGraph::476] Error Code 1: Myelin (No results returned from cublas heuristic search)
Traceback (most recent call last):
  File "test_quantization.py", line 110, in <module>
    test_tensorrt_m2m()
  File "test_quantization.py", line 95, in test_tensorrt_m2m
    convert_onnx2trt("m2m100_418M", "models")
  File "/home/vanguyen/package/translate/translate/quantization/tensorrt/utils.py", line 61, in convert_onnx2trt
    build_and_save_engine(encoder_onnx_path, encoder_trt_path)
  File "/home/vanguyen/package/translate/translate/quantization/tensorrt/utils.py", line 51, in build_and_save_engine
    fout.write(bytearray(engine.serialize()))
AttributeError: 'NoneType' object has no attribute 'serialize'
```

This is the code I use to build the engine.
```
print('Beginning ONNX file parsing')
    print("Network inputs:")
    for i in range(network.num_inputs):
        tensor = network.get_input(i)
        print(tensor.name, trt.nptype(tensor.dtype), tensor.shape)
    # allow TensorRT to use up to 1GB of GPU memory for tactic selection
    config.max_workspace_size = common.GiB(16)
    builder.max_batch_size = 4

    # set optimization profile for dynamic shape
    min_length, max_length = 1, 200
    opt_length = int(max_length / 2)
    min_batch_size, max_batch_size = 1, 4
    profile.set_shape('input_ids', (min_batch_size, min_length), (min_batch_size, opt_length),
                      (min_batch_size, max_length))
    profile.set_shape('attention_mask', (min_batch_size, min_length), (min_batch_size, opt_length),
                      (min_batch_size, max_length))
    config.add_optimization_profile(profile)

    print('Building an engine...')
    engine = builder.build_engine(network, config) # error is thrown here
    with open(trt_file_path, 'wb') as fout:
         fout.write(bytearray(engine.serialize()))
```

These are my system specs.
```
$ dpkg -l | grep TensorRT
ii  libnvinfer-bin                                              8.0.3-1+cuda11.3                             amd64        TensorRT binaries
ii  libnvinfer-dev                                              8.0.3-1+cuda11.3                             amd64        TensorRT development libraries and headers
ii  libnvinfer-doc                                              8.0.3-1+cuda11.3                             all          TensorRT documentation
ii  libnvinfer-plugin-dev                                       8.0.3-1+cuda11.3                             amd64        TensorRT plugin libraries
ii  libnvinfer-plugin8                                          8.0.3-1+cuda11.3                             amd64        TensorRT plugin libraries
ii  libnvinfer-samples                                          8.0.3-1+cuda11.3                             all          TensorRT samples
ii  libnvinfer8                                                 8.0.3-1+cuda11.3                             amd64        TensorRT runtime libraries
ii  libnvonnxparsers-dev                                        8.0.3-1+cuda11.3                             amd64        TensorRT ONNX libraries
ii  libnvonnxparsers8                                           8.0.3-1+cuda11.3                             amd64        TensorRT ONNX libraries
ii  libnvparsers-dev                                            8.0.3-1+cuda11.3                             amd64        TensorRT parsers libraries
ii  libnvparsers8                                               8.0.3-1+cuda11.3                             amd64        TensorRT parsers libraries
ii  onnx-graphsurgeon                                           8.0.3-1+cuda11.3                             amd64        ONNX GraphSurgeon for TensorRT package
ii  python3-libnvinfer                                          8.0.3-1+cuda11.3                             amd64        Python 3 bindings for TensorRT
ii  python3-libnvinfer-dev                                      8.0.3-1+cuda11.3                             amd64        Python 3 development package for TensorRT
ii  tensorrt                                                    8.0.3.4-1+cuda11.3                           amd64        Meta package of TensorRT
```

cuda: 11.3
pytorch: 1.11.0
nvidia-tensorrt: 8.0.1.6

Some Netron properties, not sure if there are useful.
![image](https://user-images.githubusercontent.com/21237688/176875232-63bfdf84-6dee-4e1a-ad4a-619b82e526cf.png)

I have been struggling with this for a few days. Hope I can find some help here.

**Comment by zerollzeng** [comment]
Looks like the reason why it failed is myelin can not find the tactic for the dynamic shape. can you try TRT 8.4? if it doesn't work can your share the onnx model here?

**Comment by nguyenvanhoang7398** [comment]
Thank you so much for the suggestion. I managed to upgrade TensorRT to 8.4.1.5 and the cublas heuristic search problem disappeared.
However, now I am running into another Assertion Error. This is the StackTrace.
```
[07/02/2022-11:04:10] [TRT] [V] *************** Autotuning format combination: Int32((# 1 (SHAPE input_ids)),1), Int32((# 1 (SHAPE input_ids)),1), Int32(1,1), Int32((# 1 (SHAPE input_ids)),1), Int32(), Int32(), Int32() -> Float((* 1024 (# 1 (SHAPE input_ids))),1024,1) ***************
[07/02/2022-11:04:10] [TRT] [V] --------------- Timing Runner: {ForeignNode[encoder.embed_tokens.weight...Add_1784]} (Myelin)
[07/02/2022-11:04:10] [TRT] [W] Myelin graph with multiple dynamic values may have poor performance if they differ. Dynamic values are: 
[07/02/2022-11:04:10] [TRT] [W]  (# 1 (SHAPE input_ids))
[07/02/2022-11:04:10] [TRT] [W]  (# 0 (SHAPE input_ids))
[07/02/2022-11:04:13] [TRT] [E] 2: [myelinSliceLayer.cpp::addSlice::110] Error Code 2: Internal Error (Assertion sliceOutDims[i] <= inputDims.d[i] failed. )
```

The model inputs are of dynamic shapes. Here are the codes where I set the optimization profile for the dynamic shape.
```
print('Beginning ONNX file parsing')
print("Network inputs:")
for i in range(network.num_inputs):
    tensor = network.get_input(i)
    print(tensor.name, trt.nptype(tensor.dtype), tensor.shape)
# allow TensorRT to use up to 16GB of GPU memory for tactic selection
config.max_workspace_size = common.GiB(16)
builder.max_batch_size = 4

# set optimization profile for dynamic shape
min_length, max_length = 1, 200
opt_length = int(max_length / 2)
min_batch_size, max_batch_size = 1, 4
profile.set_shape('input_ids', (min_batch_size, min_length), (min_batch_size, opt_length),
                  (max_batch_size, max_length))
profile.set_shape('attention_mask', (min_batch_size, min_length), (min_batch_size, opt_length),
                  (max_batch_size, max_length))
config.add_optimization_profile(profile)
```

You can find the ONNX file for the model here https://drive.google.com/file/d/12jbL88FhZDojTJASNhTW6_o1KhZLwzCB/view?usp=sharing

I really appreciate the help in troubleshooting this. Thank you so much.

**Comment by zerollzeng** [comment]
Ah, I didn't reproduce this in my environment with trtexec:
```
&&&& PASSED TensorRT.trtexec [TensorRT v8401] # /usr/src/tensorrt/bin/trtexec --onnx=m2m100_418M-encoder.onnx --verbose --minShapes=input_ids:1x1,attention_mask:1x1 --optShapes=input_ids:1x100,attention_mask:1x100 --maxShapes=input_ids:4x200,attention_mask:4x200 --shapes=input_ids:1x100,attention_mask:1x100
```

Can you try trtexec like I did?

**Comment by nguyenvanhoang7398** [comment]
Thank you so much for the prompt reply. This is my `trtexec` output

```
[07/03/2022-04:02:40] [W] [TRT] Skipping tactic 0 due to insufficient memory on requested size of 151020160 detected for tactic 0x0000000000000000.
[07/03/2022-04:02:40] [V] [TRT] Fastest Tactic: 0xd15ea5edd15ea5ed Time: inf
[07/03/2022-04:02:40] [E] Error[10]: [optimizer.cpp::computeCosts::3628] Error Code 10: Internal Error (Could not find any implementation for node {ForeignNode[encoder.embed_tokens.weight...Add_1784]}.)
[07/03/2022-04:02:40] [E] Error[2]: [builder.cpp::buildSerializedNetwork::636] Error Code 2: Internal Error (Assertion engine != nullptr failed. )
[07/03/2022-04:02:40] [E] Engine could not be created from network
[07/03/2022-04:02:40] [E] Building engine failed
[07/03/2022-04:02:40] [E] Failed to create engine from model.
[07/03/2022-04:02:40] [E] Engine set up failed
&&&& FAILED TensorRT.trtexec [TensorRT v8200] # trtexec --onnx=m2m100_418M-encoder.onnx --verbose --minShapes=input_ids:1x1,attention_mask:1x1 --optShapes=input_ids:1x100,attention_mask:1x100 --maxShapes=input_ids:4x200,attention_mask:4x200 --shapes=input_ids:1x100,attention_mask:1x100
Segmentation fault
```

It looks like some node in the optimization graph doesn't have any implementation.

**Comment by zerollzeng** [comment]
Can you try TRT 8.4? TRT 8.4 works for me.

**Comment by nguyenvanhoang7398** [comment]
Yes, I have built and been using TensorRT 8.4.1.5 from source.

![image](https://user-images.githubusercontent.com/21237688/177073693-4920a99b-49ed-4f1f-8f56-d2db6d364d9b.png)

**Comment by zerollzeng** [comment]
You have to install the TRT 8.4 SDK, not just the OSS. please install the 8.4 GA: https://developer.nvidia.com/nvidia-tensorrt-8x-download

**Comment by nguyenvanhoang7398** [comment]
Hi, I got the same error as running the conversion via Python.

```
[07/03/2022-23:06:44] [V] [TRT] >>>>>>>>>>>>>>> Chose Runner Type: Slice Tactic: 0x0000000000000000
[07/03/2022-23:06:44] [V] [TRT] =============== Computing costs for 
[07/03/2022-23:06:44] [V] [TRT] *************** Autotuning format combination: Int32((# 1 (SHAPE input_ids)),1), Int32((# 1 (SHAPE input_ids)),1), Int32(1,1), Int32((# 1 (SHAPE input_ids)),1), Int32(), Int32(), Int32() -> Float((* 1024 (# 1 (SHAPE input_ids))),1024,1) ***************
[07/03/2022-23:06:44] [V] [TRT] --------------- Timing Runner: {ForeignNode[encoder.embed_tokens.weight...Add_1784]} (Myelin)
[07/03/2022-23:06:44] [W] [TRT] Myelin graph with multiple dynamic values may have poor performance if they differ. Dynamic values are: 
[07/03/2022-23:06:44] [W] [TRT]  (# 1 (SHAPE input_ids))
[07/03/2022-23:06:44] [W] [TRT]  (# 0 (SHAPE input_ids))
[07/03/2022-23:06:50] [E] Error[2]: [myelinSliceLayer.cpp::addSlice::110] Error Code 2: Internal Error (Assertion sliceOutDims[i] <= inputDims.d[i] failed. )
```

**Comment by nguyenvanhoang7398** [comment]
After I deleted the OSS and reinstall TensorRT it works. Closing the issue.

**Comment by Amy234543** [comment]
@nguyenvanhoang7398 How many onnx files are there in m2m100? How to transfer three files to tensort
