### ISSUE TITLE
EfficientDet python sample script: create_onnx.py fail for EfficientDetD4 checkpoint

### ISSUE THREAD

**Issue by ece85** [NVIDIA/TensorRT#2132]
## Description

/TensorRT/samples/python/efficientdet/python/create_onnx.py sample script fails in update_shapes() function for checkpoint created via finetuning an efficientdet-d4 pretrained model (no error when repeating process based on efficientdet-d7 model).

```
Traceback (most recent call last):
  File "create_onnx.py", line 453, in <module>
    main(args)
  File "create_onnx.py", line 424, in main
    effdet_gs.update_shapes()
  File "create_onnx.py", line 228, in update_shapes
    scale_h = concat.inputs[1].values[0] / node.inputs[0].shape[2]
TypeError: ufunc 'divide' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

I found that the **node.inputs[0].shape[2]** is of size None

the following (hacky) code change enabled me to get past this problem and i successfully created an engine from the onnx file created.  However, i do not know if my code change resulted in the 'optimal' graph.

![image](https://user-images.githubusercontent.com/4247956/177883291-cac76ff2-cde8-4d35-9078-aba1e39d9e83.png)

## Environment

**Container **:  nvcr.io/nvidia/tensorflow:22.06-tf2-py3
all of the following libraries exist by default the container specified

**TensorRT Version**:  libnvinfer-bin   8.2.5-1+cuda11.4 
**NVIDIA GPU**: 3080ti
**NVIDIA Driver Version**: 510.73.05
**CUDA Version**: Build cuda_11.7.r11.7/compiler.31442593_0
**CUDNN Version**: libcudnn8  8.4.1.50-1+cuda11.6 
**Operating System**: ubuntu 18.04
**Python Version (if applicable)**: 3.8.10
**Tensorflow Version (if applicable)**: 2.8 
**PyTorch Version (if applicable)**: N/A

## Steps To Reproduce

option A:  

1. git clone https://github.com/ece85/Deploy_EfficientDet.git
2. run setup_and_repro.sh (this will build a docker image and run a script to reproduce the problem).

option B:

if you are confident that you current dev environment is similar enough to mine then just download the folder linked by :

https://drive.google.com/drive/folders/1yWTzCxeDUiM93Se4tOL29c7VBnuCUuHN?usp=sharing

and point that to the following python script call:

```
cd /TensorRT/samples/python/efficientdet

python3 create_onnx.py \
    --input_size 1024,1024 \
    --saved_model $saved_model \ 
    --onnx model.onnx

```
where $saved_model points to folder downloaded from link.

**Comment by zerollzeng** [comment]
Does following https://github.com/NVIDIA/TensorRT/tree/main/samples/python/efficientdet work for you? I notice that our readme is based on 
```
docker pull nvcr.io/nvidia/tensorflow:22.01-tf1-py3
```
Can you try this? 

cc @rajeevsrao

**Comment by ece85** [comment]
@zerollzeng and @rajeevsrao  - i updated my repo (https://github.com/ece85/Deploy_EfficientDet.git) to use nvcr.io/nvidia/tensorflow:22.01-tf1-py3.  I am still experiencing the same issue.
