### ISSUE TITLE
trt-engine-explorer notebook fails at display_df

### ISSUE THREAD

**Issue by kometa-triatlon** [NVIDIA/TensorRT#2264]
## Description

I am trying to follow this tutorial for my model:

https://github.com/NVIDIA/TensorRT/blob/main/tools/experimental/trt-engine-explorer/notebooks/tutorial.ipynb

The command:
```
display_df(plan.df)
```
Generates a huge error output ending with "RecursionError: maximum recursion depth exceeded while calling a Python object":
```
Exception on /dtale/iframe/1 [GET]
Traceback (most recent call last):
  File "/opt/TensorRT/tools/experimental/trt-engine-explorer/env_trex/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/TensorRT/tools/experimental/trt-engine-explorer/env_trex/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/TensorRT/tools/experimental/trt-engine-explorer/env_trex/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/TensorRT/tools/experimental/trt-engine-explorer/env_trex/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/opt/TensorRT/tools/experimental/trt-engine-explorer/env_trex/lib/python3.8/site-packages/dtale/views.py", line 1175, in view_iframe
    return _view_main(data_id, iframe=True)
  File "/opt/TensorRT/tools/experimental/trt-engine-explorer/env_trex/lib/python3.8/site-packages/dtale/views.py", line 1132, in _view_main
    return base_render_template("dtale/main.html", data_id, title=title, iframe=iframe)
  File "/opt/TensorRT/tools/experimental/trt-engine-explorer/env_trex/lib/python3.8/site-packages/dtale/views.py", line 1100, in base_render_template
    return render_template(
  File "/opt/TensorRT/tools/experimental/trt-engine-explorer/env_trex/lib/python3.8/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/opt/TensorRT/tools/experimental/trt-engine-explorer/env_trex/lib/python3.8/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/opt/TensorRT/tools/experimental/trt-engine-explorer/env_trex/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/opt/TensorRT/tools/experimental/trt-engine-explorer/env_trex/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/opt/TensorRT/tools/experimental/trt-engine-explorer/env_trex/lib/python3.8/site-packages/dtale/templates/dtale/main.html", line 1, in top-level template code
    {% extends "dtale/base.html" %}
  File "/opt/TensorRT/tools/experimental/trt-engine-explorer/env_trex/lib/python3.8/site-packages/dtale/templates/dtale/base.html", line 13, in top-level template code
    <link rel="shortcut icon" href="{{ url_for('static', filename='images/favicon.png') }}">
  File "/opt/TensorRT/tools/experimental/trt-engine-explorer/env_trex/lib/python3.8/site-packages/dtale/app.py", line 154, in url_for
    return url_for(endpoint, *args, **kwargs)
  File "/opt/TensorRT/tools/experimental/trt-engine-explorer/env_trex/lib/python3.8/site-packages/flask/helpers.py", line 256, in url_for
    return current_app.url_for(
  File "/opt/TensorRT/tools/experimental/trt-engine-explorer/env_trex/lib/python3.8/site-packages/dtale/app.py", line 154, in url_for
    return url_for(endpoint, *args, **kwargs)
  File "/opt/TensorRT/tools/experimental/trt-engine-explorer/env_trex/lib/python3.8/site-packages/flask/helpers.py", line 256, in url_for
    return current_app.url_for(
  File "/opt/TensorRT/tools/experimental/trt-engine-explorer/env_trex/lib/python3.8/site-packages/dtale/app.py", line 154, in url_for

[...]

return url_for(endpoint, *args, **kwargs)
  File "/opt/TensorRT/tools/experimental/trt-engine-explorer/env_trex/lib/python3.8/site-packages/flask/helpers.py", line 256, in url_for
    return current_app.url_for(
  File "/opt/TensorRT/tools/experimental/trt-engine-explorer/env_trex/lib/python3.8/site-packages/dtale/app.py", line 154, in url_for
    return url_for(endpoint, *args, **kwargs)
  File "/opt/TensorRT/tools/experimental/trt-engine-explorer/env_trex/lib/python3.8/site-packages/flask/helpers.py", line 256, in url_for
    return current_app.url_for(
  File "/opt/TensorRT/tools/experimental/trt-engine-explorer/env_trex/lib/python3.8/site-packages/dtale/app.py", line 154, in url_for
    return url_for(endpoint, *args, **kwargs)
  File "/opt/TensorRT/tools/experimental/trt-engine-explorer/env_trex/lib/python3.8/site-packages/flask/helpers.py", line 256, in url_for
    return current_app.url_for(
  File "/opt/TensorRT/tools/experimental/trt-engine-explorer/env_trex/lib/python3.8/site-packages/werkzeug/local.py", line 316, in __get__
    obj = instance._get_current_object()  # type: ignore[misc]
  File "/opt/TensorRT/tools/experimental/trt-engine-explorer/env_trex/lib/python3.8/site-packages/werkzeug/local.py", line 511, in _get_current_object
    obj = local.get()  # type: ignore[union-attr]
RecursionError: maximum recursion depth exceeded while calling a Python object
```

You can find attached the complete error log:
[error.log](https://github.com/NVIDIA/TensorRT/files/9392481/error.log)

It's worth to mention that at the same time jupyter kernel outputs an error message:
```
[I 10:01:28.848 NotebookApp] Kernel started: 52de3a74-bd9a-4b37-807a-c26be67da0ec, name: python3
[IPKernelApp] ERROR | No such comm target registered: jupyter.widget.control
[IPKernelApp] WARNING | No such comm: 2f00b6d9-2ef5-4905-a4d3-83e686a8b5c4
```

Some more information:
```
[I 2022-08-22 10:01:13.377 LabApp] JupyterLab extension loaded from /opt/TensorRT/tools/experimental/trt-engine-explorer/env_trex/lib/python3.8/site-packages/jupyterlab
[I 2022-08-22 10:01:13.377 LabApp] JupyterLab application directory is /opt/TensorRT/tools/experimental/trt-engine-explorer/env_trex/share/jupyter/lab
[I 10:01:13.379 NotebookApp] Serving notebooks from local directory: /home/user/devel/deploy
```

## Environment

**TensorRT Version**: 8.2.5 (git tag 22.06)
**Jupyter Notebook Version**: 6.4.12
**NVIDIA GPU**: --
**NVIDIA Driver Version**:  --
**CUDA Version**: --
**CUDNN Version**: 
**Operating System**: Ubuntu 20.04
**Python Version (if applicable)**: 3.8.10
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**:  Baremetal, virtualenv env_trex

**Comment by kometa-triatlon** [comment]
@nzmora

**Comment by netaz** [comment]
Hi @kometa-triatlon,

Sorry for the late reply (I did not see this message).
TREx uses [dtale](https://github.com/man-group/dtale) for rendering pandas dataframes because it has a very sophisticated and useful interface. Unfortunately, dtale uses flask and requires IP communication between the notebook and the notebook server which some users are having a problem with.

TREx 0.1.4 tries to deal with some of these issues, but I'm not sure if it improves much.

Please try the following:
In [trt-engine-explorer/trex/notebook.py](https://github.com/NVIDIA/TensorRT/blob/87f3394404ff9f9ec92c906cd4c39b5562aea42e/tools/experimental/trt-engine-explorer/trex/notebook.py#L72) please change:
```
def display_df(df: pd.DataFrame, **kwargs):
    display_df_dtale(df, **kwargs)
```
To the QGrid dataframe renderer:
```
def display_df(df: pd.DataFrame, **kwargs):
    display_df_qgrid(df, **kwargs)
```
Or to the default dataframe renderer (simpler interface):
```
def display_df(df: pd.DataFrame, **kwargs):
    display(df, **kwargs)
```

After making the change please reinstall the trex package.

Please let me know if this helps.

In TREx 0.1.4 you will be able to use a global setting to control the backend renderer:
```
# Control how to display tables in notebooks
trex.table_display_backend = display_df_qgrid
```

Neta

**Comment by kometa-triatlon** [comment]
Hi @netaz,

Thanks for the reply. With QGrid I am getting the following JavaScript error:
```
[Open Browser Console for more detailed log - Double click to close this message]
Failed to load model class 'QgridModel' from module 'qgrid'
Error: Script error for "qgrid"
http://requirejs.org/docs/errors.html#scripterror
```

The default renderer works fine.
