### ISSUE TITLE
exceeds maximum protobuf size of 2GB

### ISSUE THREAD

**Issue by catalwaysright** [NVIDIA/TensorRT#2325]
## Description
When I use polygraphy to sanitize the model by `polygraphy surgeon sanitize --fold-constants encoder-temp_rnnt.onnx -o encoder-temp_rnnt.onnx`, things seem to work fine but in the end when Saving ONNX model to: encoder-temp_rnnt.onnx it shows `Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/polygraphy", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python3.8/site-packages/polygraphy/tools/_main.py", line 59, in main
    status = args.subcommand(args)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/polygraphy/tools/base/tool.py", line 132, in __call__
    return self.run(args)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/polygraphy/tools/surgeon/subtool/base.py", line 79, in run
    return self.run_impl(args)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/polygraphy/tools/surgeon/subtool/sanitize.py", line 152, in run_impl
    super().save_model(model)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/polygraphy/tools/surgeon/subtool/base.py", line 43, in save_model
    model = self.arg_groups[OnnxSaveArgs].save_onnx(model)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/polygraphy/tools/args/backend/onnx/loader.py", line 349, in save_onnx
    return loader()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/polygraphy/backend/base/loader.py", line 42, in __call__
    return self.call_impl(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/polygraphy/backend/onnx/loader.py", line 672, in call_impl
    onnx.save(model, self.path)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/onnx/__init__.py", line 197, in save_model
    s = _serialize(proto)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/onnx/__init__.py", line 66, in _serialize
    result = proto.SerializeToString()
ValueError: Message onnx.ModelProto exceeds maximum protobuf size of 2GB: 2607531503`.
This is because of the oversized model, which I met it before in onnx inference. However, I don't know how to fix it in this case.

## Environment

**TensorRT Version**: 8.0.2.6
**NVIDIA GPU**: 
**NVIDIA Driver Version**: 
**CUDA Version**: 11.4
**CUDNN Version**: 
**Operating System**: 
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**:

**Comment by pranavm-nvidia** [comment]
For large models, you need to save the weights in an external file. `polygraphy surgeon sanitize` can do that for you automatically if you specify the `--save-external-data` flag. 

In the next release, we're including some additional options that will allow you to prevent Polygraphy from folding operations that generate large constants.
