### ISSUE TITLE
[stable-diffusion]demo/Diffusion is not working

### ISSUE THREAD

**Issue by RIKOYUKI** [NVIDIA/TensorRT#2554]
## Description

[fail to run following code]
python3 demo-diffusion.py "a beautiful photograph of Mt. Fuji during cherry blossom" --hf-token=$HF_TOKEN -v

## Environment

**TensorRT Version**: 8.5.2.2
**NVIDIA GPU**: A30
**NVIDIA Driver Version**: 470.57.02
**CUDA Version**: 11.6
**CUDNN Version**: 8.6.0
**Operating System**: centos 7
**Python Version (if applicable)**: 3.7
**Tensorflow Version (if applicable)**: no
**PyTorch Version (if applicable)**: 1.12.0+cu116
**onnx Version (if applicable)**: 1.12.0
**Baremetal or Container (if so, version)**: 

## Relevant Files

<img width="1205" alt="image" src="https://user-images.githubusercontent.com/41542527/208295931-9a33c3e9-15a3-4583-b109-18a8c9585382.png">

UNet: fold constants .. 4919 nodes, 7891 tensors, 3 inputs, 1 outputs
UNet: shape inference .. 4919 nodes, 7891 tensors, 3 inputs, 1 outputs
UNet: inserted 0 fMHA plugins .. 4919 nodes, 7891 tensors, 3 inputs, 1 outputs
UNet: inserted 0 fMHCA plugins .. 4919 nodes, 7891 tensors, 3 inputs, 1 outputs
UNet: inserted 61 GroupNorm plugins .. 3914 nodes, 6581 tensors, 3 inputs, 1 outputs
UNet: inserted 48 LayerNorm plugins .. 3450 nodes, 6021 tensors, 3 inputs, 1 outputs
UNet: inserted 16 SplitGeLU plugins .. 3338 nodes, 5797 tensors, 3 inputs, 1 outputs
UNet: inserted 16 SeqLen2Spatial plugins .. 3226 nodes, 5621 tensors, 3 inputs, 1 outputs
UNet: final .. 3226 nodes, 5621 tensors, 3 inputs, 1 outputs
Building TensorRT engine for onnx/unet_fp16.opt.onnx: engine/unet_fp16.plan
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:604] Reading dangerously large protocol message.  If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:81] The total number of bytes read was 1720019276
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:604] Reading dangerously large protocol message.  If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:81] The total number of bytes read was 1720019276
[W] onnx2trt_utils.cpp:403: One or more weights outside the range of INT32 was clamped
[W] builtin_op_importers.cpp:5245: Attribute height not found in plugin node! Ensure that the plugin creator has a default value defined or the engine may fail to build.
[W] builtin_op_importers.cpp:5245: Attribute width not found in plugin node! Ensure that the plugin creator has a default value defined or the engine may fail to build.
[E] Conv_735: image size is smaller than filter size
[E] ModelImporter.cpp:726: While parsing node number 625 [Conv -> "onnx::Add_1302"]:
[E] ModelImporter.cpp:727: --- Begin node ---
[E] ModelImporter.cpp:728: input: "onnx::Conv_1301"
    input: "down_blocks.0.attentions.0.proj_out.weight"
    input: "down_blocks.0.attentions.0.proj_out.bias"
    output: "onnx::Add_1302"
    name: "Conv_735"
    op_type: "Conv"
    attribute {
      name: "dilations"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "group"
      i: 1
      type: INT
    }
    attribute {
      name: "kernel_shape"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 0
      ints: 0
      ints: 0
      ints: 0
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 1
      ints: 1
      type: INTS
    }
[E] ModelImporter.cpp:729: --- End node ---
[E] ModelImporter.cpp:732: ERROR: ModelImporter.cpp:172 In function parseGraph:
    [6] Invalid Node - Conv_735
    Conv_735: image size is smaller than filter size
[E] In node 625 (parseGraph): INVALID_NODE: Invalid Node - Conv_735
    Conv_735: image size is smaller than filter size
[!] Could not parse ONNX correctly
Traceback (most recent call last):
  File "demo-diffusion.py", line 487, in <module>
    enable_preview=args.build_preview_features)
  File "demo-diffusion.py", line 244, in loadEngines
    enable_preview=enable_preview)
  File "/home/sre/koyuki/TensorRT/demo/Diffusion/utilities.py", line 72, in build
    engine = engine_from_network(network_from_onnx_path(onnx_path), config=CreateConfig(fp16=fp16, profiles=[p],
  File "<string>", line 3, in func_impl
  File "/home/sre/anaconda3/envs/sd/lib/python3.7/site-packages/polygraphy/backend/base/loader.py", line 42, in __call__
    return self.call_impl(*args, **kwargs)
  File "/home/sre/anaconda3/envs/sd/lib/python3.7/site-packages/polygraphy/backend/trt/loader.py", line 183, in call_impl
    trt_util.check_onnx_parser_errors(parser, success)
  File "/home/sre/anaconda3/envs/sd/lib/python3.7/site-packages/polygraphy/backend/trt/util.py", line 85, in check_onnx_parser_errors
    G_LOGGER.critical("Could not parse ONNX correctly")
  File "/home/sre/anaconda3/envs/sd/lib/python3.7/site-packages/polygraphy/logger/logger.py", line 597, in critical
    raise PolygraphyException(message) from None
polygraphy.exception.exception.PolygraphyException: Could not parse ONNX correctly

**Comment by nekorobov** [comment]
Hi, which version of diffusers library do you use? From your log I see that fMHA and fMHCA plugins are not inserted. It, probably, means that the onnx graph is different from expected.

Another possible problem is:
`[W] builtin_op_importers.cpp:5245: Attribute height not found in plugin node! Ensure that the plugin creator has a default value defined or the engine may fail to build.
[W] builtin_op_importers.cpp:5245: Attribute width not found in plugin node! Ensure that the plugin creator has a default value defined or the engine may fail to build.`

It means that you either have not rebuilt the plugins after pulling the code (using old version of seq2len plugin) or using old version of demo/Diffusion python code with updated plugins.

**Comment by RIKOYUKI** [comment]
I use diffusers 0.7.2, TensorRT-8.5.2.2

**Comment by ousinkou** [comment]
Same problem, waiting for help

**Comment by kisisjrlly** [comment]
you need compile libnvinfer_plugin.so and set env LD_PRELOAD, follow the instructions in the guidance document：
`LD_PRELOAD=${PLUGIN_LIBS} python3 demo-diffusion.py "a beautiful photograph of Mt. Fuji during cherry blossom" --hf-token=$HF_TOKEN -v`

**Comment by rajeevsrao** [comment]
@RIKOYUKI @ousinkou can you please try the new demoDiffusion code in release/8.6? We have removed the need for plugins and the deployment experience should hopefully go smoother.

**Comment by jettan** [comment]
I also had the problem, but was able to solve it using the `LD_PRELOAD` method.
While release/8.6 might not need the extra plugin, it may run slower because some optimizations are now deleted in `models.py` if I understand correctly.

**Comment by ttyio** [comment]
closing since no activity for more than 3 weeks and now we recommend the onnx solution for diffusion, thanks all!
