### ISSUE TITLE
 error weight loader tensorrt

### ISSUE THREAD

**Issue by Allmight0000** [NVIDIA/TensorRT#2607]
Loading C:\Users\jhon\Desktop\Valorant-AI-cheats\half.engine for TensorRT inference...
[01/19/2023-18:27:31] [TRT] [I] [MemUsageChange] Init CUDA: CPU +450, GPU +0, now: CPU 7481, GPU 1390 (MiB)
[01/19/2023-18:27:32] [TRT] [I] Loaded engine size: 15 MiB
[01/19/2023-18:27:32] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +1039, GPU +394, now: CPU 8592, GPU 1800 (MiB)
[01/19/2023-18:27:32] [TRT] [W] TensorRT was linked against cuDNN 8.4.1 but loaded cuDNN 8.3.2
[01/19/2023-18:27:32] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +0, now: CPU 0, GPU 0 (MiB)    
[01/19/2023-18:27:32] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +2, GPU +8, now: CPU 8576, GPU 1800 (MiB)
[01/19/2023-18:27:32] [TRT] [W] TensorRT was linked against cuDNN 8.4.1 but loaded cuDNN 8.3.2
[01/19/2023-18:27:32] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +0, now: CPU 0, GPU 0 (MiB)
C:\Users\jhon\Desktop\Valorant-AI-cheats\Valorant-AI-cheats-env\lib\site-packages\tensorrt\__init__.py:331: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.  (This may have returned Python scalars in past versions.
  bool: np.bool,
Traceback (most recent call last):
  File "C:\Users\jhon\Desktop\Valorant-AI-cheats\yolov5\hubconf.py", line 49, in _create
    model = DetectMultiBackend(path, device=device, fuse=autoshape)  # detection model
  File "C:\Users\jhon\Desktop\Valorant-AI-cheats\yolov5\models\common.py", line 406, in __init__
    dtype = trt.nptype(model.get_binding_dtype(i))
  File "C:\Users\jhon\Desktop\Valorant-AI-cheats\Valorant-AI-cheats-env\lib\site-packages\tensorrt\__init__.py", line 331, in nptype
    bool: np.bool,
  File "C:\Users\jhon\Desktop\Valorant-AI-cheats\Valorant-AI-cheats-env\lib\site-packages\numpy\__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'bool'. Did you mean: 'bool_'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jhon\Desktop\Valorant-AI-cheats\yolov5\hubconf.py", line 60, in _create
    model = attempt_load(path, device=device, fuse=False)  # arbitrary model
  File "C:\Users\jhon\Desktop\Valorant-AI-cheats\yolov5\models\experimental.py", line 79, in attempt_load
    ckpt = torch.load(attempt_download(w), map_location='cpu')  # load
  File "C:\Users\jhon\Desktop\Valorant-AI-cheats\Valorant-AI-cheats-env\lib\site-packages\torch\serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\jhon\Desktop\Valorant-AI-cheats\Valorant-AI-cheats-env\lib\site-packages\torch\serialization.py", line 1002, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: unpickling stack underflow

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\jhon\Desktop\Valorant-AI-cheats\scripts\dxcam_main.py", line 104, in <module>
    model = torch.hub.load(r'C:\Users\jhon\Desktop\Valorant-AI-cheats\yolov5' , 'custom', path= r'C:\Users\jhon\Desktop\Valorant-AI-cheats\half.engine',source='local')
  File "C:\Users\jhon\Desktop\Valorant-AI-cheats\Valorant-AI-cheats-env\lib\site-packages\torch\hub.py", line 542, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "C:\Users\jhon\Desktop\Valorant-AI-cheats\Valorant-AI-cheats-env\lib\site-packages\torch\hub.py", line 572, in _load_local
    model = entry(*args, **kwargs)
  File "C:\Users\jhon\Desktop\Valorant-AI-cheats\yolov5\hubconf.py", line 83, in custom
    return _create(path, autoshape=autoshape, verbose=_verbose, device=device)
  File "C:\Users\jhon\Desktop\Valorant-AI-cheats\yolov5\hubconf.py", line 78, in _create
    raise Exception(s) from e
Exception: unpickling stack underflow. Cache may be out of date, try `force_reload=True` or see https://github.com/ultralytics/yolov5/issues/36 for help.

**Comment by zerollzeng** [comment]
Like a dup issue of https://github.com/NVIDIA/TensorRT/issues/2567. Can you try it?

**Comment by Allmight0000** [comment]
Loading C:\Users\jhon\Desktop\Valorant-AI-cheats\best.engine for TensorRT inference...
[01/30/2023-10:58:26] [TRT] [I] [MemUsageChange] Init CUDA: CPU +441, GPU +0, now: CPU 6718, GPU 1390 (MiB)
[01/30/2023-10:58:26] [TRT] [I] Loaded engine size: 15 MiB
[01/30/2023-10:58:27] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +914, GPU +394, now: CPU 7704, GPU 1800 (MiB)
[01/30/2023-10:58:27] [TRT] [W] TensorRT was linked against cuDNN 8.4.1 but loaded cuDNN 8.3.2
[01/30/2023-10:58:27] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +0, now: CPU 0, GPU 0 (MiB)    
[01/30/2023-10:58:27] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +2, GPU +8, now: CPU 7689, GPU 1800 (MiB)
[01/30/2023-10:58:27] [TRT] [W] TensorRT was linked against cuDNN 8.4.1 but loaded cuDNN 8.3.2
[01/30/2023-10:58:27] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +0, now: CPU 0, GPU 0 (MiB)
Adding AutoShape... 
Traceback (most recent call last):
  File "c:\Users\jhon\Desktop\Valorant-AI-cheats\scripts\dxcam_main.py", line 124, in <module>
    df = model(screenshot, size=736).pandas().xyxy[0]
  File "C:\Users\jhon\Desktop\Valorant-AI-cheats\Valorant-AI-cheats-env\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\jhon\Desktop\Valorant-AI-cheats\Valorant-AI-cheats-env\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\jhon\Desktop\Valorant-AI-cheats\yolov5\models\common.py", line 705, in forward
    y = self.model(x, augment=augment)  # forward
  File "C:\Users\jhon\Desktop\Valorant-AI-cheats\Valorant-AI-cheats-env\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\jhon\Desktop\Valorant-AI-cheats\yolov5\models\common.py", line 537, in forward
    assert im.shape == s, f"input size {im.shape} {'>' if self.dynamic else 'not equal to'} max model size {s}"
AssertionError: input size torch.Size([1, 3, 416, 736]) not equal to max model size (1, 3, 736, 736)

**Comment by ttyio** [comment]
Closing since no activity for more than 3 weeks, please reopen if you still have question, thanks!

**Comment by Allmight0000** [comment]
Loading C:\Users\jhon\Downloads\Valorant-AI-cheats-Stable\Valorant-AI-cheats-Stable\scripts\best_nano_new.engine for TensorRT inference...
Traceback (most recent call last):
  File "C:\Users\jhon\Downloads\Valorant-AI-cheats-Stable\yolov5\hubconf.py", line 49, in _create
    model = DetectMultiBackend(path, device=device, fuse=autoshape)  # detection model
  File "C:\Users\jhon\Downloads\Valorant-AI-cheats-Stable\yolov5\models\common.py", line 390, in __init__
    import tensorrt as trt  # https://developer.nvidia.com/nvidia-tensorrt-download
ModuleNotFoundError: No module named 'tensorrt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jhon\Downloads\Valorant-AI-cheats-Stable\yolov5\hubconf.py", line 60, in _create
    model = attempt_load(path, device=device, fuse=False)  # arbitrary model
  File "C:\Users\jhon\Downloads\Valorant-AI-cheats-Stable\yolov5\models\experimental.py", line 79, in attempt_load
    ckpt = torch.load(attempt_download(w), map_location='cpu')  # load
  File "C:\AI-Aimbot-2.2.2\env\lib\site-packages\torch\serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\AI-Aimbot-2.2.2\env\lib\site-packages\torch\serialization.py", line 1002, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: unpickling stack underflow

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:/Users/jhon/Downloads/Valorant-AI-cheats-Stable/Valorant-AI-cheats-Stable/scripts/dxcam_main.py", line 104, in <module>
    model = torch.hub.load(r'C:\Users\jhon\Downloads\Valorant-AI-cheats-Stable\yolov5' , 'custom', path= r'C:\Users\jhon\Downloads\Valorant-AI-cheats-Stable\Valorant-AI-cheats-Stable\scripts\best_nano_new.engine',source='local')
  File "C:\AI-Aimbot-2.2.2\env\lib\site-packages\torch\hub.py", line 542, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "C:\AI-Aimbot-2.2.2\env\lib\site-packages\torch\hub.py", line 572, in _load_local
    model = entry(*args, **kwargs)
  File "C:\Users\jhon\Downloads\Valorant-AI-cheats-Stable\yolov5\hubconf.py", line 83, in custom
    return _create(path, autoshape=autoshape, verbose=_verbose, device=device)
  File "C:\Users\jhon\Downloads\Valorant-AI-cheats-Stable\yolov5\hubconf.py", line 78, in _create
    raise Exception(s) from e
Exception: unpickling stack underflow. Cache may be out of date, try `force_reload=True` or see https://github.com/ultralytics/yolov5/issues/36 for help.
