### ISSUE TITLE
[Stable Diffusion] vae engine build failure 

### ISSUE THREAD

**Issue by fkunn1326** [NVIDIA/TensorRT#2642]
## Description

[fail to run following code]
python demo-diffusion.py "a beautiful photograph of Mt. Fuji during cherry blossom" --hf-token=$HF_TOKEN -v --denoising-prec=fp32

## Environment

**TensorRT Version**:  8.5.3.1
**NVIDIA GPU**:  RTX 2060
**NVIDIA Driver Version**:  527.56
**CUDA Version**: 11.6
**CUDNN Version**:  
**Operating System**: Windows11
**Python Version (if applicable)**: 3.10.8
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 1.12.0+cu116
**Baremetal or Container (if so, version)**: 

## Relevant Files

https://huggingface.co/fkunn1326/tensorrt_test/blob/main/onnx/vae.opt.onnx

![image](https://user-images.githubusercontent.com/92153597/217106216-e1416734-085b-4d48-8825-e92e93548f42.png)
![image](https://user-images.githubusercontent.com/92153597/217106332-674cc640-eae3-443b-ba14-4cb453b0d2a3.png)

```
[W] Skipping tactic 0x0000000000000000 due to exception autotuning: CUDA error 2 allocating 2147747325-byte buffer: out of memory
[W] Skipping tactic 0x0000000000000000 due to exception autotuning: CUDA error 2 allocating 1073874429-byte buffer: out of memory
[E] 10: [optimizer.cpp::nvinfer1::builder::cgraph::LeafCNode::computeCosts::3728] Error Code 10: Internal Error (Could not find any implementation for node {ForeignNode[onnx::MatMul_1081 + (Unnamed Layer* 40) [Shuffle]...Div_158]}.)
[E] 2: [builder.cpp::nvinfer1::builder::Builder::buildSerializedNetwork::751] Error Code 2: Internal Error (Assertion engine != nullptr failed. )
[!] Invalid Engine. Please ensure the engine was built correctly
Traceback (most recent call last):
  File "D:\TensorRT\demo\Diffusion\demo-diffusion.py", line 489, in <module>
    demo.loadEngines(args.engine_dir, args.onnx_dir, args.onnx_opset,
  File "D:\TensorRT\demo\Diffusion\demo-diffusion.py", line 248, in loadEngines
    engine.build(onnx_opt_path, fp16=True, \
  File "D:\TensorRT\demo\Diffusion\utilities.py", line 72, in build
    engine = engine_from_network(network_from_onnx_path(onnx_path), config=CreateConfig(fp16=fp16, profiles=[p],
  File "<string>", line 3, in func_impl
  File "C:\Users\user\miniconda3\lib\site-packages\polygraphy\backend\base\loader.py", line 42, in __call__
    return self.call_impl(*args, **kwargs)
  File "C:\Users\user\miniconda3\lib\site-packages\polygraphy\backend\trt\loader.py", line 526, in call_impl
    return engine_from_bytes(super().call_impl)
  File "<string>", line 3, in func_impl
  File "C:\Users\user\miniconda3\lib\site-packages\polygraphy\backend\base\loader.py", line 42, in __call__
    return self.call_impl(*args, **kwargs)
  File "C:\Users\user\miniconda3\lib\site-packages\polygraphy\backend\trt\loader.py", line 550, in call_impl
    buffer, owns_buffer = util.invoke_if_callable(self._serialized_engine)
  File "C:\Users\user\miniconda3\lib\site-packages\polygraphy\util\util.py", line 661, in invoke_if_callable
    ret = func(*args, **kwargs)
  File "C:\Users\user\miniconda3\lib\site-packages\polygraphy\backend\trt\loader.py", line 484, in call_impl
    G_LOGGER.critical("Invalid Engine. Please ensure the engine was built correctly")
  File "C:\Users\user\miniconda3\lib\site-packages\polygraphy\logger\logger.py", line 597, in critical
    raise PolygraphyException(message) from None
polygraphy.exception.exception.PolygraphyException: Invalid Engine. Please ensure the engine was built correctly
```

**Comment by fkunn1326** [comment]
I was able to get it to work by using --build-preview-features
