### ISSUE TITLE
`Internal Error (Assertion !n->candidateRequirements.empty() failed. No supported formats for /model/Reshape_24)`

### ISSUE THREAD

**Issue by nrakltx** [NVIDIA/TensorRT#2751]
## Description

I am compiling a model from ONNX to TensorRT with plugins (usage as per [here](https://github.com/NVIDIA/TensorRT/blob/main/demo/Diffusion/README.md)).
During compilation, I am getting The following error:

```
[E] 2: [optimizer.cpp::getFormatRequirements::3103] Error Code 2: Internal Error (Assertion !n->candidateRequirements.empty() failed. No supported formats for /model/Reshape_24)
[E] 2: [builder.cpp::buildSerializedNetwork::751] Error Code 2: Internal Error (Assertion engine != nullptr failed. )
[!] Invalid Engine. Please ensure the engine was built correctly
```

From what I understand, TRT is not able to find a compatible implementation for the Reshape operator. It is quite unclear to me why, for it is quite a standard node (see Node `/model/Reshape_24` in the attached model).

The only documented event in which this error occurred is [here](https://github.com/NVIDIA/TensorRT/issues/2326), where the issue was solved by upgrading to TRT 8.5, which I am already on.

Attached  as well is the model.
## Environment

**TensorRT Version**: 8.5.2.2
**NVIDIA GPU**: A100 40G, with the same behaviour occuring on T4 as well
**NVIDIA Driver Version**: 520.61.05
**CUDA Version**: 11.8
**CUDNN Version**: 8.8.0
**Operating System**: Debian 11
**Python Version (if applicable)**: Python 3.9
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**: 

## Relevant Files

[The ONNX model and the shared library
](https://drive.google.com/drive/folders/1gZ7NG2r3w5JOuhNavTZeQ2DYITY0krpT?usp=share_link)

## Steps To Reproduce
Run the following with `LD_PRELOAD` including the attached `.so`.

```Python
import torch
import polygraphy.backend.trt as poly
network = poly.network_from_onnx_path(onnx_path)

available_cuda_mem, _ = torch.cuda.memory.mem_get_info()
# build engine with all available device memory
builder_config = poly.CreateConfig(
    max_workspace_size=available_cuda_mem,
    profiles=[trt.Profile().add('INPUT0', min=[1, 3, 800, 1344], opt=[1, 3, 800, 1344], max=[1, 3, 800, 1344])],
    fp16=True,
    tf32=True
)

engine = poly.engine_from_network(network, config=builder_config)
```

**Comment by zerollzeng** [comment]
trtexec
```
[03/12/2023-15:25:09] [V] [TRT] Registering tensor: INPUT0 for ONNX tensor: INPUT0
[03/12/2023-15:25:09] [V] [TRT] Importing initializer:
[03/12/2023-15:25:09] [W] [TRT] parsers/onnx/onnx2trt_utils.cpp:375: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[03/12/2023-15:25:09] [V] [TRT] Importing initializer:
terminate called after throwing an instance of 'std::runtime_error'
  what():  ONNX graph has duplicate tensor name:
Aborted (core dumped)
```
polygraphy with onnx runtime
```
Traceback (most recent call last):
  File "/usr/local/bin/polygraphy", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/polygraphy/tools/_main.py", line 70, in main
    status = selected_tool.run(args)
  File "/usr/local/lib/python3.8/dist-packages/polygraphy/tools/base/tool.py", line 171, in run
    status = self.run_impl(args)
  File "/usr/local/lib/python3.8/dist-packages/polygraphy/tools/run/run.py", line 224, in run_impl
    exec(str(script))
  File "<string>", line 21, in <module>
  File "/usr/local/lib/python3.8/dist-packages/polygraphy/comparator/comparator.py", line 213, in run
    run_results.append((runner.name, execute_runner(runner, loader_cache)))
  File "/usr/local/lib/python3.8/dist-packages/polygraphy/comparator/comparator.py", line 98, in execute_runner
    with runner as active_runner:
  File "/usr/local/lib/python3.8/dist-packages/polygraphy/backend/base/runner.py", line 60, in __enter__
    self.activate()
  File "/usr/local/lib/python3.8/dist-packages/polygraphy/backend/base/runner.py", line 95, in activate
    self.activate_impl()
  File "/usr/local/lib/python3.8/dist-packages/polygraphy/backend/onnxrt/runner.py", line 43, in activate_impl
    self.sess, _ = util.invoke_if_callable(self._sess)
  File "/usr/local/lib/python3.8/dist-packages/polygraphy/util/util.py", line 661, in invoke_if_callable
    ret = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/polygraphy/backend/base/loader.py", line 42, in __call__
    return self.call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/polygraphy/backend/onnxrt/loader.py", line 67, in call_impl
    return onnxrt.InferenceSession(model_bytes, providers=providers)
  File "/usr/local/lib/python3.8/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 360, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/usr/local/lib/python3.8/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 397, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Load model from /zeroz/github_bug/2751/clean_model.onnx failed:Invalid model. Node input 'model.backbone.layers.0.blocks.0.attn.relative_position_index' is not a graph input, initializer, or output of a previous node.
```
Looks like the onnx model is invalid. my download is broken?
```
# md5sum clean_model.onnx
9fc4d8929d5a2cd96a945b6a4e37f316  clean_model.onnx
```

**Comment by nrakltx** [comment]
Yes sorry I modified the model's weights incorrectly, [this](https://drive.google.com/file/d/1Cnh3oGozhj2LaOZuhwECrAh_toXYrHEk/view?usp=share_link) file is the correct one, sorry for the confusion and thx for the quick response!

**Comment by zerollzeng** [comment]
Can you try 8.6 EA? it's released. Thanks!
```
[03/16/2023-07:43:00] [I] === Performance summary ===
[03/16/2023-07:43:00] [I] Throughput: 3.35711 qps
[03/16/2023-07:43:00] [I] Latency: min = 299.569 ms, max = 299.997 ms, mean = 299.809 ms, median = 299.866 ms, percentile(90%) = 299.894 ms, percentile(95%) = 299.997 ms, percentile(99%) = 299.997 ms
[03/16/2023-07:43:00] [I] Enqueue Time: min = 297.405 ms, max = 297.831 ms, mean = 297.655 ms, median = 297.706 ms, percentile(90%) = 297.739 ms, percentile(95%) = 297.831 ms, percentile(99%) = 297.831 ms
[03/16/2023-07:43:00] [I] H2D Latency: min = 0.572998 ms, max = 0.582153 ms, mean = 0.578191 ms, median = 0.579956 ms, percentile(90%) = 0.581543 ms, percentile(95%) = 0.582153 ms, percentile(99%) = 0.582153 ms
[03/16/2023-07:43:00] [I] GPU Compute Time: min = 296.83 ms, max = 297.267 ms, mean = 297.083 ms, median = 297.132 ms, percentile(90%) = 297.164 ms, percentile(95%) = 297.267 ms, percentile(99%) = 297.267 ms
[03/16/2023-07:43:00] [I] D2H Latency: min = 2.07349 ms, max = 2.17102 ms, mean = 2.14821 ms, median = 2.15173 ms, percentile(90%) = 2.16455 ms, percentile(95%) = 2.17102 ms, percentile(99%) = 2.17102 ms
[03/16/2023-07:43:00] [I] Total Host Walltime: 3.5745 s
[03/16/2023-07:43:00] [I] Total GPU Compute Time: 3.565 s
[03/16/2023-07:43:00] [W] * Throughput may be bound by Enqueue Time rather than GPU Compute and the GPU may be under-utilized.
[03/16/2023-07:43:00] [W]   If not already in use, --useCudaGraph (utilize CUDA graphs where possible) may increase the throughput.
[03/16/2023-07:43:00] [I] Explanations of the performance metrics are printed in the verbose logs.
[03/16/2023-07:43:00] [V]
[03/16/2023-07:43:00] [V] === Explanations of the performance metrics ===
[03/16/2023-07:43:00] [V] Total Host Walltime: the host walltime from when the first query (after warmups) is enqueued to when the last query is completed.
[03/16/2023-07:43:00] [V] GPU Compute Time: the GPU latency to execute the kernels for a query.
[03/16/2023-07:43:00] [V] Total GPU Compute Time: the summation of the GPU Compute Time of all the queries. If this is significantly shorter than Total Host Walltime, the GPU may be under-utilized because of host-side overheads or data transfers.
[03/16/2023-07:43:00] [V] Throughput: the observed throughput computed by dividing the number of queries by the Total Host Walltime. If this is significantly lower than the reciprocal of GPU Compute Time, the GPU may be under-utilized because of host-side overheads or data transfers.
[03/16/2023-07:43:00] [V] Enqueue Time: the host latency to enqueue a query. If this is longer than GPU Compute Time, the GPU may be under-utilized.
[03/16/2023-07:43:00] [V] H2D Latency: the latency for host-to-device data transfers for input tensors of a single query.
[03/16/2023-07:43:00] [V] D2H Latency: the latency for device-to-host data transfers for output tensors of a single query.
[03/16/2023-07:43:00] [V] Latency: the summation of H2D Latency, GPU Compute Time, and D2H Latency. This is the latency to infer a single query.
[03/16/2023-07:43:00] [I]
&&&& PASSED TensorRT.trtexec [TensorRT v8600] # trtexec --onnx=white_model.onnx --verbose
```

**Comment by nrakltx** [comment]
Awesome! This works. Thank you!
