### ISSUE TITLE
release/8.5 demo diffusion not working

### ISSUE THREAD

**Issue by Vozf** [NVIDIA/TensorRT#2789]
I've checked out the branch release/8.5  and followed all the instructions in the readme. I've got this error on the step 
`LD_PRELOAD=${PLUGIN_LIBS} python3 demo-diffusion.py "a beautiful photograph of Mt. Fuji during cherry blossom" --hf-token=$HF_TOKEN -v`

```
Building TensorRT engine for onnx/unet_fp16.opt.onnx: engine/unet_fp16.plan
[W] CUDA lazy loading is not enabled. Enabling it can significantly reduce device memory usage. See `CUDA_MODULE_LOADING` in https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#env-vars
[W] parsers/onnx/onnx2trt_utils.cpp:375: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[W] parsers/onnx/onnx2trt_utils.cpp:403: One or more weights outside the range of INT32 was clamped
[I]     Configuring with profiles: [Profile().add('sample', min=(2, 4, 64, 64), opt=(2, 4, 64, 64), max=(32, 4, 64, 64)).add('encoder_hidden_states', min=(2, 77, 768), opt=(2, 77, 768), max=(32, 77, 768)).add('timestep', min=[1], opt=[1], max=[1])]
[I] Building engine with configuration:
    Flags                  | [FP16]
    Engine Capability      | EngineCapability.DEFAULT
    Memory Pools           | [WORKSPACE: 11170.44 MiB]
    Tactic Sources         | [CUBLAS, CUBLAS_LT, CUDNN, EDGE_MASK_CONVOLUTIONS, JIT_CONVOLUTIONS]
    Profiling Verbosity    | ProfilingVerbosity.DETAILED
[E] 9: [pluginV2Builder.cpp::reportPluginError::23] Error Code 9: Internal Error (GroupNormN-0: could not find any supported formats consistent with input/output data types)
[E] 2: [builder.cpp::buildSerializedNetwork::738] Error Code 2: Internal Error (Assertion engine != nullptr failed. )
[!] Invalid Engine. Please ensure the engine was built correctly
Traceback (most recent call last):
  File "demo-diffusion.py", line 487, in <module>
    demo.loadEngines(args.engine_dir, args.onnx_dir, args.onnx_opset, 
  File "demo-diffusion.py", line 246, in loadEngines
    engine.build(onnx_opt_path, fp16=True, \
  File "/workspace/demo/Diffusion/utilities.py", line 72, in build
    engine = engine_from_network(network_from_onnx_path(onnx_path), config=CreateConfig(fp16=fp16, profiles=[p],
  File "<string>", line 3, in func_impl
  File "/usr/local/lib/python3.8/dist-packages/polygraphy/backend/base/loader.py", line 42, in __call__
    return self.call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/polygraphy/backend/trt/loader.py", line 526, in call_impl
    return engine_from_bytes(super().call_impl)
  File "<string>", line 3, in func_impl
  File "/usr/local/lib/python3.8/dist-packages/polygraphy/backend/base/loader.py", line 42, in __call__
    return self.call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/polygraphy/backend/trt/loader.py", line 550, in call_impl
    buffer, owns_buffer = util.invoke_if_callable(self._serialized_engine)
  File "/usr/local/lib/python3.8/dist-packages/polygraphy/util/util.py", line 661, in invoke_if_callable
    ret = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/polygraphy/backend/trt/loader.py", line 484, in call_impl
    G_LOGGER.critical("Invalid Engine. Please ensure the engine was built correctly")
  File "/usr/local/lib/python3.8/dist-packages/polygraphy/logger/logger.py", line 597, in critical
    raise PolygraphyException(message) from None
polygraphy.exception.exception.PolygraphyException: Invalid Engine. Please ensure the engine was built correctly

```

As I've said in this issue https://github.com/NVIDIA/TensorRT/issues/2784 8.6.0 is also not working so it seems like all of the demo diffusion versions are not working

**Comment by zerollzeng** [comment]
which device you are using? I've seen several similar bug: https://github.com/NVIDIA/TensorRT/issues?q=%22could+not+find+any+supported+formats+consistent+with+input%2Foutput+data+types%22

**Comment by Vozf** [comment]
1080ti

**Comment by Vozf** [comment]
So for anyone having the same error, the problem is probably the gpu. Doing the same steps on t4 gpu works. If supporting 1080ti isn't intented the issue can be closed

**Comment by zerollzeng** [comment]
I have a vague memory that we only support turing+ GPU for demo diffusion. close this for now.

**Comment by Vozf** [comment]
@zerollzeng by the way is there any particular reason why fp16 flag in 8.5 is used for unet but not vae?

**Comment by Vozf** [comment]
Talking about those lines
https://github.com/NVIDIA/TensorRT/blob/68b5072fdb9df6b6edab1392b02a705394b2e906/demo/Diffusion/demo-diffusion.py#L139-L143
