### ISSUE TITLE
Diffusion demo shows Error: Invalid Engine

### ISSUE THREAD

**Issue by PeterLu8888** [NVIDIA/TensorRT#2916]
I build the Diffusion  demo in windows11 (not using docker environment)
In the final step, it showed error of **Invalid Engine**

[I] Building engine with configuration:
    Flags                  | [FP16]
    Engine Capability      | EngineCapability.DEFAULT
    Memory Pools           | [WORKSPACE: 3018.00 MiB, TACTIC_DRAM: 8191.50 MiB]
    Tactic Sources         | []
    Profiling Verbosity    | ProfilingVerbosity.DETAILED
    Preview Features       | [DISABLE_EXTERNAL_TACTIC_SOURCES_FOR_CORE_0805]
[W] Myelin graph with multiple dynamic values may have poor performance if they differ.
[E] 10: Could not find any implementation for node {ForeignNode[/decoder/up_blocks.2/resnets.0/norm1/Constant_1_output_0 + (Unnamed Layer* 524) [Shuffle].../decoder/up_blocks.2/resnets.0/conv1/Cast]}.
[E] 10: [optimizer.cpp::nvinfer1::builder::cgraph::LeafCNode::computeCosts::3873] Error Code 10: Internal Error (Could not find any implementation for node {ForeignNode[/decoder/up_blocks.2/resnets.0/norm1/Constant_1_output_0 + (Unnamed Layer* 524) [Shuffle].../decoder/up_blocks.2/resnets.0/conv1/Cast]}.)
[!] Invalid Engine. Please ensure the engine was built correctly
Traceback (most recent call last):
  File "demo_txt2img.py", line 133, in <module>
    demo.loadEngines(args.engine_dir, args.onnx_dir, args.onnx_opset,
  File "F:\AI\tensorrt\demo\Diffusion\stable_diffusion_pipeline.py", line 290, in loadEngines
    engine.build(onnx_opt_path,
  File "F:\AI\tensorrt\demo\Diffusion\utilities.py", line 206, in build
    engine = engine_from_network(
  File "<string>", line 3, in engine_from_network
  File "C:\Users\Peter\anaconda3\envs\tensor\lib\site-packages\polygraphy\backend\base\loader.py", line 42, in __call__
    return self.call_impl(*args, **kwargs)
  File "C:\Users\Peter\anaconda3\envs\tensor\lib\site-packages\polygraphy\backend\trt\loader.py", line 530, in call_impl
    return engine_from_bytes(super().call_impl)
  File "<string>", line 3, in engine_from_bytes
  File "C:\Users\Peter\anaconda3\envs\tensor\lib\site-packages\polygraphy\backend\base\loader.py", line 42, in __call__
    return self.call_impl(*args, **kwargs)
  File "C:\Users\Peter\anaconda3\envs\tensor\lib\site-packages\polygraphy\backend\trt\loader.py", line 554, in call_impl
    buffer, owns_buffer = util.invoke_if_callable(self._serialized_engine)
  File "C:\Users\Peter\anaconda3\envs\tensor\lib\site-packages\polygraphy\util\util.py", line 661, in invoke_if_callable
    ret = func(*args, **kwargs)
  File "C:\Users\Peter\anaconda3\envs\tensor\lib\site-packages\polygraphy\backend\trt\loader.py", line 488, in call_impl
    G_LOGGER.critical("Invalid Engine. Please ensure the engine was built correctly")
  File "C:\Users\Peter\anaconda3\envs\tensor\lib\site-packages\polygraphy\logger\logger.py", line 597, in critical
    raise PolygraphyException(message) from None
polygraphy.exception.exception.PolygraphyException: Invalid Engine. Please ensure the engine was built correctly

## Environment

**TensorRT Version**:  8.6.0
**NVIDIA GPU**: 3070
**NVIDIA Driver Version**: 531.61
**CUDA Version**: 12.0
**CUDNN Version**: 
**Operating System**: Window11, 22621
**Python Version (if applicable)**:  3.8.10
**PyTorch Version (if applicable)**:  1.13.1

## Steps To Reproduce

Install the requirement packages
Generate onnx files, and plan files done.
Run demo with original code.

**Comment by zerollzeng** [comment]
> [E] 10: Could not find any implementation for node {ForeignNode[/decoder/up_blocks.2/resnets.0/norm1/Constant_1_output_0 + (Unnamed Layer* 524) [Shuffle].../decoder/up_blocks.2/resnets.0/conv1/Cast]}.
> [E] 10: [optimizer.cpp::nvinfer1::builder::cgraph::LeafCNode::computeCosts::3873] Error Code 10: Internal Error (Could not find any implementation for node {ForeignNode[/decoder/up_blocks.2/resnets.0/norm1/Constant_1_output_0 + (Unnamed Layer* 524)

The reason why it fails.

@oxana-nvidia Is this a known issue? cc @nvpohanh

**Comment by oxana-nvidia** [comment]
I think it may be due to not enough memory on 3070 to run it. [samurdhikaru](https://github.com/samurdhikaru) Has more experience with it. 
 
Also we only officially support Windows 10. https://docs.nvidia.com/deeplearning/tensorrt/support-matrix/index.html#software-version-platform

**Comment by PeterLu8888** [comment]
@oxana-nvidia My friend uses 2070 to run the demo successfully. Maybe my GPU only has 8GB, but no error shows when I create the plan files.

**Comment by ttyio** [comment]
closing since no activity for more than 3 weeks per our policy, thanks all!
