### ISSUE TITLE
Could not find a version that satisfies the requirement tensorrt_libs==8.6.1

### ISSUE THREAD

**Issue by Naofel-eal** [NVIDIA/TensorRT#2963]
Hello,
I am trying to install tensorrt thanks the command
`pip install tensorrt`
And I have the following error:
```cmd
> pip install tensorrt
Collecting tensorrt
  Using cached tensorrt-8.6.1.tar.gz (16 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: tensorrt
  Building wheel for tensorrt (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [54 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib
      creating build\lib\tensorrt
      copying tensorrt\__init__.py -> build\lib\tensorrt
      running egg_info
      writing tensorrt.egg-info\PKG-INFO
      writing dependency_links to tensorrt.egg-info\dependency_links.txt
      writing requirements to tensorrt.egg-info\requires.txt
      writing top-level names to tensorrt.egg-info\top_level.txt
      reading manifest file 'tensorrt.egg-info\SOURCES.txt'
      adding license file 'LICENSE.txt'
      writing manifest file 'tensorrt.egg-info\SOURCES.txt'
      C:\Users\naofe\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      installing to build\bdist.win-amd64\wheel
      running install
      Looking in indexes: https://pypi.nvidia.com
      ERROR: Could not find a version that satisfies the requirement tensorrt_libs==8.6.1 (from versions: none)
      ERROR: No matching distribution found for tensorrt_libs==8.6.1
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\naofe\AppData\Local\Temp\pip-install-2jzqxcgm\tensorrt_5d6b54ffe8c04b4bb85f13a50eda16e5\setup.py", line 49, in <module>
          setup(
        File "C:\Users\naofe\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\naofe\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "C:\Users\naofe\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\naofe\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\naofe\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\dist.py", line 1208, in run_command
          super().run_command(command)
        File "C:\Users\naofe\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\naofe\AppData\Local\Programs\Python\Python39\lib\site-packages\wheel\bdist_wheel.py", line 360, in run
          self.run_command("install")
        File "C:\Users\naofe\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\naofe\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\dist.py", line 1208, in run_command
          super().run_command(command)
        File "C:\Users\naofe\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\naofe\AppData\Local\Temp\pip-install-2jzqxcgm\tensorrt_5d6b54ffe8c04b4bb85f13a50eda16e5\setup.py", line 43, in run
          install_dep("{:}_libs".format(tensorrt_module))
        File "C:\Users\naofe\AppData\Local\Temp\pip-install-2jzqxcgm\tensorrt_5d6b54ffe8c04b4bb85f13a50eda16e5\setup.py", line 41, in install_dep
          status.check_returncode()
        File "C:\Users\naofe\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 460, in check_returncode
          raise CalledProcessError(self.returncode, self.args, self.stdout,
      subprocess.CalledProcessError: Command '['C:\\Users\\naofe\\AppData\\Local\\Programs\\Python\\Python39\\python.exe', '-m', 'pip', 'install', 'tensorrt_libs==8.6.1', '--index-url', 'https://pypi.nvidia.com']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for tensorrt
  Running setup.py clean for tensorrt
Failed to build tensorrt
ERROR: Could not build wheels for tensorrt, which is required to install pyproject.toml-based projects
```

It sems that pip can't find the version 8.6.1 of tensorrt-libs.

Configuration:
Windows 11
Cuda 12.1
Python 3.9.13

**Comment by Neltherion** [comment]
Any update on this?

**Comment by zerollzeng** [comment]
@pranavm-nvidia do we support install trt via pip in windows?

**Comment by pranavm-nvidia** [comment]
No, the Windows wheels are only shipped via the zip packages on devzone currently.

**Comment by zerollzeng** [comment]
Thanks, @Neltherion could you please try install the python package as Pranav said, thanks!

**Comment by ttyio** [comment]
closing since no activity for more than 3 weeks, thanks!
