### ISSUE TITLE
ImportError: No module named pycuda.driver

### ISSUE THREAD

**Issue by santhoshnumberone** [NVIDIA/TensorRT#300]
## Description
I am trying out how to use tensorRT using docker [Have you Optimized your Deep Learning Model Before Deployment?](https://towardsdatascience.com/have-you-optimized-your-deep-learning-model-before-deployment-cdc3aa7f413d)

pycuda seems not installed for python 2

## Environment

**TensorRT Version**: 
**GPU Type**:  GTX 1050Ti
**Nvidia Driver Version**: 440.33.01 
**CUDA Version**:  10.2
**CUDNN Version**:  Major 7 and minor 6
**Operating System + Version**:  Ubuntu 18.04
**Python Version (if applicable)**: Python 2 
**Baremetal or Container (if container which image + tag)**: https://gitlab.com/aminehy/Docker-TensorRT-OpenCV-Python3

## Relevant Files

I am trying to follow the guide here [Have you Optimized your Deep Learning Model Before Deployment?](https://towardsdatascience.com/have-you-optimized-your-deep-learning-model-before-deployment-cdc3aa7f413d)

## Steps To Reproduce

`docker pull aminehy/tensorrt-opencv-python3:version-1.3`

Ran this

`To install Python sample dependencies, run /opt/tensorrt/python/python_setup.sh`

installed 

protobuf, numpy and tensorflow-gpu like

`python -m pip install protobuf`

`python -m pip install numpy`

`python -m pip install tensorflow-gpu==1.15.0`

Ran this

```
cd /opt/tensorrt/python
dpkg -i *-tf_*.deb
UFF_PATH="$(python -c 'import uff; print(uff.__path__[0])')"
chmod +x ${UFF_PATH}/bin/convert_to_uff.py
ln -sf ${UFF_PATH}/bin/convert_to_uff.py /usr/local/bin/convert-to-uff
```

Pulled this inside the docker
```
git clone https://gitlab.com/aminehy/YOLOv3-Darknet-ONNX-TensorRT.git
cd YOLOv3-Darknet-ONNX-TensorRT/
```

Tried to run 

`python yolov3_to_onnx.py`

I got this error

>Traceback (most recent call last):
>  File "onnx_to_tensorrt.py", line 4, in <module>
>    import common
>  File "/workspace/YOLOv3-Darknet-ONNX-TensorRT/common.py", line 5, in <module>
>    import pycuda.driver as cuda
>ImportError: No module named pycuda.driver

Tried to install pycuda using 

`python -m pip install pycuda`

But i get his long error

> x86_64-linux-gnu-gcc -pthread -fwrapv -Wall -O3 -DNDEBUG -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DBOOST_PYTHON_SOURCE=1 -DHAVE_CURAND=1 -DPYGPU_PACKAGE=pycuda -DBOOST_THREAD_DONT_USE_CHRONO=1 -DPYGPU_PYCUDA=1 -DBOOST_MULTI_INDEX_DISABLE_SERIALIZATION=1 -DBOOST_THREAD_BUILD_DLL=1 -Dboost=pycudaboost -DBOOST_ALL_NO_LIB=1 -Isrc/cpp -Ibpl-subset/bpl_subset -I/usr/local/cuda/include -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c src/cpp/cuda.cpp -o build/temp.linux-x86_64-2.7/src/cpp/cuda.o
>     In file included from bpl-subset/bpl_subset/boost/python/detail/prefix.hpp:13:0,
>                      from bpl-subset/bpl_subset/boost/python/args.hpp:8,
>                      from bpl-subset/bpl_subset/boost/python.hpp:11,
>                      from src/cpp/cuda.hpp:36,
>                      from src/cpp/cuda.cpp:1:
>     bpl-subset/bpl_subset/boost/python/detail/wrap_python.hpp:50:23: fatal error: pyconfig.h: No such file or directory
>     compilation terminated.
>     error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
>     ----------------------------------------
> ERROR: Command errored out with exit status 1: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-hEj4qY/pycuda/setup.py'"'"'; __file__='"'"'/tmp/pip-install-hEj4qY/pycuda/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-mk7D7L/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

Could anyone please help out

**Comment by santhoshnumberone** [comment]
Why don't we have a `YOLOv3-Darknet-ONNX-TensorRT` which uses `python 3` instead of `python 2`?

Since `python 2` will not be supported from `Jan 1 2020`
