### ISSUE TITLE
ImportError: /home/nvidia/.local/lib/python3.8/site-packages/tensorrt/tensorrt.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by tianxz1** [NVIDIA/TensorRT#3053]
>>> import tensorrt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nvidia/.local/lib/python3.8/site-packages/tensorrt/__init__.py", line 68, in <module>
    from .tensorrt import *
ImportError: /home/nvidia/.local/lib/python3.8/site-packages/tensorrt/tensorrt.so: cannot open shared object file: No such file or directory

Here are my environment variables：
cat ~/.bashrc | grep export
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/TensorRT-8.4.1.5/lib
export PYTHONPATH=$PYTHONPATH:/usr/TensorRT-8.4.1.5/python

My python version of tensorrt is installed through tensorrt-8.4.1.5-cp38-none-linux_aarch64.whl under /usr/TensorRT-8.4.1.5/python

**Comment by zerollzeng** [comment]
Looks like something wrong with your env, could you please try 'pip install tensorrt' directly?

**Comment by ttyio** [comment]
closing since no activity for more than 3 weeks, pls reopen if you still have question, thanks!

**Comment by tianxz1** [comment]
https://forums.developer.nvidia.com/t/is-there-pre-built-tensorrt-python-package-for-drive-agx-orin/236303/9
