### ISSUE TITLE
pip install not functional

### ISSUE THREAD

**Issue by Theratherverydarkestlordever** [NVIDIA/TensorRT#3060]
when trying to install tensorrt via pip, I receive following error:

```
Collecting tensorrt
  Using cached tensorrt-8.6.1.tar.gz (16 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: tensorrt
  Building wheel for tensorrt (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [65 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib
      creating build\lib\tensorrt
      copying tensorrt\__init__.py -> build\lib\tensorrt
      running egg_info
      writing tensorrt.egg-info\PKG-INFO
      writing dependency_links to tensorrt.egg-info\dependency_links.txt
      writing requirements to tensorrt.egg-info\requires.txt
      writing top-level names to tensorrt.egg-info\top_level.txt
      reading manifest file 'tensorrt.egg-info\SOURCES.txt'
      adding license file 'LICENSE.txt'
      writing manifest file 'tensorrt.egg-info\SOURCES.txt'
      C:\Users\Johann Ritter\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
      !!

              ********************************************************************************
              Please avoid running ``setup.py`` directly.
              Instead, use pypa/build, pypa/installer, pypa/build or
              other standards-based tools.

              See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
              ********************************************************************************

      !!
        self.initialize_options()
      installing to build\bdist.win-amd64\wheel
      running install
      Looking in indexes: https://pypi.nvidia.com
      ERROR: Could not find a version that satisfies the requirement tensorrt_libs==8.6.1 (from versions: none)
      ERROR: No matching distribution found for tensorrt_libs==8.6.1
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Johann Ritter\AppData\Local\Temp\pip-install-wmo_c2mo\tensorrt_6c5fd57cbaa44ed6876de1545f6e00b4\setup.py", line 49, in <module>
          setup(
        File "C:\Users\Johann Ritter\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\Johann Ritter\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "C:\Users\Johann Ritter\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\Johann Ritter\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\Johann Ritter\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\dist.py", line 1244, in run_command
          super().run_command(command)
        File "C:\Users\Johann Ritter\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\Johann Ritter\AppData\Local\Programs\Python\Python310\lib\site-packages\wheel\bdist_wheel.py", line 378, in run
          self.run_command("install")
        File "C:\Users\Johann Ritter\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\Johann Ritter\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\dist.py", line 1244, in run_command
          super().run_command(command)
        File "C:\Users\Johann Ritter\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\Johann Ritter\AppData\Local\Temp\pip-install-wmo_c2mo\tensorrt_6c5fd57cbaa44ed6876de1545f6e00b4\setup.py", line 43, in run
          install_dep("{:}_libs".format(tensorrt_module))
        File "C:\Users\Johann Ritter\AppData\Local\Temp\pip-install-wmo_c2mo\tensorrt_6c5fd57cbaa44ed6876de1545f6e00b4\setup.py", line 41, in install_dep
          status.check_returncode()
        File "C:\Users\Johann Ritter\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 456, in check_returncode
          raise CalledProcessError(self.returncode, self.args, self.stdout,
      subprocess.CalledProcessError: Command '['C:\\Users\\Johann Ritter\\AppData\\Local\\Programs\\Python\\Python310\\python.exe', '-m', 'pip', 'install', 'tensorrt_libs==8.6.1', '--index-url', 'https://pypi.nvidia.com']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for tensorrt
  Running setup.py clean for tensorrt
Failed to build tensorrt
ERROR: Could not build wheels for tensorrt, which is required to install pyproject.toml-based projects
```

**Comment by LukeAI** [comment]
bump. Any resolution @Theratherverydarkestlordever ?

**Comment by Theratherverydarkestlordever** [comment]
> bump. Any resolution @Theratherverydarkestlordever ?

No

**Comment by LukeAI** [comment]
I got it working in the end after doing `pip install --upgrade pip setuptools`

**Comment by zerollzeng** [comment]
> Looking in indexes: https://pypi.nvidia.com
>       ERROR: Could not find a version that satisfies the requirement tensorrt_libs==8.6.1 (from versions: none)
>       ERROR: No matching distribution found for tensorrt_libs==8.6.1

Looks like we don't support this version for Windows in pypi, @pranavm-nvidia am I correct?

**Comment by NSQY** [comment]
Please push a fix for this, I am unable to install TensorRT via pip on Windows 11 using ```pip 23.1.2 setuptools-68.0.0```

**Comment by ttyio** [comment]
let's use zip file installation on Windows follow https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html#installing-zip, I will close this issue, thanks!

**Comment by sachinchauhari479** [comment]
**Error while installing TensorRT via pip.**

 pip install tensorrt --extra-index-url https://pypi.nvidia.com
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com, https://pypi.nvidia.com
Collecting tensorrt
  Downloading https://pypi.nvidia.com/tensorrt/tensorrt-8.6.1.post1.tar.gz (18 kB)
  Preparing metadata (setup.py) ... done
INFO: pip is looking at multiple versions of tensorrt to determine which version is compatible with other requirements. This could take a while.
  Downloading https://pypi.nvidia.com/tensorrt/tensorrt-8.6.1.tar.gz (16 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: tensorrt
  Building wheel for tensorrt (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [68 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib
      creating build\lib\tensorrt
      copying tensorrt\__init__.py -> build\lib\tensorrt
      running egg_info
      writing tensorrt.egg-info\PKG-INFO
      writing dependency_links to tensorrt.egg-info\dependency_links.txt
      writing requirements to tensorrt.egg-info\requires.txt
      writing top-level names to tensorrt.egg-info\top_level.txt
      reading manifest file 'tensorrt.egg-info\SOURCES.txt'
      adding license file 'LICENSE.txt'
      writing manifest file 'tensorrt.egg-info\SOURCES.txt'
      C:\ProgramData\anaconda3\envs\sachin\Lib\site-packages\setuptools\_distutils\cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
      !!

              ********************************************************************************
              Please avoid running ``setup.py`` directly.
              Instead, use pypa/build, pypa/installer or other
              standards-based tools.

              See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
              ********************************************************************************

      !!
        self.initialize_options()
      installing to build\bdist.win-amd64\wheel
      running install
      Defaulting to user installation because normal site-packages is not writeable
      Looking in indexes: https://pypi.nvidia.com, https://pypi.ngc.nvidia.com
      ERROR: Could not find a version that satisfies the requirement tensorrt_libs==8.6.1 (from versions: 9.0.0.post11.dev1, 9.0.0.post12.dev1, 9.0.1.post11.dev4, 9.0.1.post12.dev4)
      ERROR: No matching distribution found for tensorrt_libs==8.6.1
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\sachin\AppData\Local\Temp\pip-install-833zjevk\tensorrt_f08b7d4d40744bf0a5ea732103426702\setup.py", line 49, in <module>
          setup(
        File "C:\ProgramData\anaconda3\envs\sachin\Lib\site-packages\setuptools\__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\ProgramData\anaconda3\envs\sachin\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\ProgramData\anaconda3\envs\sachin\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\ProgramData\anaconda3\envs\sachin\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\ProgramData\anaconda3\envs\sachin\Lib\site-packages\setuptools\dist.py", line 1234, in run_command
          super().run_command(command)
        File "C:\ProgramData\anaconda3\envs\sachin\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\ProgramData\anaconda3\envs\sachin\Lib\site-packages\wheel\bdist_wheel.py", line 360, in run
          self.run_command("install")
        File "C:\ProgramData\anaconda3\envs\sachin\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\ProgramData\anaconda3\envs\sachin\Lib\site-packages\setuptools\dist.py", line 1234, in run_command
          super().run_command(command)
        File "C:\ProgramData\anaconda3\envs\sachin\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\sachin\AppData\Local\Temp\pip-install-833zjevk\tensorrt_f08b7d4d40744bf0a5ea732103426702\setup.py", line 43, in run
          install_dep("{:}_libs".format(tensorrt_module))
        File "C:\Users\sachin\AppData\Local\Temp\pip-install-833zjevk\tensorrt_f08b7d4d40744bf0a5ea732103426702\setup.py", line 41, in install_dep
          status.check_returncode()
        File "C:\ProgramData\anaconda3\envs\sachin\Lib\subprocess.py", line 502, in check_returncode
          raise CalledProcessError(self.returncode, self.args, self.stdout,
      subprocess.CalledProcessError: Command '['C:\\ProgramData\\anaconda3\\envs\\sachin\\python.exe', '-m', 'pip', 'install', 'tensorrt_libs==8.6.1', '--index-url', 'https://pypi.nvidia.com']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for tensorrt
  Running setup.py clean for tensorrt
Failed to build tensorrt
ERROR: Could not build wheels for tensorrt, which is required to install pyproject.toml-based projects

**Comment by kyrie2to11** [comment]
> I got it working in the end after doing `pip install --upgrade pip setuptools`

Weird, but it works！
