### ISSUE TITLE
build engine failure of TensorRT 8.6.1 when running sd on GPU RTX3090

### ISSUE THREAD

**Issue by theNefelibata** [NVIDIA/TensorRT#3195]
## Environment

**TensorRT Version**: 8.6.1

**NVIDIA GPU**: 3090

**NVIDIA Driver Version**: 510.47.03

**CUDA Version**: 11.6

**CUDNN Version**: 8.4.0

Operating System:

Python Version (if applicable): 3.8

Tensorflow Version (if applicable):

PyTorch Version (if applicable): 1.13.1

Baremetal or Container (if so, version):

## Relevant Files

**Model link**:

## Steps To Reproduce

**Commands or scripts**:

**Have you tried [the latest release](https://developer.nvidia.com/tensorrt)?**:

**Can this model run on other frameworks?** For example run ONNX model with ONNXRuntime (`polygraphy run <model.onnx> --onnxrt`):

**Comment by theNefelibata** [comment]
I am running trt sd demo on 3090, got error:
```[I] Initializing StableDiffusion txt2img demo using TensorRT
Building TensorRT engine for onnx/unet.opt.onnx: engine/unet.plan
Segmentation fault (core dumped)```
and I followed the same steps to successfully run on A800GPU.

**Comment by zerollzeng** [comment]
Can you reproduce it with our official docker? I have a vague memory that I run the SD demo on 3090 before and it can pass.

**Comment by theNefelibata** [comment]
> Can you reproduce it with our official docker? I have a vague memory that I run the SD demo on 3090 before and it can pass.
I tried your official docker,  and reported other errors. My host's cuda driver is version 510. Does TRT have any requirements for cuda driver version?

**Comment by theNefelibata** [comment]
here is the crash code:
`python3 demo_txt2img.py "a beautiful woman with blue eyes" --hf-token=$HF_TOKEN -v
2023-08-10 03:04:08.690996: I tensorflow/core/util/[util.cc:169](http://util.cc:169/)] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
[I] Initializing StableDiffusion txt2img demo using TensorRT
==========================
sample :  [(2, 4, 64, 64), (2, 4, 64, 64), (32, 4, 64, 64)]
encoder_hidden_states :  [(2, 77, 1024), (2, 77, 1024), (32, 77, 1024)]
Building TensorRT engine for onnx/unet.opt.onnx: engine/unet.plan
[W] Unable to determine GPU memory usage
[W] CUDA initialization failure with error: 35. Please check your CUDA installation:  http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html
Traceback (most recent call last):
  File "demo_txt2img.py", line 80, in <module>
    demo.loadEngines(args.engine_dir, args.onnx_dir, args.onnx_opset,
  File "/workspace/TensorRT/demo/Diffusion/stable_diffusion_pipeline.py", line 300, in loadEngines
    engine.build(onnx_opt_path,
  File "/workspace/TensorRT/demo/Diffusion/utilities.py", line 213, in build
    network_from_onnx_path(onnx_path, flags=[trt.OnnxParserFlag.NATIVE_INSTANCENORM]),
  File "<string>", line 3, in network_from_onnx_path
  File "/usr/local/lib/python3.8/dist-packages/polygraphy/backend/base/loader.py", line 40, in __call__
    return self.call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/polygraphy/util/util.py", line 694, in wrapped
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/polygraphy/backend/trt/loader.py", line 207, in call_impl
    with util.FreeOnException(super().call_impl()) as (builder, network, parser):
  File "/usr/local/lib/python3.8/dist-packages/polygraphy/util/util.py", line 694, in wrapped
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/polygraphy/backend/trt/loader.py", line 127, in call_impl
    with util.FreeOnException(create_network(explicit_batch=self.explicit_batch)) as (builder, network):
  File "<string>", line 3, in create_network
  File "/usr/local/lib/python3.8/dist-packages/polygraphy/backend/base/loader.py", line 40, in __call__
    return self.call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/polygraphy/util/util.py", line 694, in wrapped
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/polygraphy/backend/trt/loader.py", line 100, in call_impl
    with util.FreeOnException([trt.Builder(trt_util.get_trt_logger())]) as (builder,):
TypeError: pybind11::init(): factory function returned nullptr`

**Comment by zerollzeng** [comment]
> ```python
> [W] CUDA initialization failure with error: 35. Please check your CUDA installation:  http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html
> ```

Cuda error 35 is "cudaErrorInsufficientDriver". Could you please try upgrade the driver to 525+?

**Comment by theNefelibata** [comment]
> ```python
> ```python
> [W] CUDA initialization failure with error: 35. Please check your CUDA installation:  http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> 
> Cuda error 35 is "cudaErrorInsufficientDriver". Could you please try upgrade the driver to 525+?
> ```

I am not very convenient to upgrade the driver now. Could you theoretically analyze why this is happening? I am not very clear about the impact of drivers on TRT. THX

**Comment by theNefelibata** [comment]
> ```python
> ```python
> ```python
> [W] CUDA initialization failure with error: 35. Please check your CUDA installation:  http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> Cuda error 35 is "cudaErrorInsufficientDriver". Could you please try upgrade the driver to 525+?
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> 
> I am not very convenient to upgrade the driver right now. Could you theoretically analyze why this is happening? I am not very clear about the impact of drivers on TRT. THX
> ```

**Comment by zerollzeng** [comment]
> Could you theoretically analyze why this is happening?

cuda version and driver version mismatch.



> can I use trtexec to transfer unet.opt.onnx to unet.plan?

yes.

**Comment by ttyio** [comment]
closing since no activity for more than 3 weeks, pls reopen if you still have question. thanks!
