### ISSUE TITLE
Error Code 4: failure of TensorRT 8.6 when running onnx_resnet50.py on GPU RTXA5000

### ISSUE THREAD

**Issue by minwim** [NVIDIA/TensorRT#3208]
when i run  onnx_resnet50.py i find below error:
resnet50.onnx  download at https://zenodo.org/record/2592612
img download at 
error lo
![image](https://github.com/NVIDIA/TensorRT/assets/86920530/ccb0af27-c4e6-4e1a-a82f-862061227b7f)
but i find error 
g:
**WARNING: /home/disk/wlm/datasets/resnet50 does not exist. Trying /home/disk/wlm/datasets/ instead.
[08/09/2023-17:01:52] [TRT] [W] CUDA lazy loading is not enabled. Enabling it can significantly reduce device memory usage and speed up TensorRT initialization. See "Lazy Loading" section of CUDA documentation https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#lazy-loading
onnx_resnet50.py:50: DeprecationWarning: Use set_memory_pool_limit instead.
  config.max_workspace_size = common.GiB(1)
[08/09/2023-17:01:52] [TRT] [W] onnx2trt_utils.cpp:374: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[08/09/2023-17:01:52] [TRT] [W] Tensor DataType is determined at build time for tensors not marked as input or output.
onnx_resnet50.py:58: DeprecationWarning: Use build_serialized_network instead.
  return builder.build_engine(network, config)
[08/09/2023-17:01:52] [TRT] [E] 4: [network.cpp::validate::3047] Error Code 4: Internal Error (Network has dynamic or shape inputs, but no optimization profile has been defined.)
Traceback (most recent call last):
  File "onnx_resnet50.py", line 122, in <module>
    main()
  File "onnx_resnet50.py", line 102, in main
    inputs, outputs, bindings, stream = common.allocate_buffers(engine)
  File "/home/disk/wlm/0809/TensorRT-release-8.6/samples/python/introductory_parser_samples/../common.py", line 188, in allocate_buffers
    tensor_names = [engine.get_tensor_name(i) for i in range(engine.num_io_tensors)]
AttributeError: 'NoneType' object has no attribute 'num_io_tensors'**

**Comment by zerollzeng** [comment]
> [network.cpp::validate::3047] Error Code 4: Internal Error (Network has dynamic or shape inputs, but no optimization profile has been defined.)

You need to specify the dynamic shape optimization profiles for this onnx, you can take a quick try with `trtexec --optShapes=`

**Comment by minwim** [comment]
thank@zerollzeng
