### ISSUE TITLE
tensorrt python sdk inference sometimes got stuck at initialization when using multiprocessing

### ISSUE THREAD

**Issue by handoku** [NVIDIA/TensorRT#3241]
## Description
When working with multiprocessing, sometimes all subprocesses can become stuck during runtime creation. What problems may cause this issue? Expecting for help..

Maybe useful to mention: I also enable nvidia MPS.
Here is the gdb log:
```bash
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04.1) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python...
Attaching to program: /opt/conda/bin/python, process 951
[New LWP 1096]
[New LWP 1097]
[New LWP 1098]
[New LWP 1099]
[New LWP 1100]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/x86_64-linux-gnu/libthread_db.so.1".
__libc_read (nbytes=80, buf=0x7ffe50c52070, fd=13) at ../sysdeps/unix/sysv/linux/read.c:26
26	../sysdeps/unix/sysv/linux/read.c: No such file or directory.
(gdb) bt
#0  __libc_read (nbytes=80, buf=0x7ffe50c52070, fd=13) at ../sysdeps/unix/sysv/linux/read.c:26
#1  __libc_read (fd=13, buf=0x7ffe50c52070, nbytes=80) at ../sysdeps/unix/sysv/linux/read.c:24
#2  0x00007fbeddefdc6c in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#3  0x00007fbeddfdefd8 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#4  0x00007fbeddfec9bf in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#5  0x00007fbeddeeeca0 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#6  0x00007fbe6d82ce0b in ?? () from /usr/lib/x86_64-linux-gnu/libnvinfer.so.8
#7  0x00007fbe6d82cf08 in ?? () from /usr/lib/x86_64-linux-gnu/libnvinfer.so.8
#8  0x00007fbf650524df in __pthread_once_slow (once_control=0x7fbe796e8508, init_routine=0x7fbe6d82cec0) at pthread_once.c:116
#9  0x00007fbe6d87c8d9 in ?? () from /usr/lib/x86_64-linux-gnu/libnvinfer.so.8
#10 0x00007fbe6d823837 in ?? () from /usr/lib/x86_64-linux-gnu/libnvinfer.so.8
#11 0x00007fbe6d855801 in ?? () from /usr/lib/x86_64-linux-gnu/libnvinfer.so.8
#12 0x00007fbe6c7e5fde in ?? () from /usr/lib/x86_64-linux-gnu/libnvinfer.so.8
#13 0x00007fbe6c7e6203 in ?? () from /usr/lib/x86_64-linux-gnu/libnvinfer.so.8
#14 0x00007fbe6c7e63fb in createInferRuntime_INTERNAL () from /usr/lib/x86_64-linux-gnu/libnvinfer.so.8
#15 0x00007fbe79bc5828 in pybind11::cpp_function::initialize<pybind11::detail::initimpl::factory<nvinfer1::IRuntime* (*)(nvinfer1::ILogger&), pybind11::detail::void_type (*)(), nvinfer1::IRuntime* (nvinfer1::ILogger&), pybind11::detail::void_type ()>::execute<pybind11::class_<nvinfer1::IRuntime>, pybind11::arg, char const*, pybind11::keep_alive<1ul, 2ul> >(pybind11::class_<nvinfer1::IRuntime>&, pybind11::arg const&, char const* const&, pybind11::keep_alive<1ul, 2ul> const&) &&::{lambda(pybind11::detail::value_and_holder&, nvinfer1::ILogger&)#1}, void, pybind11::detail::value_and_holder&, nvinfer1::ILogger&, pybind11::name, pybind11::is_method, pybind11::sibling, pybind11::detail::is_new_style_constructor, pybind11::arg, char const*, pybind11::keep_alive<1ul, 2ul> >(pybind11::class_<nvinfer1::IRuntime>&&, void (*)(pybind11::detail::value_and_holder&, nvinfer1::ILogger&), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&, pybind11::detail::is_new_style_constructor const&, pybind11::arg const&, char const* const&, pybind11::keep_alive<1ul, 2ul> const&)::{lambda(pybind11::detail::function_call&)#3}::_FUN(pybind11::detail::function_call) () from /opt/conda/lib/python3.8/site-packages/tensorrt/tensorrt.so
#16 0x00007fbe79b8a033 in pybind11::cpp_function::dispatcher(_object*, _object*, _object*) () from /opt/conda/lib/python3.8/site-packages/tensorrt/tensorrt.so
#17 0x0000559d87537e7e in cfunction_call_varargs (kwargs=0x0, args=0x7fbe651f2080, func=0x7fbe6858e5e0) at /usr/local/src/conda/python-3.8.13/Objects/call.c:743
#18 PyCFunction_Call (func=0x7fbe6858e5e0, args=0x7fbe651f2080, kwargs=0x0) at /usr/local/src/conda/python-3.8.13/Objects/call.c:773
#19 0x0000559d87520631 in _PyObject_MakeTpCall (callable=0x7fbe6858e5e0, args=<optimized out>, nargs=<optimized out>, keywords=<optimized out>)
    at /usr/local/src/conda/python-3.8.13/Python/errors.c:219
#20 0x0000559d87537ca7 in _PyObject_Vectorcall (kwnames=<optimized out>, nargsf=<optimized out>, args=0x7ffe50c53310, callable=0x7fbe6858e5e0)
    at /usr/local/src/conda/python-3.8.13/Include/cpython/abstract.h:125
#21 _PyObject_Vectorcall (kwnames=<optimized out>, nargsf=<optimized out>, args=<optimized out>, callable=0x7fbe6858e5e0)
    at /usr/local/src/conda/python-3.8.13/Include/cpython/abstract.h:115
#22 method_vectorcall (method=<optimized out>, args=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>) at /usr/local/src/conda/python-3.8.13/Objects/classobject.c:89
#23 0x0000559d8753a172 in PyVectorcall_Call (kwargs=0x0, tuple=<optimized out>, callable=0x7fbf328c62c0) at /usr/local/src/conda/python-3.8.13/Python/errors.c:219
#24 PyObject_Call (callable=0x7fbf328c62c0, args=<optimized out>, kwargs=0x0) at /usr/local/src/conda/python-3.8.13/Objects/call.c:228
#25 0x0000559d87533870 in slot_tp_init (self=<optimized out>, args=0x7fbf64893ee0, kwds=0x0) at /usr/local/src/conda/python-3.8.13/Objects/typeobject.c:6793
#26 0x0000559d87520968 in type_call (type=<optimized out>, args=0x7fbf64893ee0, kwds=0x0) at /usr/local/src/conda/python-3.8.13/Objects/typeobject.c:3727
#27 0x00007fbf604a9ac2 in pybind11_meta_call () from /opt/conda/lib/python3.8/site-packages/pyorc/_pyorc.cpython-38-x86_64-linux-gnu.so
#28 0x0000559d87520631 in _PyObject_MakeTpCall (callable=0x559d8d2ed5a0, args=<optimized out>, nargs=<optimized out>, keywords=<optimized out>)
    at /usr/local/src/conda/python-3.8.13/Python/errors.c:219
#29 0x0000559d8751c481 in _PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x7fbe652971d0, callable=0x559d8d2ed5a0)
    at /usr/local/src/conda/python-3.8.13/Include/cpython/abstract.h:125
#30 _PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x7fbe652971d0, callable=0x559d8d2ed5a0) at /usr/local/src/conda/python-3.8.13/Include/cpython/abstract.h:115
#31 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0x559d885aa950) at /usr/local/src/conda/python-3.8.13/Python/ceval.c:4963
```

## Environment
I am using ngc docker images pytorch-23.07-py3 with latest version tensorrt installed.

**TensorRT Version**: tensorrt 8.6.1.6

**NVIDIA GPU**: V100

**NVIDIA Driver Version**: 470.161.03

**CUDA Version**: cuda 11.8

**CUDNN Version**:  8.6.0

Operating System:

Python Version (if applicable):  3.8

PyTorch Version (if applicable): 1.13

**Comment by zerollzeng** [comment]
Well I can give specific suggestion in this case, but the first thing I would do is to check whether there are resource conflict etc, and monitor the CPU/GPU loading and Memory utilization.

**Comment by ttyio** [comment]
Closing since no activity for more than 3 weeks, pls reopen if you still have question, thanks!

**Comment by lix19937** [comment]
> #14 0x00007fbe6c7e63fb in createInferRuntime_INTERNAL () from /usr/lib/x86_64-linux-gnu/libnvinfer.so.8   

I also come across this, in DRIVE ORIN-X  

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  tcache_get (tc_idx=<optimized out>) at malloc.c:2937
2937    malloc.c: No such file or directory.
[Current thread is 1 (Thread 0x7fbb24c16000 (LWP 1761))]
(gdb) where
#0  tcache_get (tc_idx=<optimized out>) at malloc.c:2937
#1  __GI___libc_malloc (bytes=48) at malloc.c:3051
#2  0x00007fbb22dc7b30 in ?? () from /usr/lib/wsl/drivers/nvlt.inf_amd64_824503e093f1e574/libcuda.so.1.1
#3  0x00007fbb22ed67f0 in ?? () from /usr/lib/wsl/drivers/nvlt.inf_amd64_824503e093f1e574/libcuda.so.1.1
#4  0x00007fbb22ec6698 in ?? () from /usr/lib/wsl/drivers/nvlt.inf_amd64_824503e093f1e574/libcuda.so.1.1
#5  0x00007fbb22ec71a0 in ?? () from /usr/lib/wsl/drivers/nvlt.inf_amd64_824503e093f1e574/libcuda.so.1.1
#6  0x00007fbb22ea3563 in ?? () from /usr/lib/wsl/drivers/nvlt.inf_amd64_824503e093f1e574/libcuda.so.1.1
#7  0x00007fbb22ea3a53 in ?? () from /usr/lib/wsl/drivers/nvlt.inf_amd64_824503e093f1e574/libcuda.so.1.1
#8  0x00007fbb2911eab4 in ?? () from /usr/local/tensorrt/lib/x86_64-linux-gnu/libnvinfer.so.8
#9  0x00007fbb2910e60e in ?? () from /usr/local/tensorrt/lib/x86_64-linux-gnu/libnvinfer.so.8
#10 0x00007fbb29125244 in ?? () from /usr/local/tensorrt/lib/x86_64-linux-gnu/libnvinfer.so.8
#11 0x00007fbb2912996a in ?? () from /usr/local/tensorrt/lib/x86_64-linux-gnu/libnvinfer.so.8
#12 0x00007fbb29129be4 in ?? () from /usr/local/tensorrt/lib/x86_64-linux-gnu/libnvinfer.so.8
#13 0x00007fbb2911c05f in ?? () from /usr/local/tensorrt/lib/x86_64-linux-gnu/libnvinfer.so.8
#14 0x00007fbb2910025e in ?? () from /usr/local/tensorrt/lib/x86_64-linux-gnu/libnvinfer.so.8
#15 0x00007fbb2913b6b0 in ?? () from /usr/local/tensorrt/lib/x86_64-linux-gnu/libnvinfer.so.8
#16 0x00007fbb26534652 in ?? () from /usr/local/tensorrt/lib/x86_64-linux-gnu/libnvinfer.so.8
#17 0x00007fbb2653486d in createInferRuntime_INTERNAL () from /usr/local/tensorrt/lib/x86_64-linux-gnu/libnvinfer.so.8
#18 0x00007fbb3f484c75 in nvinfer1::(anonymous namespace)::createInferRuntime (logger=...)
    at /usr/local/tensorrt/include/x86_64-linux-gnu/NvInferRuntime.h:3440
#19 0x00007fbb3f4850cc in nni::Infer::LoadEngine (this=0x556d3a8f6020,
    engine="../src/test/instances/BV_PSD_P01_V03_20240805_TEST/engine/BV_PSD_P01_V03_20240805_TEST_x86_fp16.plan")
    at /mnt/d/workspace/gitlab/nni/src/core/infer.cpp:70
```
