### ISSUE TITLE
Converting CNN frozen graph(.pb) to UFF and ONNX file format

### ISSUE THREAD

**Issue by lyanshin** [NVIDIA/TensorRT#332]
## Description

Hello,

I would like to use pre-trained U-net inspired network which uses 3D convolutional and deconvolutional layers and I want it to employ TensorRT C-API.

I found TensorRT supports these 3D layers.  
https://docs.nvidia.com/deeplearning/sdk/tensorrt-release-notes/tensorrt-6.html#rel_6-0-1

I could make frozen graph(.pb) file and I want to convert it into UFF file format in order to read from TensorRT C-API.
But I couldn't convert it to UFF file format and even ONNX format.

My first step was a training network.
I trained my network using Keras as follows.

    img_shape = (None, None, None, 1)  
    inputs = Input(shape = img_shape)
    conv1 = layers.Conv3D(32, 3, padding='same')(inputs)
    conv1 = layers.BatchNormalization()(conv1)
    conv1 = Activation('relu')(conv1)
    conv1 = layers.Conv3D(32, 3, padding='same')(conv1)
    conv1 = layers.BatchNormalization()(conv1)
    conv1 = Activation('relu')(conv1)
    pool1 = layers.MaxPooling3D(pool_size=(2, 2, 2))(conv1)
    
    conv2 = layers.Conv3D(64, 3, padding='same')(pool1)
    conv2 = layers.BatchNormalization()(conv2)
    conv2 = Activation('relu')(conv2)
    conv2 = layers.Conv3D(64, 3, padding='same')(conv2)
    conv2 = layers.BatchNormalization()(conv2)
    conv2 = Activation('relu')(conv2)
    pool2 = layers.MaxPooling3D(pool_size=(2, 2, 2))(conv2)

    conv3 = layers.Conv3D(128, 3, padding='same')(pool2)
    conv3 = layers.BatchNormalization()(conv3)
    conv3 = Activation('relu')(conv3)
    conv3 = layers.Conv3D(128, 3, padding='same')(conv3)
    conv3 = layers.BatchNormalization()(conv3)
    conv3 = Activation('relu')(conv3)
    conv3 = layers.UpSampling3D(size=(2, 2, 2))(conv3)

    up4  = layers.concatenate([conv3, conv2])
    conv4 = layers.Conv3DTranspose(64, 3, padding='same')(up4)
    conv4 = layers.BatchNormalization()(conv4)
    conv4 = Activation('relu')(conv4)
    conv4 = layers.Conv3DTranspose(64, 3, padding='same')(conv4)
    conv4 = layers.BatchNormalization()(conv4)
    conv4 = Activation('relu')(conv4)
    conv4 = layers.Conv3DTranspose(64, 1, padding='same')(conv4)
    conv4 = layers.UpSampling3D(size=(2, 2, 2))(conv4)

    up5  = layers.concatenate([conv4, conv1])
    conv5 = layers.Conv3DTranspose(32, 3, padding='same')(up5)
    conv5 = layers.BatchNormalization()(conv5)
    conv5 = Activation('relu')(conv5)
    conv5 = layers.Conv3DTranspose(32, 3, padding='same')(conv5)
    conv5 = layers.BatchNormalization()(conv5)
    conv5 = Activation('relu')(conv5)
    conv5 = layers.Conv3DTranspose(1, 1, padding='same', activation='relu')(conv5)

    model = Model(inputs=inputs, outputs=conv5)

Then, I tried to convert this .pb file into UFF format using "convert-to-uff" executable and output was as following,

```
Loading ./model/Trained_CNN.pb
NOTE: UFF has been tested with TensorFlow 1.14.0.
WARNING: The version of TensorFlow installed on this system is not guaranteed to work with UFF.
UFF Version 0.6.5
=== Automatically deduced input nodes ===
[name: "input_1"
op: "Placeholder"
attr {
  key: "dtype"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "shape"
  value {
    shape {
      dim {
        size: -1
      }
      dim {
        size: -1
      }
      dim {
        size: -1
      }
      dim {
        size: -1
      }
      dim {
        size: 1
      }
    }
  }
}
]
=========================================

=== Automatically deduced output nodes ===
[name: "conv3d_transpose_6/Relu"
op: "Relu"
input: "conv3d_transpose_6/add"
attr {
  key: "T"
  value {
    type: DT_FLOAT
  }
}
]
==========================================

Using output node conv3d_transpose_6/Relu
Converting to UFF graph
Warning: No conversion function registered for layer: Conv3DBackpropInputV2 yet.
Converting conv3d_transpose_6/conv3d_transpose as custom op: Conv3DBackpropInputV2
Warning: No conversion function registered for layer: Conv3DBackpropInputV2 yet.
Converting conv3d_transpose_5/conv3d_transpose as custom op: Conv3DBackpropInputV2
Warning: No conversion function registered for layer: Conv3DBackpropInputV2 yet.
Converting conv3d_transpose_4/conv3d_transpose as custom op: Conv3DBackpropInputV2
Warning: No conversion function registered for layer: Conv3D yet.
Converting conv3d_2/convolution as custom op: Conv3D
Warning: No conversion function registered for layer: Conv3D yet.
Converting conv3d_1/convolution as custom op: Conv3D
Warning: No conversion function registered for layer: Conv3DBackpropInputV2 yet.
Converting conv3d_transpose_3/conv3d_transpose as custom op: Conv3DBackpropInputV2
Warning: No conversion function registered for layer: Conv3DBackpropInputV2 yet.
Converting conv3d_transpose_2/conv3d_transpose as custom op: Conv3DBackpropInputV2
Warning: No conversion function registered for layer: Conv3DBackpropInputV2 yet.
Converting conv3d_transpose_1/conv3d_transpose as custom op: Conv3DBackpropInputV2
Warning: No conversion function registered for layer: Conv3D yet.
Converting conv3d_4/convolution as custom op: Conv3D
Warning: No conversion function registered for layer: Conv3D yet.
Converting conv3d_3/convolution as custom op: Conv3D
Warning: No conversion function registered for layer: MaxPool3D yet.
Converting max_pooling3d_1/MaxPool3D as custom op: MaxPool3D
Warning: No conversion function registered for layer: Conv3D yet.
Converting conv3d_6/convolution as custom op: Conv3D
Warning: No conversion function registered for layer: Conv3D yet.
Converting conv3d_5/convolution as custom op: Conv3D
Warning: No conversion function registered for layer: MaxPool3D yet.
Converting max_pooling3d_2/MaxPool3D as custom op: MaxPool3D
Warning: No conversion function registered for layer: Tile yet.
Converting up_sampling3d_1/Tile as custom op: Tile
Warning: No conversion function registered for layer: Tile yet.
Converting up_sampling3d_1/Tile_1 as custom op: Tile
Warning: No conversion function registered for layer: Tile yet.
Converting up_sampling3d_1/Tile_2 as custom op: Tile
Warning: No conversion function registered for layer: Tile yet.
Converting up_sampling3d_2/Tile as custom op: Tile
Warning: No conversion function registered for layer: Tile yet.
Converting up_sampling3d_2/Tile_1 as custom op: Tile
Warning: No conversion function registered for layer: Tile yet.
Converting up_sampling3d_2/Tile_2 as custom op: Tile
DEBUG [/home/junsu/.local/lib/python3.6/site-packages/uff/converters/tensorflow/converter.py:96] Marking ['conv3d_transpose_6/Relu'] as outputs
No. nodes: 401
UFF Output written to ./model/Trained_CNN.uff
```

It indicated that there were no conversion functions of Conv3D, MaxPool3D, Conv3DBackpropInpuitV2, and Tile(up_sampling3D).

I have found there was a similar issue and found this solution.
https://github.com/NVIDIA/TensorRT/issues/153#issuecomment-547202413

So, I tried to convert it into ONNX file format using  this command
```
python -m tf2onnx.convert --fold_const --input ./model/Trained_CNN.pb --inputs input_1:0[None,None,None,1,1] --outputs conv3d_transpose_6/Relu:0 --output ./model/Trained_CNN.onnx
```

And output was as following.
```
2020-01-13 14:50:25,881 - WARNING - inputs [1,None] is not in frozen graph, delete them
2020-01-13 14:50:25,975 - INFO - Using tensorflow=1.13.1, onnx=1.6.0, tf2onnx=1.5.4/ee756a
2020-01-13 14:50:25,975 - INFO - Using opset <onnx, 8>
2020-01-13 14:50:26,178 - ERROR - Failed to convert node conv3d_1/convolution
OP=Conv
Name=conv3d_1/convolution
Inputs:
	input_1:0=Placeholder, [-1, -1, -1, -1, 1], 1
	conv3d_1/kernel:0=Const, [3, 3, 3, 1, 32], 1
Outpus:
	conv3d_1/convolution:0=[-1, -1, -1, -1, 32], 1
Traceback (most recent call last):
  File "/home/junsu/anaconda3/envs/tf-onnx/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 354, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/home/junsu/anaconda3/envs/tf-onnx/lib/python3.6/site-packages/tf2onnx/onnx_opset/nn.py", line 204, in version_1
    kernel_shape = conv_kernel_shape(ctx, node, 1, spatial=2)
  File "/home/junsu/anaconda3/envs/tf-onnx/lib/python3.6/site-packages/tf2onnx/onnx_opset/nn.py", line 189, in conv_kernel_shape
    raise ValueError("kernel rank must be 2* spatial")
ValueError: kernel rank must be 2* spatial
2020-01-13 14:50:26,179 - ERROR - Failed to convert node conv3d_2/convolution
OP=Conv
Name=conv3d_2/convolution
Inputs:
	activation_1/Relu:0=Relu, [-1, -1, -1, -1, 32], 1
	conv3d_2/kernel:0=Const, [3, 3, 3, 32, 32], 1
Outpus:
	conv3d_2/convolution:0=[-1, -1, -1, -1, 32], 1
Traceback (most recent call last):
  File "/home/junsu/anaconda3/envs/tf-onnx/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 354, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/home/junsu/anaconda3/envs/tf-onnx/lib/python3.6/site-packages/tf2onnx/onnx_opset/nn.py", line 204, in version_1
    kernel_shape = conv_kernel_shape(ctx, node, 1, spatial=2)
  File "/home/junsu/anaconda3/envs/tf-onnx/lib/python3.6/site-packages/tf2onnx/onnx_opset/nn.py", line 189, in conv_kernel_shape
    raise ValueError("kernel rank must be 2* spatial")
ValueError: kernel rank must be 2* spatial
2020-01-13 14:50:26,179 - ERROR - Tensorflow op [max_pooling3d_1/MaxPool3D: MaxPool3D] is not supported
2020-01-13 14:50:26,179 - ERROR - Failed to convert node conv3d_3/convolution
OP=Conv
Name=conv3d_3/convolution
Inputs:
	max_pooling3d_1/MaxPool3D:0=MaxPool3D, [-1, -1, -1, -1, 32], 1
	conv3d_3/kernel:0=Const, [3, 3, 3, 32, 64], 1
Outpus:
	conv3d_3/convolution:0=[-1, -1, -1, -1, 64], 1
Traceback (most recent call last):
  File "/home/junsu/anaconda3/envs/tf-onnx/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 354, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/home/junsu/anaconda3/envs/tf-onnx/lib/python3.6/site-packages/tf2onnx/onnx_opset/nn.py", line 204, in version_1
    kernel_shape = conv_kernel_shape(ctx, node, 1, spatial=2)
  File "/home/junsu/anaconda3/envs/tf-onnx/lib/python3.6/site-packages/tf2onnx/onnx_opset/nn.py", line 189, in conv_kernel_shape
    raise ValueError("kernel rank must be 2* spatial")
ValueError: kernel rank must be 2* spatial
2020-01-13 14:50:26,179 - ERROR - Failed to convert node conv3d_4/convolution
OP=Conv
Name=conv3d_4/convolution
Inputs:
	activation_3/Relu:0=Relu, [-1, -1, -1, -1, 64], 1
	conv3d_4/kernel:0=Const, [3, 3, 3, 64, 64], 1
Outpus:
	conv3d_4/convolution:0=[-1, -1, -1, -1, 64], 1
Traceback (most recent call last):
  File "/home/junsu/anaconda3/envs/tf-onnx/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 354, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/home/junsu/anaconda3/envs/tf-onnx/lib/python3.6/site-packages/tf2onnx/onnx_opset/nn.py", line 204, in version_1
    kernel_shape = conv_kernel_shape(ctx, node, 1, spatial=2)
  File "/home/junsu/anaconda3/envs/tf-onnx/lib/python3.6/site-packages/tf2onnx/onnx_opset/nn.py", line 189, in conv_kernel_shape
    raise ValueError("kernel rank must be 2* spatial")
ValueError: kernel rank must be 2* spatial
2020-01-13 14:50:26,179 - ERROR - Tensorflow op [max_pooling3d_2/MaxPool3D: MaxPool3D] is not supported
2020-01-13 14:50:26,179 - ERROR - Failed to convert node conv3d_5/convolution
OP=Conv
Name=conv3d_5/convolution
Inputs:
	max_pooling3d_2/MaxPool3D:0=MaxPool3D, [-1, -1, -1, -1, 64], 1
	conv3d_5/kernel:0=Const, [3, 3, 3, 64, 128], 1
Outpus:
	conv3d_5/convolution:0=[-1, -1, -1, -1, 128], 1
Traceback (most recent call last):
  File "/home/junsu/anaconda3/envs/tf-onnx/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 354, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/home/junsu/anaconda3/envs/tf-onnx/lib/python3.6/site-packages/tf2onnx/onnx_opset/nn.py", line 204, in version_1
    kernel_shape = conv_kernel_shape(ctx, node, 1, spatial=2)
  File "/home/junsu/anaconda3/envs/tf-onnx/lib/python3.6/site-packages/tf2onnx/onnx_opset/nn.py", line 189, in conv_kernel_shape
    raise ValueError("kernel rank must be 2* spatial")
ValueError: kernel rank must be 2* spatial
2020-01-13 14:50:26,179 - ERROR - Failed to convert node conv3d_6/convolution
OP=Conv
Name=conv3d_6/convolution
Inputs:
	activation_5/Relu:0=Relu, [-1, -1, -1, -1, 128], 1
	conv3d_6/kernel:0=Const, [3, 3, 3, 128, 128], 1
Outpus:
	conv3d_6/convolution:0=[-1, -1, -1, -1, 128], 1
Traceback (most recent call last):
  File "/home/junsu/anaconda3/envs/tf-onnx/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 354, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/home/junsu/anaconda3/envs/tf-onnx/lib/python3.6/site-packages/tf2onnx/onnx_opset/nn.py", line 204, in version_1
    kernel_shape = conv_kernel_shape(ctx, node, 1, spatial=2)
  File "/home/junsu/anaconda3/envs/tf-onnx/lib/python3.6/site-packages/tf2onnx/onnx_opset/nn.py", line 189, in conv_kernel_shape
    raise ValueError("kernel rank must be 2* spatial")
ValueError: kernel rank must be 2* spatial
2020-01-13 14:50:26,192 - ERROR - Tensorflow op [conv3d_transpose_1/conv3d_transpose: Conv3DBackpropInputV2] is not supported
2020-01-13 14:50:26,201 - ERROR - Tensorflow op [conv3d_transpose_2/conv3d_transpose: Conv3DBackpropInputV2] is not supported
2020-01-13 14:50:26,210 - ERROR - Tensorflow op [conv3d_transpose_3/conv3d_transpose: Conv3DBackpropInputV2] is not supported
2020-01-13 14:50:26,223 - ERROR - Tensorflow op [conv3d_transpose_4/conv3d_transpose: Conv3DBackpropInputV2] is not supported
2020-01-13 14:50:26,233 - ERROR - Tensorflow op [conv3d_transpose_5/conv3d_transpose: Conv3DBackpropInputV2] is not supported
2020-01-13 14:50:26,244 - ERROR - Tensorflow op [conv3d_transpose_6/conv3d_transpose: Conv3DBackpropInputV2] is not supported
2020-01-13 14:50:26,244 - ERROR - Unsupported ops: Counter({'Conv3DBackpropInputV2': 6, 'MaxPool3D': 2})
Traceback (most recent call last):
  File "/home/junsu/anaconda3/envs/tf-onnx/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/junsu/anaconda3/envs/tf-onnx/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/junsu/anaconda3/envs/tf-onnx/lib/python3.6/site-packages/tf2onnx/convert.py", line 161, in <module>
    main()
  File "/home/junsu/anaconda3/envs/tf-onnx/lib/python3.6/site-packages/tf2onnx/convert.py", line 145, in main
    inputs_as_nchw=args.inputs_as_nchw)
  File "/home/junsu/anaconda3/envs/tf-onnx/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 577, in process_tf_graph
    raise exceptions[0]
  File "/home/junsu/anaconda3/envs/tf-onnx/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 354, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/home/junsu/anaconda3/envs/tf-onnx/lib/python3.6/site-packages/tf2onnx/onnx_opset/nn.py", line 204, in version_1
    kernel_shape = conv_kernel_shape(ctx, node, 1, spatial=2)
  File "/home/junsu/anaconda3/envs/tf-onnx/lib/python3.6/site-packages/tf2onnx/onnx_opset/nn.py", line 189, in conv_kernel_shape
    raise ValueError("kernel rank must be 2* spatial")
ValueError: kernel rank must be 2* spatial
```

It also indicated it doesn't support MaxPooling3D, Conv3DBackPropInputV2 layers.

Does anyone have a solution to this?

## Environment

**TensorRT Version**: 6.0.1.5
**GPU Type**:  Titan V
**Nvidia Driver Version**: 430.50
**CUDA Version**: 10.1
**CUDNN Version**: 10.0
**Operating System + Version**: Ubuntu 18.04.3 LTS
**Python Version (if applicable)**: 3.6.9
**TensorFlow Version (if applicable)**: 1.13.1
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if container which image + tag)**:

**Comment by rmccorm4** [comment]
Hi @lyanshin,

Can you share your `.pb` model so I can reproduce?

**Comment by rmccorm4** [comment]
Closing since no response. You can share this issue in https://github.com/onnx/tensorflow-onnx to request support for these ops.
