### ISSUE TITLE
IAssertionLayer layer build engine failed

### ISSUE THREAD

**Issue by sky-fun** [NVIDIA/TensorRT#3334]
## Description
I want to build an engine with IAssertionLayer layer to check whether two tensor is equally during runtime;
But it failed and shows
 ``` shell
[graphShapeAnalyzer.cpp::getSymbolicValue::899] Error Code 2: Internal Error (Assertion isDefined(it->second) failed. value should have been set by symbolic execution of producer.)
```

## Environment

**TensorRT Version**: 9.0.1.post12.dev4

**NVIDIA GPU**:NVIDIA A10

**NVIDIA Driver Version**:515.48.07

**CUDA Version**:V12.1.66

Python Version :python3.8.10

## Steps To Reproduce

**Commands or scripts**:
use runtime_assertion.py
```python
import tensorrt as trt
import numpy as np

def runtime_assertion_network(network):
    in1 = network.add_input("input1", dtype=trt.float32, shape=(1, 3, 4, 4))
    w_1 = np.random.rand(3, 4, 1, 1)
    conv_1 = network.add_convolution_nd(
        input=in1,
        num_output_maps=4,
        kernel_shape=(1, 1),
        kernel=trt.Weights(w_1.astype(np.float32)),
    )

    in2 = network.add_input("input2", dtype=trt.float32, shape=(1, 4, 4, 4))
    w_2 = np.random.rand(4, 4, 1, 1)
    conv_2 = network.add_convolution_nd(
        input=in2,
        num_output_maps=4,
        kernel_shape=(1, 1),
        kernel=trt.Weights(w_2.astype(np.float32)),
    )

    runtime_cond = network.add_elementwise(conv_1.get_output(0), conv_2.get_output(0), op=trt.ElementWiseOperation.EQUAL)
    reshape_layer = network.add_shuffle(runtime_cond.get_output(0))
    reshape_layer.reshape_dims = trt.Dims([-1])
    runtime_assertion = network.add_assertion(reshape_layer.get_output(0), message="Tensors not equal")

    output = network.add_identity(conv_1.get_output(0))
    network.mark_output(output.get_output(0))

def main():
    TRT_LOGGER = trt.Logger(trt.Logger.VERBOSE)
    builder = trt.Builder(TRT_LOGGER)
    explicit_batch_flag = 1 << int(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)
    network = builder.create_network(explicit_batch_flag)
    builder_config = builder.create_builder_config()
    builder_config.set_flag(trt.BuilderFlag.FP16)
    builder_config.profiling_verbosity = trt.ProfilingVerbosity.DETAILED

    runtime_assertion_network(network)
    engine_path = "runtime_assertion.engine"

    engine = builder.build_serialized_network(network, builder_config)
    with open(engine_path, "wb") as f:
        f.write(engine)

if __name__ == "__main__":
    main()
```

run `python3 runtime_assertion.py` and it failed
```shell
[TRT] [E] 2: [graphShapeAnalyzer.cpp::getSymbolicValue::899] Error Code 2: Internal Error (Assertion isDefined(it->second) failed. value should have been set by symbolic execution of producer.) 
Traceback (most recent call last): 
   File "runtime_assertion.py", line 50, in <module>       
   File "runtime_assertion.py", line 47, in main
TypeError: a bytes-like object is required, not 'NoneType'
```

**Comment by zerollzeng** [comment]
@pranavm-nvidia @nvpohanh I can reproduce the error and I didn't see any obvious error in user's code, do you have any suggestions?

**Comment by sky-fun** [comment]
@nvpohanh how to create a shape tensor manually? I can only find some descriptions of shape tensor in  https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#exe_shape_tensors ;

**Comment by nvpohanh** [comment]
You can use IShapeLayer to get a shape of a tensor. The output of IShapeLayer is a "shape tensor". Then, you can use the ElementWise layer to do some calculations on the shape tensors and use IAssertionLayer to assert that two shape tensors must be equal at runtime.

Here are some docs: https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#dimension-constraint-assertion

**Comment by sky-fun** [comment]
@nvpohanh Thanks
