### ISSUE TITLE
Failing to convert int8 onnx model to trt engine

### ISSUE THREAD

**Issue by ChickenTarm** [NVIDIA/TensorRT#3360]
## Description
I produced a quantized int8 onnx model, however when I attempt to convert it to trt it fails at the first Q/DQ convolution layer where it attempts to DequantizeLinear the weights and bias. I did see a recommendation [here](https://forums.developer.nvidia.com/t/trtexec-error-only-activation-types-allowed-as-input-to-this-layer/254274) to use onnx-graphsurgeon to fix it, but it doesn't specify what would need to be changed to get it to work.

Also I attempted to convert an int8 onnx model that was created using QOperator however there is an error in attempting to import QlinearConv. Are there any plans to support that operator?

```
/usr/src/tensorrt/bin/trtexec --workspace=4096 --int8 --onnx=/home/experimentation-pipeline/onnx_models/person_coarse_ground_vehicle__5672256760429727__minmax-per_channel-sym_act+sym_weight.qdq.onnx --minShapes=input:1x3x320x320 --optShapes=input:5x3x1024x1024 --maxShapes=input:10x3x1536x1536 --saveEngine=int8.trt
[09/28/2023-23:14:28] [W] --workspace flag has been deprecated by --memPoolSize flag.
[09/28/2023-23:14:28] [I] === Model Options ===
[09/28/2023-23:14:28] [I] Format: ONNX
[09/28/2023-23:14:28] [I] Model: /home/experimentation-pipeline/onnx_models/person_coarse_ground_vehicle__5672256760429727__minmax-per_channel-sym_act+sym_weight.qdq.onnx
[09/28/2023-23:14:28] [I] Output:
[09/28/2023-23:14:28] [I] === Build Options ===
[09/28/2023-23:14:28] [I] Max batch: explicit batch
[09/28/2023-23:14:28] [I] Memory Pools: workspace: 4096 MiB, dlaSRAM: default, dlaLocalDRAM: default, dlaGlobalDRAM: default
[09/28/2023-23:14:28] [I] minTiming: 1
[09/28/2023-23:14:28] [I] avgTiming: 8
[09/28/2023-23:14:28] [I] Precision: FP32+INT8
[09/28/2023-23:14:28] [I] LayerPrecisions: 
[09/28/2023-23:14:28] [I] Layer Device Types: 
[09/28/2023-23:14:28] [I] Calibration: Dynamic
[09/28/2023-23:14:28] [I] Refit: Disabled
[09/28/2023-23:14:28] [I] Version Compatible: Disabled
[09/28/2023-23:14:28] [I] TensorRT runtime: full
[09/28/2023-23:14:28] [I] Lean DLL Path: 
[09/28/2023-23:14:28] [I] Tempfile Controls: { in_memory: allow, temporary: allow }
[09/28/2023-23:14:28] [I] Exclude Lean Runtime: Disabled
[09/28/2023-23:14:28] [I] Sparsity: Disabled
[09/28/2023-23:14:28] [I] Safe mode: Disabled
[09/28/2023-23:14:28] [I] Build DLA standalone loadable: Disabled
[09/28/2023-23:14:28] [I] Allow GPU fallback for DLA: Disabled
[09/28/2023-23:14:28] [I] DirectIO mode: Disabled
[09/28/2023-23:14:28] [I] Restricted mode: Disabled
[09/28/2023-23:14:28] [I] Skip inference: Disabled
[09/28/2023-23:14:28] [I] Save engine: int8.trt
[09/28/2023-23:14:28] [I] Load engine: 
[09/28/2023-23:14:28] [I] Profiling verbosity: 0
[09/28/2023-23:14:28] [I] Tactic sources: Using default tactic sources
[09/28/2023-23:14:28] [I] timingCacheMode: local
[09/28/2023-23:14:28] [I] timingCacheFile: 
[09/28/2023-23:14:28] [I] Heuristic: Disabled
[09/28/2023-23:14:28] [I] Preview Features: Use default preview flags.
[09/28/2023-23:14:28] [I] MaxAuxStreams: -1
[09/28/2023-23:14:28] [I] BuilderOptimizationLevel: -1
[09/28/2023-23:14:28] [I] Input(s)s format: fp32:CHW
[09/28/2023-23:14:28] [I] Output(s)s format: fp32:CHW
[09/28/2023-23:14:28] [I] Input build shape: input=1x3x320x320+5x3x1024x1024+10x3x1536x1536
[09/28/2023-23:14:28] [I] Input calibration shapes: model
[09/28/2023-23:14:28] [I] === System Options ===
[09/28/2023-23:14:28] [I] Device: 0
[09/28/2023-23:14:28] [I] DLACore: 
[09/28/2023-23:14:28] [I] Plugins:
[09/28/2023-23:14:28] [I] setPluginsToSerialize:
[09/28/2023-23:14:28] [I] dynamicPlugins:
[09/28/2023-23:14:28] [I] ignoreParsedPluginLibs: 0
[09/28/2023-23:14:28] [I] 
[09/28/2023-23:14:28] [I] === Inference Options ===
[09/28/2023-23:14:28] [I] Batch: Explicit
[09/28/2023-23:14:28] [I] Input inference shape: input=5x3x1024x1024
[09/28/2023-23:14:28] [I] Iterations: 10
[09/28/2023-23:14:28] [I] Duration: 3s (+ 200ms warm up)
[09/28/2023-23:14:28] [I] Sleep time: 0ms
[09/28/2023-23:14:28] [I] Idle time: 0ms
[09/28/2023-23:14:28] [I] Inference Streams: 1
[09/28/2023-23:14:28] [I] ExposeDMA: Disabled
[09/28/2023-23:14:28] [I] Data transfers: Enabled
[09/28/2023-23:14:28] [I] Spin-wait: Disabled
[09/28/2023-23:14:28] [I] Multithreading: Disabled
[09/28/2023-23:14:28] [I] CUDA Graph: Disabled
[09/28/2023-23:14:28] [I] Separate profiling: Disabled
[09/28/2023-23:14:28] [I] Time Deserialize: Disabled
[09/28/2023-23:14:28] [I] Time Refit: Disabled
[09/28/2023-23:14:28] [I] NVTX verbosity: 0
[09/28/2023-23:14:28] [I] Persistent Cache Ratio: 0
[09/28/2023-23:14:28] [I] Inputs:
[09/28/2023-23:14:28] [I] === Reporting Options ===
[09/28/2023-23:14:28] [I] Verbose: Disabled
[09/28/2023-23:14:28] [I] Averages: 10 inferences
[09/28/2023-23:14:28] [I] Percentiles: 90,95,99
[09/28/2023-23:14:28] [I] Dump refittable layers:Disabled
[09/28/2023-23:14:28] [I] Dump output: Disabled
[09/28/2023-23:14:28] [I] Profile: Disabled
[09/28/2023-23:14:28] [I] Export timing to JSON file: 
[09/28/2023-23:14:28] [I] Export output to JSON file: 
[09/28/2023-23:14:28] [I] Export profile to JSON file: 
[09/28/2023-23:14:28] [I] 
[09/28/2023-23:14:28] [I] === Device Information ===
[09/28/2023-23:14:28] [I] Selected Device: Tesla T4
[09/28/2023-23:14:28] [I] Compute Capability: 7.5
[09/28/2023-23:14:28] [I] SMs: 40
[09/28/2023-23:14:28] [I] Device Global Memory: 14930 MiB
[09/28/2023-23:14:28] [I] Shared Memory per SM: 64 KiB
[09/28/2023-23:14:28] [I] Memory Bus Width: 256 bits (ECC enabled)
[09/28/2023-23:14:28] [I] Application Compute Clock Rate: 1.59 GHz
[09/28/2023-23:14:28] [I] Application Memory Clock Rate: 5.001 GHz
[09/28/2023-23:14:28] [I] 
[09/28/2023-23:14:28] [I] Note: The application clock rates do not reflect the actual clock rates that the GPU is currently running at.
[09/28/2023-23:14:28] [I] 
[09/28/2023-23:14:28] [I] TensorRT version: 8.6.1
[09/28/2023-23:14:28] [I] Loading standard plugins
[09/28/2023-23:14:29] [I] [TRT] [MemUsageChange] Init CUDA: CPU +2, GPU +0, now: CPU 19, GPU 2903 (MiB)
[09/28/2023-23:14:36] [I] [TRT] [MemUsageChange] Init builder kernel library: CPU +889, GPU +174, now: CPU 984, GPU 3214 (MiB)
[09/28/2023-23:14:36] [I] Start parsing network model.
[09/28/2023-23:14:36] [I] [TRT] ----------------------------------------------------------------
[09/28/2023-23:14:36] [I] [TRT] Input filename:   /home/experimentation-pipeline/onnx_models/person_coarse_ground_vehicle__5672256760429727__minmax-per_channel-sym_act+sym_weight.qdq.onnx
[09/28/2023-23:14:36] [I] [TRT] ONNX IR version:  0.0.8
[09/28/2023-23:14:36] [I] [TRT] Opset version:    16
[09/28/2023-23:14:36] [I] [TRT] Producer name:    onnx.quantize
[09/28/2023-23:14:36] [I] [TRT] Producer version: 0.1.0
[09/28/2023-23:14:36] [I] [TRT] Domain:           
[09/28/2023-23:14:36] [I] [TRT] Model version:    0
[09/28/2023-23:14:36] [I] [TRT] Doc string:       
[09/28/2023-23:14:36] [I] [TRT] ----------------------------------------------------------------
[09/28/2023-23:14:37] [W] [TRT] onnx2trt_utils.cpp:374: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[09/28/2023-23:14:37] [W] [TRT] onnx2trt_utils.cpp:400: One or more weights outside the range of INT32 was clamped
[09/28/2023-23:14:37] [E] Error[3]: onnx::Conv_1707_DequantizeLinear: only activation types allowed as input to this layer.
[09/28/2023-23:14:37] [E] [TRT] ModelImporter.cpp:771: While parsing node number 12 [DequantizeLinear -> "onnx::Conv_1707"]:
[09/28/2023-23:14:37] [E] [TRT] ModelImporter.cpp:772: --- Begin node ---
[09/28/2023-23:14:37] [E] [TRT] ModelImporter.cpp:773: input: "onnx::Conv_1707_quantized"
input: "onnx::Conv_1707_quantized_scale"
input: "onnx::Conv_1707_quantized_zero_point"
output: "onnx::Conv_1707"
name: "onnx::Conv_1707_DequantizeLinear"
op_type: "DequantizeLinear"
attribute {
  name: "axis"
  i: 0
  type: INT
}

[09/28/2023-23:14:37] [E] [TRT] ModelImporter.cpp:774: --- End node ---
[09/28/2023-23:14:37] [E] [TRT] ModelImporter.cpp:777: ERROR: ModelImporter.cpp:195 In function parseGraph:
[6] Invalid Node - onnx::Conv_1707_DequantizeLinear
onnx::Conv_1707_DequantizeLinear: only activation types allowed as input to this layer.
[09/28/2023-23:14:37] [E] Failed to parse onnx file
[09/28/2023-23:14:37] [I] Finished parsing network model. Parse time: 0.244093
[09/28/2023-23:14:37] [E] Parsing model failed
[09/28/2023-23:14:37] [E] Failed to create engine from model or file.
[09/28/2023-23:14:37] [E] Engine set up failed
```

The types of the inputs for this node are:
onnx::Conv_1707_quantized - int32
onnx::Conv_1707_quantized_scale - float32
onnx::Conv_1707_quantized_zero_point - int 32

Is it possible that tensorrt expects the int32 to be int8?

## Environment

**TensorRT Version**: 8.6.1.6-1+cuda12.0

**NVIDIA GPU**: T4

**NVIDIA Driver Version**: 535.104.05

**CUDA Version**: 12.2

**CUDNN Version**: 8

Operating System: Ubuntu 22.04

Baremetal or Container (if so, version): Container nvidia/cuda:11.7.1-cudnn8-devel-ubuntu22.04

## Relevant Files

**Model link**:

## Steps To Reproduce

**Commands or scripts**:

**Comment by ChickenTarm** [comment]
I have used onnx-graphsurgeon to convert all int32 to int8:

```
quantized_model = onnx.load_model("quantized.qdq.onnx")
graph = gs.import_onnx(quantized_model)

qconv_node_names = []
qconv_nodes = []
eps = 0.000000001

for node in graph.nodes:
    if node.name.startswith("onnx::Conv") and node.name.endswith("DequantizeLinear"):
        if isinstance(node.inputs[0].values.dtype, np.dtypes.Int32DType):
            print(f"Modifying {node.name}")
            original_dequantized = node.inputs[0].values * node.inputs[1].values
            positives = node.inputs[0].values > 0
            new_postive_scale = node.inputs[0].values[positives] * node.inputs[1].values[positives] / 69
            new_negative_scale = node.inputs[0].values[~positives] * node.inputs[1].values[~positives] / -69
            node.inputs[0].values[positives] = 69
            node.inputs[0].values[~positives] = -69
            node.inputs[1].values[positives] = new_postive_scale + eps
            node.inputs[1].values[~positives] = new_negative_scale + eps
            new_dequantized = node.inputs[0].values * node.inputs[1].values
            node.inputs[0].values = node.inputs[0].values.astype(np.int8)
            node.inputs[2].values = node.inputs[2].values.astype(np.int8)
            diff_sum = (np.abs(original_dequantized - new_dequantized)).sum()
            if diff_sum > 0.0001:
                raise Exception
modified_onnx = gs.export_onnx(graph=graph, do_type_check=True)
```

However I run into a new error:

```
(experimentation-pipeline-py3.10) root@gc1dlml4gpu01:/home/experimentation-pipeline# /usr/src/tensorrt/bin/trtexec --workspace=4096 --fp16 --int8 --onnx=modified_model.onnx --minShapes='input:1x3x320x320' --optShapes='input:5x3x1024x1024' --maxShapes='input:10x3x1536x1536' --saveEngine='int8.trt'
&&&& RUNNING TensorRT.trtexec [TensorRT v8601] # /usr/src/tensorrt/bin/trtexec --workspace=4096 --fp16 --int8 --onnx=modified_model.onnx --minShapes=input:1x3x320x320 --optShapes=input:5x3x1024x1024 --maxShapes=input:10x3x1536x1536 --saveEngine=int8.trt
[09/29/2023-04:37:45] [W] --workspace flag has been deprecated by --memPoolSize flag.
[09/29/2023-04:37:45] [I] === Model Options ===
[09/29/2023-04:37:45] [I] Format: ONNX
[09/29/2023-04:37:45] [I] Model: modified_model.onnx
[09/29/2023-04:37:45] [I] Output:
[09/29/2023-04:37:45] [I] === Build Options ===
[09/29/2023-04:37:45] [I] Max batch: explicit batch
[09/29/2023-04:37:45] [I] Memory Pools: workspace: 4096 MiB, dlaSRAM: default, dlaLocalDRAM: default, dlaGlobalDRAM: default
[09/29/2023-04:37:45] [I] minTiming: 1
[09/29/2023-04:37:45] [I] avgTiming: 8
[09/29/2023-04:37:45] [I] Precision: FP32+FP16+INT8
[09/29/2023-04:37:45] [I] LayerPrecisions: 
[09/29/2023-04:37:45] [I] Layer Device Types: 
[09/29/2023-04:37:45] [I] Calibration: Dynamic
[09/29/2023-04:37:45] [I] Refit: Disabled
[09/29/2023-04:37:45] [I] Version Compatible: Disabled
[09/29/2023-04:37:45] [I] TensorRT runtime: full
[09/29/2023-04:37:45] [I] Lean DLL Path: 
[09/29/2023-04:37:45] [I] Tempfile Controls: { in_memory: allow, temporary: allow }
[09/29/2023-04:37:45] [I] Exclude Lean Runtime: Disabled
[09/29/2023-04:37:45] [I] Sparsity: Disabled
[09/29/2023-04:37:45] [I] Safe mode: Disabled
[09/29/2023-04:37:45] [I] Build DLA standalone loadable: Disabled
[09/29/2023-04:37:45] [I] Allow GPU fallback for DLA: Disabled
[09/29/2023-04:37:45] [I] DirectIO mode: Disabled
[09/29/2023-04:37:45] [I] Restricted mode: Disabled
[09/29/2023-04:37:45] [I] Skip inference: Disabled
[09/29/2023-04:37:45] [I] Save engine: int8.trt
[09/29/2023-04:37:45] [I] Load engine: 
[09/29/2023-04:37:45] [I] Profiling verbosity: 0
[09/29/2023-04:37:45] [I] Tactic sources: Using default tactic sources
[09/29/2023-04:37:45] [I] timingCacheMode: local
[09/29/2023-04:37:45] [I] timingCacheFile: 
[09/29/2023-04:37:45] [I] Heuristic: Disabled
[09/29/2023-04:37:45] [I] Preview Features: Use default preview flags.
[09/29/2023-04:37:45] [I] MaxAuxStreams: -1
[09/29/2023-04:37:45] [I] BuilderOptimizationLevel: -1
[09/29/2023-04:37:45] [I] Input(s)s format: fp32:CHW
[09/29/2023-04:37:45] [I] Output(s)s format: fp32:CHW
[09/29/2023-04:37:45] [I] Input build shape: input=1x3x320x320+5x3x1024x1024+10x3x1536x1536
[09/29/2023-04:37:45] [I] Input calibration shapes: model
[09/29/2023-04:37:45] [I] === System Options ===
[09/29/2023-04:37:45] [I] Device: 0
[09/29/2023-04:37:45] [I] DLACore: 
[09/29/2023-04:37:45] [I] Plugins:
[09/29/2023-04:37:45] [I] setPluginsToSerialize:
[09/29/2023-04:37:45] [I] dynamicPlugins:
[09/29/2023-04:37:45] [I] ignoreParsedPluginLibs: 0
[09/29/2023-04:37:45] [I] 
[09/29/2023-04:37:45] [I] === Inference Options ===
[09/29/2023-04:37:45] [I] Batch: Explicit
[09/29/2023-04:37:45] [I] Input inference shape: input=5x3x1024x1024
[09/29/2023-04:37:45] [I] Iterations: 10
[09/29/2023-04:37:45] [I] Duration: 3s (+ 200ms warm up)
[09/29/2023-04:37:45] [I] Sleep time: 0ms
[09/29/2023-04:37:45] [I] Idle time: 0ms
[09/29/2023-04:37:45] [I] Inference Streams: 1
[09/29/2023-04:37:45] [I] ExposeDMA: Disabled
[09/29/2023-04:37:45] [I] Data transfers: Enabled
[09/29/2023-04:37:45] [I] Spin-wait: Disabled
[09/29/2023-04:37:45] [I] Multithreading: Disabled
[09/29/2023-04:37:45] [I] CUDA Graph: Disabled
[09/29/2023-04:37:45] [I] Separate profiling: Disabled
[09/29/2023-04:37:45] [I] Time Deserialize: Disabled
[09/29/2023-04:37:45] [I] Time Refit: Disabled
[09/29/2023-04:37:45] [I] NVTX verbosity: 0
[09/29/2023-04:37:45] [I] Persistent Cache Ratio: 0
[09/29/2023-04:37:45] [I] Inputs:
[09/29/2023-04:37:45] [I] === Reporting Options ===
[09/29/2023-04:37:45] [I] Verbose: Disabled
[09/29/2023-04:37:45] [I] Averages: 10 inferences
[09/29/2023-04:37:45] [I] Percentiles: 90,95,99
[09/29/2023-04:37:45] [I] Dump refittable layers:Disabled
[09/29/2023-04:37:45] [I] Dump output: Disabled
[09/29/2023-04:37:45] [I] Profile: Disabled
[09/29/2023-04:37:45] [I] Export timing to JSON file: 
[09/29/2023-04:37:45] [I] Export output to JSON file: 
[09/29/2023-04:37:45] [I] Export profile to JSON file: 
[09/29/2023-04:37:45] [I] 
[09/29/2023-04:37:46] [I] === Device Information ===
[09/29/2023-04:37:46] [I] Selected Device: Tesla T4
[09/29/2023-04:37:46] [I] Compute Capability: 7.5
[09/29/2023-04:37:46] [I] SMs: 40
[09/29/2023-04:37:46] [I] Device Global Memory: 14930 MiB
[09/29/2023-04:37:46] [I] Shared Memory per SM: 64 KiB
[09/29/2023-04:37:46] [I] Memory Bus Width: 256 bits (ECC enabled)
[09/29/2023-04:37:46] [I] Application Compute Clock Rate: 1.59 GHz
[09/29/2023-04:37:46] [I] Application Memory Clock Rate: 5.001 GHz
[09/29/2023-04:37:46] [I] 
[09/29/2023-04:37:46] [I] Note: The application clock rates do not reflect the actual clock rates that the GPU is currently running at.
[09/29/2023-04:37:46] [I] 
[09/29/2023-04:37:46] [I] TensorRT version: 8.6.1
[09/29/2023-04:37:46] [I] Loading standard plugins
[09/29/2023-04:37:46] [I] [TRT] [MemUsageChange] Init CUDA: CPU +2, GPU +0, now: CPU 19, GPU 374 (MiB)
[09/29/2023-04:37:53] [I] [TRT] [MemUsageChange] Init builder kernel library: CPU +889, GPU +174, now: CPU 984, GPU 548 (MiB)
[09/29/2023-04:37:53] [I] Start parsing network model.
[09/29/2023-04:37:53] [I] [TRT] ----------------------------------------------------------------
[09/29/2023-04:37:53] [I] [TRT] Input filename:   modified_model.onnx
[09/29/2023-04:37:53] [I] [TRT] ONNX IR version:  0.0.9
[09/29/2023-04:37:53] [I] [TRT] Opset version:    16
[09/29/2023-04:37:53] [I] [TRT] Producer name:    onnx.quantize
[09/29/2023-04:37:53] [I] [TRT] Producer version: 0.1.0
[09/29/2023-04:37:53] [I] [TRT] Domain:           
[09/29/2023-04:37:53] [I] [TRT] Model version:    0
[09/29/2023-04:37:53] [I] [TRT] Doc string:       
[09/29/2023-04:37:53] [I] [TRT] ----------------------------------------------------------------
[09/29/2023-04:37:54] [W] [TRT] onnx2trt_utils.cpp:374: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[09/29/2023-04:37:54] [W] [TRT] onnx2trt_utils.cpp:400: One or more weights outside the range of INT32 was clamped
[09/29/2023-04:37:54] [I] Finished parsing network model. Parse time: 0.262231
[09/29/2023-04:37:54] [I] [TRT] BuilderFlag::kTF32 is set but hardware does not support TF32. Disabling TF32.
[09/29/2023-04:37:54] [W] [TRT] Calibrator won't be used in explicit precision mode. Use quantization aware training to generate network with Quantize/Dequantize nodes.
[09/29/2023-04:37:55] [I] [TRT] Graph optimization time: 0.393973 seconds.
[09/29/2023-04:37:55] [I] [TRT] BuilderFlag::kTF32 is set but hardware does not support TF32. Disabling TF32.
[09/29/2023-04:37:55] [I] [TRT] Local timing cache in use. Profiling results in this builder pass will not be stored.
[09/29/2023-04:37:56] [E] Error[10]: Could not find any implementation for node onnx::Conv_1707_DequantizeLinear.
[09/29/2023-04:37:56] [E] Error[10]: [optimizer.cpp::computeCosts::3869] Error Code 10: Internal Error (Could not find any implementation for node onnx::Conv_1707_DequantizeLinear.)
[09/29/2023-04:37:56] [E] Engine could not be created from network
[09/29/2023-04:37:56] [E] Building engine failed
[09/29/2023-04:37:56] [E] Failed to create engine from model or file.
[09/29/2023-04:37:56] [E] Engine set up failed
&&&& FAILED TensorRT.trtexec [TensorRT v8601] # /usr/src/tensorrt/bin/trtexec --workspace=4096 --fp16 --int8 --onnx=modified_model.onnx --minShapes=input:1x3x320x320 --optShapes=input:5x3x1024x1024 --maxShapes=input:10x3x1536x1536 --saveEngine=int8.trt
```

**Comment by zerollzeng** [comment]
Please make sure your model is valid for onnxruntime first.
```
$ polygraphy run --onnxrt quantize__1530132561151892__minmax-per_channel-sym_act+sym_weight.qdq.onnx 
[I] RUNNING | Command: /home/scratch.zeroz_sw/miniconda3/bin/polygraphy run --onnxrt quantize__1530132561151892__minmax-per_channel-sym_act+sym_weight.qdq.onnx
[I] onnxrt-runner-N0-10/05/23-14:37:10  | Activating and starting inference
[I] Creating ONNX-Runtime Inference Session with providers: ['CPUExecutionProvider']
[W] Input tensor: input [shape=BoundedShape(['batch', 3, 'height', 'width'], min=None, max=None)] | Will generate data of shape: [1, 3, 1, 1].
    If this is incorrect, please provide a custom data loader.
[I] onnxrt-runner-N0-10/05/23-14:37:10 
    ---- Inference Input(s) ----
    {input [dtype=float32, shape=(1, 3, 1, 1)]}
2023-10-05 14:37:11.845725175 [E:onnxruntime:, sequential_executor.cc:514 ExecuteKernel] Non-zero status code returned while running QLinearConcat node. Name:'/Concat_8' Status Message: concat.cc:154 PrepareForCompute Non concat axis dimensions must match: Axis 2 has mismatched dimensions of 2 and 1
Traceback (most recent call last):
  File "/home/scratch.zeroz_sw/miniconda3/bin/polygraphy", line 8, in <module>
    sys.exit(main())
  File "/home/scratch.zeroz_sw/miniconda3/lib/python3.9/site-packages/polygraphy/tools/_main.py", line 70, in main
    status = selected_tool.run(args)
  File "/home/scratch.zeroz_sw/miniconda3/lib/python3.9/site-packages/polygraphy/tools/base/tool.py", line 171, in run
    status = self.run_impl(args)
  File "/home/scratch.zeroz_sw/miniconda3/lib/python3.9/site-packages/polygraphy/tools/run/run.py", line 228, in run_impl
    exec(str(script))
  File "<string>", line 21, in <module>
  File "/home/scratch.zeroz_sw/miniconda3/lib/python3.9/site-packages/polygraphy/comparator/comparator.py", line 213, in run
    run_results.append((runner.name, execute_runner(runner, loader_cache)))
  File "/home/scratch.zeroz_sw/miniconda3/lib/python3.9/site-packages/polygraphy/comparator/comparator.py", line 132, in execute_runner
    outputs = active_runner.infer(feed_dict=feed_dict)
  File "/home/scratch.zeroz_sw/miniconda3/lib/python3.9/site-packages/polygraphy/backend/base/runner.py", line 177, in infer
    return self.infer_impl(feed_dict, *args, **kwargs)
  File "/home/scratch.zeroz_sw/miniconda3/lib/python3.9/site-packages/polygraphy/util/util.py", line 694, in wrapped
    return func(*args, **kwargs)
  File "/home/scratch.zeroz_sw/miniconda3/lib/python3.9/site-packages/polygraphy/backend/onnxrt/runner.py", line 73, in infer_impl
    inference_outputs = self.sess.run(None, feed_dict)
  File "/home/scratch.zeroz_sw/miniconda3/lib/python3.9/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 217, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running QLinearConcat node. Name:'/Concat_8' Status Message: concat.cc:154 PrepareForCompute Non concat axis dimensions must match: Axis 2 has mismatched dimensions of 2 and 1
```

**Comment by zerollzeng** [comment]
I kind of feel like this is incorrect, @ttyio 
![image](https://github.com/NVIDIA/TensorRT/assets/38289304/57257203-ddc1-482c-b95b-537ff23f8231)
in the above pic, x and zero_point has type int32 and scale has type fp32. I've only seen pattern like weights -> Q -> DQ -> Conv

**Comment by ChickenTarm** [comment]
It is by design that the bias of a convolution is quantized to int32 instead of int 8 according to [this](https://github.com/microsoft/onnxruntime/issues/17738#issuecomment-1740883360)

**Comment by ttyio** [comment]
@ChickenTarm , the `DQ` input should match the `Q` output, according to https://github.com/onnx/onnx/blob/main/docs/Operators.md#QuantizeLinear, the `Q` output should be either `INT8` or `FP8`.
we recommend https://github.com/NVIDIA/TensorRT/tree/main/tools/pytorch-quantization to do QAT for TensorRT. 
Thanks!

**Comment by ttyio** [comment]
closing since no activity for more than 3 weeks, thanks!

**Comment by ShuaiShao93** [comment]
I see a similar issue, did you fix this? @ChickenTarm
