### ISSUE TITLE
Tensorrt import failed using generated wheel file on jetson nano. <tensorrt.so: cannot open shareed object file: no such file or directory>

### ISSUE THREAD

**Issue by Dovahlore** [NVIDIA/TensorRT#3388]
## Description

Hi, I have generated wheels file using pybind11 (v2.9) on my PC linux virtual machine(x86_64) . The wheels file < tensorrt-8.0.1.6-cp38-none-linux_aarch64.whl > is only 800kb. After pip installation in conda enviroment, I found python unable to import tensorrt. I setuptools warned as i build wheels for python3.8 arm64 . 
## ENV

* __jetpack version__:4.6.4
* __conda python version__ : 3.8.12
## Build wheels file logs
```
 /home/dovahlore/TensorRT/python/build /home/dovahlore/TensorRT/python
ForwardDeclarations.h utils.h
-- The CXX compiler identification is GNU 11.4.0
-- The C compiler identification is GNU 11.4.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dovahlore/TensorRT/python/build
[  8%] Building CXX object CMakeFiles/tensorrt.dir/src/infer/pyInt8.cpp.o
[ 16%] Building CXX object CMakeFiles/tensorrt.dir/src/infer/pyCore.cpp.o
[ 25%] Building CXX object CMakeFiles/tensorrt.dir/src/infer/pyFoundationalTypes.cpp.o
[ 33%] Building CXX object CMakeFiles/tensorrt.dir/src/infer/pyAlgorithmSelector.cpp.o
[ 41%] Building CXX object CMakeFiles/tensorrt.dir/src/infer/pyGraph.cpp.o
[ 50%] Building CXX object CMakeFiles/tensorrt.dir/src/infer/pyPlugin.cpp.o
[ 58%] Building CXX object CMakeFiles/tensorrt.dir/src/parsers/pyOnnx.cpp.o
[ 66%] Building CXX object CMakeFiles/tensorrt.dir/src/parsers/pyCaffe.cpp.o
[ 75%] Building CXX object CMakeFiles/tensorrt.dir/src/parsers/pyUff.cpp.o
[ 83%] Building CXX object CMakeFiles/tensorrt.dir/src/pyTensorRT.cpp.o
[ 91%] Building CXX object CMakeFiles/tensorrt.dir/src/utils.cpp.o
[100%] Linking CXX shared library tensorrt/tensorrt.so
[100%] Built target tensorrt
Generating python 3.8 bindings for TensorRT 8.0.1.6
/home/dovahlore/TensorRT/python/packaging /home/dovahlore/TensorRT/python/build /home/dovahlore/TensorRT/python
/home/dovahlore/TensorRT/python/build /home/dovahlore/TensorRT/python
/usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/home/dovahlore/TensorRT/python
```
## `Error` logs on jetson
```Python 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 23:40:23) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
> import tensorrt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dovahlore/mambaforge/envs/venv/lib/python3.8/site-packages/tensorrt/__init__.py", line 36, in <module>
    from .tensorrt import *
ImportError: /home/dovahlore/mambaforge/envs/venv/lib/python3.8/site-packages/tensorrt/tensorrt.so: cannot open shared object file: No such file or directory
```

**Comment by Dovahlore** [comment]
i use comand __ldd tensorrt.so__ it returns not a dynamic executables, do i have to build it on arm64 platform?

**Comment by zerollzeng** [comment]
> ```python
> cannot open shared object file: No such file or directory
> ```

TRT core lib is not installed? After flash the board, did you install the CUDA-X package? cc @pranavm-nvidia

**Comment by Dovahlore** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Dovahlore** [comment]
Thanks for reply. I installed the jetpack sdk through sdkmanager. All the packges should had been installed successfully. I would check them later.

**Comment by Dovahlore** [comment]
Thanks for reply. I installed the jetpack sdk through sdkmanager. All the packges should had been installed successfully. I would check them later.I m trying to run yolov8 on jetson nano. Yolov8 requires python 3.8 but tensorrt only suports 3.6. maybe is the conda problem? Im totally confused.

**Comment by zerollzeng** [comment]
You can build the TensorRT python binding with this repo on your own if the package don't have the python version you want.
