### ISSUE TITLE
when I convert onnx to trt,this warning occurs and then error occurs "was not able to infer a KopT value for tensor using one(s)" Could not find any implementation for node {ForeignNode[(Unnamed Layer* 75544) [Shuffle]_output[Constant].../Greater_2]}.

### ISSUE THREAD

**Issue by YUjunuuuuu** [NVIDIA/TensorRT#3401]
tensorrt is 8.6GA
the onnx model is here [https://drive.google.com/file/d/1l1QR-V7Bzp5nOFJJvOzkZOFqU59FPaVQ/view?usp=share_link](url)
![image](https://github.com/NVIDIA/TensorRT/assets/49989327/3689cf67-56cd-4279-89ab-86569325f375)

**Comment by zerollzeng** [comment]
Please provide the command in copy-paste instead of just a screenshot :-)

Looks like your model is actually a static shape model, which some shape in isvalid. Here is the error return by onnxruntime:
```
$ polygraphy run mid_transformer2.onnx --onnxrt --input-shapes queries:[1,200,2] coarse_corrs:[1,200,2]
[I] RUNNING | Command: /home/scratch.zeroz_sw/miniconda3/bin/polygraphy run mid_transformer2.onnx --onnxrt --input-shapes queries:[1,200,2] coarse_corrs:[1,200,2]
[I] Will generate inference input data according to provided TensorMetadata: {queries [shape=(1, 200, 2)],
     coarse_corrs [shape=(1, 200, 2)]}
[I] onnxrt-runner-N0-10/28/23-12:37:21  | Activating and starting inference
[I] Creating ONNX-Runtime Inference Session with providers: ['CPUExecutionProvider']
[I] onnxrt-runner-N0-10/28/23-12:37:21 
    ---- Inference Input(s) ----
    {mid_src [dtype=float32, shape=(1, 128, 52, 156)],
     queries [dtype=float32, shape=(1, 200, 2)],
     coarse_corrs [dtype=float32, shape=(1, 200, 2)]}
2023-10-28 12:37:25.417242361 [E:onnxruntime:, sequential_executor.cc:514 ExecuteKernel] Non-zero status code returned while running Reshape node. Name:'/Reshape_619' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:40 onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape&, onnxruntime::TensorShapeVector&, bool) gsl::narrow_cast<int64_t>(input_shape.Size()) == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{1,0,128,17,17}, requested shape:{1,128,17,17}

Traceback (most recent call last):
  File "/home/scratch.zeroz_sw/miniconda3/bin/polygraphy", line 8, in <module>
    sys.exit(main())
  File "/home/scratch.zeroz_sw/miniconda3/lib/python3.9/site-packages/polygraphy/tools/_main.py", line 70, in main
    status = selected_tool.run(args)
  File "/home/scratch.zeroz_sw/miniconda3/lib/python3.9/site-packages/polygraphy/tools/base/tool.py", line 171, in run
    status = self.run_impl(args)
  File "/home/scratch.zeroz_sw/miniconda3/lib/python3.9/site-packages/polygraphy/tools/run/run.py", line 228, in run_impl
    exec(str(script))
  File "<string>", line 25, in <module>
  File "/home/scratch.zeroz_sw/miniconda3/lib/python3.9/site-packages/polygraphy/comparator/comparator.py", line 213, in run
    run_results.append((runner.name, execute_runner(runner, loader_cache)))
  File "/home/scratch.zeroz_sw/miniconda3/lib/python3.9/site-packages/polygraphy/comparator/comparator.py", line 132, in execute_runner
    outputs = active_runner.infer(feed_dict=feed_dict)
  File "/home/scratch.zeroz_sw/miniconda3/lib/python3.9/site-packages/polygraphy/backend/base/runner.py", line 177, in infer
    return self.infer_impl(feed_dict, *args, **kwargs)
  File "/home/scratch.zeroz_sw/miniconda3/lib/python3.9/site-packages/polygraphy/util/util.py", line 694, in wrapped
    return func(*args, **kwargs)
  File "/home/scratch.zeroz_sw/miniconda3/lib/python3.9/site-packages/polygraphy/backend/onnxrt/runner.py", line 73, in infer_impl
    inference_outputs = self.sess.run(None, feed_dict)
  File "/home/scratch.zeroz_sw/miniconda3/lib/python3.9/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 217, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Reshape node. Name:'/Reshape_619' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:40 onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape&, onnxruntime::TensorShapeVector&, bool) gsl::narrow_cast<int64_t>(input_shape.Size()) == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{1,0,128,17,17}, requested shape:{1,128,17,17}
```

**Comment by Hoi2022** [comment]
When I convert QAlign model to tensorrt, I found there is a diff between trt-model output and onnx model output. The onnx model output matches that of torch inference. 

I also noticed this warning:
[W] [TRT] Was not able to infer a kOPT value for tensor /model/Gather_1_output_0. Using one(s).

I don't know if this is the cause of the diff.
