### ISSUE TITLE
Failed to create ONNX file from Tensor flow Object detection saved model, That was trained on our own dataset

### ISSUE THREAD

**Issue by atosh603** [NVIDIA/TensorRT#3433]
We trained a fpnlite ssd mobilenet 320x320 model on our own dataset. and Followed this examples in this below website
https://github.com/NVIDIA/TensorRT/tree/main/samples/python/tensorflow_object_detection_api#build-tensorrt-engine
to create ONNX file and then build Tensorrt engine after that. We are using Windows Desktop machine to create the ONNX file later we can build Engine in Jetson Nano.

So while running Create_Onnx.py We are facing this issue:
INFO:tf2onnx.optimizer:After optimization: BatchNormalization -45 (76->31), Cast -40 (196->156), Const -513 (1070->557), Gather +7 (48->55), Identity -110 (110->0), Less -2 (11->9), Mul -2 (64->62), Shape -7 (40->33), Slice -6 (75->69), Squeeze -22 (77->55), Transpose -383 (410->27), Unsqueeze -111 (163->52)
INFO:ModelHelper:TF2ONNX graph created successfully
INFO:ModelHelper:Model is ssd_mobilenet_v2_fpn_keras
INFO:ModelHelper:Height is 320
INFO:ModelHelper:Width is 320
INFO:ModelHelper:First NMS score threshold is 9.99999993922529e-09
INFO:ModelHelper:First NMS iou threshold is 0.6000000238418579
INFO:ModelHelper:First NMS max proposals is 100
INFO:ModelHelper:ONNX graph input shape: [1, 320, 320, 3] [NCHW format set]
[E] No function: transpose registered for opset: 11
Traceback (most recent call last):
  File "C:\Users\NDJ2KOR\tensorflow_model\create_onnx.py", line 671, in <module>
    main(args)
  File "C:\Users\NDJ2KOR\tensorflow_model\create_onnx.py", line 646, in main
    effdet_gs.update_preprocessor(args.batch_size, args.input_format)
  File "C:\Users\NDJ2KOR\tensorflow_model\create_onnx.py", line 228, in update_preprocessor
    input_tensor = self.graph.transpose("preprocessor/transpose", input_tensor, [0, 3, 1, 2])
  File "C:\Users\NDJ2KOR\AppData\Local\anaconda3\envs\tiny\lib\site-packages\onnx_graphsurgeon\ir\graph.py", line 127, in __getattr__
    raise err
  File "C:\Users\NDJ2KOR\AppData\Local\anaconda3\envs\tiny\lib\site-packages\onnx_graphsurgeon\ir\graph.py", line 117, in __getattr__
    return super().__getattribute__(name)
AttributeError: 'Graph' object has no attribute 'transpose'

Please let us know as soon as possible How can we solve this issue.
This model we are trying to deploy in Jetson Nano

**Comment by zerollzeng** [comment]
which onnx_graphsurgeon version you are using? does it align with the requirement in NDJ2KOR\tensorflow_model\create_onnx.py?

@pranavm-nvidia for viz

**Comment by atosh603** [comment]
Hey thank you for your reply. 
Successfully built the Tensorrt Engine for my model.
I am stuck in getting inference from that Tensorrt Engine of FPN lite object detection model.
Can you please suggest me a sample code to infer from Tensorrt Object Detection model and display bounding boxes of that inferred image.
I am stuck in this process please help me out.
