### ISSUE TITLE
Fused MHA failure of TensorRT 8.6.1.6-1+cuda12.0 when running bertQKVToContextPlugin on GPU NVIDIA A100-SXM4-40GB

### ISSUE THREAD

**Issue by alxmamaev** [NVIDIA/TensorRT#3435]
## Description

I have tried to use `bertQKVToContextPlugin` plugin in my network implementation by TensorRT python network api. Every time it fails on the sequences of size 64, 128, 384. I found that the reason in the Fused MHA in the MHA plugin, because it uses fused kernels in this input sizes. I have create the isolated example to reproduce the issue and run separately in `nvcr.io/nvidia/tensorrt:23.10-py3` container. The issue is reproduced again.

There is the code:
```python
import numpy as np
import tensorrt as trt
from cuda import cuda, cudart


def check_cuda_err(err):
    if isinstance(err, cuda.CUresult):
        if err != cuda.CUresult.CUDA_SUCCESS:
            raise RuntimeError("Cuda Error: {}".format(err))
    if isinstance(err, cudart.cudaError_t):
        if err != cudart.cudaError_t.cudaSuccess:
            raise RuntimeError("Cuda Runtime Error: {}".format(err))
    else:
        raise RuntimeError("Unknown error type: {}".format(err))

def cuda_call(call):
    err, res = call[0], call[1:]
    check_cuda_err(err)
    if len(res) == 1:
        res = res[0]
    return res

plg_registry = trt.get_plugin_registry()

hidden_size_value = 1024
n_heads = 16


plugin_creator = plg_registry.get_plugin_creator("CustomQKVToContextPluginDynamic", "1", "")
type_id = trt.PluginField(
    "type_id", np.array([int(trt.float16)], dtype=np.int32), trt.PluginFieldType.INT32
)
hidden_size = trt.PluginField(
    "hidden_size",
    np.array([hidden_size_value], dtype=np.int32),
    trt.PluginFieldType.INT32,
)
num_heads = trt.PluginField(
    "num_heads",
    np.array([n_heads], dtype=np.int32),
    trt.PluginFieldType.INT32,
)
has_mask = trt.PluginField(
    "has_mask", np.array([0], dtype=np.int32), trt.PluginFieldType.INT32
)

field_collection = trt.PluginFieldCollection(
    [type_id, hidden_size, num_heads, has_mask]
)
plugin = plugin_creator.create_plugin(
    name="qkv2ctx", field_collection=field_collection
)


logger = trt.Logger(trt.Logger.ERROR)
builder = trt.Builder(logger)
config = builder.create_builder_config()
config.set_flag(trt.BuilderFlag.FP16)
config.set_memory_pool_limit(trt.tensorrt.MemoryPoolType.WORKSPACE, 1 << 30)

network = builder.create_network(1 << int(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH))

my_input = network.add_input(
            name="my_input", 
            dtype=trt.float16, 
            shape=(-1, 2, hidden_size_value * 3, 1, 1)
        )

qkv_attention = network.add_plugin_v2(
    inputs=[my_input],
    plugin=plugin,
)

qkv_attention.get_output(0).dtype # I dont know why, but output type will not change without pre-checking the dtype, it will be fp32 by default in anyway
qkv_attention.get_output(0).dtype = trt.float16


qkv_attention.get_output(0).name = "output"


network.mark_output(qkv_attention.get_output(0))

opt_profile = builder.create_optimization_profile()
opt_profile.set_shape(
            "my_input",
            trt.Dims((1, 2, hidden_size_value * 3, 1, 1)),
            trt.Dims((256, 2, hidden_size_value * 3, 1, 1)),
            trt.Dims((512, 2, hidden_size_value * 3, 1, 1)),
        )
opt_profile_index = config.add_optimization_profile(opt_profile)


plan = builder.build_serialized_network(network, config)
runtime = trt.Runtime(logger)
engine = runtime.deserialize_cuda_engine(plan)


input_dtype = np.dtype(trt.nptype(engine.get_tensor_dtype("my_input")))
output_dtype = np.dtype(trt.nptype(engine.get_tensor_dtype("output")))


print("INPUT DTYPE:", input_dtype)
print("OUTPUT DTYPE:", output_dtype)
print()

bindings = [
    cuda_call(cudart.cudaMalloc(512 * 2 * hidden_size_value * 3 * input_dtype.itemsize)), #input
    cuda_call(cudart.cudaMalloc(512 * 2 * hidden_size_value * output_dtype.itemsize)) # output
]

stream = cuda_call(cudart.cudaStreamCreate())
context = engine.create_execution_context()


for sequence_len in [381, 383, 384]:
    print("SEQUENCE LEN:", sequence_len)
    input_data = np.random.randn(sequence_len, 2, hidden_size_value * 3, 1, 1).astype(input_dtype)
    context.set_input_shape("my_input", trt.Dims(list(input_data.shape)))

    output_shape = context.get_tensor_shape("output")
    output_data = np.zeros(output_shape, dtype=output_dtype)



    cuda_call(cudart.cudaMemcpy(bindings[0], input_data.ctypes.data, input_data.nbytes, cudart.cudaMemcpyKind.cudaMemcpyHostToDevice))
    context.execute_async_v2(bindings=bindings, stream_handle=stream)
    cuda_call(cudart.cudaStreamSynchronize(stream))
    cuda_call(cudart.cudaMemcpy(output_data.ctypes.data, bindings[1], output_data.nbytes, cudart.cudaMemcpyKind.cudaMemcpyDeviceToHost))

    print("Ok\n======\n")
```

There is output of this script running on my machine:
```
root@25546f960a57:/workspace# python3 test_mha.py
INPUT DTYPE: float16
OUTPUT DTYPE: float16

SEQUENCE LEN: 381
Ok
======

SEQUENCE LEN: 383
Ok
======

SEQUENCE LEN: 384
Traceback (most recent call last):
  File "/workspace/test_mha.py", line 128, in <module>
    cuda_call(cudart.cudaStreamSynchronize(stream))
  File "/workspace/test_mha.py", line 18, in cuda_call
    check_cuda_err(err)
  File "/workspace/test_mha.py", line 12, in check_cuda_err
    raise RuntimeError("Cuda Runtime Error: {}".format(err))
RuntimeError: Cuda Runtime Error: 700
[11/07/2023-15:12:30] [TRT] [E] 1: [defaultAllocator.cpp::deallocate::61] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[11/07/2023-15:12:30] [TRT] [E] 1: [defaultAllocator.cpp::deallocate::61] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[11/07/2023-15:12:30] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaStream::47] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[11/07/2023-15:12:30] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[11/07/2023-15:12:30] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
```

It is every time crash on the size 384. I have tried to fix it on different ways, but nothing helps, there no any option to disable FMHA, so only one solution which works for me now is forking the repo with plugin and removing FMHA implementation. But this looks like a really weird solution.

## Environment

I have run it on this container: nvcr.io/nvidia/tensorrt:23.10-py3
My GPU: NVIDIA A100-SXM4-40GB
Driver Version: 510.47.03 
CUDA Version: 11.6

**Comment by zerollzeng** [comment]
I've file internal bug 4375003 for this.

**Comment by alxmamaev** [comment]
@zerollzeng You were able to reproduce it?

**Comment by zerollzeng** [comment]
Our fMHA kernel always assume their was a mask for input and you didn't provide it in your reproduce code. Could you please try add the mask to the plugin as WAR?
```
import numpy as np
import tensorrt as trt
from cuda import cuda, cudart


def check_cuda_err(err):
    if isinstance(err, cuda.CUresult):
        if err != cuda.CUresult.CUDA_SUCCESS:
            raise RuntimeError("Cuda Error: {}".format(err))
    if isinstance(err, cudart.cudaError_t):
        if err != cudart.cudaError_t.cudaSuccess:
            raise RuntimeError("Cuda Runtime Error: {}".format(err))
    else:
        raise RuntimeError("Unknown error type: {}".format(err))

def cuda_call(call):
    err, res = call[0], call[1:]
    check_cuda_err(err)
    if len(res) == 1:
        res = res[0]
    return res

plg_registry = trt.get_plugin_registry()

hidden_size_value = 1024
n_heads = 16


plugin_creator = plg_registry.get_plugin_creator("CustomQKVToContextPluginDynamic", "1", "")
type_id = trt.PluginField(
    "type_id", np.array([int(trt.float16)], dtype=np.int32), trt.PluginFieldType.INT32
)
hidden_size = trt.PluginField(
    "hidden_size",
    np.array([hidden_size_value], dtype=np.int32),
    trt.PluginFieldType.INT32,
)
num_heads = trt.PluginField(
    "num_heads",
    np.array([n_heads], dtype=np.int32),
    trt.PluginFieldType.INT32,
)
has_mask = trt.PluginField(
    "has_mask", np.array([1], dtype=np.int32), trt.PluginFieldType.INT32
)

field_collection = trt.PluginFieldCollection(
    [type_id, hidden_size, num_heads, has_mask]
)
plugin = plugin_creator.create_plugin(
    name="qkv2ctx", field_collection=field_collection
)


logger = trt.Logger(trt.Logger.ERROR)
builder = trt.Builder(logger)
config = builder.create_builder_config()
config.set_flag(trt.BuilderFlag.FP16)
config.set_memory_pool_limit(trt.tensorrt.MemoryPoolType.WORKSPACE, 1 << 30)

network = builder.create_network(1 << int(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH))

my_input = network.add_input(
            name="my_input",
            dtype=trt.float16,
            shape=(-1, 2, hidden_size_value * 3, 1, 1)
        )

my_mask = network.add_input(
            name="my_mask",
            dtype=trt.int32,
            shape=(2, 1)
        )


qkv_attention = network.add_plugin_v2(
    inputs=[my_input, my_mask],
    plugin=plugin,
)

qkv_attention.get_output(0).dtype # I dont know why, but output type will not change without pre-checking the dtype, it will be fp32 by default in anyway
qkv_attention.get_output(0).dtype = trt.float16


qkv_attention.get_output(0).name = "output"


network.mark_output(qkv_attention.get_output(0))

opt_profile = builder.create_optimization_profile()
opt_profile.set_shape(
            "my_input",
            trt.Dims((1, 2, hidden_size_value * 3, 1, 1)),
            trt.Dims((256, 2, hidden_size_value * 3, 1, 1)),
            trt.Dims((512, 2, hidden_size_value * 3, 1, 1)),
        )
opt_profile_index = config.add_optimization_profile(opt_profile)


plan = builder.build_serialized_network(network, config)
runtime = trt.Runtime(logger)
engine = runtime.deserialize_cuda_engine(plan)


input_dtype = np.dtype(trt.nptype(engine.get_tensor_dtype("my_input")))
mask_dtype = np.dtype(trt.nptype(engine.get_tensor_dtype("my_mask")))
output_dtype = np.dtype(trt.nptype(engine.get_tensor_dtype("output")))


print("INPUT DTYPE:", input_dtype)
print("OUTPUT DTYPE:", output_dtype)
print()

bindings = [
    cuda_call(cudart.cudaMalloc(512 * 2 * hidden_size_value * 3 * input_dtype.itemsize)), #input
    cuda_call(cudart.cudaMalloc(2 * mask_dtype.itemsize)), #input mask
    cuda_call(cudart.cudaMalloc(512 * 2 * hidden_size_value * output_dtype.itemsize)) # output
]

stream = cuda_call(cudart.cudaStreamCreate())
context = engine.create_execution_context()


for sequence_len in [381, 383, 384]:
    print("SEQUENCE LEN:", sequence_len)
    input_data = np.random.randn(sequence_len, 2, hidden_size_value * 3, 1, 1).astype(input_dtype)
    mask_data = np.array([sequence_len, sequence_len]).astype(mask_dtype)
    context.set_input_shape("my_input", trt.Dims(list(input_data.shape)))

    output_shape = context.get_tensor_shape("output")
    output_data = np.zeros(output_shape, dtype=output_dtype)



    cuda_call(cudart.cudaMemcpy(bindings[0], input_data.ctypes.data, input_data.nbytes, cudart.cudaMemcpyKind.cudaMemcpyHostToDevice))
    cuda_call(cudart.cudaMemcpy(bindings[1], mask_data.ctypes.data, mask_data.nbytes, cudart.cudaMemcpyKind.cudaMemcpyHostToDevice))
    context.execute_async_v2(bindings=bindings, stream_handle=stream)
    cuda_call(cudart.cudaStreamSynchronize(stream))
    cuda_call(cudart.cudaMemcpy(output_data.ctypes.data, bindings[2], output_data.nbytes, cudart.cudaMemcpyKind.cudaMemcpyDeviceToHost))

    print("Ok\n======\n")
```

**Comment by zerollzeng** [comment]
We will also improve this in our plugin code.

**Comment by alxmamaev** [comment]
I will try it with mask today.

Btw. Can you please explain this part?
```
qkv_attention.get_output(0).dtype # I dont know why, but output type will not change without pre-checking the dtype, it will be fp32 by default in anyway
qkv_attention.get_output(0).dtype = trt.float16
```

If I will remove `qkv_attention.get_output(0).dtype` from the code, then `print("OUTPUT DTYPE:", output_dtype)` will print `float32` as an output type.

**Comment by alxmamaev** [comment]
@zerollzeng I will try it with mask today.

Btw. Can you please explain this part?
```
qkv_attention.get_output(0).dtype # I dont know why, but output type will not change without pre-checking the dtype, it will be fp32 by default in anyway
qkv_attention.get_output(0).dtype = trt.float16
```

If I will remove `qkv_attention.get_output(0).dtype` from the code, then `print("OUTPUT DTYPE:", output_dtype)` will print `float32` as an output type.

**Comment by zerollzeng** [comment]
@ttyio ^ ^

**Comment by alxmamaev** [comment]
@ttyio any updates?

**Comment by ttyio** [comment]
Hey @alxmamaev, for the `dtype` question. TensorRT need auto tune the kernels base on your problem size in each of the layers, and in the network build stage, we have not start auto tuning yet, so the query result is `FP32`, here it means it is a floating point, can be change to `FP16` or `INT8` based on your `builderConfig` and global auto tuning result.
