### ISSUE TITLE
couldn't install pytorch-quantization 

### ISSUE THREAD

**Issue by YellenYeason** [NVIDIA/TensorRT#3488]
## Description
**I couldn't install pytorch-quantization in my computer and I need your help!
when I git clone this code and use "pip install -v -e." for installing ,it returns:**

Using pip 23.3 from /home/yellen/miniconda3/envs/trtfx/lib/python3.9/site-packages/pip (python 3.9)
Looking in indexes: http://mirrors.aliyun.com/pypi/simple/, https://pypi.ngc.nvidia.com
Obtaining file:///home/yellen/run/proj/01-shouxieai-all/04-quant/TensorRT/tools/pytorch-quantization
  Running command python setup.py egg_info
  /home/yellen/miniconda3/envs/trtfx/lib/python3.9/site-packages/setuptools/__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
  !!
          ********************************************************************************
          Requirements should be satisfied by a PEP 517 installer.
          If you are using pip, you can try `pip install --use-pep517`.
          ********************************************************************************

  !!
    dist.fetch_build_eggs(dist.setup_requires)
  WARNING: The repository located at mirrors.aliyun.com is not a trusted or secure host and is being ignored. If this repository is available via HTTPS we recommend you use HTTPS instead, otherwise you may silence this warning and allow it anyway with '--trusted-host mirrors.aliyun.com'.
  ERROR: Could not find a version that satisfies the requirement pytest-runner (from versions: none)
  ERROR: No matching distribution found for pytest-runner
  Traceback (most recent call last):
    File "/home/yellen/miniconda3/envs/trtfx/lib/python3.9/site-packages/setuptools/installer.py", line 96, in _fetch_build_egg_no_warn
      subprocess.check_call(cmd)
    File "/home/yellen/miniconda3/envs/trtfx/lib/python3.9/subprocess.py", line 373, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/home/yellen/miniconda3/envs/trtfx/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpobilbn4e', '--quiet', 'pytest-runner']' returned non-zero exit status 1.
  The above exception was the direct cause of the following exception:
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "/home/yellen/run/proj/01-shouxieai-all/04-quant/TensorRT/tools/pytorch-quantization/setup.py", line 55, in <module>
      setup(
    File "/home/yellen/miniconda3/envs/trtfx/lib/python3.9/site-packages/setuptools/__init__.py", line 106, in setup
      _install_setup_requires(attrs)
    File "/home/yellen/miniconda3/envs/trtfx/lib/python3.9/site-packages/setuptools/__init__.py", line 79, in _install_setup_requires
      _fetch_build_eggs(dist)
    File "/home/yellen/miniconda3/envs/trtfx/lib/python3.9/site-packages/setuptools/__init__.py", line 84, in _fetch_build_eggs
      dist.fetch_build_eggs(dist.setup_requires)
    File "/home/yellen/miniconda3/envs/trtfx/lib/python3.9/site-packages/setuptools/dist.py", line 907, in fetch_build_eggs
      return _fetch_build_eggs(self, requires)
    File "/home/yellen/miniconda3/envs/trtfx/lib/python3.9/site-packages/setuptools/installer.py", line 38, in _fetch_build_eggs
      resolved_dists = pkg_resources.working_set.resolve(
    File "/home/yellen/miniconda3/envs/trtfx/lib/python3.9/site-packages/pkg_resources/__init__.py", line 829, in resolve
      dist = self._resolve_dist(
    File "/home/yellen/miniconda3/envs/trtfx/lib/python3.9/site-packages/pkg_resources/__init__.py", line 865, in _resolve_dist
      dist = best[req.key] = env.best_match(
    File "/home/yellen/miniconda3/envs/trtfx/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1135, in best_match
      return self.obtain(req, installer)
    File "/home/yellen/miniconda3/envs/trtfx/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1147, in obtain
      return installer(requirement)
    File "/home/yellen/miniconda3/envs/trtfx/lib/python3.9/site-packages/setuptools/installer.py", line 98, in _fetch_build_egg_no_warn
      raise DistutilsError(str(e)) from e
  distutils.errors.DistutilsError: Command '['/home/yellen/miniconda3/envs/trtfx/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpobilbn4e', '--quiet', 'pytest-runner']' returned non-zero exit status 1.
  error: subprocess-exited-with-error
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
 ╰─> See above for output. 
  This error originates from a subprocess, and is likely not a problem with pip.
  full command: /home/yellen/miniconda3/envs/trtfx/bin/python -c '
  exec(compile('"'"''"'"''"'"'
   This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
  
   - It imports setuptools before invoking setup.py, to enable projects that directly
   import from `distutils.core` to work with newer packaging standards.
   - It provides a clear error message when setuptools is not installed.
   - It sets `sys.argv[0]` to the underlying `setup.py`, when invoking `setup.py` so
    setuptools doesn'"'"'t think the script is `-c`. This avoids the following warning:
       manifest_maker: standard file '"'"'-c'"'"' not found".
   - It generates a shim setup.py, for handling setup.cfg-only projects.
  import os, sys, tokenize
  try:
      import setuptools
  except ImportError as error:
      print(
          "ERROR: Can not execute `setup.py` since setuptools is not available in "
          "the build environment.",
          file=sys.stderr,
      )
      sys.exit(1)
  
  __file__ = %r
  sys.argv[0] = __file__  
  if os.path.exists(__file__):
      filename = __file__
      with tokenize.open(__file__) as f:
          setup_py_code = f.read()
  else:
      filename = "<auto-generated setuptools caller>"
      setup_py_code = "from setuptools import setup; setup()"
  exec(compile(setup_py_code, filename, "exec"))
  '"'"''"'"''"'"' % ('"'"'/home/yellen/run/proj/01-shouxieai-all/04-quant/TensorRT/tools/pytorch-quantization/setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' egg_info --egg-base /tmp/pip-pip-egg-info-m0iea7lw
  cwd: /home/yellen/run/proj/01-shouxieai-all/04-quant/TensorRT/tools/pytorch-quantization/
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**when I  used "python set_up.py" for installing ,it returns:**

/home/yellen/miniconda3/envs/trtfx/lib/python3.9/site-packages/setuptools/__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
!!

        ********************************************************************************
        Requirements should be satisfied by a PEP 517 installer.
        If you are using pip, you can try `pip install --use-pep517`.
        ********************************************************************************

!!
  dist.fetch_build_eggs(dist.setup_requires)
WARNING: The repository located at mirrors.aliyun.com is not a trusted or secure host and is being ignored. If this repository is available via HTTPS we recommend you use HTTPS instead, otherwise you may silence this warning and allow it anyway with '--trusted-host mirrors.aliyun.com'.
ERROR: Could not find a version that satisfies the requirement pytest-runner (from versions: none)
ERROR: No matching distribution found for pytest-runner
Traceback (most recent call last):
  File "/home/yellen/miniconda3/envs/trtfx/lib/python3.9/site-packages/setuptools/installer.py", line 96, in _fetch_build_egg_no_warn
    subprocess.check_call(cmd)
  File "/home/yellen/miniconda3/envs/trtfx/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/yellen/miniconda3/envs/trtfx/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpeqxgniuy', '--quiet', 'pytest-runner']' returned non-zero exit status 1.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/yellen/run/proj/01-shouxieai-all/04-quant/TensorRT/tools/pytorch-quantization/setup.py", line 55, in <module>
    setup(
  File "/home/yellen/miniconda3/envs/trtfx/lib/python3.9/site-packages/setuptools/__init__.py", line 106, in setup
    _install_setup_requires(attrs)
  File "/home/yellen/miniconda3/envs/trtfx/lib/python3.9/site-packages/setuptools/__init__.py", line 79, in _install_setup_requires
    _fetch_build_eggs(dist)
  File "/home/yellen/miniconda3/envs/trtfx/lib/python3.9/site-packages/setuptools/__init__.py", line 84, in _fetch_build_eggs
    dist.fetch_build_eggs(dist.setup_requires)
  File "/home/yellen/miniconda3/envs/trtfx/lib/python3.9/site-packages/setuptools/dist.py", line 907, in fetch_build_eggs
    return _fetch_build_eggs(self, requires)
  File "/home/yellen/miniconda3/envs/trtfx/lib/python3.9/site-packages/setuptools/installer.py", line 38, in _fetch_build_eggs
    resolved_dists = pkg_resources.working_set.resolve(
  File "/home/yellen/miniconda3/envs/trtfx/lib/python3.9/site-packages/pkg_resources/__init__.py", line 829, in resolve
    dist = self._resolve_dist(
  File "/home/yellen/miniconda3/envs/trtfx/lib/python3.9/site-packages/pkg_resources/__init__.py", line 865, in _resolve_dist
    dist = best[req.key] = env.best_match(
  File "/home/yellen/miniconda3/envs/trtfx/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1135, in best_match
    return self.obtain(req, installer)
  File "/home/yellen/miniconda3/envs/trtfx/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1147, in obtain
    return installer(requirement)
  File "/home/yellen/miniconda3/envs/trtfx/lib/python3.9/site-packages/setuptools/installer.py", line 98, in _fetch_build_egg_no_warn
    raise DistutilsError(str(e)) from e
distutils.errors.DistutilsError: Command '['/home/yellen/miniconda3/envs/trtfx/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpeqxgniuy', '--quiet', 'pytest-runner']' returned non-zero exit status 1

**I changed the vision of torch(1.11/1.10) but the same situation occured.**

## Environment
absl-py                  2.0.0
appdirs                  1.4.4
certifi                  2023.11.17
charset-normalizer       3.3.2
contourpy                1.2.0
cycler                   0.12.1
exceptiongroup           1.2.0
filelock                 3.13.1
flatbuffers              23.5.26
fonttools                4.45.1
fsspec                   2023.10.0
gitdb                    4.0.11
GitPython                3.1.40
idna                     3.5
importlib-resources      6.1.1
iniconfig                2.0.0
Jinja2                   3.1.2
kiwisolver               1.4.5
Mako                     1.3.0
MarkupSafe               2.1.3
matplotlib               3.8.2
mpmath                   1.3.0
networkx                 3.2.1
numpy                    1.26.2
nvidia-cublas-cu12       12.1.3.1
nvidia-cuda-cupti-cu12   12.1.105
nvidia-cuda-nvrtc-cu12   12.1.105
nvidia-cuda-runtime-cu12 12.1.105
nvidia-cudnn-cu12        8.9.2.26
nvidia-cufft-cu12        11.0.2.54
nvidia-curand-cu12       10.3.2.106
nvidia-cusolver-cu12     11.4.5.107
nvidia-cusparse-cu12     12.1.0.106
nvidia-nccl-cu12         2.18.1
nvidia-nvjitlink-cu12    12.3.101
nvidia-nvtx-cu12         12.1.105
onnx                     1.15.0
onnx-graphsurgeon        0.3.27
onnxruntime              1.8.1
opencv-python            4.8.1.78
packaging                23.2
pandas                   2.1.3
Pillow                   10.1.0
pip                      23.3
platformdirs             4.0.0
pluggy                   1.3.0
prettytable              3.9.0
protobuf                 4.25.1
psutil                   5.9.6
py-cpuinfo               9.0.0
pycuda                   2023.1
pyparsing                3.1.1
pytest                   7.4.3
python-dateutil          2.8.2
pytools                  2023.1.1
pytz                     2023.3.post1
PyYAML                   6.0.1
requests                 2.31.0
scipy                    1.11.4
seaborn                  0.13.0
setuptools               68.0.0
six                      1.16.0
smmap                    5.0.1
sphinx-glpi-theme        0.4.1
sympy                    1.12
thop                     0.1.1.post2209072238
tomli                    2.0.1
torch                    2.1.1
torchvision              0.16.1
tqdm                     4.66.1
triton                   2.1.0
typing_extensions        4.8.0
tzdata                   2023.3
ultralytics              8.0.217
urllib3                  2.1.0
wcwidth                  0.2.12
wheel                    0.41.2
zipp                     3.17.0

ubuntu 20.04
python 3.9.0
**TensorRT Version**:8.5.3.1

**NVIDIA GPU**:3060

**NVIDIA Driver Version**:531.29

**CUDA Version**:11.8

**CUDNN Version**:8.6

**Comment by zerollzeng** [comment]
> ERROR: Could not find a version that satisfies the requirement pytest-runner (from versions: none)
> ERROR: No matching distribution found for pytest-runner

check this.

**Comment by YellenYeason** [comment]
Thanks for your help，I installed  pytest-runner and this issue has been solved.
