### ISSUE TITLE
`Could not find any implementation for node {ForeignNode[onnx::LayerNormalization...` when shape change happens with TensorRT 8.6.1.6

### ISSUE THREAD

**Issue by sunhs** [NVIDIA/TensorRT#3490]
## Description

I need to change the shape of a tensor during inference. When the new shape is computed by `torch.sqrt` and the new tensor is fed to `LayerNormalization`, I encounter the error:

```
[E] 10: Could not find any implementation for node {ForeignNode[onnx::LayerNormalization_28 + (Unnamed Layer* 34) [Shuffle]...(Unnamed Layer* 36) [Normalization]]}.
```

Here's the overview of different cases I've tried:

1. Change the tensor shape but not feed it to LayerNormalization  [OK]
2. Compute the new shape using constants or other dimensions of the shape, and feed the new tensor to LayerNormalization  [OK]
3. Compute the new shape using `sqrt` and feed the new tensor to LayerNormalization  [ERROR]

## Environment

**TensorRT Version**: 8.6.1.6
**NVIDIA GPU**: Tried `RTX 2080Ti`, `V100` and `RTX 4090`
**NVIDIA Driver Version**: Tried `455.45.01`, `460.91.03` and `535.104.05`, each corresponding to the GPUs above, respectively
**CUDA Version**: Tried `11.1`, `11.2` and `12.2`, each corresponding to the GPUs above, respectively
**Other**:
    polygraphy: 0.49.0
    onnx: 1.15.0

Operating System: Ubuntu 16.04 and Ubuntu 20.04

Python Version (if applicable): 3.10

PyTorch Version (if applicable): 2.1.0

Baremetal or Container (if so, version): Baremetal

## Minimum Reproduce Code

In the real case, I use `torch.nn.functional.interpolate` to change the tensor into a new shape. For simplicity, here I use index slicing.

```python
import os

import tensorrt as trt
import torch
from polygraphy.backend.trt import CreateConfig, Profile, engine_from_network, network_from_onnx_path, save_engine

# ==================================================
#                    user config
# ==================================================
root_out_dir = "./out"
os.makedirs(root_out_dir)
onnx_path = os.path.join(root_out_dir, "model.onnx")
engine_path = os.path.join(root_out_dir, "model.plan")

device = torch.device("cuda:0")
dtype = torch.half

batch_sizes = [1, 2, 2]
lens = [100, 200, 200]
dim = 320


class Model(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.norm = torch.nn.LayerNorm(dim)

    def forward(self, x):
        # Other cases I tried:
        # l = x.shape[1].to(dtype=torch.int64)  # OK
        # l = (x.shape[1] / 2).to(dtype=torch.int64)  # OK
        # l = (x.shape[1] / x.shape[0]).to(dtype=torch.int64)  # OK
        l = torch.sqrt(x.shape[1]).to(dtype=torch.int64)  # Error
        x = x[:, :l]
        return self.norm(x)

        # If no LayerNormalization is used, the script also works
        # return x


model = Model()
model.to(device=device, dtype=dtype)


# ==================================================
#                    export onnx
# ==================================================
dynamic_axes = {
    "x": {0: "B", 1: "L"},
    "output": {0: "B", 1: "L_SQRT"},
}


with torch.inference_mode(), torch.autocast("cuda"):
    x = torch.randn(batch_sizes[1], lens[1], dim).to(device, dtype)

    torch.onnx.export(
        model,
        (x),
        onnx_path,
        input_names=["x"],
        output_names=["output"],
        dynamic_axes=dynamic_axes,
        export_params=True,
        do_constant_folding=True,
        opset_version=18,
    )


# ==================================================
#                    build trt engine
# ==================================================
p = Profile()
p.add(
    "x",
    min=(batch_sizes[0], lens[0], dim),
    opt=(batch_sizes[1], lens[1], dim),
    max=(batch_sizes[2], lens[2], dim),
)
profiles = [p]
preview_features = [
    trt.PreviewFeature.DISABLE_EXTERNAL_TACTIC_SOURCES_FOR_CORE_0805,
    trt.PreviewFeature.FASTER_DYNAMIC_SHAPES_0805,
]

engine = engine_from_network(
    network_from_onnx_path(onnx_path, flags=[trt.OnnxParserFlag.NATIVE_INSTANCENORM]),
    config=CreateConfig(
        fp16=True,
        profiles=profiles,
        preview_features=preview_features,
        tactic_sources=[],
    ),
)
save_engine(engine, path=engine_path)
```

**Have you tried [the latest release](https://developer.nvidia.com/tensorrt)?**: I couldn't find the download link for version 9

**Can this model run on other frameworks?** For example run ONNX model with ONNXRuntime (`polygraphy run <model.onnx> --onnxrt`): Yes

## full log
[full_log.txt](https://github.com/NVIDIA/TensorRT/files/13466572/full_log.txt)

**Comment by sunhs** [comment]
> Could you please try the latest 9.1/9.2 release?

Sorry but where can I get it? I can't find it on [https://developer.nvidia.com/tensorrt-download](https://developer.nvidia.com/tensorrt-download)

**Comment by sunhs** [comment]
With 9.2.0.5, the error still occurs. Here's the log

```
[W] CUDA lazy loading is not enabled. Enabling it can significantly reduce device memory usage and speed up TensorRT initialization. See "Lazy Loading" section of CUDA documentation https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#lazy-loading
[I] Configuring with profiles:[
        Profile 0:
            {x [min=(1, 100, 320), opt=(2, 200, 320), max=(2, 200, 320)]}
    ]
[I] Building engine with configuration:
    Flags                  | [FP16]
    Engine Capability      | EngineCapability.DEFAULT
    Memory Pools           | [WORKSPACE: 11019.44 MiB, TACTIC_DRAM: 11019.44 MiB]
    Tactic Sources         | []
    Profiling Verbosity    | ProfilingVerbosity.DETAILED
    Preview Features       | [FASTER_DYNAMIC_SHAPES_0805, DISABLE_EXTERNAL_TACTIC_SOURCES_FOR_CORE_0805]
[E] 1: [cudaResources.cpp::haveStreamOrderedAllocatorHelper::67] Error Code 1: Cuda Runtime (invalid argument)
[E] 9: Skipping tactic 0x0000000000000000 due to exception TRT-15060 will add this functionality.
[E] 9: Skipping tactic 0x0000000000000000 due to exception TRT-15060 will add this functionality.
[E] 10: Could not find any implementation for node {ForeignNode[onnx::LayerNormalization_28 + ONNXTRT_Broadcast...(Unnamed Layer* 47) [Normalization]]}.
[E] 10: [optimizer.cpp::computeCosts::4048] Error Code 10: Internal Error (Could not find any implementation for node {ForeignNode[onnx::LayerNormalization_28 + ONNXTRT_Broadcast...(Unnamed Layer* 47) [Normalization]]}.)
[!] Invalid Engine. Please ensure the engine was built correctly
Traceback (most recent call last):
  File "test.py", line 86, in <module>
    engine = engine_from_network(
  File "<string>", line 3, in engine_from_network
  File "/opt/conda/envs/test/lib/python3.10/site-packages/polygraphy/backend/base/loader.py", line 40, in __call__
    return self.call_impl(*args, **kwargs)
  File "/opt/conda/envs/test/lib/python3.10/site-packages/polygraphy/util/util.py", line 710, in wrapped
    return func(*args, **kwargs)
  File "/opt/conda/envs/test/lib/python3.10/site-packages/polygraphy/backend/trt/loader.py", line 604, in call_impl
    return engine_from_bytes(super().call_impl, runtime=self._runtime)
  File "<string>", line 3, in engine_from_bytes
  File "/opt/conda/envs/test/lib/python3.10/site-packages/polygraphy/backend/base/loader.py", line 40, in __call__
    return self.call_impl(*args, **kwargs)
  File "/opt/conda/envs/test/lib/python3.10/site-packages/polygraphy/util/util.py", line 710, in wrapped
    return func(*args, **kwargs)
  File "/opt/conda/envs/test/lib/python3.10/site-packages/polygraphy/backend/trt/loader.py", line 633, in call_impl
    buffer, _ = util.invoke_if_callable(self._serialized_engine)
  File "/opt/conda/envs/test/lib/python3.10/site-packages/polygraphy/util/util.py", line 678, in invoke_if_callable
    ret = func(*args, **kwargs)
  File "/opt/conda/envs/test/lib/python3.10/site-packages/polygraphy/util/util.py", line 710, in wrapped
    return func(*args, **kwargs)
  File "/opt/conda/envs/test/lib/python3.10/site-packages/polygraphy/backend/trt/loader.py", line 537, in call_impl
    G_LOGGER.critical("Invalid Engine. Please ensure the engine was built correctly")
  File "/opt/conda/envs/test/lib/python3.10/site-packages/polygraphy/logger/logger.py", line 605, in critical
    raise ExceptionType(message) from None
polygraphy.exception.exception.PolygraphyException: Invalid Engine. Please ensure the engine was built correctly
```

**Comment by zerollzeng** [comment]
I can reproduce and file internal bug 4433622 to track

**Comment by zerollzeng** [comment]
Fixed in TRT 10, close this issue.

**Comment by yflv-yanxia** [comment]
I tested using the latest TRT 10.5 on an A6000 GPU on another machine, and the results were correct. 
However, when using the latest TRT 10.5 tool, trtexec, to convert the ONNX model on this machine's T4 GPU, the following error occurred. Could you help me figure out what the issue might be?![Image](https://github.com/user-attachments/assets/bc7aeebe-d183-44fc-b5d8-cde966be4d07)
