### ISSUE TITLE
pytorch_quantization error - undefined symbol in `pytorch_quantization.cuda_ext`

### ISSUE THREAD

**Issue by talcs** [NVIDIA/TensorRT#3497]
## Description

Working in Pytorch with pytorch_quantization.
`pytorch_quantization` has been installed by running: `pip install --no-cache-dir --extra-index-url https://pypi.nvidia.com pytorch-quantization`.

I'm getting this error:

```
>>> from pytorch_quantization import cuda_ext
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/smart/.local/lib/python3.10/site-packages/pytorch_quantization/__init__.py", line 20, in <module>
    from .quant_modules import *
  File "/home/smart/.local/lib/python3.10/site-packages/pytorch_quantization/quant_modules.py", line 23, in <module>
    from pytorch_quantization import nn as quant_nn
  File "/home/smart/.local/lib/python3.10/site-packages/pytorch_quantization/nn/__init__.py", line 19, in <module>
    from pytorch_quantization.nn.modules.tensor_quantizer import *
  File "/home/smart/.local/lib/python3.10/site-packages/pytorch_quantization/nn/modules/tensor_quantizer.py", line 24, in <module>
    from pytorch_quantization.tensor_quant import QuantDescriptor, tensor_quant, fake_tensor_quant, scaled_e4m3
  File "/home/smart/.local/lib/python3.10/site-packages/pytorch_quantization/tensor_quant.py", line 28, in <module>
    from pytorch_quantization import cuda_ext
ImportError: /home/smart/.local/lib/python3.10/site-packages/pytorch_quantization/cuda_ext.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZNK3c107SymBool10guard_boolEPKcl
```

## Environment

Operating system: `Ubuntu 22.04.3 LTS - server version`
Python version: `Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux`
PyTorch version: `torch  1.12.1+cu116`
pytorch_quantization version: `pytorch-quantization   2.2.1`

NVIDIA driver version: `535.129.03`
CUDA version: `12.3`

Originally, the error was regarding missing shared object `libcudart.so.12`. Then, I installed CUDA 12. Now it is the error listed above.

**Comment by talcs** [comment]
When upgrading to `torch 2.11+cu121`, still getting a similar error, but different symbols...

```
>>> from pytorch_quantization import cuda_ext
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/smart/venvs/torch2/lib/python3.10/site-packages/pytorch_quantization/__init__.py", line 20, in <module>
    from .quant_modules import *
  File "/home/smart/venvs/torch2/lib/python3.10/site-packages/pytorch_quantization/quant_modules.py", line 23, in <module>
    from pytorch_quantization import nn as quant_nn
  File "/home/smart/venvs/torch2/lib/python3.10/site-packages/pytorch_quantization/nn/__init__.py", line 19, in <module>
    from pytorch_quantization.nn.modules.tensor_quantizer import *
  File "/home/smart/venvs/torch2/lib/python3.10/site-packages/pytorch_quantization/nn/modules/tensor_quantizer.py", line 24, in <module>
    from pytorch_quantization.tensor_quant import QuantDescriptor, tensor_quant, fake_tensor_quant, scaled_e4m3
  File "/home/smart/venvs/torch2/lib/python3.10/site-packages/pytorch_quantization/tensor_quant.py", line 28, in <module>
    from pytorch_quantization import cuda_ext
ImportError: /home/smart/venvs/torch2/lib/python3.10/site-packages/pytorch_quantization/cuda_ext.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c106detail14torchCheckFailEPKcS2_jRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
```

**Comment by ttyio** [comment]
Hmmm, the error show this is ABI issue, will need  `-D_GLIBCXX_USE_CXX11_ABI=0` when build the code, created internal issue, and will update here, thanks!

**Comment by JWHer** [comment]
I had the same problem.

My two cents, I don't know your exact settings but I'm working with pytorch_quantization with [install from source](https://github.com/NVIDIA/TensorRT/tree/release/8.6/tools/pytorch-quantization#from-source).

> #### From Source
> 
> ```bash
> git clone https://github.com/NVIDIA/TensorRT.git
> cd tools/pytorch-quantization
> ```
> 
> Install PyTorch and prerequisites
> ```bash
> pip install -r requirements.txt
> # for CUDA 10.2 users
> pip install torch>=1.9.1
> # for CUDA 11.1 users
> pip install torch>=1.9.1+cu111
> ```
> 
> Build and install pytorch-quantization
> ```bash
> # Python version >= 3.7, GCC version >= 5.4 required
> python setup.py install
> ```

or may use `nvcr.io/nvidia/pytorch:22.12-py3` will help
