### ISSUE TITLE
Segmentation fault of TensorRT 8.5.3 when running nvinfer1::createInferBuilder on GPU: DRIVE AGX ORIN

### ISSUE THREAD

**Issue by Wuqiqi123** [NVIDIA/TensorRT#3507]
## Description

On NVIDIA DRIVE AGX ORIN, I update apt source by https://developer.nvidia.com/blog/updating-the-cuda-linux-gpg-repository-key and then I donwload cuda and tensorrt by apt-get install

```bash
sudo apt-get install cuda-toolkit-11-8 libcudnn8=8.8.0.121-1+cuda11.8 libnvinfer8=8.5.3-1+cuda11.8 libnvinfer-plugin8=8.5.3-1+cuda11.8 libnvonnxparsers8=8.5.3-1+cuda11.8libnvparsers8=8.5.3-1+cuda11.8
```

## Environment

**TensorRT Version**:  8.5.3-1+cuda11.8

**NVIDIA GPU**: DRIVE AGX ORIN
```
lspci | grep -i nvidia
0000:17:00.0 VGA compatible controller: NVIDIA Corporation Device 2504 (rev a1)
0000:17:00.1 Audio device: NVIDIA Corporation Device 228e (rev a1)

```

**NVIDIA Driver Version**: 
```
cat /proc/driver/nvidia/version
NVRM version: NVIDIA UNIX x86_64 Kernel Module  535.86.10  Wed Jul 26 23:20:03 UTC 2023
GCC version:  gcc version 11.4.0 (Ubuntu 11.4.0-2ubuntu1~20.04) 
```
**CUDA Version**:
```
vcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:43:33_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
```

**CUDNN Version**: 8.8.0.121-1+cuda11.8

Operating System: 
```
uname -a
Linux tegra-ubuntu 5.10.120-rt70-tegra #1 SMP PREEMPT RT Thu Oct 20 18:31:36 PDT 2022 aarch64 aarch64 aarch64 GNU/Linux
```

The program crash on the orin, **but works fine on my PC with same code**.
The call stack is: 
```
Reading symbols from tests/test_trt_engine...
Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/aarch64-linux-gnu/libthread_db.so.1".
[New Thread 0xffffb3fe5900 (LWP 120320)]
[New Thread 0xffffb33d4900 (LWP 120321)]
[New Thread 0xffffb2bd3900 (LWP 120322)]
[New Thread 0xffffb1fc2900 (LWP 120323)]
[==========] Running 2 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 2 tests from porting_master
[ RUN      ] porting_master.trt_backend_load_onnx
[New Thread 0xffffb0e96900 (LWP 120324)]

Thread 1 "test_trt_engine" received signal SIGSEGV, Segmentation fault.
__strlen_generic () at ../sysdeps/aarch64/multiarch/../strlen.S:98
98	../sysdeps/aarch64/multiarch/../strlen.S: No such file or directory.
(gdb) bt
#0  __strlen_generic () at ../sysdeps/aarch64/multiarch/../strlen.S:98
#1  0x0000fffff5e0f05c in ?? () from /lib/aarch64-linux-gnu/libgcc_s.so.1
#2  0x0000fffff5e0faa8 in ?? () from /lib/aarch64-linux-gnu/libgcc_s.so.1
#3  0x0000fffff5e10704 in _Unwind_Find_FDE () from /lib/aarch64-linux-gnu/libgcc_s.so.1
#4  0x0000fffff5e0c510 in ?? () from /lib/aarch64-linux-gnu/libgcc_s.so.1
#5  0x0000fffff5e0dd20 in _Unwind_RaiseException () from /lib/aarch64-linux-gnu/libgcc_s.so.1
#6  0x0000fffff5f79d48 in __cxa_throw () from /lib/aarch64-linux-gnu/libstdc++.so.6
#7  0x0000ffffe19f3a20 in ?? () from /lib/aarch64-linux-gnu/libnvinfer.so.8
#8  0x0000ffffe1a02d64 in ?? () from /lib/aarch64-linux-gnu/libnvinfer.so.8
#9  0x0000ffffe199b290 in ?? () from /lib/aarch64-linux-gnu/libnvinfer.so.8
#10 0x0000ffffe19a84b8 in createInferBuilder_INTERNAL () from /lib/aarch64-linux-gnu/libnvinfer.so.8
#11 0x0000fffff7b75710 in nvinfer1::(anonymous namespace)::createInferBuilder (logger=...)
    at /usr/include/aarch64-linux-gnu/NvInfer.h:9093
#12 0x0000fffff7b7757c in pm::TensorRTBackend::CreateTrtEngineFromOnnx (this=0xaaaaabbb5520, 
    onnx_model_buffer="\b\a\022\004CNTK\032\005\062.5.1\"\aai.cntk(\001:\373\313\001\n\253\001\n\006Input3\n\nParameter5\022\026Convolution28_Output_0\032\rConvolution28\"\004Conv*\025\n\fkernel_shape@\005@\005\240\001\a*\020\n\astrides@\001@\001\240\001\a*\031\n\bauto_pad\"\nSAME_UPPER\240\001\003*\f\n\005group\030\001\240\001\002*\022\n\tdilations@\001@\001\240\001\a"...)

```

By the way, I try almost all tensorrt's versions on orin(apt-get only), but none of them works. Low version of tensorrt < 8.5 won't crash but the program is stuck forever.

**Comment by zerollzeng** [comment]
For Drive, you need to use DriveOS compatible TensorRT, you should install it via deb, e.g. for 8.5, the Drive version TRT should be 8.5.10.

**Comment by zerollzeng** [comment]
Check https://developer.nvidia.com/drive/os

**Comment by Wuqiqi123** [comment]
Thanks, reinstall the [drive/os](https://developer.nvidia.com/drive/os) solve this issue.
The tensorrt aarch64 version from https://developer.nvidia.com/nvidia-tensorrt-8x-download may not works.
