### ISSUE TITLE
XXX failure of TensorRT X.Y when running XXX on GPU XXX

### ISSUE THREAD

**Issue by yanqzhao** [NVIDIA/TensorRT#3585]
## Description
what's the "LayerType": "TrainStation" is ?

when i use the [trt-engine-explorer], I get the following error: 

>>> plan = EnginePlan(f'{PATH}/graph.json', f'{PATH}/profile.json')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/disk_1/zyq/work/TensorRT/tools/experimental/trt-engine-explorer/trex/engine_plan.py", line 127, in __init__
    graph_df = construct_df(raw_layers)
  File "/home/disk_1/zyq/work/TensorRT/tools/experimental/trt-engine-explorer/trex/engine_plan.py", line 106, in construct_df
    graph_df = fix_df(graph_df)
  File "/home/disk_1/zyq/work/TensorRT/tools/experimental/trt-engine-explorer/trex/df_preprocessing.py", line 176, in fix_df
    __fix_output_precision(df)
  File "/home/disk_1/zyq/work/TensorRT/tools/experimental/trt-engine-explorer/trex/df_preprocessing.py", line 164, in __fix_output_precision
    df['output_precision'] = [Activation(outputs[1]).precision for outputs in df['Outputs']]
  File "/home/disk_1/zyq/work/TensorRT/tools/experimental/trt-engine-explorer/trex/df_preprocessing.py", line 164, in <listcomp>
    df['output_precision'] = [Activation(outputs[1]).precision for outputs in df['Outputs']]
IndexError: list index out of range

I think this may be caused by the TrainStation layer, since in my graph.json,there is a layer like this:

"Layers": [{
  "Name": "[trainStation1]",
  "LayerType": "TrainStation",
  "Inputs": [],
  "Outputs": [],
  "TacticValue": "0x0000000000000000",
  "StreamId": 0,
  "Metadata": ""
}

## Environment

**TensorRT Version**: 8.6

**NVIDIA GPU**: 3090

**NVIDIA Driver Version**: 525.105.17 

**CUDA Version**: 11.6

**CUDNN Version**: 8.9.2.26_cuda11

Operating System: ubuntu 18.04

Python Version (if applicable): 3.9.18

Tensorflow Version (if applicable):

PyTorch Version (if applicable): 

Baremetal or Container (if so, version): 

## Relevant Files

**Model link**:

## Steps To Reproduce

**Commands or scripts**:

**Have you tried [the latest release](https://developer.nvidia.com/tensorrt)?**:

**Can this model run on other frameworks?** For example run ONNX model with ONNXRuntime (`polygraphy run <model.onnx> --onnxrt`):

**Comment by nzmora-nvidia** [comment]
@yanqzhao can you share your model?

**Comment by nzmora-nvidia** [comment]
@slimwangyue your error is different and it will be better addressed in a new ticket.
A TrainStation layer is not an ONNX operator but an internal TensorRT engine layer that manages data-dependent shapes device memory allocation. TrainStation layers synchronize the stream they are invoked from.
