### ISSUE TITLE
TensorRT Polygraphy issue when running comparison between TensorRT and ONNX models

### ISSUE THREAD

**Issue by david-PHR** [NVIDIA/TensorRT#3670]
## Description
Is there any way to execute polygraphy to compare an ONNX and TensorRT model with mark-outputs all for models producing Tensor bigger than 2GB? Maybe an CLI argument when I execute `polygraphy run` command? 
The command :
`polygraphy run tmp_dir/MyModel.onnx --trt --onnxrt --atol 0.001 --rtol 0.001 --trt-outputs mark all --no-save-all-tensors-to-one-file --save-external-data tmp_dir/ --onnx-outputs mark all --verbose --trt-min-shapes input_0:[1,4,16,16] input_1:[1,4,16,16] input_2:[1,1,16,16] input_3:[1,3,128,128] input_4:[1,1,128,128]  --trt-opt-shapes input_0:[1,4,16,16] input_1:[1,4,16,16] input_2:[1,1,16,16] input_3:[1,3,128,128] input_4:[1,1,128,128] --pool-limit workspace:20G`

Produce this issue:
```
[V] Loaded Module: onnx | Version: 1.14.0 | Path: ['/usr/local/lib/python3.10/dist-packages/onnx']
[V] Marking all ONNX tensors as outputs
Traceback (most recent call last):
  File "/usr/local/bin/polygraphy", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/polygraphy/tools/_main.py", line 70, in main
    status = selected_tool.run(args)
  File "/usr/local/lib/python3.10/dist-packages/polygraphy/tools/base/tool.py", line 171, in run
    status = self.run_impl(args)
  File "/usr/local/lib/python3.10/dist-packages/polygraphy/tools/run/run.py", line 224, in run_impl
    exec(str(script))
  File "<string>", line 38, in <module>
  File "/usr/local/lib/python3.10/dist-packages/polygraphy/comparator/comparator.py", line 213, in run
    run_results.append((runner.name, execute_runner(runner, loader_cache)))
  File "/usr/local/lib/python3.10/dist-packages/polygraphy/comparator/comparator.py", line 98, in execute_runner
    with runner as active_runner:
  File "/usr/local/lib/python3.10/dist-packages/polygraphy/backend/base/runner.py", line 60, in __enter__
    self.activate()
  File "/usr/local/lib/python3.10/dist-packages/polygraphy/backend/base/runner.py", line 95, in activate
    self.activate_impl()
  File "/usr/local/lib/python3.10/dist-packages/polygraphy/backend/onnxrt/runner.py", line 43, in activate_impl
    self.sess, _ = util.invoke_if_callable(self._sess)
  File "/usr/local/lib/python3.10/dist-packages/polygraphy/util/util.py", line 661, in invoke_if_callable
    ret = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/polygraphy/backend/base/loader.py", line 42, in __call__
    return self.call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/polygraphy/backend/onnxrt/loader.py", line 54, in call_impl
    model_bytes, _ = util.invoke_if_callable(self._model_bytes_or_path)
  File "/usr/local/lib/python3.10/dist-packages/polygraphy/util/util.py", line 661, in invoke_if_callable
    ret = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/polygraphy/backend/base/loader.py", line 42, in __call__
    return self.call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/polygraphy/backend/onnx/loader.py", line 762, in call_impl
    return model.SerializeToString()
ValueError: Message onnx.ModelProto exceeds maximum protobuf size of 2GB: 3269846977
```

**Comment by zerollzeng** [comment]
Check https://github.com/microsoft/onnxruntime/issues/15349

**Comment by zerollzeng** [comment]
> --trt-outputs mark all

mark all is not a good practice, it will break all layer fusion, I guess you are trying to debug an accuracy drop, I would suggest using bisect technique.

**Comment by david-PHR** [comment]
Thanks for the answer. I've already checked the link you shared but I still have the issue when running inference comparison for` --onnx-outputs mark all`. Without specifying ` --onnx-outputs mark all` it works but the information is not helping me in solving the accuracy loss.

I've found how to bypass the accuracy loss issue by forcing dynamic batch size at compile time with TensorRT. 
It seems to be a broadcasting issue when the model is compiled for batchsize=1. 
The `torchscript` and `ONNX` models produce correct results at runtime for batchsize=1.
The TensorRT model doesn't produce correct results when compiling with a static batch-size of 1. However, when I compile the model for a dynamic batch-size range up to 2, the results are correct when executing for batchsize=1. I guess it is a broadcasting issue on TensorRT but I cannot figure out how to debug this easily. I would like to find the defective operator automatically. 
 
The model memory footprint is bigger than expected as I am forcing a batch-size support range of up to 2.

Do you have any idea on how to debug this kind of issue with Polygraphy without using` --onnx-outputs mark all`?

**Comment by zerollzeng** [comment]
> The TensorRT model doesn't produce correct results when compiling with a static batch-size of 1

Do you mean the onnx model has static shape input of batch size 1 but TRT didn't produce correct result? this looks like a bug, could you please provide a reproduce?

**Comment by david-PHR** [comment]
The issue is solved by rewriting a bit the Torch code. TensorRT seems to fail to broadcast the correct dimension sometimes
