### ISSUE TITLE
ERROR: Could not build wheels for tensorrt, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by KaifAhmad1** [NVIDIA/TensorRT#3685]
## Description

Getting this error '''

```
Collecting tensorrt
  Using cached tensorrt-8.6.1.post1.tar.gz (18 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: tensorrt
  Building wheel for tensorrt (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [91 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib
      creating build\lib\tensorrt
      copying tensorrt\__init__.py -> build\lib\tensorrt
      running egg_info
      writing tensorrt.egg-info\PKG-INFO
      writing dependency_links to tensorrt.egg-info\dependency_links.txt
      writing requirements to tensorrt.egg-info\requires.txt
      writing top-level names to tensorrt.egg-info\top_level.txt
      reading manifest file 'tensorrt.egg-info\SOURCES.txt'
      adding license file 'LICENSE.txt'
      writing manifest file 'tensorrt.egg-info\SOURCES.txt'
      C:\Users\Mohd Kaif\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      --- Logging error ---
      Traceback (most recent call last):
        File "C:\Users\Mohd Kaif\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 1103, in emit
          stream.write(msg + self.terminator)
      ValueError: underlying buffer has been detached
      Call stack:
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Mohd Kaif\AppData\Local\Temp\pip-install-lipyfz_c\tensorrt_d789779f2efa4eff90634466b11d75f1\setup.py", line 110, in <module>
          setup(
        File "C:\Users\Mohd Kaif\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\Mohd Kaif\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "C:\Users\Mohd Kaif\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\Mohd Kaif\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "C:\Users\Mohd Kaif\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\Users\Mohd Kaif\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
        File "C:\Users\Mohd Kaif\AppData\Local\Programs\Python\Python310\lib\site-packages\wheel\bdist_wheel.py", line 401, in run
          log.info(f"installing to {self.bdist_dir}")
      Message: 'installing to build\\bdist.win-amd64\\wheel'
      Arguments: ()
      running install
      Looking in indexes: https://pypi.org/simple, https://pypi.nvidia.com
      ERROR: Could not find a version that satisfies the requirement tensorrt_libs==8.6.1 (from versions: 9.0.0.post11.dev1, 9.0.0.post12.dev1, 9.0.1.post11.dev4, 9.0.1.post12.dev4, 9.1.0.post11.dev4, 9.1.0.post12.dev4, 9.2.0.post11.dev5, 9.2.0.post12.dev5, 9.3.0.post11.dev1, 9.3.0.post12.dev1)
      ERROR: No matching distribution found for tensorrt_libs==8.6.1
      Looking in indexes: https://pypi.org/simple, https://pypi.nvidia.com
      ERROR: Could not find a version that satisfies the requirement tensorrt_libs==8.6.1 (from versions: 9.0.0.post11.dev1, 9.0.0.post12.dev1, 9.0.1.post11.dev4, 9.0.1.post12.dev4, 9.1.0.post11.dev4, 9.1.0.post12.dev4, 9.2.0.post11.dev5, 9.2.0.post12.dev5, 9.3.0.post11.dev1, 9.3.0.post12.dev1)
      ERROR: No matching distribution found for tensorrt_libs==8.6.1
      Traceback (most recent call last):
        File "C:\Users\Mohd Kaif\AppData\Local\Temp\pip-install-lipyfz_c\tensorrt_d789779f2efa4eff90634466b11d75f1\setup.py", line 40, in run_pip_command
          return call_func([sys.executable, "-m", "pip"] + args, env=env)
        File "C:\Users\Mohd Kaif\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['C:\\Users\\Mohd Kaif\\AppData\\Local\\Programs\\Python\\Python310\\python.exe', '-m', 'pip', 'install', '--extra-index-url', 'https://pypi.nvidia.com', 'tensorrt_libs==8.6.1', 'tensorrt_bindings==8.6.1']' returned non-zero exit status 1.

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Mohd Kaif\AppData\Local\Temp\pip-install-lipyfz_c\tensorrt_d789779f2efa4eff90634466b11d75f1\setup.py", line 110, in <module>
          setup(
        File "C:\Users\Mohd Kaif\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\Mohd Kaif\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "C:\Users\Mohd Kaif\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\Mohd Kaif\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "C:\Users\Mohd Kaif\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\Users\Mohd Kaif\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
        File "C:\Users\Mohd Kaif\AppData\Local\Programs\Python\Python310\lib\site-packages\wheel\bdist_wheel.py", line 403, in run
          self.run_command("install")
        File "C:\Users\Mohd Kaif\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "C:\Users\Mohd Kaif\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\Users\Mohd Kaif\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
        File "C:\Users\Mohd Kaif\AppData\Local\Temp\pip-install-lipyfz_c\tensorrt_d789779f2efa4eff90634466b11d75f1\setup.py", line 62, in run
          run_pip_command(
        File "C:\Users\Mohd Kaif\AppData\Local\Temp\pip-install-lipyfz_c\tensorrt_d789779f2efa4eff90634466b11d75f1\setup.py", line 56, in run_pip_command
          return call_func([pip_path] + args, env=env)
        File "C:\Users\Mohd Kaif\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['C:\\Users\\Mohd Kaif\\AppData\\Local\\Programs\\Python\\Python310\\Scripts\\pip.exe', 'install', '--extra-index-url', 'https://pypi.nvidia.com', 'tensorrt_libs==8.6.1', 'tensorrt_bindings==8.6.1']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for tensorrt
  Running setup.py clean for tensorrt
Failed to build tensorrt
ERROR: Could not build wheels for tensorrt, which is required to install pyproject.toml-based projects

```
## Environment

**NVIDIA GPU**:  NVIDIA GeForce MX330

**CUDA Version**: 12.1

Operating System:

Python Version (if applicable): 3.10.10

Tensorflow Version (if applicable): 2.15.0

PyTorch Version (if applicable): 2.1.2

**Comment by RajUpadhyay** [comment]
TensorRT Installation can be excrutiating but if you read the documentation, you'll find something I guess.
I am unsure if pip installation can be done on a Windows OS.

I would recommend you to use a Nvidia L4T container (either pytorch one or deepstream one) which already has Tensorrt pre-installed.

If you would like to install TensorRT directly on your host PC then (Windows machine), then [zip file installation](https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html#:~:text=The%20zip%20file%20is%20the%20only%20option%20currently%20for%20Windows.) is been suggested in the documentation.

**Comment by zerollzeng** [comment]
I believe we don't support install the python binding with pip on windows. @pranavm-nvidia not sure if we support it today.

**Comment by ttyio** [comment]
Yes we recommend the zip file installation on Windows, I will close this since there is already answer, thanks all!
