### ISSUE TITLE
tensorrt not working 

### ISSUE THREAD

**Issue by Rinox89** [NVIDIA/TensorRT#3694]
## Description

#Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: v1.8.0-72-g45b8a499
Commit hash: 45b8a499a7e6d732b1711a0016c211f2b3c19232
*** Error running install.py for extension C:\Data\Packages\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT.
*** Command: "C:\Data\Packages\stable-diffusion-webui\venv\Scripts\python.exe" "C:\Data\Packages\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\install.py"
*** Error code: 1
*** stdout: Traceback (most recent call last):
***   File "C:\Data\Packages\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\install.py", line 3, in <module>
***     from importlib_metadata import version
*** ModuleNotFoundError: No module named 'importlib_metadata'
Launching Web UI with arguments: --xformers --api
reading metadata for C:\Data\Packages\stable-diffusion-webui\models\Stable-diffusion\dreamshaper_8LCM.safetensors: AssertionError
Traceback (most recent call last):
  File "C:\Data\Packages\stable-diffusion-webui\modules\sd_models.py", line 76, in __init__
    self.metadata = cache.cached_data_for_file('safetensors-metadata', "checkpoint/" + name, filename, read_metadata)
  File "C:\Data\Packages\stable-diffusion-webui\modules\cache.py", line 114, in cached_data_for_file
    value = func()
  File "C:\Data\Packages\stable-diffusion-webui\modules\sd_models.py", line 68, in read_metadata
    metadata = read_metadata_from_safetensors(filename)
  File "C:\Data\Packages\stable-diffusion-webui\modules\sd_models.py", line 283, in read_metadata_from_safetensors
    assert metadata_len > 2 and json_start in (b'{"', b"{'"), f"{filename} is not a safetensors file"
AssertionError: C:\Data\Packages\stable-diffusion-webui\models\Stable-diffusion\dreamshaper_8LCM.safetensors is not a safetensors file

reading metadata for C:\Data\Packages\stable-diffusion-webui\models\Stable-diffusion\maturemalemix_v14.safetensors: AssertionError
Traceback (most recent call last):
  File "C:\Data\Packages\stable-diffusion-webui\modules\sd_models.py", line 76, in __init__
    self.metadata = cache.cached_data_for_file('safetensors-metadata', "checkpoint/" + name, filename, read_metadata)
  File "C:\Data\Packages\stable-diffusion-webui\modules\cache.py", line 114, in cached_data_for_file
    value = func()
  File "C:\Data\Packages\stable-diffusion-webui\modules\sd_models.py", line 68, in read_metadata
    metadata = read_metadata_from_safetensors(filename)
  File "C:\Data\Packages\stable-diffusion-webui\modules\sd_models.py", line 283, in read_metadata_from_safetensors
    assert metadata_len > 2 and json_start in (b'{"', b"{'"), f"{filename} is not a safetensors file"
AssertionError: C:\Data\Packages\stable-diffusion-webui\models\Stable-diffusion\maturemalemix_v14.safetensors is not a safetensors file

reading metadata for C:\Data\Packages\stable-diffusion-webui\models\Stable-diffusion\toonyou_beta6.safetensors: AssertionError
Traceback (most recent call last):
  File "C:\Data\Packages\stable-diffusion-webui\modules\sd_models.py", line 76, in __init__
    self.metadata = cache.cached_data_for_file('safetensors-metadata', "checkpoint/" + name, filename, read_metadata)
  File "C:\Data\Packages\stable-diffusion-webui\modules\cache.py", line 114, in cached_data_for_file
    value = func()
  File "C:\Data\Packages\stable-diffusion-webui\modules\sd_models.py", line 68, in read_metadata
    metadata = read_metadata_from_safetensors(filename)
  File "C:\Data\Packages\stable-diffusion-webui\modules\sd_models.py", line 283, in read_metadata_from_safetensors
    assert metadata_len > 2 and json_start in (b'{"', b"{'"), f"{filename} is not a safetensors file"
AssertionError: C:\Data\Packages\stable-diffusion-webui\models\Stable-diffusion\toonyou_beta6.safetensors is not a safetensors file

reading lora C:\Data\Packages\stable-diffusion-webui\models\Lora\add_detail.safetensors: AssertionError
Traceback (most recent call last):
  File "C:\Data\Packages\stable-diffusion-webui\extensions-builtin\Lora\network.py", line 38, in __init__
    self.metadata = cache.cached_data_for_file('safetensors-metadata', "lora/" + self.name, filename, read_metadata)
  File "C:\Data\Packages\stable-diffusion-webui\modules\cache.py", line 114, in cached_data_for_file
    value = func()
  File "C:\Data\Packages\stable-diffusion-webui\extensions-builtin\Lora\network.py", line 31, in read_metadata
    metadata = sd_models.read_metadata_from_safetensors(filename)
  File "C:\Data\Packages\stable-diffusion-webui\modules\sd_models.py", line 283, in read_metadata_from_safetensors
    assert metadata_len > 2 and json_start in (b'{"', b"{'"), f"{filename} is not a safetensors file"
AssertionError: C:\Data\Packages\stable-diffusion-webui\models\Lora\add_detail.safetensors is not a safetensors file

reading lora C:\Data\Packages\stable-diffusion-webui\models\Lora\andrewtate2.safetensors: AssertionError
Traceback (most recent call last):
  File "C:\Data\Packages\stable-diffusion-webui\extensions-builtin\Lora\network.py", line 38, in __init__
    self.metadata = cache.cached_data_for_file('safetensors-metadata', "lora/" + self.name, filename, read_metadata)
  File "C:\Data\Packages\stable-diffusion-webui\modules\cache.py", line 114, in cached_data_for_file
    value = func()
  File "C:\Data\Packages\stable-diffusion-webui\extensions-builtin\Lora\network.py", line 31, in read_metadata
    metadata = sd_models.read_metadata_from_safetensors(filename)
  File "C:\Data\Packages\stable-diffusion-webui\modules\sd_models.py", line 283, in read_metadata_from_safetensors
    assert metadata_len > 2 and json_start in (b'{"', b"{'"), f"{filename} is not a safetensors file"
AssertionError: C:\Data\Packages\stable-diffusion-webui\models\Lora\andrewtate2.safetensors is not a safetensors file

reading lora C:\Data\Packages\stable-diffusion-webui\models\Lora\EdobDrugs_v1.0.safetensors: AssertionError
Traceback (most recent call last):
  File "C:\Data\Packages\stable-diffusion-webui\extensions-builtin\Lora\network.py", line 38, in __init__
    self.metadata = cache.cached_data_for_file('safetensors-metadata', "lora/" + self.name, filename, read_metadata)
  File "C:\Data\Packages\stable-diffusion-webui\modules\cache.py", line 114, in cached_data_for_file
    value = func()
  File "C:\Data\Packages\stable-diffusion-webui\extensions-builtin\Lora\network.py", line 31, in read_metadata
    metadata = sd_models.read_metadata_from_safetensors(filename)
  File "C:\Data\Packages\stable-diffusion-webui\modules\sd_models.py", line 283, in read_metadata_from_safetensors
    assert metadata_len > 2 and json_start in (b'{"', b"{'"), f"{filename} is not a safetensors file"
AssertionError: C:\Data\Packages\stable-diffusion-webui\models\Lora\EdobDrugs_v1.0.safetensors is not a safetensors file

reading lora C:\Data\Packages\stable-diffusion-webui\models\Lora\Ferrari 296.safetensors: AssertionError
Traceback (most recent call last):
  File "C:\Data\Packages\stable-diffusion-webui\extensions-builtin\Lora\network.py", line 38, in __init__
    self.metadata = cache.cached_data_for_file('safetensors-metadata', "lora/" + self.name, filename, read_metadata)
  File "C:\Data\Packages\stable-diffusion-webui\modules\cache.py", line 114, in cached_data_for_file
    value = func()
  File "C:\Data\Packages\stable-diffusion-webui\extensions-builtin\Lora\network.py", line 31, in read_metadata
    metadata = sd_models.read_metadata_from_safetensors(filename)
  File "C:\Data\Packages\stable-diffusion-webui\modules\sd_models.py", line 283, in read_metadata_from_safetensors
    assert metadata_len > 2 and json_start in (b'{"', b"{'"), f"{filename} is not a safetensors file"
AssertionError: C:\Data\Packages\stable-diffusion-webui\models\Lora\Ferrari 296.safetensors is not a safetensors file

reading lora C:\Data\Packages\stable-diffusion-webui\models\Lora\hypercars-10.safetensors: AssertionError
Traceback (most recent call last):
  File "C:\Data\Packages\stable-diffusion-webui\extensions-builtin\Lora\network.py", line 38, in __init__
    self.metadata = cache.cached_data_for_file('safetensors-metadata', "lora/" + self.name, filename, read_metadata)
  File "C:\Data\Packages\stable-diffusion-webui\modules\cache.py", line 114, in cached_data_for_file
    value = func()
  File "C:\Data\Packages\stable-diffusion-webui\extensions-builtin\Lora\network.py", line 31, in read_metadata
    metadata = sd_models.read_metadata_from_safetensors(filename)
  File "C:\Data\Packages\stable-diffusion-webui\modules\sd_models.py", line 283, in read_metadata_from_safetensors
    assert metadata_len > 2 and json_start in (b'{"', b"{'"), f"{filename} is not a safetensors file"
AssertionError: C:\Data\Packages\stable-diffusion-webui\models\Lora\hypercars-10.safetensors is not a safetensors file

reading lora C:\Data\Packages\stable-diffusion-webui\models\Lora\JJsHotelBuilding_v2.safetensors: AssertionError
Traceback (most recent call last):
  File "C:\Data\Packages\stable-diffusion-webui\extensions-builtin\Lora\network.py", line 38, in __init__
    self.metadata = cache.cached_data_for_file('safetensors-metadata', "lora/" + self.name, filename, read_metadata)
  File "C:\Data\Packages\stable-diffusion-webui\modules\cache.py", line 114, in cached_data_for_file
    value = func()
  File "C:\Data\Packages\stable-diffusion-webui\extensions-builtin\Lora\network.py", line 31, in read_metadata
    metadata = sd_models.read_metadata_from_safetensors(filename)
  File "C:\Data\Packages\stable-diffusion-webui\modules\sd_models.py", line 283, in read_metadata_from_safetensors
    assert metadata_len > 2 and json_start in (b'{"', b"{'"), f"{filename} is not a safetensors file"
AssertionError: C:\Data\Packages\stable-diffusion-webui\models\Lora\JJsHotelBuilding_v2.safetensors is not a safetensors file

reading lora C:\Data\Packages\stable-diffusion-webui\models\Lora\LCM_LoRA_Weights_SD15.safetensors: AssertionError
Traceback (most recent call last):
  File "C:\Data\Packages\stable-diffusion-webui\extensions-builtin\Lora\network.py", line 38, in __init__
    self.metadata = cache.cached_data_for_file('safetensors-metadata', "lora/" + self.name, filename, read_metadata)
  File "C:\Data\Packages\stable-diffusion-webui\modules\cache.py", line 114, in cached_data_for_file
    value = func()
  File "C:\Data\Packages\stable-diffusion-webui\extensions-builtin\Lora\network.py", line 31, in read_metadata
    metadata = sd_models.read_metadata_from_safetensors(filename)
  File "C:\Data\Packages\stable-diffusion-webui\modules\sd_models.py", line 283, in read_metadata_from_safetensors
    assert metadata_len > 2 and json_start in (b'{"', b"{'"), f"{filename} is not a safetensors file"
AssertionError: C:\Data\Packages\stable-diffusion-webui\models\Lora\LCM_LoRA_Weights_SD15.safetensors is not a safetensors file

reading lora C:\Data\Packages\stable-diffusion-webui\models\Lora\midjourney_20230624181825.safetensors: AssertionError
Traceback (most recent call last):
  File "C:\Data\Packages\stable-diffusion-webui\extensions-builtin\Lora\network.py", line 38, in __init__
    self.metadata = cache.cached_data_for_file('safetensors-metadata', "lora/" + self.name, filename, read_metadata)
  File "C:\Data\Packages\stable-diffusion-webui\modules\cache.py", line 114, in cached_data_for_file
    value = func()
  File "C:\Data\Packages\stable-diffusion-webui\extensions-builtin\Lora\network.py", line 31, in read_metadata
    metadata = sd_models.read_metadata_from_safetensors(filename)
  File "C:\Data\Packages\stable-diffusion-webui\modules\sd_models.py", line 283, in read_metadata_from_safetensors
    assert metadata_len > 2 and json_start in (b'{"', b"{'"), f"{filename} is not a safetensors file"
AssertionError: C:\Data\Packages\stable-diffusion-webui\models\Lora\midjourney_20230624181825.safetensors is not a safetensors file

reading lora C:\Data\Packages\stable-diffusion-webui\models\Lora\SinCity_v1.0.safetensors: AssertionError
Traceback (most recent call last):
  File "C:\Data\Packages\stable-diffusion-webui\extensions-builtin\Lora\network.py", line 38, in __init__
    self.metadata = cache.cached_data_for_file('safetensors-metadata', "lora/" + self.name, filename, read_metadata)
  File "C:\Data\Packages\stable-diffusion-webui\modules\cache.py", line 114, in cached_data_for_file
    value = func()
  File "C:\Data\Packages\stable-diffusion-webui\extensions-builtin\Lora\network.py", line 31, in read_metadata
    metadata = sd_models.read_metadata_from_safetensors(filename)
  File "C:\Data\Packages\stable-diffusion-webui\modules\sd_models.py", line 283, in read_metadata_from_safetensors
    assert metadata_len > 2 and json_start in (b'{"', b"{'"), f"{filename} is not a safetensors file"
AssertionError: C:\Data\Packages\stable-diffusion-webui\models\Lora\SinCity_v1.0.safetensors is not a safetensors file

reading lora C:\Data\Packages\stable-diffusion-webui\models\Lora\thickline_fp16.safetensors: AssertionError
Traceback (most recent call last):
  File "C:\Data\Packages\stable-diffusion-webui\extensions-builtin\Lora\network.py", line 38, in __init__
    self.metadata = cache.cached_data_for_file('safetensors-metadata', "lora/" + self.name, filename, read_metadata)
  File "C:\Data\Packages\stable-diffusion-webui\modules\cache.py", line 114, in cached_data_for_file
    value = func()
  File "C:\Data\Packages\stable-diffusion-webui\extensions-builtin\Lora\network.py", line 31, in read_metadata
    metadata = sd_models.read_metadata_from_safetensors(filename)
  File "C:\Data\Packages\stable-diffusion-webui\modules\sd_models.py", line 283, in read_metadata_from_safetensors
    assert metadata_len > 2 and json_start in (b'{"', b"{'"), f"{filename} is not a safetensors file"
AssertionError: C:\Data\Packages\stable-diffusion-webui\models\Lora\thickline_fp16.safetensors is not a safetensors file

*** Error loading script: lora.py
    Traceback (most recent call last):
      File "C:\Data\Packages\stable-diffusion-webui\modules\scripts.py", line 527, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Data\Packages\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Data\Packages\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\scripts\lora.py", line 7, in <module>
        import onnx
    ModuleNotFoundError: No module named 'onnx'

---
*** Error loading script: trt.py
    Traceback (most recent call last):
      File "C:\Data\Packages\stable-diffusion-webui\modules\scripts.py", line 527, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Data\Packages\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Data\Packages\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\scripts\trt.py", line 8, in <module>
        from polygraphy.logger import G_LOGGER
    ModuleNotFoundError: No module named 'polygraphy'

---
Loading weights [1a11ddc691] from C:\Data\Packages\stable-diffusion-webui\models\Stable-diffusion\dreamshaper_8LCM.safetensors
loading stable diffusion model: SafetensorError
Traceback (most recent call last):
  File "threading.py", line 973, in _bootstrap
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "C:\Data\Packages\stable-diffusion-webui\modules\initialize.py", line 148, in load_model
    shared.sd_model  # noqa: B018
  File "C:\Data\Packages\stable-diffusion-webui\modules\shared_items.py", line 133, in sd_model
    return modules.sd_models.model_data.get_sd_model()
  File "C:\Data\Packages\stable-diffusion-webui\modules\sd_models.py", line 621, in get_sd_model
    load_model()
  File "C:\Data\Packages\stable-diffusion-webui\modules\sd_models.py", line 706, in load_model
    state_dict = get_checkpoint_state_dict(checkpoint_info, timer)
  File "C:\Data\Packages\stable-diffusion-webui\modules\sd_models.py", line 331, in get_checkpoint_state_dict
    res = read_state_dict(checkpoint_info.filename)
  File "C:\Data\Packages\stable-diffusion-webui\modules\sd_models.py", line 305, in read_state_dict
    pl_sd = safetensors.torch.load_file(checkpoint_file, device=device)
  File "C:\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\safetensors\torch.py", line 308, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: InvalidHeaderDeserialization

Stable diffusion model failed to load
Applying attention optimization: xformers... done.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 7.2s (prepare environment: 1.8s, import torch: 2.4s, import gradio: 0.7s, setup paths: 0.7s, initialize shared: 0.2s, other imports: 0.5s, load scripts: 0.5s, create ui: 0.3s, gradio launch: 0.1s, add APIs: 0.3s).
Loading weights [1a11ddc691] from C:\Data\Packages\stable-diffusion-webui\models\Stable-diffusion\dreamshaper_8LCM.safetensors
loading stable diffusion model: SafetensorError
Traceback (most recent call last):
  File "threading.py", line 973, in _bootstrap
  File "threading.py", line 1016, in _bootstrap_inner
  File "C:\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\Data\Packages\stable-diffusion-webui\modules\ui.py", line 1172, in <lambda>
    update_image_cfg_scale_visibility = lambda: gr.update(visible=shared.sd_model and shared.sd_model.cond_stage_key == "edit")
  File "C:\Data\Packages\stable-diffusion-webui\modules\shared_items.py", line 133, in sd_model
    return modules.sd_models.model_data.get_sd_model()
  File "C:\Data\Packages\stable-diffusion-webui\modules\sd_models.py", line 621, in get_sd_model
    load_model()
  File "C:\Data\Packages\stable-diffusion-webui\modules\sd_models.py", line 706, in load_model
    state_dict = get_checkpoint_state_dict(checkpoint_info, timer)
  File "C:\Data\Packages\stable-diffusion-webui\modules\sd_models.py", line 331, in get_checkpoint_state_dict
    res = read_state_dict(checkpoint_info.filename)
  File "C:\Data\Packages\stable-diffusion-webui\modules\sd_models.py", line 305, in read_state_dict
    pl_sd = safetensors.torch.load_file(checkpoint_file, device=device)
  File "C:\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\safetensors\torch.py", line 308, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: InvalidHeaderDeserialization

Stable diffusion model failed to load
Loading weights [1a11ddc691] from C:\Data\Packages\stable-diffusion-webui\models\Stable-diffusion\dreamshaper_8LCM.safetensors
loading stable diffusion model: SafetensorError
Traceback (most recent call last):
  File "threading.py", line 973, in _bootstrap
  File "threading.py", line 1016, in _bootstrap_inner
  File "C:\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\Data\Packages\stable-diffusion-webui\modules\ui_extra_networks.py", line 710, in pages_html
    create_html()
  File "C:\Data\Packages\stable-diffusion-webui\modules\ui_extra_networks.py", line 706, in create_html
    ui.pages_contents = [pg.create_html(ui.tabname) for pg in ui.stored_extra_pages]
  File "C:\Data\Packages\stable-diffusion-webui\modules\ui_extra_networks.py", line 706, in <listcomp>
    ui.pages_contents = [pg.create_html(ui.tabname) for pg in ui.stored_extra_pages]
  File "C:\Data\Packages\stable-diffusion-webui\modules\ui_extra_networks.py", line 518, in create_html
    self.items = {x["name"]: x for x in items_list}
  File "C:\Data\Packages\stable-diffusion-webui\modules\ui_extra_networks.py", line 518, in <dictcomp>
    self.items = {x["name"]: x for x in items_list}
  File "C:\Data\Packages\stable-diffusion-webui\extensions-builtin\Lora\ui_extra_networks_lora.py", line 82, in list_items
    item = self.create_item(name, index)
  File "C:\Data\Packages\stable-diffusion-webui\extensions-builtin\Lora\ui_extra_networks_lora.py", line 66, in create_item
    model_version = network.SdVersion.SDXL if shared.sd_model.is_sdxl else network.SdVersion.SD2 if shared.sd_model.is_sd2 else network.SdVersion.SD1
  File "C:\Data\Packages\stable-diffusion-webui\modules\shared_items.py", line 133, in sd_model
    return modules.sd_models.model_data.get_sd_model()
  File "C:\Data\Packages\stable-diffusion-webui\modules\sd_models.py", line 621, in get_sd_model
    load_model()
  File "C:\Data\Packages\stable-diffusion-webui\modules\sd_models.py", line 706, in load_model
    state_dict = get_checkpoint_state_dict(checkpoint_info, timer)
  File "C:\Data\Packages\stable-diffusion-webui\modules\sd_models.py", line 331, in get_checkpoint_state_dict
    res = read_state_dict(checkpoint_info.filename)
  File "C:\Data\Packages\stable-diffusion-webui\modules\sd_models.py", line 305, in read_state_dict
    pl_sd = safetensors.torch.load_file(checkpoint_file, device=device)
  File "C:\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\safetensors\torch.py", line 308, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: InvalidHeaderDeserialization

Stable diffusion model failed to load
Loading weights [1a11ddc691] from C:\Data\Packages\stable-diffusion-webui\models\Stable-diffusion\dreamshaper_8LCM.safetensors
loading stable diffusion model: SafetensorError
Traceback (most recent call last):
  File "threading.py", line 973, in _bootstrap
  File "threading.py", line 1016, in _bootstrap_inner
  File "C:\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\Data\Packages\stable-diffusion-webui\modules\ui_extra_networks.py", line 710, in pages_html
    create_html()
  File "C:\Data\Packages\stable-diffusion-webui\modules\ui_extra_networks.py", line 706, in create_html
    ui.pages_contents = [pg.create_html(ui.tabname) for pg in ui.stored_extra_pages]
  File "C:\Data\Packages\stable-diffusion-webui\modules\ui_extra_networks.py", line 706, in <listcomp>
    ui.pages_contents = [pg.create_html(ui.tabname) for pg in ui.stored_extra_pages]
  File "C:\Data\Packages\stable-diffusion-webui\modules\ui_extra_networks.py", line 518, in create_html
    self.items = {x["name"]: x for x in items_list}
  File "C:\Data\Packages\stable-diffusion-webui\modules\ui_extra_networks.py", line 518, in <dictcomp>
    self.items = {x["name"]: x for x in items_list}
  File "C:\Data\Packages\stable-diffusion-webui\extensions-builtin\Lora\ui_extra_networks_lora.py", line 82, in list_items
    item = self.create_item(name, index)
  File "C:\Data\Packages\stable-diffusion-webui\extensions-builtin\Lora\ui_extra_networks_lora.py", line 66, in create_item
    model_version = network.SdVersion.SDXL if shared.sd_model.is_sdxl else network.SdVersion.SD2 if shared.sd_model.is_sd2 else network.SdVersion.SD1
  File "C:\Data\Packages\stable-diffusion-webui\modules\shared_items.py", line 133, in sd_model
    return modules.sd_models.model_data.get_sd_model()
  File "C:\Data\Packages\stable-diffusion-webui\modules\sd_models.py", line 621, in get_sd_model
    load_model()
  File "C:\Data\Packages\stable-diffusion-webui\modules\sd_models.py", line 706, in load_model
    state_dict = get_checkpoint_state_dict(checkpoint_info, timer)
  File "C:\Data\Packages\stable-diffusion-webui\modules\sd_models.py", line 331, in get_checkpoint_state_dict
    res = read_state_dict(checkpoint_info.filename)
Traceback (most recent call last):
  File "C:\Data\Packages\stable-diffusion-webui\modules\sd_models.py", line 305, in read_state_dict
    pl_sd = safetensors.torch.load_file(checkpoint_file, device=device)
  File "C:\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\safetensors\torch.py", line 308, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: InvalidHeaderDeserialization

  File "C:\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
Stable diffusion model failed to load  File "C:\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(

  File "C:\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\Data\Packages\stable-diffusion-webui\modules\ui_extra_networks.py", line 710, in pages_html
    create_html()
  File "C:\Data\Packages\stable-diffusion-webui\modules\ui_extra_networks.py", line 706, in create_html
    ui.pages_contents = [pg.create_html(ui.tabname) for pg in ui.stored_extra_pages]
  File "C:\Data\Packages\stable-diffusion-webui\modules\ui_extra_networks.py", line 706, in <listcomp>
    ui.pages_contents = [pg.create_html(ui.tabname) for pg in ui.stored_extra_pages]
  File "C:\Data\Packages\stable-diffusion-webui\modules\ui_extra_networks.py", line 518, in create_html
    self.items = {x["name"]: x for x in items_list}
  File "C:\Data\Packages\stable-diffusion-webui\modules\ui_extra_networks.py", line 518, in <dictcomp>
    self.items = {x["name"]: x for x in items_list}
  File "C:\Data\Packages\stable-diffusion-webui\extensions-builtin\Lora\ui_extra_networks_lora.py", line 82, in list_items
    item = self.create_item(name, index)
  File "C:\Data\Packages\stable-diffusion-webui\extensions-builtin\Lora\ui_extra_networks_lora.py", line 66, in create_item
    model_version = network.SdVersion.SDXL if shared.sd_model.is_sdxl else network.SdVersion.SD2 if shared.sd_model.is_sd2 else network.SdVersion.SD1
AttributeError: 'NoneType' object has no attribute 'is_sdxl'
Traceback (most recent call last):
  File "C:\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\Data\Packages\stable-diffusion-webui\modules\ui_extra_networks.py", line 710, in pages_html
    create_html()
  File "C:\Data\Packages\stable-diffusion-webui\modules\ui_extra_networks.py", line 706, in create_html
    ui.pages_contents = [pg.create_html(ui.tabname) for pg in ui.stored_extra_pages]
  File "C:\Data\Packages\stable-diffusion-webui\modules\ui_extra_networks.py", line 706, in <listcomp>
    ui.pages_contents = [pg.create_html(ui.tabname) for pg in ui.stored_extra_pages]
  File "C:\Data\Packages\stable-diffusion-webui\modules\ui_extra_networks.py", line 518, in create_html
    self.items = {x["name"]: x for x in items_list}
  File "C:\Data\Packages\stable-diffusion-webui\modules\ui_extra_networks.py", line 518, in <dictcomp>
    self.items = {x["name"]: x for x in items_list}
  File "C:\Data\Packages\stable-diffusion-webui\extensions-builtin\Lora\ui_extra_networks_lora.py", line 82, in list_items
    item = self.create_item(name, index)
  File "C:\Data\Packages\stable-diffusion-webui\extensions-builtin\Lora\ui_extra_networks_lora.py", line 66, in create_item
    model_version = network.SdVersion.SDXL if shared.sd_model.is_sdxl else network.SdVersion.SD2 if shared.sd_model.is_sd2 else network.SdVersion.SD1
AttributeError: 'NoneType' object has no attribute 'is_sdxl'

**Comment by zerollzeng** [comment]
dup of #3693 so I'm closing this.
