### ISSUE TITLE
install failure of TensorRT

### ISSUE THREAD

**Issue by Tom-Teamo** [NVIDIA/TensorRT#3721]
## Description

When I install TrensorRT in my Ubuntu22.04 as [step No.1 in setup](https://github.com/NVIDIA/TensorRT?tab=readme-ov-file#setting-up-the-build-environment), it always failed at "extracting: ngc-cli.md5 ". And I do not know how to fix this.
```
... 
9.464   inflating: ngc-cli/opentelemetry/proto/common/v1/common_pb2.pyi  
9.464   inflating: ngc-cli/opentelemetry/proto/version.py  
9.464    creating: ngc-cli/opentelemetry/util/
9.464   inflating: ngc-cli/opentelemetry/util/_once.py  
9.464    creating: ngc-cli/opentelemetry/util/__pycache__/
9.464   inflating: ngc-cli/opentelemetry/util/__pycache__/_once.cpython-39.pyc  
9.464   inflating: ngc-cli/opentelemetry/util/__pycache__/_providers.cpython-39.pyc  
9.464   inflating: ngc-cli/opentelemetry/util/__pycache__/re.cpython-39.pyc  
9.464   inflating: ngc-cli/opentelemetry/util/__pycache__/_importlib_metadata.cpython-39.pyc  
9.464   inflating: ngc-cli/opentelemetry/util/__pycache__/types.cpython-39.pyc  
9.464   inflating: ngc-cli/opentelemetry/util/_importlib_metadata.py  
9.464   inflating: ngc-cli/opentelemetry/util/_providers.py  
9.464   inflating: ngc-cli/opentelemetry/util/re.py  
9.464   inflating: ngc-cli/opentelemetry/util/types.py  
9.464  extracting: ngc-cli.md5             
71.87 Connection failed; retrying... (Retries left: 5)
137.0 Connection failed; retrying... (Retries left: 4)
202.1 Connection failed; retrying... (Retries left: 3)
267.3 Connection failed; retrying... (Retries left: 2)
332.4 Connection failed; retrying... (Retries left: 1)
332.4 Error: Request timed out.
------
ubuntu-20.04.Dockerfile:109
--------------------
 107 |     
 108 |     # Download NGC client
 109 | >>> RUN cd /usr/local/bin && wget https://ngc.nvidia.com/downloads/ngccli_cat_linux.zip && unzip ngccli_cat_linux.zip && chmod u+x ngc-cli/ngc && rm ngccli_cat_linux.zip ngc-cli.md5 && echo "no-apikey\nascii\n" | ngc-cli/ngc config set
 110 |     
 111 |     # Set environment and working directory
--------------------
ERROR: failed to solve: process "/bin/bash -c cd /usr/local/bin && wget https://ngc.nvidia.com/downloads/ngccli_cat_linux.zip && unzip ngccli_cat_linux.zip && chmod u+x ngc-cli/ngc && rm ngccli_cat_linux.zip ngc-cli.md5 && echo \"no-apikey\\nascii\\n\" | ngc-cli/ngc config set" did not complete successfully: exit code: 1

```
## Environment

**TensorRT Version**: latest

**NVIDIA GPU**: 3090

**NVIDIA Driver Version**:  12.2

**CUDA Version**: 12.1

Operating System: Ubuntu22.04

## Steps To Reproduce

just as  [step No.1 in setup](https://github.com/NVIDIA/TensorRT?tab=readme-ov-file#setting-up-the-build-environment), it always failed at "extracting: ngc-cli.md5 ".

**Comment by lix19937** [comment]
Maybe network problem, you need a stable vpn

**Comment by YongWookHa** [comment]
I'm facing same problem at `extracting: ngc-cli.md5`.
@lix19937 did you test it?

**Comment by lix19937** [comment]
you can offline download `ngccli_cat_linux.zip` and then unzip and  
`chmod u+x ngc-cli/ngc &&  echo \"no-apikey\\nascii\\n\" | ngc-cli/ngc config set`

**Comment by YongWookHa** [comment]
@lix19937 It's not about network problem the command stucks at the `echo "no-apikey\nascii\n" | ngc-cli/ngc config set` part.

**Comment by YongWookHa** [comment]
I just resolved the problem by the steps below.

1. Split the line in dockerfile

https://github.com/NVIDIA/TensorRT/blob/c0c633cc629cc0705f0f69359f531a192e524c0f/docker/ubuntu-20.04.Dockerfile#L113 to
  ```
  # Download NGC client
  RUN cd /usr/local/bin && wget https://ngc.nvidia.com/downloads/ngccli_cat_linux.zip
  RUN cd /usr/local/bin && unzip ngccli_cat_linux.zip
  RUN cd /usr/local/bin && chmod u+x ngc-cli/ngc
  RUN cd /usr/local/bin && rm -f ngccli_cat_linux.zip ngc-cli.md5
  RUN cd /usr/local/bin && echo "no-apikey\nascii\n" | ngc-cli/ngc config set
  ```

2. Comment out the problem causing command
```
# RUN cd /usr/local/bin && echo "no-apikey\nascii\n" | ngc-cli/ngc config set
```
3. Build the docker image
``` bash
> ./docker/build.sh --file docker/ubuntu-20.04.Dockerfile --tag tensorrt-ubuntu20.04-cuda12.1
```
4. Launch the container
```
> ./docker/launch.sh --tag tensorrt-ubuntu20.04-cuda12.1 --gpus all
``` 
5. Put the command manually
```
> ngc-cli/ngc config set
Enter API key [no-apikey]. Choices: [<VALID_APIKEY>, 'no-apikey']: no-apikey
Enter CLI output format type [ascii]. Choices: ['ascii', 'csv', 'json']: ascii
Validating configuration...
Successfully validated configuration.
Saving configuration...
Successfully saved NGC configuration to /home/trtuser/.ngc/config
```

**Comment by bashirmindee** [comment]
doing echo "no-apikey\Nascii\n" | ... is really weird.
I suggest doing: `/usr/local/bin/ngc-cli/ngc config set --format_type ascii`

**Comment by bashirmindee** [comment]
for some reason, you have to run ngc-cli/ngc config twice in order for it to work!
The 1st time it blocks and doesn't work. The second time it works correctly

**Comment by bashirmindee** [comment]
I finally found it. 
ngc config ... generates /root/.ngc/meta_data if it doesn't exist. However it blocks the 1st time because it doesn't already exist.
by generating dummy data you can bypass this:
```dockerfile
RUN mkdir -p /root/.ngc
RUN echo -e ";WARNING - This is a machine generated file.  Do not edit manually.\n\n[COMMAND_MAP]\n\n[UPGRADE]\nlast_upgrade_msg_date = 2024-03-26::09:43:31\n\n[USER_ROLES]\n\n[PRODUCT_NAMES]\n" > /root/.ngc/meta_data
RUN /usr/local/bin/ngc-cli/ngc config set --format_type ascii
```

This works directly. I can do a PR to fix it

**Comment by Goodluckhf** [comment]
It happened after release new CLI version. I installed specific previous version and it fixed.

you can change this line 

```
RUN cd /usr/local/bin && wget https://ngc.nvidia.com/downloads/ngccli_cat_linux.zip && unzip ngccli_cat_linux.zip && chmod u+x ngc-cli/ngc && rm ngccli_cat_linux.zip ngc-cli.md5 && echo "no-apikey\nascii\n" | ngc-cli/ngc config set
```
To ->
```
RUN cd /usr/local/bin && wget --content-disposition https://api.ngc.nvidia.com/v2/resources/nvidia/ngc-apps/ngc_cli/versions/3.38.0/files/ngccli_linux.zip -O ngccli_linux.zip && unzip ngccli_linux.zip && chmod u+x ngc-cli/ngc && rm ngccli_linux.zip ngc-cli.md5 && echo "no-apikey\nascii\n" | ngc-cli/ngc config set
```

p.s you can choose specific version here -> https://org.ngc.nvidia.com/setup/installers/cli

**Comment by Nghiauet** [comment]
@Goodluckhf Thanks it work for me.

**Comment by ZhenshengLee** [comment]
I encounter the ngc protobuf version missmatching bug.
Does anyone know which protobuf version should I install, I've tried 3.14.0, 4.21.7, 3.19.6

```sh
./ngc -h
google/protobuf/internal/api_implementation.py:89: UserWarning: Selected implementation cpp is not available.
Traceback (most recent call last):
  File "ngc.py", line 12, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "ngccli/ngc.py", line 11, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "ngcbase/command/basecli.py", line 17, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "ngcbase/api/baseclient.py", line 11, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "ngcbase/api/authentication.py", line 45, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "ngcbase/tracing.py", line 21, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "opentelemetry/exporter/otlp/proto/grpc/metric_exporter/__init__.py", line 21, in <module>
    from opentelemetry.exporter.otlp.proto.common._internal.metrics_encoder import (
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "opentelemetry/exporter/otlp/proto/common/_internal/__init__.py", line 30, in <module>
    from opentelemetry.proto.common.v1.common_pb2 import AnyValue as PB2AnyValue
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "opentelemetry/proto/common/v1/common_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "google/protobuf/descriptor.py", line 28, in <module>
ImportError: cannot import name '_message' from 'google.protobuf.pyext' (/home/zs/opt/ngc-cli/google/protobuf/pyext/__init__.pyc)
[10949] Failed to execute script 'ngc' due to unhandled exception!
```
