### ISSUE TITLE
Facing "Unexpected exception invalid unordered_map<K, T> key" when calibrating int8 engine

### ISSUE THREAD

**Issue by Justin020718** [NVIDIA/TensorRT#3926]
## Description
The model to convert is of dynamic multiple inputs and outputs, since I'm unfamiliar with Polygraphy, I've decided to write a python script for converting, and here's my script:
```
import os
import random
import sys
import tensorrt as trt
import numpy as np
import torch
from src.tetra.model_wrapper import IntraNoAR_encoder_wrapper, DMC_encoder_wrapper
from src.transforms.functional import ycbcr420_to_444
from src.utils.video_reader import YUVReader
from test_video import np_image_to_tensor
import pycuda.driver as cuda
import pycuda.autoinit

image_model_path = './checkpoints/cvpr2023_image_psnr.pth.tar'
video_model_path = './checkpoints/cvpr2023_video_psnr.pth.tar'
sample_path = 'E:\BaiduNetdiskDownload\HEVCceshishipin'

intra_no_ar_encoder = IntraNoAR_encoder_wrapper(model_path=image_model_path).cuda()
dmc_encoder = DMC_encoder_wrapper(model_path=video_model_path).cuda()

class_list = os.listdir(sample_path)
class_list.remove('H264')
class_list.remove('ClassD')
class_list.remove('ClassF')
video_list = {}
for cls in class_list:
    video_list[cls] = os.listdir(sample_path + '/' + cls)
src_readers = {}

class IntraNoARCalibrator(trt.IInt8EntropyCalibrator2):
    # calibrator
    def __init__(self):
        trt.IInt8EntropyCalibrator2.__init__(self)
        self.cache_file = 'i_frame.cache'
        self.batch_size = 1
        self.batch_idx = 0
        self.max_batch_idx = 500

    def next_batch(self):
        if self.batch_idx < self.max_batch_idx:
            cls = random.choice(class_list)
            path = sample_path + '/' + cls + '/' + random.choice(video_list[cls])
            width, height = get_shape_from_class(cls)
            x, q, dummy_input = read_one_frame(path, width, height)
            self.batch_idx += 1
            return np.ascontiguousarray(x.cpu()), np.ascontiguousarray(q.cpu()), np.ascontiguousarray(dummy_input.cpu())
        else:
            return np.array([])

    def get_batch_size(self):
        return self.batch_size

    def get_batch(self, names, p_str=None):
        try:
            inputs = self.next_batch()
            device_inputs = []
            for input in inputs:
                device_input = cuda.mem_alloc(input.size * trt.float32.itemsize)
                cuda.memcpy_htod(device_input, input.astype(np.float32))
                device_inputs.append(device_input)
            return [int(device_inputs)]
        except:
            return None

    def read_calibration_cache(self):
        # If there is a cache, use it instead of calibrating again. Otherwise, implicitly return None.
        if os.path.exists(self.cache_file):
            with open(self.cache_file, "rb") as f:
                return f.read()

    def write_calibration_cache(self, cache):
        with open(self.cache_file, "wb") as f:
            f.write(cache)

def ONNX2TRT(onnx_path, engine_path, calib=None):
    ''' convert onnx to tensorrt engine
    :return: trt engine
    '''
    TRT_LOGGER = trt.Logger(trt.Logger.WARNING)
    TRT_BUILDER = trt.Builder(TRT_LOGGER)

    network_creation_flag = 0
    if "EXPLICIT_BATCH" in trt.NetworkDefinitionCreationFlag.__members__.keys():
        network_creation_flag = 1 << int(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)
    network = TRT_BUILDER.create_network(network_creation_flag)
    onnx_parser = trt.OnnxParser(network, TRT_LOGGER)
    parse_success = onnx_parser.parse_from_file(onnx_path)
    for idx in range(onnx_parser.num_errors):
        print(onnx_parser.get_error(idx))
    if not parse_success:
        sys.exit('ONNX model parsing failed')

    config = TRT_BUILDER.create_builder_config()
    profile = TRT_BUILDER.create_optimization_profile()
    profile.set_shape('y_hat', (1, 256, 23, 30), (1, 256, 100, 160), (1, 256, 100, 160))
    profile.set_shape('q', (1, ), (1, ), (1, ))
    profile.set_shape('dummy', (1, ), (1, ), (1, ))
    config.add_optimization_profile(profile)
    config.set_memory_pool_limit(trt.MemoryPoolType.WORKSPACE, 8192*(1 << 20))
    config.set_flag(trt.BuilderFlag.INT8)
    config.int8_calibrator = calib
    config.set_calibration_profile(profile)
    serialized_engine = TRT_BUILDER.build_serialized_network(network, config)

    # 保存计划文件
    print('Saving TRT engine file to path {}...'.format(engine_path))
    with open(engine_path, "wb") as f:
        f.write(serialized_engine)
    print('Engine file has already saved to {}!'.format(engine_path))

def read_one_frame(path, width, height):
    if path not in list(src_readers.keys()):
        src_readers[path] = YUVReader(path, width, height)
    src_reader = src_readers[path]
    y, uv = src_reader.read_one_frame(dst_format="420")
    y1, uv1 = src_reader.read_one_frame(dst_format="420")
    if y1 is None or uv1 is None or y is None or uv is None:
        return None
    yuv = ycbcr420_to_444(y, uv, order=0)
    yuv1 = ycbcr420_to_444(y1, uv1, order=0)
    x = np_image_to_tensor(yuv).cuda()
    x1 = np_image_to_tensor(yuv1).cuda()
    with ((torch.no_grad())):
        return intra_no_ar_encoder.forward(x=x, q_index=torch.Tensor([random.random()*63]).reshape(1,).cuda(), dummy_input = torch.Tensor([0]).reshape(1,).cuda()),\
        torch.Tensor([random.random()*63]).reshape(1,),\
        torch.Tensor([0]).reshape(1,)

def get_shape_from_class(cls):
    if cls == 'ClassA':
        return 2560,1600
    elif cls == 'ClassB':
        return 1920,1088
    elif cls == 'ClassC':
        return 832,480
    elif cls == 'ClassE':
        return 1280,720
    else:
        return None

def load_data():
    for _ in range(500):
        cls = random.choice(class_list)
        path = sample_path + '/' + cls + '/' + random.choice(video_list[cls])
        width, height = get_shape_from_class(cls)
        x, _ = read_one_frame(path, width, height)
        yield {
            "x": np.array(x, dtype=np.float16)
        }  # Still totally real data

if __name__ == '__main__':
    onnx_path = './IntraNoAR_decoder_sur_sim.onnx'
    engine_path = './I_D_int8.engine'
    calib = IntraNoARCalibrator()
    ONNX2TRT(onnx_path, engine_path, calib)
```
When I'm trying to execute the script, some errors jump out:
```
E:\anaconda3\envs\python3.8\python.exe E:\DCVC-main\DCVC-DC-encoder-decoder\calib_i.py 
Traceback (most recent call last):
  File "E:\DCVC-main\DCVC-DC-encoder-decoder\calib_i.py", line 159, in <module>
    ONNX2TRT(onnx_path, engine_path, calib)
  File "E:\DCVC-main\DCVC-DC-encoder-decoder\calib_i.py", line 114, in ONNX2TRT
    f.write(serialized_engine)
TypeError: a bytes-like object is required, not 'NoneType'
[06/06/2024-22:10:57] [TRT] [E] 1: Unexpected exception invalid unordered_map<K, T> key
Saving TRT engine file to path ./I_D_int8.engine...
```
ONNX->fp32 or fp16 trt engine works well. I'll appreciate it if someone could help.

## Environment

**TensorRT Version**:
10.0.1.6
**NVIDIA GPU**:
RTX 3070 laptop
**NVIDIA Driver Version**:
551.86
**CUDA Version**:
12.4

Operating System:
Windows 10
Python Version:
3.8
PyTorch Version:
2.3.0

## Relevant Files

**Model link**:
https://drive.google.com/file/d/1O-ZT50QBbaED0ouYgUQGXprYadiPr3P2/view?usp=sharing

## Steps To Reproduce
1. Download the "IntraNoAR_decoder_sur_sim.onnx" and copy my script;
2. The model has three inputs and one output, and the calibration should include inputs with different shapes, see
```
profile.set_shape('y_hat', (1, 256, 23, 30), (1, 256, 100, 160), (1, 256, 100, 160))
profile.set_shape('q', (1, ), (1, ), (1, ))
profile.set_shape('dummy', (1, ), (1, ), (1, ))
```
2. Replace "read_one_frame" function in my code to generate some random inputs, for example:
```
def read_one_frame(path, width, height):
    # y_hat
    y_hat = torch.randn((1, 256, height / 16, width / 16))
    # q
    q = torch.Tensor([random.random()*63]).reshape(1,)
    # dummy input
    dummy = torch.Tensor([0]).reshape(1,)
    return y_hat, q, dummy
```
3. Remove some lines in "next_batch", delete all the irrelevant packages and run the script.
```
def next_batch(self):
    if self.batch_idx < self.max_batch_idx:
        x, q, dummy_input = read_one_frame(path, width, height)
        self.batch_idx += 1
        return np.ascontiguousarray(x.cpu()), np.ascontiguousarray(q.cpu()), np.ascontiguousarray(dummy_input.cpu())
    else:
        return np.array([])
```

**Commands or scripts**:
python my_script.py
**Have you tried [the latest release](https://developer.nvidia.com/tensorrt)?**:
Yes.
**Can this model run on other frameworks?** For example run ONNX model with ONNXRuntime (`polygraphy run <model.onnx> --onnxrt`):
Yes.

**Comment by Justin020718** [comment]
I just wonder where can I find some official implementation to convert and calibrate int8 engines with dynamic shapes and multiple inputs/outputs, through python scripts or Polygraphy.

**Comment by Justin020718** [comment]
Closing this since it works fine with polygraphy 0.49.9
