### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'is_sdxl'

### ISSUE THREAD

**Issue by kimyouk** [NVIDIA/TensorRT#3997]
## Description

The installation of the checkpoint was refreshed. The checklist is listed. However, it does not change. After a short loading after clicking, it returns to one specific checklist repeatedly. The name of that particular checklist is [beautifulRealistic_v7.safetensors]

## Environment

11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz   2.59 GHz
RAM : 8.00GB
64bit

Operating System:
Python Version (if applicable): python-3.10.6-amd64

## Relevant Files

Chrome brouser 
The name of that particular checklist is [beautifulRealistic_v7.safetensors]

**Model link**:

https://civitai.com/models/25494?modelVersionId=177164

## Steps To Reproduce

<!--
  Craft a minimal bug report following this guide - https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

  Please include:

Stable diffusion model failed to load
Loading weights [1a17bcd93d] from D:\SD\webui\models\Stable-diffusion\beautifulRealistic_v7.safetensors
Creating model from config: D:\SD\webui\configs\v1-inference.yaml
Traceback (most recent call last):
  File "D:\SD\webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\SD\webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "D:\SD\webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\SD\webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\SD\webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\SD\webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\SD\webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "D:\SD\webui\modules\ui_extra_networks.py", line 787, in pages_html
    create_html()
  File "D:\SD\webui\modules\ui_extra_networks.py", line 783, in create_html
    ui.pages_contents = [pg.create_html(ui.tabname) for pg in ui.stored_extra_pages]
  File "D:\SD\webui\modules\ui_extra_networks.py", line 783, in <listcomp>
    ui.pages_contents = [pg.create_html(ui.tabname) for pg in ui.stored_extra_pages]
  File "D:\SD\webui\modules\ui_extra_networks.py", line 591, in create_html
    self.items = {x["name"]: x for x in items_list}
  File "D:\SD\webui\modules\ui_extra_networks.py", line 591, in <dictcomp>
    self.items = {x["name"]: x for x in items_list}
  File "D:\SD\webui\extensions-builtin\Lora\ui_extra_networks_lora.py", line 82, in list_items
    item = self.create_item(name, index)
  File "D:\SD\webui\extensions-builtin\Lora\ui_extra_networks_lora.py", line 66, in create_item
    model_version = network.SdVersion.SDXL if shared.sd_model.is_sdxl else network.SdVersion.SD2 if shared.sd_model.is_sd2 else network.SdVersion.SD1
AttributeError: 'NoneType' object has no attribute 'is_sdxl'
loading stable diffusion model: OutOfMemoryError
Traceback (most recent call last):
  File "C:\Users\김기연\AppData\Local\Programs\Python\Python310\lib\threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\김기연\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "D:\SD\webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\SD\webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "D:\SD\webui\modules\ui.py", line 1154, in <lambda>
    update_image_cfg_scale_visibility = lambda: gr.update(visible=shared.sd_model and shared.sd_model.cond_stage_key == "edit")
  File "D:\SD\webui\modules\shared_items.py", line 175, in sd_model
    return modules.sd_models.model_data.get_sd_model()
  File "D:\SD\webui\modules\sd_models.py", line 620, in get_sd_model
    load_model()
  File "D:\SD\webui\modules\sd_models.py", line 748, in load_model
    load_model_weights(sd_model, checkpoint_info, state_dict, timer)
  File "D:\SD\webui\modules\sd_models.py", line 403, in load_model_weights
    model.float()
  File "D:\SD\webui\venv\lib\site-packages\lightning_fabric\utilities\device_dtype_mixin.py", line 88, in float
    return super().float()
  File "D:\SD\webui\venv\lib\site-packages\torch\nn\modules\module.py", line 992, in float
    return self._apply(lambda t: t.float() if t.is_floating_point() else t)
  File "D:\SD\webui\venv\lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
    module._apply(fn)
  File "D:\SD\webui\venv\lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
    module._apply(fn)
  File "D:\SD\webui\venv\lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
    module._apply(fn)
  [Previous line repeated 8 more times]
  File "D:\SD\webui\venv\lib\site-packages\torch\nn\modules\module.py", line 833, in _apply
    param_applied = fn(param)
  File "D:\SD\webui\venv\lib\site-packages\torch\nn\modules\module.py", line 992, in <lambda>
    return self._apply(lambda t: t.float() if t.is_floating_point() else t)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 50.00 MiB. GPU 0 has a total capacty of 4.00 GiB of which 0 bytes is free. Of the allocated memory 3.00 GiB is allocated by PyTorch, and 449.51 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Stable diffusion model failed to load
changing setting sd_model_checkpoint to epicrealism_naturalSinRC1VAE.safetensors: AttributeError
Traceback (most recent call last):
  File "D:\SD\webui\modules\options.py", line 165, in set
    option.onchange()
  File "D:\SD\webui\modules\call_queue.py", line 13, in f
    res = func(*args, **kwargs)
  File "D:\SD\webui\modules\initialize_util.py", line 181, in <lambda>
    shared.opts.onchange("sd_model_checkpoint", wrap_queued_call(lambda: sd_models.reload_model_weights()), call=False)
  File "D:\SD\webui\modules\sd_models.py", line 860, in reload_model_weights
    sd_model = reuse_model_from_already_loaded(sd_model, checkpoint_info, timer)
  File "D:\SD\webui\modules\sd_models.py", line 793, in reuse_model_from_already_loaded
    send_model_to_cpu(sd_model)
  File "D:\SD\webui\modules\sd_models.py", line 662, in send_model_to_cpu
    if m.lowvram:
AttributeError: 'NoneType' object has no attribute 'lowvram'

**Commands or scripts**:

**Have you tried [the latest release](https://developer.nvidia.com/tensorrt)?**:

**Can this model run on other frameworks?** For example run ONNX model with ONNXRuntime (`polygraphy run <model.onnx> --onnxrt`):

```[tasklist]
### Tasks
```

**Comment by kimyouk** [comment]
changing setting sd_model_checkpoint to v1-5-pruned-emaonly.safetensors: AttributeError
Traceback (most recent call last):
  File "D:\SD\webui\modules\options.py", line 165, in set
    option.onchange()
  File "D:\SD\webui\modules\call_queue.py", line 13, in f
    res = func(*args, **kwargs)
  File "D:\SD\webui\modules\initialize_util.py", line 181, in <lambda>
    shared.opts.onchange("sd_model_checkpoint", wrap_queued_call(lambda: sd_models.reload_model_weights()), call=False)
  File "D:\SD\webui\modules\sd_models.py", line 860, in reload_model_weights
    sd_model = reuse_model_from_already_loaded(sd_model, checkpoint_info, timer)
  File "D:\SD\webui\modules\sd_models.py", line 793, in reuse_model_from_already_loaded
    send_model_to_cpu(sd_model)
  File "D:\SD\webui\modules\sd_models.py", line 662, in send_model_to_cpu
    if m.lowvram:
AttributeError: 'NoneType' object has no attribute 'lowvram'

**Comment by kimyouk** [comment]
<img width="562" alt="스크린샷 2024-07-10 220914" src="https://github.com/NVIDIA/TensorRT/assets/175220675/c12cc0f2-88a6-43fe-a3d7-98f385ba2178">

**Comment by kevinch-nv** [comment]
This is not StableDiffusion demo in this repo. Closing.
