### ISSUE TITLE
Cannot install tensorRT==9.3.0

### ISSUE THREAD

**Issue by kylechang523** [NVIDIA/TensorRT#4038]
When I try to install tensorRT==9.3.0 for SD accelerate, I met this problem:
#####
pip install tensorrt==9.3.0.post12.dev1
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting tensorrt==9.3.0.post12.dev1
  Downloading tensorrt-9.3.0.post12.dev1.tar.gz (6.9 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-yed5wc3z/tensorrt_c24c447630754a1dab1dc69d9c06b225/setup.py", line 90, in <module>
          raise RuntimeError("Bad params")
      RuntimeError: Bad params
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

[notice] A new release of pip is available: 23.3.1 -> 24.2
#####

Then I go to the https://developer.nvidia.com/tensorrt/download to download the package manually but I found there is no more TensorRT 9, may I ask which version should I use to implement to diffusion acclerate.

**Comment by lix19937** [comment]
Try to use the latest version v10.2.

**Comment by lix19937** [comment]
Try to use the latest version v10.2.

**Comment by lix19937** [comment]
Try to use the latest version v10.2. https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html#installing-pip

**Comment by ttyio** [comment]
@kylechang523 does this sample helps? https://github.com/NVIDIA/TensorRT/tree/release/10.2/demo/Diffusion

**Comment by moraxu** [comment]
@kylechang523 , I will be closing this ticket due to our policy to close tickets with no activity for more than 21 days after a reply had been posted. Please reopen a new ticket if you still need help.
