### ISSUE TITLE
sampleUffMaskRCNN Keras .h5 to UFF For Jetson Nano

### ISSUE THREAD

**Issue by muhammadabdullah34907** [NVIDIA/TensorRT#418]
I am trying to convert the mask_rcnn_coco.h5 keras model to uff (tensorRT) to run it on nvidia jetson nano. After running below command, i got below error. 
Also, all dependencies are installed as per given requirements.txt file.
 
python mrcnn_to_trt_single.py -w mask_rcnn_coco.h5 -o mrcnn_nchw.uff -p ./config.py

Traceback (most recent call last):
  File "mrcnn_to_trt_single.py", line 170, in <module>
    main()
  File "mrcnn_to_trt_single.py", line 129, in main
    text=True, list_nodes=list_nodes)
  File "mrcnn_to_trt_single.py", line 163, in convert_model
    debug_mode = False
  File "/home/admin/Videos/test/wade-ai/Trash_Detection/env/lib/python3.7/site-packages/uff/converters/tensorflow/conversion_helpers.py", line 229, in from_tensorflow_frozen_model
    return from_tensorflow(graphdef, output_nodes, preprocessor, **kwargs)
  File "/home/admin/Videos/test/wade-ai/Trash_Detection/env/lib/python3.7/site-packages/uff/converters/tensorflow/conversion_helpers.py", line 106, in from_tensorflow
    pre.preprocess(dynamic_graph)
  File "./config.py", line 119, in preprocess
    dynamic_graph.remove(timedistributed_remove_list)
  File "/home/admin/Videos/test/wade-ai/Trash_Detection/env/lib/python3.7/site-packages/graphsurgeon/DynamicGraph.py", line 470, in remove
    nodes = self._force_to_nodes(nodes)
  File "/home/admin/Videos/test/wade-ai/Trash_Detection/env/lib/python3.7/site-packages/graphsurgeon/DynamicGraph.py", line 324, in _force_to_nodes
    buf = self._force_to_names(buf)
  File "/home/admin/Videos/test/wade-ai/Trash_Detection/env/lib/python3.7/site-packages/graphsurgeon/DynamicGraph.py", line 307, in _force_to_names
    assert False, "The name %s does not exist" % el
AssertionError: The name mrcnn_class_bn1/Reshape_5/shape does not exist

**Comment by jqx37** [comment]
@muhammadabdullah34907 Cannot find "<TensorRT root directory>/samples/sample_uff_maskRCNN" dir --> UFF parser error #424

**Comment by Tyler-D** [comment]
Hi @jqx37 , you'd better convert the model from keras model to .uff on your host PC. Then run the .uff on Jetson NANO. 

Try this [step](https://github.com/NVIDIA/TensorRT/issues/626#issuecomment-652222259)

**Comment by rajeevsrao** [comment]
> Hi @jqx37 , you'd better convert the model from keras model to .uff on your host PC. Then run the .uff on Jetson NANO.
> 
> Try this [step](https://github.com/NVIDIA/TensorRT/issues/626#issuecomment-652222259)

Closing as duplicate of https://github.com/NVIDIA/TensorRT/issues/626

**Comment by batselem** [comment]
I got the same problem `KeyError: 'mrcnn_class_bn1/Reshape_5/shape'`. Did you solve it?

**Comment by jqx37** [comment]
Seems like this was an internal bug from NVIDIA, and I think it was solved. Please refer to https://forums.developer.nvidia.com/t/mask-rcnn-tensorrt-implement-on-jetson-xavier/82023. Hopefully, this can fix the issue we faced.
