### ISSUE TITLE
How to convert own model tensorrt - Question

### ISSUE THREAD

**Issue by ahmet-f-gumustas** [NVIDIA/TensorRT#4184]
Hi trt community;

How ı can convert my depth-anyting-v2 model tensorrt its possible ?

Ubuntu : 22:04
TensorRT: 10.4
Cuda : 12.2
GPU : RTX A2000

**Comment by yuanyao-nv** [comment]
If you have the torch checkpoint you can export it to ONNX format before running with TRT.
https://pytorch.org/docs/stable/onnx_torchscript.html

**Comment by ahmet-f-gumustas** [comment]
Hello @yuanyao-nv 

I write this code and I am taking some errors . How to solve . 

**CODE**
```
import torch
import onnx
import onnxruntime as ort
import numpy as np

from depth_anything_v2.dpt import DepthAnythingV2  # Adjust the import path as necessary

model = DepthAnythingV2()  # Adjust parameters as needed

checkpoint_path = '/home/ahmet/workspace-Depth/depth-estimation-2/metric_depth/checkpoints/depth_anything_v2_metric_vkitti_vits.pth'
checkpoint = torch.load(checkpoint_path, map_location='cpu')

adjusted_checkpoint = {}
for k in checkpoint.keys():
    new_key = k.replace('pretrained.', '', 1)
    adjusted_checkpoint[new_key] = checkpoint[k]

model_state_dict = model.state_dict()

filtered_checkpoint = {k: v for k, v in adjusted_checkpoint.items() if k in model_state_dict and v.size() == model_state_dict[k].size()}

model.load_state_dict(filtered_checkpoint, strict=False)

model.eval()

patch_size = 14
height = 384
width = 384

adjusted_height = (height // patch_size) * patch_size
adjusted_width = (width // patch_size) * patch_size

dummy_input = torch.randn(1, 3, adjusted_height, adjusted_width)

model = model.cuda()

dummy_input = dummy_input.cuda()

torch.onnx.export(
    model,
    dummy_input,
    'depth_anything_v2.onnx',
    opset_version=17,
    input_names=['input'],
    output_names=['output'],
    dynamic_axes={
        'input': {0: 'batch_size', 2: 'height', 3: 'width'},
        'output': {0: 'batch_size', 2: 'height', 3: 'width'}
    },
    do_constant_folding=True
)
```

**This is the terminal output** 

```
/home/ahmet/workspace-Depth/depth-estimation-2/metric_depth/onnx-try.py:15: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(checkpoint_path, map_location='cpu')
/home/ahmet/workspace-Depth/depth-estimation-2/metric_depth/depth_anything_v2/dinov2_layers/patch_embed.py:73: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert H % patch_H == 0, f"Input image height {H} is not a multiple of patch height {patch_H}"
/home/ahmet/workspace-Depth/depth-estimation-2/metric_depth/depth_anything_v2/dinov2_layers/patch_embed.py:74: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert W % patch_W == 0, f"Input image width {W} is not a multiple of patch width: {patch_W}"
/home/ahmet/workspace-Depth/depth-estimation-2/metric_depth/depth_anything_v2/dinov2.py:183: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if npatch == N and w == h:
/home/ahmet/workspace-Depth/depth-estimation-2/metric_depth/depth_anything_v2/dinov2.py:197: TracerWarning: Converting a tensor to a Python float might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  sqrt_N = math.sqrt(N)
/home/ahmet/workspace-Depth/depth-estimation-2/metric_depth/depth_anything_v2/dinov2.py:198: TracerWarning: Converting a tensor to a Python float might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  sx, sy = float(w0) / sqrt_N, float(h0) / sqrt_N
/home/ahmet/workspace-Depth/depth-estimation-2/metric_depth/depth_anything_v2/dinov2.py:207: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert int(w0) == patch_pos_embed.shape[-2]
/home/ahmet/workspace-Depth/depth-estimation-2/metric_depth/depth_anything_v2/dinov2.py:207: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert int(w0) == patch_pos_embed.shape[-2]
/home/ahmet/workspace-Depth/depth-estimation-2/metric_depth/depth_anything_v2/dinov2.py:208: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert int(h0) == patch_pos_embed.shape[-1]
/home/ahmet/workspace-Depth/depth-estimation-2/metric_depth/depth_anything_v2/dinov2.py:208: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert int(h0) == patch_pos_embed.shape[-1]
/home/ahmet/.local/lib/python3.10/site-packages/xformers/ops/fmha/common.py:219: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  self.query.shape == (B, Mq, H, K)
/home/ahmet/.local/lib/python3.10/site-packages/xformers/ops/fmha/common.py:220: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  and self.key.shape == (B, Mkv, H, key_embed_dim)
/home/ahmet/.local/lib/python3.10/site-packages/xformers/ops/fmha/common.py:221: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  and self.value.shape == (B, Mkv, H, Kv)
/home/ahmet/.local/lib/python3.10/site-packages/xformers/ops/fmha/common.py:336: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if not cls.SUPPORTS_DIFFERENT_VALUE_EMBED and K != Kv:
/home/ahmet/.local/lib/python3.10/site-packages/xformers/ops/fmha/common.py:338: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if max(K, Kv) > cls.SUPPORTED_MAX_K:
/home/ahmet/.local/lib/python3.10/site-packages/xformers/ops/fmha/common.py:342: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if min(K, Kv) < cls.SUPPORTED_MIN_K:
/home/ahmet/.local/lib/python3.10/site-packages/xformers/ops/fmha/common.py:485: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if x.shape[-1] % alignment != 0:
Traceback (most recent call last):
  File "/home/ahmet/workspace-Depth/depth-estimation-2/metric_depth/onnx-try.py", line 52, in <module>
    torch.onnx.export(
  File "/home/ahmet/.local/lib/python3.10/site-packages/torch/onnx/utils.py", line 551, in export
    _export(
  File "/home/ahmet/.local/lib/python3.10/site-packages/torch/onnx/utils.py", line 1648, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/home/ahmet/.local/lib/python3.10/site-packages/torch/onnx/utils.py", line 1170, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "/home/ahmet/.local/lib/python3.10/site-packages/torch/onnx/utils.py", line 1046, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/home/ahmet/.local/lib/python3.10/site-packages/torch/onnx/utils.py", line 950, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(
  File "/home/ahmet/.local/lib/python3.10/site-packages/torch/jit/_trace.py", line 1497, in _get_trace_graph
    outs = ONNXTracedModule(
  File "/home/ahmet/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ahmet/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ahmet/.local/lib/python3.10/site-packages/torch/jit/_trace.py", line 141, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "/home/ahmet/.local/lib/python3.10/site-packages/torch/jit/_trace.py", line 132, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/home/ahmet/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ahmet/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ahmet/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1543, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/ahmet/workspace-Depth/depth-estimation-2/metric_depth/depth_anything_v2/dpt.py", line 181, in forward
    features = self.pretrained.get_intermediate_layers(x, self.intermediate_layer_idx[self.encoder], return_class_token=True)
  File "/home/ahmet/workspace-Depth/depth-estimation-2/metric_depth/depth_anything_v2/dinov2.py", line 308, in get_intermediate_layers
    outputs = self._get_intermediate_layers_not_chunked(x, n)
  File "/home/ahmet/workspace-Depth/depth-estimation-2/metric_depth/depth_anything_v2/dinov2.py", line 277, in _get_intermediate_layers_not_chunked
    x = blk(x)
  File "/home/ahmet/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ahmet/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ahmet/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1543, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/ahmet/workspace-Depth/depth-estimation-2/metric_depth/depth_anything_v2/dinov2_layers/block.py", line 247, in forward
    return super().forward(x_or_x_list)
  File "/home/ahmet/workspace-Depth/depth-estimation-2/metric_depth/depth_anything_v2/dinov2_layers/block.py", line 105, in forward
    x = x + attn_residual_func(x)
  File "/home/ahmet/workspace-Depth/depth-estimation-2/metric_depth/depth_anything_v2/dinov2_layers/block.py", line 84, in attn_residual_func
    return self.ls1(self.attn(self.norm1(x)))
  File "/home/ahmet/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ahmet/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ahmet/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1543, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/ahmet/workspace-Depth/depth-estimation-2/metric_depth/depth_anything_v2/dinov2_layers/attention.py", line 76, in forward
    x = memory_efficient_attention(q, k, v, attn_bias=attn_bias)
  File "/home/ahmet/.local/lib/python3.10/site-packages/xformers/ops/fmha/__init__.py", line 301, in memory_efficient_attention
    return _memory_efficient_attention(
  File "/home/ahmet/.local/lib/python3.10/site-packages/xformers/ops/fmha/__init__.py", line 470, in _memory_efficient_attention
    return _fMHA.apply(
  File "/home/ahmet/.local/lib/python3.10/site-packages/torch/autograd/function.py", line 574, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/ahmet/.local/lib/python3.10/site-packages/xformers/ops/fmha/__init__.py", line 84, in forward
    out, op_ctx = _memory_efficient_attention_forward_requires_grad(
  File "/home/ahmet/.local/lib/python3.10/site-packages/xformers/ops/fmha/__init__.py", line 498, in _memory_efficient_attention_forward_requires_grad
    out = op.apply(inp, needs_gradient=True)
  File "/home/ahmet/.local/lib/python3.10/site-packages/xformers/ops/fmha/cutlass.py", line 218, in apply
    return cls.apply_bmhk(inp, needs_gradient=needs_gradient)
  File "/home/ahmet/.local/lib/python3.10/site-packages/xformers/ops/fmha/cutlass.py", line 282, in apply_bmhk
    out, lse, rng_seed, rng_offset, _, _ = cls.OPERATOR(
  File "/home/ahmet/.local/lib/python3.10/site-packages/torch/_ops.py", line 1061, in __call__
    return self_._op(*args, **(kwargs or {}))
RuntimeError: Found an unsupported argument type c10::SymInt in the JIT tracer. File a bug report.

```

Can you help me ? Thank You!

**Comment by lix19937** [comment]
Found an unsupported argument type c10::SymInt in the JIT tracer.    

It seems that transformer block has issue, you can  gradually export calculation graphs.
