### ISSUE TITLE
There is no acceleration for crnn model?

### ISSUE THREAD

**Issue by Hubert2102** [NVIDIA/TensorRT#446]
## Description
I trained a image-based sequence recognition model called CRNN in pytorch.The network contain some conv and BiLSTM modules.  
I exported my model to onnx and  trt. For a input such as (1,1,32,320)  ,it costs 6ms with trt to do inference,while the pytorch inference time is 5ms.

## Environment

**TensorRT Version**: TensorRT-7.0.0.11
**GPU Type**: Tesla P40
**Nvidia Driver Version**: 440.33.01
**CUDA Version**: 10.2
**CUDNN Version**: 7.6.5
**Operating System + Version**: Centos
**Python Version (if applicable)**: 3.7.4
**PyTorch Version (if applicable)**: 1.2

**Comment by Hubert2102** [comment]
I export the pytorch model first:
`torch.onnx.export(model,dummy_input,"crnn.onnx",export_params=True,verbose=True, input_names = ['input'],output_names = ['output'],dynamic_axes={'input' : {3 : 'w'},'output' : {3 : 'w'}})`
and then build engine:
`def build_engine(model_file):
    # For more information on TRT basics, refer to the introductory samples.
    with trt.Builder(TRT_LOGGER) as builder, builder.create_network(EXPLICIT_BATCH) as network, trt.OnnxParser(network, TRT_LOGGER) as parser:
        builder.max_workspace_size = common.GiB(2)
        #builder.max_workspace_size = 1 << 30
        builder.max_batch_size = 1
        with open(model_file, 'rb') as model:
            if not parser.parse(model.read()):
                print ('ERROR: Failed to parse the ONNX file.')
                for error in range(parser.num_errors):
                    print (parser.get_error(error))
                return None
        config = builder.create_builder_config()
        config.max_workspace_size = 512*1024*1024
        profile = builder.create_optimization_profile()
        profile.set_shape(network.get_input(0).name,(1,1,32,10),(1,1,32,320),(1,1,32,1000))
        config.add_optimization_profile(profile)
        engine = builder.build_engine(network, config)
        with open("sample.engine", "wb") as f:
            f.write(engine.serialize())
`
and inference test:
`def allocate_buffersV2(engine,context):
    inputs = []
    outputs = []
    bindings = []
    stream = cuda.Stream()
    for binding in engine:
        if binding=='input':
            size = trt.volume(context.get_binding_shape(0)) * engine.max_batch_size
            dtype = trt.nptype(engine.get_binding_dtype(0))
        if binding=='output':
            size = trt.volume(context.get_binding_shape(1)) * engine.max_batch_size
            dtype = trt.nptype(engine.get_binding_dtype(1))
        # Allocate host and device buffers
        host_mem = cuda.pagelocked_empty(size, dtype)
        device_mem = cuda.mem_alloc(host_mem.nbytes)
        # Append the device buffer to device bindings.
        bindings.append(int(device_mem))
        # Append to the appropriate list.
        if engine.binding_is_input(binding):
            inputs.append(HostDeviceMem(host_mem, device_mem))
        else:
            outputs.append(HostDeviceMem(host_mem, device_mem))
    return inputs, outputs, bindings, stream

def main():
    with open("sample.engine", "rb") as f, trt.Runtime(TRT_LOGGER) as runtime, \
        runtime.deserialize_cuda_engine(f.read()) as engine,engine.create_execution_context() as context:
        rectime = 0
        for i in range(1000):
            '''
            get dynamic shape input,and w is the image width
            '''
            context.active_optimization_profile = 0
            context.set_binding_shape(0, (1, 1, 32,w))
            inputs, outputs, bindings, stream = common.allocate_buffersV2(engine,context)
            inputs[0].host=image
            start_t = time.time()
            op = common.do_inference(context, bindings=bindings, inputs=inputs, outputs=outputs, stream=stream, batch_size=1)
            end_t = time.time()
            rectime+=int(round((start_t-end_t)*1000))
        print(rectime)`
the output is as below:
[TensorRT] WARNING: Current optimization profile is: 0. Please ensure there are no enqueued operations pending in this context prior to switching profiles
(1, 1, 32, 320)
10240
[TensorRT] WARNING: Explicit batch network detected and batch size specified, use enqueue without batch size instead.
[TensorRT] WARNING: Explicit batch network detected and batch size specified, use enqueue without batch size instead.
[TensorRT] WARNING: Explicit batch network detected and batch size specified, use enqueue without batch size instead.
...

**Comment by Hubert2102** [comment]
`torch.onnx.export(model,dummy_input,"crnn.onnx",export_params=True,verbose=True, input_names = ['input'],output_names = ['output'],dynamic_axes={'input' : {3 : 'w'},'output' : {3 : 'w'}})
`

**Comment by Hubert2102** [comment]
`for k, v in state_dict.items():
    name = k[7:] # remove `module.`
    #name = name[7:]
    state_dict_rename[name] = v
`

**Comment by ZimingLu** [comment]
> ## Description
> I trained a image-based sequence recognition model called CRNN in pytorch.The network contain some conv and BiLSTM modules.
> I exported my model to onnx and trt. For a input such as (1,1,32,320) ,it costs 6ms with trt to do inference,while the pytorch inference time is 5ms.
> 
> ## Environment
> **TensorRT Version**: TensorRT-7.0.0.11
> **GPU Type**: Tesla P40
> **Nvidia Driver Version**: 440.33.01
> **CUDA Version**: 10.2
> **CUDNN Version**: 7.6.5
> **Operating System + Version**: Centos
> **Python Version (if applicable)**: 3.7.4
> **PyTorch Version (if applicable)**: 1.2

same problem，I profile the cnn and rnn part, and I found rnn is 3 times faster but cnn is too slow!

**Comment by ZimingLu** [comment]
> ## Description
> I trained a image-based sequence recognition model called CRNN in pytorch.The network contain some conv and BiLSTM modules.
> I exported my model to onnx and trt. For a input such as (1,1,32,320) ,it costs 6ms with trt to do inference,while the pytorch inference time is 5ms.
> 
> ## Environment
> **TensorRT Version**: TensorRT-7.0.0.11
> **GPU Type**: Tesla P40
> **Nvidia Driver Version**: 440.33.01
> **CUDA Version**: 10.2
> **CUDNN Version**: 7.6.5
> **Operating System + Version**: Centos
> **Python Version (if applicable)**: 3.7.4
> **PyTorch Version (if applicable)**: 1.2

I guess we could talk about this problem in detail, my email address is gtayxlyc@163.com.

**Comment by Hubert2102** [comment]
I export the pytorch model firstly:
`
torch.onnx.export(model,dummy_input,"super_crnn.onnx",export_params=True,verbose=True, input_names = ['input'],output_names = ['output'],dynamic_axes={'input' : {3 : 'w'},'output' : {3 : 'w'}})
`
and then my trt script is 
[dynam_test_crnn.py.txt](https://github.com/NVIDIA/TensorRT/files/4379879/dynam_test_crnn.py.txt)
the output is as below:

[TensorRT] WARNING: Current optimization profile is: 0. Please ensure there are no enqueued operations pending in this context prior to switching profiles
(1, 1, 32, 320)
10240
[TensorRT] WARNING: Explicit batch network detected and batch size specified, use enqueue without batch size instead.
[TensorRT] WARNING: Explicit batch network detected and batch size specified, use enqueue without batch size instead.
[TensorRT] WARNING: Explicit batch network detected and batch size specified, use enqueue without batch size instead.
...

**Comment by YIYANGCAI** [comment]
# Problem
Hello, I am also arranging a CRNN model from PyTorch to TensorRT via ONNX, and I have got the .onnx model successfully.
However, when I try to convert the onnx to trt, I met the failure.
I also referred your code of producing the engine, but got these errors:
```
Traceback (most recent call last):
  File "test.py", line 105, in <module>
    build_engine('./data/crnn_data/model1016.onnx')
  File "test.py", line 32, in build_engine
    profile.set_shape(network.get_input(0).name,(1,1,32,320))
TypeError: set_shape(): incompatible function arguments. The following argument types are supported:
    1. (self: tensorrt.tensorrt.IOptimizationProfile, input: str, min: tensorrt.tensorrt.Dims, opt: tensorrt.tensorrt.Dims, max: tensorrt.tensorrt.Dims) -> None

Invoked with: <tensorrt.tensorrt.IOptimizationProfile object at 0x7fa4c77d5490>, 'input.1', (1, 1, 32, 320)

```

Since my onnx file have the same output with the original pth model, I think my onnx file is correct, could you help me to find out the problem? Many thanks.

If you would like to discuss the problem, my email is caiyiyang980311@icloud.com

**Comment by YIYANGCAI** [comment]
> # Problem
> Hello @Hubert2102, I am also arranging a CRNN model from PyTorch to TensorRT via ONNX, and I have got the .onnx model successfully.
> However, when I try to convert the onnx to trt, I met the failure.
> I also referred your code of producing the engine, but got these errors:
> 
> ```
> Traceback (most recent call last):
>   File "test.py", line 105, in <module>
>     build_engine('./data/crnn_data/model1016.onnx')
>   File "test.py", line 32, in build_engine
>     profile.set_shape(network.get_input(0).name,(1,1,32,320))
> TypeError: set_shape(): incompatible function arguments. The following argument types are supported:
>     1. (self: tensorrt.tensorrt.IOptimizationProfile, input: str, min: tensorrt.tensorrt.Dims, opt: tensorrt.tensorrt.Dims, max: tensorrt.tensorrt.Dims) -> None
> 
> Invoked with: <tensorrt.tensorrt.IOptimizationProfile object at 0x7fa4c77d5490>, 'input.1', (1, 1, 32, 320)
> ```
> 
> Since my onnx file have the same output with the original pth model, I think my onnx file is correct, could you help me to find out the problem? Many thanks.
> 
> By the way, when I construct the model of crnn from onnx to trt, the Slice operator met the following error:
> 
> ```
> ERROR: (Unnamed Layer* 316) [Slice]: slice size must be positive, size = [0,0,0]
> ```
> 
> If you would like to discuss the problem, my email is [caiyiyang980311@icloud.com](mailto:caiyiyang980311@icloud.com)

anyway, I have solved this problem, many thanks for this issue!

**Comment by wyp19960713** [comment]
@YIYANGCAI 您好，我这边也遇到了同样的切片异常问题，您能方便告诉下是怎么解决的吗？
`
[TensorRT] ERROR: (Unnamed Layer* 238) [Slice]: slice size must be positive, size = [0,0,0]
[TensorRT] ERROR: (Unnamed Layer* 239) [Slice]: slice size must be positive, size = [0,0,0]
`

**Comment by kevinch-nv** [comment]
@Hubert2102 @ZimingLu are you still having trouble with the performance of your model? Have you tried benchmarking with TensorRT 7.1?

**Comment by quietsmile** [comment]
> @YIYANGCAI 您好，我这边也遇到了同样的切片异常问题，您能方便告诉下是怎么解决的吗？
> 
> ```
> [TensorRT] ERROR: (Unnamed Layer* 238) [Slice]: slice size must be positive, size = [0,0,0]
> [TensorRT] ERROR: (Unnamed Layer* 239) [Slice]: slice size must be positive, size = [0,0,0]
> ```

请问你的问题解决了么？

**Comment by quietsmile** [comment]
> > # Problem
> > Hello @Hubert2102, I am also arranging a CRNN model from PyTorch to TensorRT via ONNX, and I have got the .onnx model successfully.
> > However, when I try to convert the onnx to trt, I met the failure.
> > I also referred your code of producing the engine, but got these errors:
> > ```
> > Traceback (most recent call last):
> >   File "test.py", line 105, in <module>
> >     build_engine('./data/crnn_data/model1016.onnx')
> >   File "test.py", line 32, in build_engine
> >     profile.set_shape(network.get_input(0).name,(1,1,32,320))
> > TypeError: set_shape(): incompatible function arguments. The following argument types are supported:
> >     1. (self: tensorrt.tensorrt.IOptimizationProfile, input: str, min: tensorrt.tensorrt.Dims, opt: tensorrt.tensorrt.Dims, max: tensorrt.tensorrt.Dims) -> None
> > 
> > Invoked with: <tensorrt.tensorrt.IOptimizationProfile object at 0x7fa4c77d5490>, 'input.1', (1, 1, 32, 320)
> > ```
> > 
> > 
> > Since my onnx file have the same output with the original pth model, I think my onnx file is correct, could you help me to find out the problem? Many thanks.
> > By the way, when I construct the model of crnn from onnx to trt, the Slice operator met the following error:
> > ```
> > ERROR: (Unnamed Layer* 316) [Slice]: slice size must be positive, size = [0,0,0]
> > ```
> > 
> > 
> > If you would like to discuss the problem, my email is [caiyiyang980311@icloud.com](mailto:caiyiyang980311@icloud.com)
> 
> anyway, I have solved this problem, many thanks for this issue!

请问，你这边实验的加速比如何？谢谢。

**Comment by ttyio** [comment]
Hello @Hubert2102 @ZimingLu , have you got any chance to try TRT 7.2, and how is the performance? thanks!

**Comment by ttyio** [comment]
Closing since no activity for more than 3 weeks, please reopen if you still have question, thanks!

**Comment by jinec** [comment]
> 您好，请问您这个问题解决的怎么样了呀

**Comment by jinec** [comment]
@Hubert2102 @ZimingLu   请问，你们这个问题解决的怎么样了呀
