### ISSUE TITLE
Error loading model with ONNX Runtime with TensorRT on Jetson devices

### ISSUE THREAD

**Issue by thirdeye-callum** [NVIDIA/TensorRT#465]
Hello,

Myself and another colleague have been attempting to use ONNXRuntime with the TensorrtExecutionProvider  to perform inference on Nvidia Jetson devices, however, we seem to be running into TensorRT related errors. After successfully building ONNX Runtime 1.1.0 (according to https://github.com/microsoft/onnxruntime/issues/2684#issuecomment-568548387 but using a newer commit https://github.com/microsoft/onnxruntime/commit/273868eaa55431164a2e5b5a94b8941bd550a7c3) on Nvidia Jetson devices (TX2, Xavier and Nano), creating an InferenceSession for a SlowFast ONNX model produces the following output:

```
Found unsupport node: 120
Found unsupport node: 132
2020-03-17 11:35:19.054683156 [W:onnxruntime:Default, tensorrt_execution_provider.h:28 log] [2020-03-17 11:35:19 WARNING] Calling isShapeTensor before the entire network is constructed may result in an inaccurate result.
2020-03-17 11:35:19.129416191 [W:onnxruntime:Default, tensorrt_execution_provider.h:28 log] [2020-03-17 11:35:19 WARNING] Setting layouts of network and plugin input/output tensors to linear, as 3D operators are found and 3D non-linear IO formats are not supported, yet.
2020-03-17 11:35:24.933445802 [W:onnxruntime:Default, tensorrt_execution_provider.h:28 log] [2020-03-17 11:35:24   ERROR] ../builder/cudnnBuilderUtils.cpp (354) - Cuda Error in findFastestTactic: 4 (unspecified launch failure)
2020-03-17 11:35:24.933948237 [W:onnxruntime:Default, tensorrt_execution_provider.h:28 log] [2020-03-17 11:35:24   ERROR] ../rtSafe/safeRuntime.cpp (32) - Cuda Error in free: 4 (unspecified launch failure)
terminate called after throwing an instance of 'nvinfer1::CudaError'
  what():  std::exception
Aborted (core dumped)
```
After increasing ORT_TENSORRT_MAX_WORKSPACE_SIZE (I have tried values ranging from 2gb to 6gb) the output becomes:
```
Found unsupport node: 120
Found unsupport node: 132
2020-03-17 11:41:59.570229117 [W:onnxruntime:Default, tensorrt_execution_provider.h:28 log] [2020-03-17 11:41:59 WARNING] Calling isShapeTensor before the entire network is constructed may result in an inaccurate result.
2020-03-17 11:41:59.647684879 [W:onnxruntime:Default, tensorrt_execution_provider.h:28 log] [2020-03-17 11:41:59 WARNING] Setting layouts of network and plugin input/output tensors to linear, as 3D operators are found and 3D non-linear IO formats are not supported, yet.
2020-03-17 11:42:01.764136091 [W:onnxruntime:Default, tensorrt_execution_provider.h:28 log] [2020-03-17 11:42:01   ERROR] ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
2020-03-17 11:42:01.774280999 [W:onnxruntime:Default, tensorrt_execution_provider.h:28 log] [2020-03-17 11:42:01   ERROR] ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
Traceback (most recent call last):
  File "test_onnx.py", line 79, in <module>
    main()
  File "test_onnx.py", line 56, in main
    ort_session = ort.InferenceSession(args.model)
  File "/home/callum/.local/lib/python3.6/site-packages/onnxruntime/capi/session.py", line 23, in __init__
    self._load_model()
  File "/home/callum/.local/lib/python3.6/site-packages/onnxruntime/capi/session.py", line 35, in _load_model
    self._sess.load_model(self._path_or_bytes, providers)
onnxruntime.capi.onnxruntime_pybind11_state.EPFail: [ONNXRuntimeError] : 11 : EP_FAIL : TensorRT EP could not build Engine for fused node: TensorrtExecutionProvider_TRTKernel_0_0
```
I have been able to run my model with both the CPU and CUDA Execution providers so where  `Found unsupported node: XXX` appears ONNX Runtime should successfully fallback to a non-TensorRT provider. When monitoring the memory usage using tegrastats it appears if the memory used is less than a third of total system memory. Additionally the model normally only requires ~1.5gb GPU memory when running in PyTorch.

It should be noted that my colleague has managed to successfully perform inference using the same version of ONNX Runtime/TensorRT on desktop, therefore it appears to be a Jetson specific issue. Could it be related to the fact that on Jetson devices memory is shared between the GPU and CPU?

## System information
- NVIDIA Jetson TX2, Xavier, Nano flashed with JetPack 4.3
- OS Platform and Distribution: L4T 32.3.1
- ONNX Runtime installed from source
- ONNX Runtime version 1.1.0 (same error appears with 1.0.0) https://github.com/microsoft/onnxruntime/commit/b783805f957c88f97b2b4398e2ace138fbdf831b
- Python version: Python 3.6.9
- GCC/Compiler version: 7.5.0-3ubuntu1~18.04
- CUDA/cuDNN version: 10.0.326/7.6.3
- GPU model and memory:  
  - Nvidia Jetson TX2 - 8gb shared between CPU and GPU
  - Nvidia Jetson Xavier - 32gb shared between CPU and GPU
  - Nvidia Jetson Nano - 4gb shared between CPU and GPU

### ONNX Runtime Installation
- Flash Jetson device with Jetpack 4.3
- Upgrade cmake to version 3.13.5 (following https://anglehit.com/how-to-install-the-latest-version-of-cmake-via-command-line/)
- `sudo apt-get install python3-dev python3-pip`
- `pip3 install cython numpy`
- build using specified instructions https://github.com/microsoft/onnxruntime/issues/2684#issuecomment-568548387 but with https://github.com/microsoft/onnxruntime/commit/273868eaa55431164a2e5b5a94b8941bd550a7c3 
- `pip3 install ./build/Linux/Release/dist/onnxruntime_gpu_tensorrt-1.1.0-cp36-cp36m-linux_aarch64.whl`

### Run Instructions
- Download model from https://drive.google.com/file/d/1d6eZkPcWam4CfCFERlbFJHtJ0ZLoAqmm/view?usp=sharing
- Run following python script ensuring that `model_path` is correct:
```
import numpy as np
import onnxruntime as ort

model_path = 'model_export_20200316_175122_class.onnx'

ort_session = ort.InferenceSession(model_path)
feed_dict = {}
feed_dict['slow'] = np.random.randn(1, 3, 8, 256, 256).astype(np.float32)
feed_dict['fast'] = np.random.randn(1, 3, 32, 256, 256).astype(np.float32)
print('Running inference...')
outputs = ort_session.run(
    None,
    feed_dict
)
print('Success!')
print(outputs)
```

## Expected behavior
As above, `Cuda Error in free` initially. Once TensorRT's maximum workspace is increased `Cuda Error in allocate`

## Additional context
- I am able to load ResNet18 and ResNet152 from the ONNX Model Zoo with the Tensorrt Execution Provider
- I am able to load my Model using both CPU and CUDA Execution Providers
- Re-exporting my model with with opset 7 produces the same errors

**Comment by thirdeye-callum** [comment]
I have been playing with the ORT_TENSORRT_MAX_PARTITION_ITERATIONS value. My understanding is that every time TensorRT doesn't support an operation the graph will be partitioned, so that the unsupported node(s) is run using a fallback provider (CUDA or CPU). If we have to partitions more than ORT_TENSORRT_MAX_PARTITION_ITERATIONS then the whole graph falls back to the fallback provider.

- With a value of 1 I get no warnings and the graph falls back to another provider and runs successfully.
- With a value of 2 I get the following warning and the graph falls back to another provider and runs successfully:
```
2020-03-19 09:03:50.109044117 [W:onnxruntime:Default, tensorrt_execution_provider.h:28 log] [2020-03-19 09:03:50 WARNING] Calling isShapeTensor before the entire network is constructed may result in an inaccurate result.
```
- With a value of 3 I get the following warnings and the same error again:
```
2020-03-19 09:04:25.529049981 [W:onnxruntime:Default, tensorrt_execution_provider.h:28 log] [2020-03-19 09:04:25 WARNING] Calling isShapeTensor before the entire network is constructed may result in an inaccurate result.
2020-03-19 09:04:25.721145280 [W:onnxruntime:Default, tensorrt_execution_provider.h:28 log] [2020-03-19 09:04:25 WARNING] Setting layouts of network and plugin input/output tensors to linear, as 3D operators are found and 3D non-linear IO formats are not supported, yet.
2020-03-19 09:04:27.483482298 [W:onnxruntime:Default, tensorrt_execution_provider.h:28 log] [2020-03-19 09:04:27   ERROR] ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
2020-03-19 09:04:27.490360049 [W:onnxruntime:Default, tensorrt_execution_provider.h:28 log] [2020-03-19 09:04:27   ERROR] ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
Traceback (most recent call last):
  File "test_onnx.py", line 87, in <module>
    main()
  File "test_onnx.py", line 61, in main
    ort_session = ort.InferenceSession(args.model, providers=['TensorrtExecutionProvider','CUDAExecutionProvider','CPUExecutionProvider'])
  File "/home/callum/.local/lib/python3.6/site-packages/onnxruntime/capi/session.py", line 25, in __init__
    self._load_model(providers)
  File "/home/callum/.local/lib/python3.6/site-packages/onnxruntime/capi/session.py", line 43, in _load_model
    self._sess.load_model(providers)
onnxruntime.capi.onnxruntime_pybind11_state.EPFail: [ONNXRuntimeError] : 11 : EP_FAIL : TensorRT EP could not build Engine for fused node: TensorrtExecutionProvider_TRTKernel_0_0
```
Maybe this suggests:
-  that the 2nd or 3rd (I am not sure if the max value is inclusive) subgraph (or the optimization of that subgraph) requires too much memory 
- or that the act of building multiple TensorRT subgraphs requires too much memory

**Comment by rmccorm4** [comment]
Hi @thirdeye-callum ,

> It should be noted that my colleague has managed to successfully perform inference using the same version of ONNX Runtime/TensorRT on desktop, therefore it appears to be a Jetson specific issue.

Just to clarify, was the desktop run also using TensorRT 6 (what Jetpack 4.3 comes with)? Or was desktop using TensorRT 7?

**Comment by rmccorm4** [comment]
> It should be noted that my colleague has managed to successfully perform inference using the same version of ONNX Runtime/TensorRT on desktop, therefore it appears to be a Jetson specific issue. Could it be related to the fact that on Jetson devices memory is shared between the GPU and CPU?

@dusty-nv, have you ever seen something like this?

**Comment by kevinch-nv** [comment]
Due to the limited memory size of Jetson, it is expected that some large models that can run on desktop would fail to run on Jetson.

We are actively working on reducing the memory footprint of ONNXRT-TRT, any updates will come from a future release of ONNXRT.

**Comment by wwdok** [comment]
@kevinch-nv Slowfast is indeed large, what about TSN ? i want to do action recognition using TensorRT on jetson xavier nx, is there any related tutorial ?

**Comment by Darshcg** [comment]
Hi @thirdeye-callum,

Can you please help me in converting the Slowfast PT to the ONNX model?. Would be a great help. Actually, I have a model which is trained in the custom dataset, so I need to convert the pt model to ONNX and to TRT.

Thanks in advance,
Darshan

**Comment by nvpohanh** [comment]
@thirdeye-callum Could you try TRT 8.2/8.4 and see if the issue still exists? If it does, we will debug it. Thanks

**Comment by nvpohanh** [comment]
Closing for now due to >14 days without activity. Please feel free to reopen if the issue still exists. Thanks
