### ISSUE TITLE
run multiple models at one time on xavier.

### ISSUE THREAD

**Issue by jeansely** [NVIDIA/TensorRT#488]
Hi,
how can i take two model at same time on nvidia jetson xavier. with last update i have error.
```python
[cuda.memcpy_htod_async(inp.device, inp.host, stream) for inp in inputs]
pycuda._driver.LogicError: cuMemcpyHtoDAsync failed: invalid argument
CException ignored in: <module 'threading' from '/usr/lib/python3.6/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 1294, in _shutdown
    t.join()
  File "/usr/lib/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
FATAL: exception not rethrown
Aborted (core dumped)
```

**Comment by rmccorm4** [comment]
Hi @jeansely ,

Seems like an issue specific to multi-threaded use of pycuda.

Might be better to ask this question here: https://github.com/inducer/pycuda
