### ISSUE TITLE
UFF parser does not support TensorFlow 2.x.

### ISSUE THREAD

**Issue by KellyZhang2020** [NVIDIA/TensorRT#513]
## Description

I trained a model with tensorflow 2.1 and export it as frozen graph. I then try to convert it to a .uff file with `uff.from_tensorflow_frozen_model()`. Then I get this error: -->

```
Traceback (most recent call last):
  File "compile_model.py", line 43, in <module>
    _main()
  File "compile_model.py", line 38, in _main
    result = model_compiler.compile_model(request)
  File "/usr/local/lib/python3.6/dist-packages/model_compiler/mo.py", line 18, in compile_model
    compiler = create_compiler(create_config_from_obj(request))
  File "/usr/local/lib/python3.6/dist-packages/model_compiler/runtime/__init__.py", line 22, in create_compiler
    from .tensorrt.compiler import Compiler
  File "/usr/local/lib/python3.6/dist-packages/model_compiler/runtime/tensorrt/compiler.py", line 13, in <module>
    import uff  # pylint:disable=import-error
  File "/usr/local/lib/python3.6/dist-packages/uff/__init__.py", line 2, in <module>
    from uff.converters.tensorflow.conversion_helpers import from_tensorflow  # noqa
  File "/usr/local/lib/python3.6/dist-packages/uff/converters/tensorflow/conversion_helpers.py", line 23, in <module>
    https://www.tensorflow.org/install/""".format(err))
ImportError: ERROR: Failed to import module (cannot import name 'GraphDef')
```

## Environment

**TensorRT Version**: 7.0.0.11
**GPU Type**: V100
**Nvidia Driver Version**: 440.33.01
**CUDA Version**: 10.2
**Operating System + Version**: ubuntu 18.04
**Python Version (if applicable)**: 3.6
**TensorFlow Version (if applicable)**: 2.1

Can UFF parser support TensorFlow 2.x?

**Comment by zyt312074545** [comment]
You can modify /usr/local/lib/python3.6/dist-packages/uff/converters/tensorflow/conversion_helpers.py file

modify `from tensorflow import GraphDef` to `from tensorflow.compat.v1 import GraphDef`

**Comment by rmccorm4** [comment]
Hi,

The UFF Parser does not support TF 2.0. The workaround above might work, but is not officially supported.

Please try converting your models to ONNX and using the ONNX parser instead.
