### ISSUE TITLE
Will BatchedNMS Plugin support runtime input dimensions (IPluginV2DynamicExt)?

### ISSUE THREAD

**Issue by zldrobit** [NVIDIA/TensorRT#544]
I converted ONNX YOLOv3 model to TensorRT Engine with [the repo](https://github.com/zldrobit/onnx_tflite_yolov3/tree/dynamic_axes).
Moreover, I would like to add BatchedNMS Plugin at the end of YOLO output.
Unfortunately, the Plugin is of type [IPluginV2Ext](https://github.com/NVIDIA/TensorRT/blob/master/plugin/batchedNMSPlugin/batchedNMSPlugin.h#L32), which does not support runtime input dimensions.
TensorRT compliants that only V2DynamicExt(IPluginV2DynamicExt) Plugin support runtime input dimensions:
```
root@9641ef65c22a:/workspace/onnx_tflite_yolov3# ./run_trt_convert.sh
2020-05-12 07:32:48 - __main__ - INFO - TRT_LOGGER Verbosity: Severity.ERROR
2020-05-12 07:32:49 - __main__ - DEBUG - === Network Description ===
2020-05-12 07:32:49 - __main__ - DEBUG - Input  0 | Name: input_1        | Shape: (-1, 3, 416, 416)
[TensorRT] ERROR: (Unnamed Layer* 641) [PluginV2Ext]: PluginV2Layer must be V2DynamicExt when there are runtime input dimensions.
2020-05-12 07:32:49 - __main__ - DEBUG - Output 0 | Name: num_detections | Shape: (0)
[TensorRT] ERROR: (Unnamed Layer* 641) [PluginV2Ext]: PluginV2Layer must be V2DynamicExt when there are runtime input dimensions.
2020-05-12 07:32:49 - __main__ - DEBUG - Output 1 | Name: nmsed_boxes    | Shape: (0)
[TensorRT] ERROR: (Unnamed Layer* 641) [PluginV2Ext]: PluginV2Layer must be V2DynamicExt when there are runtime input dimensions.
2020-05-12 07:32:49 - __main__ - DEBUG - Output 2 | Name: nmsed_scores   | Shape: (0)
[TensorRT] ERROR: (Unnamed Layer* 641) [PluginV2Ext]: PluginV2Layer must be V2DynamicExt when there are runtime input dimensions.
2020-05-12 07:32:49 - __main__ - DEBUG - Output 3 | Name: nmsed_classes  | Shape: (0)
2020-05-12 07:32:49 - __main__ - DEBUG - === Optimization Profiles ===
2020-05-12 07:32:49 - __main__ - DEBUG - input_1 - OptProfile 0 - Min (1, 3, 416, 416) Opt (64, 3, 416, 416) Max (64, 3, 416, 416)
2020-05-12 07:32:49 - __main__ - INFO - Building Engine...
[TensorRT] ERROR: (Unnamed Layer* 641) [PluginV2Ext]: PluginV2Layer must be V2DynamicExt when there are runtime input dimensions.
[TensorRT] ERROR: (Unnamed Layer* 641) [PluginV2Ext]: PluginV2Layer must be V2DynamicExt when there are runtime input dimensions.
[TensorRT] ERROR: (Unnamed Layer* 641) [PluginV2Ext]: PluginV2Layer must be V2DynamicExt when there are runtime input dimensions.
[TensorRT] ERROR: (Unnamed Layer* 641) [PluginV2Ext]: PluginV2Layer must be V2DynamicExt when there are runtime input dimensions.
[TensorRT] ERROR: (Unnamed Layer* 641) [PluginV2Ext]: PluginV2Layer must be V2DynamicExt when there are runtime input dimensions.
[TensorRT] ERROR: Layer (Unnamed Layer* 641) [PluginV2Ext] failed validation
[TensorRT] ERROR: Network validation failed.
Traceback (most recent call last):
  File "trt_convert.py", line 278, in <module>
    main()
  File "trt_convert.py", line 273, in main
    with builder.build_engine(network, config) as engine, open(args.output, "wb") as f:
AttributeError: __enter__
```

I have to use runtime input dimension for batch size, because Triton Inference Server runs with dynamic batching for acceleration.
The fastest way I see is to replace some code in BatchedNMS Plugin with IPluginV2DynamicExt specific code in fcPlugin.

**Comment by rmccorm4** [comment]
Hi @zldrobit ,

Yes I believe you'll have to tweak the existing implementation to implement the `IPluginV2DynamicExt` interface instead. Please try this, and feel free to submit a pull request if you get a working implementation.
