### ISSUE TITLE
Python onnx_ to_ tensorrt.py  boxes, classes, scores: None None None????

### ISSUE THREAD

**Issue by hande6688** [NVIDIA/TensorRT#732]
My environment is as follows:

TensorRT Version: 6.0.1.5

GPU Type: 2080Ti

CUDA Version: 10.0

CUDNN Version: 7.6.5

Operating System + Version: ubuntu 18.04

python3.6

pytorch1.4.0

onnx1.5.0
Run Python onnx_ to_ tensorrt.py The error is as follows:
Reading engine from file best.trt
Running inference on image 1.jpg...
boxes, classes, scores: None None None
None None None
Traceback (most recent call last):
File "onnx_to_tensorrt.py", line 181, in
main()
File "onnx_to_tensorrt.py", line 175, in main
obj_detected_img = draw_bboxes(image_raw, boxes, scores, classes, ALL_CATEGORIES)
File "onnx_to_tensorrt.py", line 84, in draw_bboxes
for box, score, category in zip(bboxes, confidences, categories):
TypeError: zip argument #1 must support iteration
The code uses tensorrt-6.0.1.5/samples/python/yolov3 in tensor RT_ Onnx code

**Comment by mk-nvidia** [comment]
@hande6688 do you see this problem with a recent TensorRT release as well?

**Comment by ttyio** [comment]
I will close issue since we have policy to close issue with no activity for more than 3 weeks. Please reopen if you still have questions. Thanks!
